In [1]:
import pandas as pd

In [11]:
import pandas as pd
import numpy as np

data = {
    "employee_id": [
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        101, 122, 123, 124, 125, 126, 127, 128, 129, 130
    ],

    "name": [
        "Aarav Sharma", "Priya Patil", "Rahul Deshmukh", "",
        "Sneha Joshi", "Vikram More", "Om Pawar", "Isha Shah",
        "Kunal Jadhav", "Pooja Sane", "Sahil Chavan", None,
        "Riya Bhosale", "Yash Thakur", "Neha Pawar", "Rohan Shinde",
        "Tanvi Gokhale", "Nikhil Patil", "Aditi Desai", "Kavya More",
        "Aarav Sharma", "Dev Kulkarni", "Sana Khan", "Arjun Nair",
        "Mitali Shah", "Siddharth Kale", "Diya Pawar", "Irfan Shaikh",
        "Ritu Pawar", "  "
    ],

    "age": [
        25, 28, 32, 26, np.nan, 35, 150, 24, 29, 31,
        27, 33, 26, -5, 30, 28, 24, 36, 27, 29,
        25, 31, np.nan, 34, 28, 26, 23, 32, 29, 200
    ],

    "gender": [
        "Male", "Female", "Male", "Female", "Female", "Male",
        "Male", "Female", "Male", "Female", "Male", "Female",
        "Female", "Male", "Female", "Male", "Female", "Male",
        "Female", "Female", "Male", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female", "Unknown"
    ],

    "department": [
        "IT", "HR", "Finance", "IT", "Marketing", "IT", "HR",
        "Finance", "IT", "Marketing", "HR", "IT", "Finance",
        "IT", "HR", "Marketing", "IT", "Finance", "HR", "IT",
        "IT", "Finance", "HR", "IT", "Marketing", "IT",
        "Finance", "HR", "IT", "Marketing"
    ],

    "salary": [
        45000, 52000, 60000, 47000, np.nan, 75000, 50000,
        48000, 62000, 55000, 51000, 68000, 49000, -1000,
        53000, 72000, 46000, 80000, 54000, 58000,
        45000, 65000, 0, 90000, 56000, np.nan, 48000,
        61000, 52000, 999999
    ],

    "performance_score": [
        4.2, 3.8, 4.5, 3.9, 4.1, np.nan, 3.5, 4.8,
        4.0, 3.7, 4.3, 3.9, 4.6, 2.8, 4.1, 5.5,
        3.6, 4.7, 4.0, np.nan, 4.2, 3.8, 4.4, 4.1,
        3.9, 4.6, 3.7, 4.0, 4.2, 8.5
    ],

    "location": [
        "Pune", "Mumbai", "Nashik", "Pune", "Pune", "Mumbai",
        "Pune", "Nashik", "Mumbai", "Pune", "PUNE", "Mumbai",
        "Nashik", "Pune", "Mumbai", "Nashik", "Pune", "Mumbai",
        "Pune", "Nashik", "Pune", "Mumbai", "Pune", "Nashik",
        "Mumbai", "Pune", "Nashik", "Mumbai", "Pune", None
    ],

    "joining_date": [
        "2022-05-17", "2021-03-10", "2020-11-25", "2023-01-15",
        "2022-08-20", "2021-06-12", "2020-02-30", "2023-04-18",
        "2022-09-05", None, "2021-12-01", "2020-07-14",
        "2023-02-30", "2022-10-10", "not available", "2021-05-22",
        "2023-06-01", "2020-09-15", "2022-01-30", "2021-11-11",
        "2022-05-17", "2023-03-12", "2021-07-19", "2020-12-05",
        "2022-04-25", "2021-08-16", "2023-05-20", "2022-02-14",
        "2020-10-10", "2024-13-40"
    ],

    "experience_years": [
        2, 4, 7, 1, np.nan, 8, 3, 1, 5, 6,
        4, 9, 2, -1, 5, 7, 1, 10, 3, 4,
        2, 6, 3, 8, 4, 5, 1, 7, 3, 50
    ],

    "email": [
        "aarav@example.com", "priya@example.com", "rahul@example.com",
        "sneha.example.com", "sneha@example.com", None,
        "om@example.com", "isha@example.com", "kunal@example.com",
        "pooja@example.com", "sahil@example.com", "riya@example.com",
        "yash@example.com", "neha@example.com", "rohan@example.com",
        "tanvi@example.com", "nikhil@example.com", "aditi@example.com",
        "kavya@example.com", "dev@example.com", "aarav@example.com",
        "dev.k@example.com", "sana@example.com", "arjun@example.com",
        "mitali@example.com", "siddharth@example.com", "diya@example.com",
        "irfan@example.com", "ritu@example.com", ""
    ]
}

df = pd.DataFrame(data)

print(df)
print(df.shape)

    employee_id            name    age   gender department    salary  \
0           101    Aarav Sharma   25.0     Male         IT   45000.0
1           102     Priya Patil   28.0   Female         HR   52000.0
2           103  Rahul Deshmukh   32.0     Male    Finance   60000.0
3           104                   26.0   Female         IT   47000.0
4           105     Sneha Joshi    NaN   Female  Marketing       NaN
5           106     Vikram More   35.0     Male         IT   75000.0
6           107        Om Pawar  150.0     Male         HR   50000.0
7           108       Isha Shah   24.0   Female    Finance   48000.0
8           109    Kunal Jadhav   29.0     Male         IT   62000.0
9           110      Pooja Sane   31.0   Female  Marketing   55000.0
10          111    Sahil Chavan   27.0     Male         HR   51000.0
11          112            None   33.0   Female         IT   68000.0
12          113    Riya Bhosale   26.0   Female    Finance   49000.0
13          114     Yash Thakur   -5.0     Male         IT   -1000.0
14          115      Neha Pawar   30.0   Female         HR   53000.0
15          116    Rohan Shinde   28.0     Male  Marketing   72000.0
16          117   Tanvi Gokhale   24.0   Female         IT   46000.0
17          118    Nikhil Patil   36.0     Male    Finance   80000.0
18          119     Aditi Desai   27.0   Female         HR   54000.0
19          120      Kavya More   29.0   Female         IT   58000.0
20          101    Aarav Sharma   25.0     Male         IT   45000.0
21          122    Dev Kulkarni   31.0     Male    Finance   65000.0
22          123       Sana Khan    NaN   Female         HR       0.0
23          124      Arjun Nair   34.0     Male         IT   90000.0
24          125     Mitali Shah   28.0   Female  Marketing   56000.0
25          126  Siddharth Kale   26.0     Male         IT       NaN
26          127      Diya Pawar   23.0   Female    Finance   48000.0
27          128    Irfan Shaikh   32.0     Male         HR   61000.0
28          129      Ritu Pawar   29.0   Female         IT   52000.0
29          130                  200.0  Unknown  Marketing  999999.0

    performance_score location   joining_date  experience_years  \
0                 4.2     Pune     2022-05-17               2.0
1                 3.8   Mumbai     2021-03-10               4.0
2                 4.5   Nashik     2020-11-25               7.0
3                 3.9     Pune     2023-01-15               1.0
4                 4.1     Pune     2022-08-20               NaN
5                 NaN   Mumbai     2021-06-12               8.0
6                 3.5     Pune     2020-02-30               3.0
7                 4.8   Nashik     2023-04-18               1.0
8                 4.0   Mumbai     2022-09-05               5.0
9                 3.7     Pune           None               6.0
10                4.3     PUNE     2021-12-01               4.0
11                3.9   Mumbai     2020-07-14               9.0
12                4.6   Nashik     2023-02-30               2.0
13                2.8     Pune     2022-10-10              -1.0
14                4.1   Mumbai  not available               5.0
15                5.5   Nashik     2021-05-22               7.0
16                3.6     Pune     2023-06-01               1.0
17                4.7   Mumbai     2020-09-15              10.0
18                4.0     Pune     2022-01-30               3.0
19                NaN   Nashik     2021-11-11               4.0
20                4.2     Pune     2022-05-17               2.0
21                3.8   Mumbai     2023-03-12               6.0
22                4.4     Pune     2021-07-19               3.0
23                4.1   Nashik     2020-12-05               8.0
24                3.9   Mumbai     2022-04-25               4.0
25                4.6     Pune     2021-08-16               5.0
26                3.7   Nashik     2023-05-20               1.0
27                4.0   Mumbai     2022-02-14               7.0
28                4.2     Pune     2020-10-10               3.0
29                8.5     None     2024-13-40              50.0

                    email
0       aarav@example.com
1       priya@example.com
2       rahul@example.com
3       sneha.example.com
4       sneha@example.com
5                    None
6          om@example.com
7        isha@example.com
8       kunal@example.com
9       pooja@example.com
10      sahil@example.com
11       riya@example.com
12       yash@example.com
13       neha@example.com
14      rohan@example.com
15      tanvi@example.com
16     nikhil@example.com
17      aditi@example.com
18      kavya@example.com
19        dev@example.com
20      aarav@example.com
21      dev.k@example.com
22       sana@example.com
23      arjun@example.com
24     mitali@example.com
25  siddharth@example.com
26       diya@example.com
27      irfan@example.com
28       ritu@example.com
29
(30, 11)

In [3]:
df

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
1,102,Priya Patil,28.0,Female,HR,52000.0,3.8,Mumbai,2021-03-10,4.0,priya@example.com
2,103,Rahul Deshmukh,32.0,Male,Finance,60000.0,4.5,Nashik,2020-11-25,7.0,rahul@example.com
3,104,,26.0,Female,IT,47000.0,3.9,Pune,2023-01-15,1.0,sneha.example.com
4,105,Sneha Joshi,NaN,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com
5,106,Vikram More,35.0,Male,IT,75000.0,NaN,Mumbai,2021-06-12,8.0,None
6,107,Om Pawar,150.0,Male,HR,50000.0,3.5,Pune,2020-02-30,3.0,om@example.com
7,108,Isha Shah,24.0,Female,Finance,48000.0,4.8,Nashik,2023-04-18,1.0,isha@example.com
8,109,Kunal Jadhav,29.0,Male,IT,62000.0,4.0,Mumbai,2022-09-05,5.0,kunal@example.com
9,110,Pooja Sane,31.0,Female,Marketing,55000.0,3.7,Pune,None,6.0,pooja@example.com
10,111,Sahil Chavan,27.0,Male,HR,51000.0,4.3,PUNE,2021-12-01,4.0,sahil@example.com
11,112,None,33.0,Female,IT,68000.0,3.9,Mumbai,2020-07-14,9.0,riya@example.com
12,113,Riya Bhosale,26.0,Female,Finance,49000.0,4.6,Nashik,2023-02-30,2.0,yash@example.com
13,114,Yash Thakur,-5.0,Male,IT,-1000.0,2.8,Pune,2022-10-10,-1.0,neha@example.com
14,115,Neha Pawar,30.0,Female,HR,53000.0,4.1,Mumbai,not available,5.0,rohan@example.com
15,116,Rohan Shinde,28.0,Male,Marketing,72000.0,5.5,Nashik,2021-05-22,7.0,tanvi@example.com
16,117,Tanvi Gokhale,24.0,Female,IT,46000.0,3.6,Pune,2023-06-01,1.0,nikhil@example.com
17,118,Nikhil Patil,36.0,Male,Finance,80000.0,4.7,Mumbai,2020-09-15,10.0,aditi@example.com
18,119,Aditi Desai,27.0,Female,HR,54000.0,4.0,Pune,2022-01-30,3.0,kavya@example.com
19,120,Kavya More,29.0,Female,IT,58000.0,NaN,Nashik,2021-11-11,4.0,dev@example.com
20,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
21,122,Dev Kulkarni,31.0,Male,Finance,65000.0,3.8,Mumbai,2023-03-12,6.0,dev.k@example.com
22,123,Sana Khan,NaN,Female,HR,0.0,4.4,Pune,2021-07-19,3.0,sana@example.com
23,124,Arjun Nair,34.0,Male,IT,90000.0,4.1,Nashik,2020-12-05,8.0,arjun@example.com
24,125,Mitali Shah,28.0,Female,Marketing,56000.0,3.9,Mumbai,2022-04-25,4.0,mitali@example.com
25,126,Siddharth Kale,26.0,Male,IT,NaN,4.6,Pune,2021-08-16,5.0,siddharth@example.com
26,127,Diya Pawar,23.0,Female,Finance,48000.0,3.7,Nashik,2023-05-20,1.0,diya@example.com
27,128,Irfan Shaikh,32.0,Male,HR,61000.0,4.0,Mumbai,2022-02-14,7.0,irfan@example.com
28,129,Ritu Pawar,29.0,Female,IT,52000.0,4.2,Pune,2020-10-10,3.0,ritu@example.com
29,130,,200.0,Unknown,Marketing,999999.0,8.5,None,2024-13-40,50.0,

In [10]:
df=df["name"].str.strip().replace("name","")

KeyError: 'name'

In [6]:
df

0       Aarav Sharma
1        Priya Patil
2     Rahul Deshmukh
3
4        Sneha Joshi
5        Vikram More
6           Om Pawar
7          Isha Shah
8       Kunal Jadhav
9         Pooja Sane
10      Sahil Chavan
11              None
12      Riya Bhosale
13       Yash Thakur
14        Neha Pawar
15      Rohan Shinde
16     Tanvi Gokhale
17      Nikhil Patil
18       Aditi Desai
19        Kavya More
20      Aarav Sharma
21      Dev Kulkarni
22         Sana Khan
23        Arjun Nair
24       Mitali Shah
25    Siddharth Kale
26        Diya Pawar
27      Irfan Shaikh
28        Ritu Pawar
29
Name: name, dtype: object

In [21]:
df["name"]=df.loc[df["name"].str.strip()].replace("name","roshan")

KeyError: "None of [Index([  'Aarav Sharma',    'Priya Patil', 'Rahul Deshmukh',               '',\n          'Sneha Joshi',    'Vikram More',       'Om Pawar',      'Isha Shah',\n         'Kunal Jadhav',     'Pooja Sane',   'Sahil Chavan',             None,\n         'Riya Bhosale',    'Yash Thakur',     'Neha Pawar',   'Rohan Shinde',\n        'Tanvi Gokhale',   'Nikhil Patil',    'Aditi Desai',     'Kavya More',\n         'Aarav Sharma',   'Dev Kulkarni',      'Sana Khan',     'Arjun Nair',\n          'Mitali Shah', 'Siddharth Kale',     'Diya Pawar',   'Irfan Shaikh',\n           'Ritu Pawar',               ''],\n      dtype='object')] are in the [index]"

In [20]:
df.name

0       Aarav Sharma
1        Priya Patil
2     Rahul Deshmukh
3
4        Sneha Joshi
5        Vikram More
6           Om Pawar
7          Isha Shah
8       Kunal Jadhav
9         Pooja Sane
10      Sahil Chavan
11              None
12      Riya Bhosale
13       Yash Thakur
14        Neha Pawar
15      Rohan Shinde
16     Tanvi Gokhale
17      Nikhil Patil
18       Aditi Desai
19        Kavya More
20      Aarav Sharma
21      Dev Kulkarni
22         Sana Khan
23        Arjun Nair
24       Mitali Shah
25    Siddharth Kale
26        Diya Pawar
27      Irfan Shaikh
28        Ritu Pawar
29
Name: name, dtype: object

In [27]:
df.name.fillna("")

a = df[df["name"]==""].index

df.drop(a,inplace=True)

In [28]:
df

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
1,102,Priya Patil,28.0,Female,HR,52000.0,3.8,Mumbai,2021-03-10,4.0,priya@example.com
2,103,Rahul Deshmukh,32.0,Male,Finance,60000.0,4.5,Nashik,2020-11-25,7.0,rahul@example.com
4,105,Sneha Joshi,NaN,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com
5,106,Vikram More,35.0,Male,IT,75000.0,NaN,Mumbai,2021-06-12,8.0,None
6,107,Om Pawar,150.0,Male,HR,50000.0,3.5,Pune,2020-02-30,3.0,om@example.com
7,108,Isha Shah,24.0,Female,Finance,48000.0,4.8,Nashik,2023-04-18,1.0,isha@example.com
8,109,Kunal Jadhav,29.0,Male,IT,62000.0,4.0,Mumbai,2022-09-05,5.0,kunal@example.com
9,110,Pooja Sane,31.0,Female,Marketing,55000.0,3.7,Pune,None,6.0,pooja@example.com
10,111,Sahil Chavan,27.0,Male,HR,51000.0,4.3,PUNE,2021-12-01,4.0,sahil@example.com
11,112,None,33.0,Female,IT,68000.0,3.9,Mumbai,2020-07-14,9.0,riya@example.com
12,113,Riya Bhosale,26.0,Female,Finance,49000.0,4.6,Nashik,2023-02-30,2.0,yash@example.com
13,114,Yash Thakur,-5.0,Male,IT,-1000.0,2.8,Pune,2022-10-10,-1.0,neha@example.com
14,115,Neha Pawar,30.0,Female,HR,53000.0,4.1,Mumbai,not available,5.0,rohan@example.com
15,116,Rohan Shinde,28.0,Male,Marketing,72000.0,5.5,Nashik,2021-05-22,7.0,tanvi@example.com
16,117,Tanvi Gokhale,24.0,Female,IT,46000.0,3.6,Pune,2023-06-01,1.0,nikhil@example.com
17,118,Nikhil Patil,36.0,Male,Finance,80000.0,4.7,Mumbai,2020-09-15,10.0,aditi@example.com
18,119,Aditi Desai,27.0,Female,HR,54000.0,4.0,Pune,2022-01-30,3.0,kavya@example.com
19,120,Kavya More,29.0,Female,IT,58000.0,NaN,Nashik,2021-11-11,4.0,dev@example.com
20,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
21,122,Dev Kulkarni,31.0,Male,Finance,65000.0,3.8,Mumbai,2023-03-12,6.0,dev.k@example.com
22,123,Sana Khan,NaN,Female,HR,0.0,4.4,Pune,2021-07-19,3.0,sana@example.com
23,124,Arjun Nair,34.0,Male,IT,90000.0,4.1,Nashik,2020-12-05,8.0,arjun@example.com
24,125,Mitali Shah,28.0,Female,Marketing,56000.0,3.9,Mumbai,2022-04-25,4.0,mitali@example.com
25,126,Siddharth Kale,26.0,Male,IT,NaN,4.6,Pune,2021-08-16,5.0,siddharth@example.com
26,127,Diya Pawar,23.0,Female,Finance,48000.0,3.7,Nashik,2023-05-20,1.0,diya@example.com
27,128,Irfan Shaikh,32.0,Male,HR,61000.0,4.0,Mumbai,2022-02-14,7.0,irfan@example.com
28,129,Ritu Pawar,29.0,Female,IT,52000.0,4.2,Pune,2020-10-10,3.0,ritu@example.com

In [29]:
df.isnull().sum()

employee_id          0
name                 1
age                  2
gender               0
department           0
salary               2
performance_score    2
location             0
joining_date         1
experience_years     1
email                1
dtype: int64

In [32]:
df[df["name"].isnull()].index

Index([11], dtype='int64')

In [33]:
df.drop(11)

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
1,102,Priya Patil,28.0,Female,HR,52000.0,3.8,Mumbai,2021-03-10,4.0,priya@example.com
2,103,Rahul Deshmukh,32.0,Male,Finance,60000.0,4.5,Nashik,2020-11-25,7.0,rahul@example.com
4,105,Sneha Joshi,NaN,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com
5,106,Vikram More,35.0,Male,IT,75000.0,NaN,Mumbai,2021-06-12,8.0,None
6,107,Om Pawar,150.0,Male,HR,50000.0,3.5,Pune,2020-02-30,3.0,om@example.com
7,108,Isha Shah,24.0,Female,Finance,48000.0,4.8,Nashik,2023-04-18,1.0,isha@example.com
8,109,Kunal Jadhav,29.0,Male,IT,62000.0,4.0,Mumbai,2022-09-05,5.0,kunal@example.com
9,110,Pooja Sane,31.0,Female,Marketing,55000.0,3.7,Pune,None,6.0,pooja@example.com
10,111,Sahil Chavan,27.0,Male,HR,51000.0,4.3,PUNE,2021-12-01,4.0,sahil@example.com
12,113,Riya Bhosale,26.0,Female,Finance,49000.0,4.6,Nashik,2023-02-30,2.0,yash@example.com
13,114,Yash Thakur,-5.0,Male,IT,-1000.0,2.8,Pune,2022-10-10,-1.0,neha@example.com
14,115,Neha Pawar,30.0,Female,HR,53000.0,4.1,Mumbai,not available,5.0,rohan@example.com
15,116,Rohan Shinde,28.0,Male,Marketing,72000.0,5.5,Nashik,2021-05-22,7.0,tanvi@example.com
16,117,Tanvi Gokhale,24.0,Female,IT,46000.0,3.6,Pune,2023-06-01,1.0,nikhil@example.com
17,118,Nikhil Patil,36.0,Male,Finance,80000.0,4.7,Mumbai,2020-09-15,10.0,aditi@example.com
18,119,Aditi Desai,27.0,Female,HR,54000.0,4.0,Pune,2022-01-30,3.0,kavya@example.com
19,120,Kavya More,29.0,Female,IT,58000.0,NaN,Nashik,2021-11-11,4.0,dev@example.com
20,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
21,122,Dev Kulkarni,31.0,Male,Finance,65000.0,3.8,Mumbai,2023-03-12,6.0,dev.k@example.com
22,123,Sana Khan,NaN,Female,HR,0.0,4.4,Pune,2021-07-19,3.0,sana@example.com
23,124,Arjun Nair,34.0,Male,IT,90000.0,4.1,Nashik,2020-12-05,8.0,arjun@example.com
24,125,Mitali Shah,28.0,Female,Marketing,56000.0,3.9,Mumbai,2022-04-25,4.0,mitali@example.com
25,126,Siddharth Kale,26.0,Male,IT,NaN,4.6,Pune,2021-08-16,5.0,siddharth@example.com
26,127,Diya Pawar,23.0,Female,Finance,48000.0,3.7,Nashik,2023-05-20,1.0,diya@example.com
27,128,Irfan Shaikh,32.0,Male,HR,61000.0,4.0,Mumbai,2022-02-14,7.0,irfan@example.com
28,129,Ritu Pawar,29.0,Female,IT,52000.0,4.2,Pune,2020-10-10,3.0,ritu@example.com

In [34]:
df.shape

(28, 11)

In [35]:
df.head()

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
1,102,Priya Patil,28.0,Female,HR,52000.0,3.8,Mumbai,2021-03-10,4.0,priya@example.com
2,103,Rahul Deshmukh,32.0,Male,Finance,60000.0,4.5,Nashik,2020-11-25,7.0,rahul@example.com
4,105,Sneha Joshi,NaN,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com
5,106,Vikram More,35.0,Male,IT,75000.0,NaN,Mumbai,2021-06-12,8.0,None

In [36]:
df.columns.to_list()

['employee_id',
 'name',
 'age',
 'gender',
 'department',
 'salary',
 'performance_score',
 'location',
 'joining_date',
 'experience_years',
 'email']

In [38]:
df.index

Index([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
      dtype='int64')

In [39]:
df.dtypes

employee_id            int64
name                  object
age                  float64
gender                object
department            object
salary               float64
performance_score    float64
location              object
joining_date          object
experience_years     float64
email                 object
dtype: object

In [40]:
df.isnull().sum()

employee_id          0
name                 1
age                  2
gender               0
department           0
salary               2
performance_score    2
location             0
joining_date         1
experience_years     1
email                1
dtype: int64

In [41]:
df.drop(11,inplace=True)

In [43]:
df.isnull().sum()

employee_id          0
name                 0
age                  2
gender               0
department           0
salary               2
performance_score    2
location             0
joining_date         1
experience_years     1
email                1
dtype: int64

In [44]:
df["salary"] = df["salary"].fillna(df["salary"].mean())

In [46]:
df.isnull().sum()

employee_id          0
name                 0
age                  2
gender               0
department           0
salary               0
performance_score    2
location             0
joining_date         1
experience_years     1
email                1
dtype: int64

In [47]:
import numpy as np

In [50]:
# d = np.array([75,88
75+88+60

223