In [1]:
name = "roshan pardeshi"
print(f"hellow world :-{name}")

hellow world :-roshan pardeshi

In [3]:
a = 10
b = 20
a = a+b
b = a-b
a = a-b

print(a)
print(b)

20
10

In [4]:
num = 9

if num%2==0:
    print("even")
else:
    print("odd")

odd

In [7]:
li = [10,30,40,50,50,50,40]
li1 = []
for i in li:
    if i not in li1:
        li1.append(i)

a = sorted(li1)

a[-3]

30

In [8]:
st = "roshan"

print(st[::-1])

nahsor

In [18]:
st = "rrrr"

if st==st[::-1]:
    print("palindrome")

palindrome

In [20]:
st = "datascience"
count = 0
for i in st:
    if i in "aeiou":
        count+=1
print(count)

5

In [22]:
st  = "datascience"
d1 = {}

for i in st:
    count = st.count(i)
    if i not in d1:
        d1[i]=count
print(d1)

{'d': 1, 'a': 2, 't': 1, 's': 1, 'c': 2, 'i': 1, 'e': 2, 'n': 1}

In [26]:
st = "Hellow world"

# print(st.upper())
print(st.swapcase())

hELLOW WORLD

In [29]:
st = "roshan pardeshi"

# st = st.split()
st = st.replace(" ","_")
print(st)

roshan_pardeshi

In [37]:
st = "listen"
st1 = "slinet"
count=0
a = len(st)
if len(st)==len(st1):
    for i in st:
        if i in st1:
            count+=1
    if count==a:
        print("anagrams")
    else:
        print("not anagrams")

anagrams

In [39]:
st = "aaabbccaaddr"

for i in st:
    count=st.count(i)
    if count==1:
        print(i)
        break

r

In [43]:
st = "roshan pardeshi i am final year computer engineering student at gangamai college"

st1 = st.replace(" ","_")
st1

'roshan_pardeshi_i_am_final_year_computer_engineering_student_at_gangamai_college'

In [48]:
st = "roshanpardeshi35@345"

print(st.isdigit())
print(st.isalpha())

False
False

In [54]:
st = "roshan pardeshi kusumba"

st = st.split()

for i in st:
    print(i,end="_")

roshan_pardeshi_kusumba_

In [55]:
st = "roshan pardeshi kasba peth pune i am final year computer engineering student"

st = st.split()
count =0 
for i in st:
    count+=1

print(count)

12

In [61]:
st = "pardeshi rrrosihan"
size = ""
st = st.split()
for i in st:
    if len(i)>len(size):
        size=i

print(size)

rrrosihan

In [62]:
st = "roshan pardeshi kasba peth"

print(st.capitalize())

Roshan pardeshi kasba peth

In [68]:
st11 = "aaabbccddee"
size = ""

for i in st11:
    if i not in size:
        size+=i

print("",size)

 abcde

In [69]:
st = "aaabbc"

li = []

for i in st:
    count = st.count(i)

    if i not in li:
        print(i,":",count)
        li.append(i)

a : 3
b : 2
c : 1

In [70]:
sum1 = 0
num = 12345

for i in str(num):
    sum1+=int(i)

print(sum1)

15

In [71]:
fact = 1

num = 5

for i in range(1,num+1,1):
    fact*=i
print(fact)

120

In [80]:
perfect_nu = 29
total = 0

for i in range(1,perfect_nu):
    if perfect_nu%i==0:
        total+=i

if perfect_nu==total:
    print("A number is a perfect")
else:
    print("A number is a not perfect")

A number is a not perfect

In [82]:
a = 0
b = 1
num = 10

for i in range(1,num+1,1):
    print(a)
    c = a+b
    a=b
    b=c

0
1
1
2
3
5
8
13
21
34

In [97]:
count = 0 
def prime_number(n):
    factor = 0
    num = n
    count = 0 
    for i in range(2,num,1):
        if num%2==0:
            factor+=1
    if factor==0:
        print("prime number----",num)
        count+=1
    
        
    
       
for i in range(1,101,1):
    prime_number(i)
print(count)

prime number---- 1
prime number---- 2
prime number---- 3
prime number---- 5
prime number---- 7
prime number---- 9
prime number---- 11
prime number---- 13
prime number---- 15
prime number---- 17
prime number---- 19
prime number---- 21
prime number---- 23
prime number---- 25
prime number---- 27
prime number---- 29
prime number---- 31
prime number---- 33
prime number---- 35
prime number---- 37
prime number---- 39
prime number---- 41
prime number---- 43
prime number---- 45
prime number---- 47
prime number---- 49
prime number---- 51
prime number---- 53
prime number---- 55
prime number---- 57
prime number---- 59
prime number---- 61
prime number---- 63
prime number---- 65
prime number---- 67
prime number---- 69
prime number---- 71
prime number---- 73
prime number---- 75
prime number---- 77
prime number---- 79
prime number---- 81
prime number---- 83
prime number---- 85
prime number---- 87
prime number---- 89
prime number---- 91
prime number---- 93
prime number---- 95
prime number---- 97
prime number---- 99
0

In [102]:
num = 15

for i in range(0,15):
    if i%3==0 and i%5==0:
        print("fizz Buzz number",i)
    elif i%3==0:
        print("Fizz",i)
    else:
        print("Buzz",i)

fizz Buzz number 0
Buzz 1
Buzz 2
Fizz 3
Buzz 4
Buzz 5
Fizz 6
Buzz 7
Buzz 8
Fizz 9
Buzz 10
Buzz 11
Fizz 12
Buzz 13
Buzz 14

In [1]:
import math as m

In [3]:
a = 20
b = 30
print(m.gcd(a,b))
print(m.lcm(a,b))

10
60

In [11]:
num = 375
a1 = len(str(num))

no = num
res = 0
for i in range(1,num+1,1):
    a = no%10
    res = res + a**a1
    no = no//10

if res == num:
    print("amstrong")

In [16]:
a = 5

bin(a)

'0b101'

In [17]:
num = 123
num = str(num)
print(num[::-1])

321

In [18]:
for i in range(1,11,1):
    print(5*i)

5
10
15
20
25
30
35
40
45
50

In [22]:
sum=0
for i in range(1,101,1):
    if i%2==0:
        sum+=i
print(sum)

2550

In [26]:
year = 367

if year<=365:
    print("normal year")
else:
    print("leaf year")

leaf year

In [39]:
# *
# *
# *
# *
# *
# * * * * * * * 

for i in range(0,6,1):
    for j in range(0,6,1):
        if j==1:
            print("*",end="")
        if i==5:
            print("*",end="-")

    print()

*
*
*
*
*
*-**-*-*-*-*-

In [40]:
a = 10
b = 20
choice = int(input("enter"))
match(choice):
    case 1:
        print("addition")
        print(a+b)
    case 2:
        print("sunstraction")
        print(a-b)
    case 3:
        print("division")
        print(a/b)
    case 4:
        print("multiplication")
        print(a*b)
    case 5:
        print("fewler division")
        print(a//10)
    case _:
        print("invalied choice")

enter 1

addition
30

In [41]:
li = [10,20,20,30,40,50,60,70]

li1 = []

for i in li:
    if i not in li1:
        li1.append(i)

max1 = li1[0]
for i in li1:
    if max1<i:
        max=i
li1.remove(max1)
max2 = li1[0]
for i in li1:
    if max2<i:
        max2=i

print(max2)

70

In [42]:
li = [1,2,3,4,5,3,2,3,5,6,33,1,2,3,6,7,8,9]
li1 = []

for i in li:
    if i not in li1:
        li1.append(i)
print(li1)

[1, 2, 3, 4, 5, 6, 33, 7, 8, 9]

In [46]:
li = [1,2,3,4,5,6]
li1 = li[-1]
li2 = li[-2]

li.pop()
li.pop()

li.insert(0,li1)
li.insert(1,li2)

print(li)

[6, 5, 1, 2, 3, 4]

In [69]:
li = [[1, 2], [3, [4, 5]]]
li1=[]
for i in range(0,len(li),1):
    for j in range(0,len(li[i]),1):
            li1.append(li[i][j])

print(li1)

for i in li1:
    print(i)

[1, 2, 3, [4, 5]]
1
2
3
[4, 5]

In [71]:
li = [1,2,3,4,5,6,7]
li1 = [44,55,6,7,8,9]

print(set(li).intersection(set(li1)))

{6, 7}

In [72]:
for i in li:
    li1.append(i)
print(li1)

[44, 55, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7]

In [73]:
li = [0,1,2,0,3,4,5,0,2,5,8,1]
li1 = []

count = 0
for i in li:
    if i==0:
        count+=1
    else:
        li1.append(i)

for i in range(count):
    li1.append(0)
print(li1)

[1, 2, 3, 4, 5, 2, 5, 8, 1, 0, 0, 0]

In [75]:
li = [1,2,3,7]
li1 = []
target = 9

for i in range(0,len(li),1):
    for j in range(i+1,len(li)):
        if li[i]+li[j]==target:
            li1.append((li[i],li[j]))

print(li1)

[(2, 7)]

In [77]:
li = [1,2,3,4,5,6]

li1=li.split()

AttributeError: 'list' object has no attribute 'split'

In [81]:
li = [10,30,40,50,60,80,90]

for i in range(1,len(li)+2,1):
    if i not in li:
        print(i)

1
2
3
4
5
6
7
8

In [86]:
li = [1,2,3,4,5,6,7,1,8]

for i in li:
    count = li.count(i)

    if count>1:
        print(count)
        break

2

In [87]:
li = []
for i in range(1,20,1):
    if i%2==0:
        li.append(i**2)

print(li)

[4, 16, 36, 64, 100, 144, 196, 256, 324]

In [88]:
li = [1,2,3,4,5]

li.append(10)

li.extend([1,2,3,4,5])

In [89]:
li

[1, 2, 3, 4, 5, 10, 1, 2, 3, 4, 5]

In [92]:
st = ["apply","cerry","banana","mango"]

print(sorted(st))

['apply', 'banana', 'cerry', 'mango']

In [94]:
s1 = {1,2,3,4,5}
s2 = {4,5,6,7,8}

print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s1.symmetric_difference(s2))

{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}

In [96]:
li = [10,20,30,40,50]

print(sorted(li))

[10, 20, 30, 40, 50]

In [98]:
st = "datascience"
li1 = []
for i in st:
    count = st.count(i)
    
    if count>1:
        pass
    else:
        li1.append(i)

print(li1)

['d', 't', 's', 'i', 'n']

In [121]:
d1 = {1:"roshan",2:"sonu",3:"monu"}
d2 = {}

# for i in 
a = d1.keys()
b = d1.values()
for i in d1:
    d2[i]=d1.values()

In [122]:
d2

{1: dict_values(['roshan', 'sonu', 'monu']),
 2: dict_values(['roshan', 'sonu', 'monu']),
 3: dict_values(['roshan', 'sonu', 'monu'])}

In [125]:
d1 = {1:"roshan",2:"sonu",3:"monu"}

print(sorted(d1.values()))

['monu', 'roshan', 'sonu']

In [134]:
st = "roshan pardeshi is good boy"
d1 = {}
a = st.split()
for i in range(0,len(st),1):
    
    count = st.count(st[i])

    d1[st[i]] = count

print(d1)

{'r': 2, 'o': 4, 's': 3, 'h': 2, 'a': 2, 'n': 1, ' ': 4, 'p': 1, 'd': 2, 'e': 1, 'i': 2, 'g': 1, 'b': 1, 'y': 1}

In [136]:
!pip install tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D, MaxPooling2D,
    Flatten, Dense
)

model = Sequential([
    Conv2D(32, (3, 3), activation="relu",
           input_shape=(128, 128, 3)),

    MaxPooling2D((2, 2)),

    Conv2D(64, (3, 3), activation="relu"),

    MaxPooling2D((2, 2)),

    Flatten(),

    Dense(128, activation="relu"),

    Dense(4, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

Defaulting to user installation because normal site-packages is not writeable
Collecting tensorflow
  Downloading tensorflow-2.22.0rc0-cp314-cp314-win_amd64.whl.metadata (4.6 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.5.1-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (26.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: six>=1.12.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (1.81.1)
Collecting keras-nightly>=3.12.0.dev (from tensorflow)
  Downloading keras_nightly-3.16.0.dev2026101704-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (2.4.6)
Collecting h5py~=3.15.1 (from tensorflow)
  Downloading h5py-3.15.1-cp314-cp314-win_amd64.whl.metadata (3.1 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.6.0-cp314-cp314-win_amd64.whl.metadata (8.8 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.48.0-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras-nightly>=3.12.0.dev->tensorflow)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras-nightly>=3.12.0.dev->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras-nightly>=3.12.0.dev->tensorflow)
  Downloading optree-0.20.0-cp314-cp314-win_amd64.whl.metadata (33 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras-nightly>=3.12.0.dev->tensorflow)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from rich->keras-nightly>=3.12.0.dev->tensorflow) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras-nightly>=3.12.0.dev->tensorflow)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.22.0rc0-cp314-cp314-win_amd64.whl (384.1 MB)
   ---------------------------------------- 0.0/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.5/384.1 MB 524.6 kB/s eta 0:12:12
   ---------------------------------------- 0.5/384.1 MB 524.6 kB/s eta 0:12:12
   ---------------------------------------- 0.8/384.1 MB 582.5 kB/s eta 0:10:59
   ---------------------------------------- 0.8/384.1 MB 582.5 kB/s eta 0:10:59
   ---------------------------------------- 1.0/384.1 MB 611.6 kB/s eta 0:10:27
   ---------------------------------------- 1.0/384.1 MB 611.6 kB/s eta 0:10:27
   ---------------------------------------- 1.3/384.1 MB 637.3 kB/s eta 0:10:01
   ---------------------------------------- 1.3/384.1 MB 637.3 kB/s eta 0:10:01
   ---------------------------------------- 1.6/384.1 MB 652.5 kB/s eta 0:09:47
   ---------------------------------------- 1.6/384.1 MB 652.5 kB/s eta 0:09:47
   ---------------------------------------- 1.8/384.1 MB 655.2 kB/s eta 0:09:44
   ---------------------------------------- 2.1/384.1 MB 657.6 kB/s eta 0:09:41
   ---------------------------------------- 2.1/384.1 MB 657.6 kB/s eta 0:09:41
   ---------------------------------------- 2.4/384.1 MB 665.1 kB/s eta 0:09:34
   ---------------------------------------- 2.4/384.1 MB 665.1 kB/s eta 0:09:34
   ---------------------------------------- 2.6/384.1 MB 666.7 kB/s eta 0:09:33
   ---------------------------------------- 2.6/384.1 MB 666.7 kB/s eta 0:09:33
   ---------------------------------------- 2.9/384.1 MB 671.9 kB/s eta 0:09:28
   ---------------------------------------- 2.9/384.1 MB 671.9 kB/s eta 0:09:28
   ---------------------------------------- 3.1/384.1 MB 675.2 kB/s eta 0:09:25
   ---------------------------------------- 3.4/384.1 MB 676.7 kB/s eta 0:09:23
   ---------------------------------------- 3.4/384.1 MB 676.7 kB/s eta 0:09:23
   ---------------------------------------- 3.7/384.1 MB 680.8 kB/s eta 0:09:19
   ---------------------------------------- 3.7/384.1 MB 680.8 kB/s eta 0:09:19
   ---------------------------------------- 3.9/384.1 MB 683.2 kB/s eta 0:09:17
   ---------------------------------------- 3.9/384.1 MB 683.2 kB/s eta 0:09:17
   ---------------------------------------- 4.2/384.1 MB 685.2 kB/s eta 0:09:15
   ---------------------------------------- 4.5/384.1 MB 684.5 kB/s eta 0:09:15
   ---------------------------------------- 4.5/384.1 MB 684.5 kB/s eta 0:09:15
   ---------------------------------------- 4.7/384.1 MB 686.7 kB/s eta 0:09:13
   ---------------------------------------- 4.7/384.1 MB 686.7 kB/s eta 0:09:13
    --------------------------------------- 5.0/384.1 MB 682.6 kB/s eta 0:09:16
    --------------------------------------- 5.0/384.1 MB 682.6 kB/s eta 0:09:16
    --------------------------------------- 5.2/384.1 MB 684.7 kB/s eta 0:09:14
    --------------------------------------- 5.2/384.1 MB 684.7 kB/s eta 0:09:14
    --------------------------------------- 5.5/384.1 MB 686.8 kB/s eta 0:09:12
    --------------------------------------- 5.8/384.1 MB 688.1 kB/s eta 0:09:10
    --------------------------------------- 5.8/384.1 MB 688.1 kB/s eta 0:09:10
    --------------------------------------- 6.0/384.1 MB 689.9 kB/s eta 0:09:09
    --------------------------------------- 6.0/384.1 MB 689.9 kB/s eta 0:09:09
    --------------------------------------- 6.3/384.1 MB 692.3 kB/s eta 0:09:06
    --------------------------------------- 6.3/384.1 MB 692.3 kB/s eta 0:09:06
    --------------------------------------- 6.3/384.1 MB 692.3 kB/s eta 0:09:06
    --------------------------------------- 6.6/384.1 MB 677.8 kB/s eta 0:09:17
    --------------------------------------- 6.6/384.1 MB 677.8 kB/s eta 0:09:17
    --------------------------------------- 6.6/384.1 MB 677.8 kB/s eta 0:09:17
    --------------------------------------- 6.8/384.1 MB 658.5 kB/s eta 0:09:33
    --------------------------------------- 6.8/384.1 MB 658.5 kB/s eta 0:09:33
    --------------------------------------- 6.8/384.1 MB 658.5 kB/s eta 0:09:33
    --------------------------------------- 7.1/384.1 MB 647.4 kB/s eta 0:09:43
    --------------------------------------- 7.1/384.1 MB 647.4 kB/s eta 0:09:43
    --------------------------------------- 7.3/384.1 MB 639.4 kB/s eta 0:09:50
    --------------------------------------- 7.3/384.1 MB 639.4 kB/s eta 0:09:50
    --------------------------------------- 7.3/384.1 MB 639.4 kB/s eta 0:09:50
    --------------------------------------- 7.6/384.1 MB 631.5 kB/s eta 0:09:57
    --------------------------------------- 7.6/384.1 MB 631.5 kB/s eta 0:09:57
    --------------------------------------- 7.6/384.1 MB 631.5 kB/s eta 0:09:57
    --------------------------------------- 7.9/384.1 MB 622.6 kB/s eta 0:10:05
    --------------------------------------- 7.9/384.1 MB 622.6 kB/s eta 0:10:05
    --------------------------------------- 8.1/384.1 MB 614.4 kB/s eta 0:10:12
    --------------------------------------- 8.1/384.1 MB 614.4 kB/s eta 0:10:12
    --------------------------------------- 8.1/384.1 MB 614.4 kB/s eta 0:10:12
    --------------------------------------- 8.4/384.1 MB 607.2 kB/s eta 0:10:19
    --------------------------------------- 8.4/384.1 MB 607.2 kB/s eta 0:10:19
    --------------------------------------- 8.4/384.1 MB 607.2 kB/s eta 0:10:19
    --------------------------------------- 8.7/384.1 MB 604.4 kB/s eta 0:10:22
    --------------------------------------- 8.7/384.1 MB 604.4 kB/s eta 0:10:22
    --------------------------------------- 8.9/384.1 MB 599.7 kB/s eta 0:10:26
    --------------------------------------- 8.9/384.1 MB 599.7 kB/s eta 0:10:26
    --------------------------------------- 8.9/384.1 MB 599.7 kB/s eta 0:10:26
    --------------------------------------- 9.2/384.1 MB 593.3 kB/s eta 0:10:32
    --------------------------------------- 9.2/384.1 MB 593.3 kB/s eta 0:10:32
    --------------------------------------- 9.2/384.1 MB 593.3 kB/s eta 0:10:32
    --------------------------------------- 9.4/384.1 MB 587.7 kB/s eta 0:10:38
    --------------------------------------- 9.4/384.1 MB 587.7 kB/s eta 0:10:38
   - -------------------------------------- 9.7/384.1 MB 585.2 kB/s eta 0:10:40
   - -------------------------------------- 9.7/384.1 MB 585.2 kB/s eta 0:10:40
   - -------------------------------------- 9.7/384.1 MB 585.2 kB/s eta 0:10:40
   - ------------------------------------- 10.0/384.1 MB 582.6 kB/s eta 0:10:43
   - ------------------------------------- 10.0/384.1 MB 582.6 kB/s eta 0:10:43
   - ------------------------------------- 10.0/384.1 MB 582.6 kB/s eta 0:10:43
   - ------------------------------------- 10.2/384.1 MB 576.9 kB/s eta 0:10:49
   - ------------------------------------- 10.2/384.1 MB 576.9 kB/s eta 0:10:49
   - ------------------------------------- 10.5/384.1 MB 576.0 kB/s eta 0:10:49
   - ------------------------------------- 10.5/384.1 MB 576.0 kB/s eta 0:10:49
   - ------------------------------------- 10.5/384.1 MB 576.0 kB/s eta 0:10:49
   - ------------------------------------- 10.7/384.1 MB 572.3 kB/s eta 0:10:53
   - ------------------------------------- 10.7/384.1 MB 572.3 kB/s eta 0:10:53
   - ------------------------------------- 10.7/384.1 MB 572.3 kB/s eta 0:10:53
   - ------------------------------------- 11.0/384.1 MB 568.6 kB/s eta 0:10:57
   - ------------------------------------- 11.0/384.1 MB 568.6 kB/s eta 0:10:57
   - ------------------------------------- 11.3/384.1 MB 567.2 kB/s eta 0:10:58
   - ------------------------------------- 11.3/384.1 MB 567.2 kB/s eta 0:10:58
   - ------------------------------------- 11.3/384.1 MB 567.2 kB/s eta 0:10:58
   - ------------------------------------- 11.5/384.1 MB 561.4 kB/s eta 0:11:04
   - ------------------------------------- 11.5/384.1 MB 561.4 kB/s eta 0:11:04
   - ------------------------------------- 11.5/384.1 MB 561.4 kB/s eta 0:11:04
   - ------------------------------------- 11.8/384.1 MB 561.3 kB/s eta 0:11:04
   - ------------------------------------- 11.8/384.1 MB 561.3 kB/s eta 0:11:04
   - ------------------------------------- 12.1/384.1 MB 563.1 kB/s eta 0:11:01
   - ------------------------------------- 12.1/384.1 MB 563.1 kB/s eta 0:11:01
   - ------------------------------------- 12.3/384.1 MB 565.5 kB/s eta 0:10:58
   - ------------------------------------- 12.3/384.1 MB 565.5 kB/s eta 0:10:58
   - ------------------------------------- 12.3/384.1 MB 565.5 kB/s eta 0:10:58
   - ------------------------------------- 12.6/384.1 MB 561.4 kB/s eta 0:11:02
   - ------------------------------------- 12.6/384.1 MB 561.4 kB/s eta 0:11:02
   - ------------------------------------- 12.8/384.1 MB 560.0 kB/s eta 0:11:03
   - ------------------------------------- 12.8/384.1 MB 560.0 kB/s eta 0:11:03
   - ------------------------------------- 13.1/384.1 MB 561.6 kB/s eta 0:11:01
   - ------------------------------------- 13.1/384.1 MB 561.6 kB/s eta 0:11:01
   - ------------------------------------- 13.4/384.1 MB 563.5 kB/s eta 0:10:58
   - ------------------------------------- 13.4/384.1 MB 563.5 kB/s eta 0:10:58
   - ------------------------------------- 13.4/384.1 MB 563.5 kB/s eta 0:10:58
   - ------------------------------------- 13.6/384.1 MB 561.4 kB/s eta 0:11:00
   - ------------------------------------- 13.6/384.1 MB 561.4 kB/s eta 0:11:00
   - ------------------------------------- 13.9/384.1 MB 560.8 kB/s eta 0:11:01
   - ------------------------------------- 13.9/384.1 MB 560.8 kB/s eta 0:11:01
   - ------------------------------------- 13.9/384.1 MB 560.8 kB/s eta 0:11:01
   - ------------------------------------- 14.2/384.1 MB 557.3 kB/s eta 0:11:04
   - ------------------------------------- 14.2/384.1 MB 557.3 kB/s eta 0:11:04
   - ------------------------------------- 14.2/384.1 MB 557.3 kB/s eta 0:11:04
   - ------------------------------------- 14.4/384.1 MB 552.8 kB/s eta 0:11:09
   - ------------------------------------- 14.4/384.1 MB 552.8 kB/s eta 0:11:09
   - ------------------------------------- 14.4/384.1 MB 552.8 kB/s eta 0:11:09
   - ------------------------------------- 14.7/384.1 MB 552.1 kB/s eta 0:11:10
   - ------------------------------------- 14.7/384.1 MB 552.1 kB/s eta 0:11:10
   - ------------------------------------- 14.9/384.1 MB 550.5 kB/s eta 0:11:11
   - ------------------------------------- 14.9/384.1 MB 550.5 kB/s eta 0:11:11
   - ------------------------------------- 14.9/384.1 MB 550.5 kB/s eta 0:11:11
   - ------------------------------------- 15.2/384.1 MB 548.8 kB/s eta 0:11:13
   - ------------------------------------- 15.2/384.1 MB 548.8 kB/s eta 0:11:13
   - ------------------------------------- 15.2/384.1 MB 548.8 kB/s eta 0:11:13
   - ------------------------------------- 15.5/384.1 MB 546.3 kB/s eta 0:11:15
   - ------------------------------------- 15.5/384.1 MB 546.3 kB/s eta 0:11:15
   - ------------------------------------- 15.5/384.1 MB 546.3 kB/s eta 0:11:15
   - ------------------------------------- 15.7/384.1 MB 543.3 kB/s eta 0:11:18
   - ------------------------------------- 15.7/384.1 MB 543.3 kB/s eta 0:11:18
   - ------------------------------------- 15.7/384.1 MB 543.3 kB/s eta 0:11:18
   - ------------------------------------- 16.0/384.1 MB 541.9 kB/s eta 0:11:20
   - ------------------------------------- 16.0/384.1 MB 541.9 kB/s eta 0:11:20
   - ------------------------------------- 16.0/384.1 MB 541.9 kB/s eta 0:11:20
   - ------------------------------------- 16.3/384.1 MB 539.1 kB/s eta 0:11:23
   - ------------------------------------- 16.3/384.1 MB 539.1 kB/s eta 0:11:23
   - ------------------------------------- 16.3/384.1 MB 539.1 kB/s eta 0:11:23
   - ------------------------------------- 16.5/384.1 MB 536.4 kB/s eta 0:11:26
   - ------------------------------------- 16.5/384.1 MB 536.4 kB/s eta 0:11:26
   - ------------------------------------- 16.8/384.1 MB 536.5 kB/s eta 0:11:25
   - ------------------------------------- 16.8/384.1 MB 536.5 kB/s eta 0:11:25
   - ------------------------------------- 17.0/384.1 MB 536.3 kB/s eta 0:11:25
   - ------------------------------------- 17.0/384.1 MB 536.3 kB/s eta 0:11:25
   - ------------------------------------- 17.3/384.1 MB 535.6 kB/s eta 0:11:25
   - ------------------------------------- 17.3/384.1 MB 535.6 kB/s eta 0:11:25
   - ------------------------------------- 17.6/384.1 MB 535.3 kB/s eta 0:11:25
   - ------------------------------------- 17.6/384.1 MB 535.3 kB/s eta 0:11:25
   - ------------------------------------- 17.6/384.1 MB 535.3 kB/s eta 0:11:25
   - ------------------------------------- 17.8/384.1 MB 528.7 kB/s eta 0:11:33
   - ------------------------------------- 17.8/384.1 MB 528.7 kB/s eta 0:11:33
   - ------------------------------------- 18.1/384.1 MB 527.2 kB/s eta 0:11:35
   - ------------------------------------- 18.1/384.1 MB 527.2 kB/s eta 0:11:35
   - ------------------------------------- 18.1/384.1 MB 527.2 kB/s eta 0:11:35
   - ------------------------------------- 18.4/384.1 MB 518.7 kB/s eta 0:11:46
   - ------------------------------------- 18.4/384.1 MB 518.7 kB/s eta 0:11:46
   - ------------------------------------- 18.4/384.1 MB 518.7 kB/s eta 0:11:46
   - ------------------------------------- 18.6/384.1 MB 512.6 kB/s eta 0:11:53
   - ------------------------------------- 18.6/384.1 MB 512.6 kB/s eta 0:11:53
   - ------------------------------------- 18.6/384.1 MB 512.6 kB/s eta 0:11:53
   - ------------------------------------- 18.6/384.1 MB 512.6 kB/s eta 0:11:53
   - ------------------------------------- 18.9/384.1 MB 506.9 kB/s eta 0:12:01
   - ------------------------------------- 18.9/384.1 MB 506.9 kB/s eta 0:12:01
   - ------------------------------------- 19.1/384.1 MB 502.6 kB/s eta 0:12:07
   - ------------------------------------- 19.1/384.1 MB 502.6 kB/s eta 0:12:07
   - ------------------------------------- 19.4/384.1 MB 501.0 kB/s eta 0:12:08
   - ------------------------------------- 19.4/384.1 MB 501.0 kB/s eta 0:12:08
   - ------------------------------------- 19.7/384.1 MB 499.4 kB/s eta 0:12:10
   - ------------------------------------- 19.7/384.1 MB 499.4 kB/s eta 0:12:10
   - ------------------------------------- 19.7/384.1 MB 499.4 kB/s eta 0:12:10
   -- ------------------------------------ 19.9/384.1 MB 493.1 kB/s eta 0:12:19
   -- ------------------------------------ 19.9/384.1 MB 493.1 kB/s eta 0:12:19
   -- ------------------------------------ 19.9/384.1 MB 493.1 kB/s eta 0:12:19
   -- ------------------------------------ 20.2/384.1 MB 491.6 kB/s eta 0:12:21
   -- ------------------------------------ 20.2/384.1 MB 491.6 kB/s eta 0:12:21
   -- ------------------------------------ 20.4/384.1 MB 490.3 kB/s eta 0:12:22
   -- ------------------------------------ 20.4/384.1 MB 490.3 kB/s eta 0:12:22
   -- ------------------------------------ 20.7/384.1 MB 485.8 kB/s eta 0:12:28
   -- ------------------------------------ 20.7/384.1 MB 485.8 kB/s eta 0:12:28
   -- ------------------------------------ 21.0/384.1 MB 488.4 kB/s eta 0:12:24
   -- ------------------------------------ 21.0/384.1 MB 488.4 kB/s eta 0:12:24
   -- ------------------------------------ 21.2/384.1 MB 491.0 kB/s eta 0:12:20
   -- ------------------------------------ 21.2/384.1 MB 491.0 kB/s eta 0:12:20
   -- ------------------------------------ 21.5/384.1 MB 493.6 kB/s eta 0:12:15
   -- ------------------------------------ 21.5/384.1 MB 493.6 kB/s eta 0:12:15

  WARNING: The script wheel.exe is installed in 'C:\Users\Admin\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown-it.exe is installed in 'C:\Users\Admin\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts import_pb_to_tensorboard.exe, saved_model_cli.exe, tensorboard.exe, tf_upgrade_v2.exe, tflite_convert.exe and toco.exe are installed in 'C:\Users\Admin\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.36.2 which is incompatible.
google-api-core 2.25.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5, but you have protobuf 7.36.2 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.36.2 which is incompatible.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
model

In [1]:
import pandas as pd
import numpy as np

In [174]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\employee_practice_dataset.csv")

In [3]:
df.head()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212

In [4]:
df.shape

(20, 11)

In [5]:
df.describe()

          emp_id        age         salary    dept_id  manager_id
count   20.00000  19.000000      19.000000  20.000000   17.000000
mean   110.50000  30.684211  102947.368421   1.950000  108.529412
std      5.91608   9.866062   98397.986477   0.825578    5.363274
min    101.00000  -2.000000   47000.000000   1.000000  103.000000
25%    105.75000  27.500000   66000.000000   1.000000  105.000000
50%    110.50000  31.000000   78000.000000   2.000000  105.000000
75%    115.25000  35.500000   97000.000000   3.000000  110.000000
max    120.00000  45.000000  500000.000000   3.000000  117.000000

In [6]:
df.describe(include="object")

,name,job_title,city,hire_date,email,phone
count,20,20,19,20,20,20
unique,19,7,6,19,19,19
top,Priya Patil,Manager,Mumbai,2020-03-10,priya.patil@example.com,98765 43211
freq,2,5,6,2,2,2

In [7]:
df.tail()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [8]:
df.sample()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [9]:
df.columns.to_list()

['emp_id',
 'name',
 'age',
 'salary',
 'dept_id',
 'job_title',
 'city',
 'hire_date',
 'manager_id',
 'email',
 'phone']

In [10]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [11]:
df.set_index('manager_id')

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,email,phone
manager_id,,,,,,,,,,
103.0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,aarav@example.com,9876543210
105.0,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,priya.patil@example.com,98765 43211
117.0,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,rahul@example.com,9988776655
110.0,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,sneha@example.com,9123456789
117.0,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,vikram@example.com,9876543212
NaN,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,om@example.com,9876543213
108.0,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,isha@example.com,9876543214
105.0,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,kunal@example.com,9876543215
105.0,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,priya.patil@example.com,98765 43211
110.0,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,meera@example.com,9876543217
103.0,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,aditya@example.com,9876543218
105.0,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,neha@example.com,9876543219
117.0,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,rohan@example.com,9876543220
110.0,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,anaya@example.com,9876543221
NaN,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,kabir@example.com,9876543222
105.0,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,sana@example.com,9876543223
NaN,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,arjun@example.com,9876543224
103.0,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,maya@example.com,9876543225
105.0,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,dev@example.com,9876543226
117.0,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,tara.example.com,123

In [12]:
df.reset_index()

,index,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
5,5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
11,11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
12,12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
14,14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
15,15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [13]:
df.head()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212

In [14]:
df.tail()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [17]:
df["name"].str.strip()

0       Aarav Sharma
1        Priya Patil
2     Rahul Deshmukh
3        Sneha Joshi
4        Vikram More
5           Om Pawar
6          Isha Shah
7       Kunal Jadhav
8        Priya Patil
9     Meera Kulkarni
10      Aditya Joshi
11        Neha Patil
12        Rohan More
13        Anaya Shah
14       Kabir Pawar
15         Sana Khan
16       Arjun Desai
17          Maya Rao
18      Dev Kulkarni
19        Tara Singh
Name: name, dtype: object

In [18]:
df[["name","age","salary"]]

              name   age    salary
0     Aarav Sharma  24.0   52000.0
1      Priya Patil  29.0   78000.0
2   Rahul Deshmukh  35.0   95000.0
3      Sneha Joshi  31.0   68000.0
4      Vikram More  42.0  125000.0
5         Om Pawar  26.0   61000.0
6        Isha Shah   NaN   72000.0
7     Kunal Jadhav  38.0  105000.0
8      Priya Patil  29.0   78000.0
9   Meera Kulkarni  33.0   88000.0
10    Aditya Joshi  27.0   58000.0
11      Neha Patil  45.0       NaN
12      Rohan More  30.0   99000.0
13      Anaya Shah  36.0   83000.0
14     Kabir Pawar  28.0   47000.0
15       Sana Khan  32.0   92000.0
16     Arjun Desai  41.0  115000.0
17        Maya Rao  25.0   64000.0
18    Dev Kulkarni  34.0   76000.0
19      Tara Singh  -2.0  500000.0

In [19]:
df.shape

(20, 11)

In [22]:
df["salary"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: salary
Non-Null Count  Dtype
--------------  -----
19 non-null     float64
dtypes: float64(1)
memory usage: 292.0 bytes

In [24]:
df.describe(include="all")

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
count,20.00000,20,19.000000,19.000000,20.000000,20,19,20,17.000000,20,20
unique,NaN,19,NaN,NaN,NaN,7,6,19,NaN,19,19
top,NaN,Priya Patil,NaN,NaN,NaN,Manager,Mumbai,2020-03-10,NaN,priya.patil@example.com,98765 43211
freq,NaN,2,NaN,NaN,NaN,5,6,2,NaN,2,2
mean,110.50000,NaN,30.684211,102947.368421,1.950000,NaN,NaN,NaN,108.529412,NaN,NaN
std,5.91608,NaN,9.866062,98397.986477,0.825578,NaN,NaN,NaN,5.363274,NaN,NaN
min,101.00000,NaN,-2.000000,47000.000000,1.000000,NaN,NaN,NaN,103.000000,NaN,NaN
25%,105.75000,NaN,27.500000,66000.000000,1.000000,NaN,NaN,NaN,105.000000,NaN,NaN
50%,110.50000,NaN,31.000000,78000.000000,2.000000,NaN,NaN,NaN,105.000000,NaN,NaN
75%,115.25000,NaN,35.500000,97000.000000,3.000000,NaN,NaN,NaN,110.000000,NaN,NaN
max,120.00000,NaN,45.000000,500000.000000,3.000000,NaN,NaN,NaN,117.000000,NaN,NaN

In [25]:
df["name"].to_list()

['Aarav Sharma',
 'Priya Patil',
 'Rahul Deshmukh',
 'Sneha Joshi',
 'Vikram More',
 'Om Pawar',
 'Isha Shah',
 'Kunal Jadhav',
 'Priya Patil',
 'Meera Kulkarni',
 'Aditya Joshi',
 'Neha Patil',
 'Rohan More',
 'Anaya Shah',
 'Kabir Pawar',
 'Sana Khan',
 'Arjun Desai',
 'Maya Rao',
 'Dev Kulkarni',
 'Tara Singh']

In [26]:
df.set_index("age")

,emp_id,name,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
age,,,,,,,,,,
24.0,101,Aarav Sharma,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
29.0,102,Priya Patil,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
35.0,103,Rahul Deshmukh,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
31.0,104,Sneha Joshi,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
42.0,105,Vikram More,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
26.0,106,Om Pawar,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
NaN,107,Isha Shah,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
38.0,108,Kunal Jadhav,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
29.0,109,Priya Patil,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
33.0,110,Meera Kulkarni,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
27.0,111,Aditya Joshi,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
45.0,112,Neha Patil,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
30.0,113,Rohan More,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
36.0,114,Anaya Shah,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
28.0,115,Kabir Pawar,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
32.0,116,Sana Khan,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
41.0,117,Arjun Desai,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
25.0,118,Maya Rao,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
34.0,119,Dev Kulkarni,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
-2.0,120,Tara Singh,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [27]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [28]:
df.reset_index()

,index,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
5,5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
11,11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
12,12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
14,14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
15,15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [32]:
df[["name","age"]]

              name   age
0     Aarav Sharma  24.0
1      Priya Patil  29.0
2   Rahul Deshmukh  35.0
3      Sneha Joshi  31.0
4      Vikram More  42.0
5         Om Pawar  26.0
6        Isha Shah   NaN
7     Kunal Jadhav  38.0
8      Priya Patil  29.0
9   Meera Kulkarni  33.0
10    Aditya Joshi  27.0
11      Neha Patil  45.0
12      Rohan More  30.0
13      Anaya Shah  36.0
14     Kabir Pawar  28.0
15       Sana Khan  32.0
16     Arjun Desai  41.0
17        Maya Rao  25.0
18    Dev Kulkarni  34.0
19      Tara Singh  -2.0

In [33]:
df.loc[5:10:1]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218

In [34]:
df.iloc[5:11:1]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218

In [35]:
df[df["salary"]>80000]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [36]:
df[(df["dept_id"]==1)&(df["salary"]>60000)]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225

In [43]:
res = df[df["city"].isin(["Pune","mumbai"])]

In [44]:
res

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224

In [47]:
df[df["salary"].isin([50000,90000])]

Empty DataFrame
Columns: [emp_id, name, age, salary, dept_id, job_title, city, hire_date, manager_id, email, phone]
Index: []

In [53]:
df[df["name"].apply(lambda x:x.startswith("A"))]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224

In [55]:
df["name"].apply(lambda x:x[0])

0     A
1     P
2     R
3     S
4     V
5     O
6     I
7     K
8     P
9     M
10    A
11    N
12    R
13    A
14    K
15    S
16    A
17    M
18    D
19    T
Name: name, dtype: object

In [57]:
df[df["salary"].query("salary">100)]

AttributeError: 'Series' object has no attribute 'query'

In [58]:
df[["name","salary"]].sort_values("salary",ascending=False).head(5)

            name    salary
19    Tara Singh  500000.0
4    Vikram More  125000.0
16   Arjun Desai  115000.0
7   Kunal Jadhav  105000.0
12    Rohan More   99000.0

In [76]:
df["job_title"].apply(lambda x:x.split()[1])

IndexError: list index out of range

In [60]:
df["job_title"]

0            Analyst
1            Manager
2           Engineer
3       HR Executive
4     Senior Manager
5            Analyst
6       Data Analyst
7            Manager
8            Manager
9       HR Executive
10          Engineer
11    Senior Manager
12          Engineer
13      Data Analyst
14           Analyst
15           Manager
16    Senior Manager
17           Analyst
18           Manager
19          Director
Name: job_title, dtype: object

In [79]:
df[df["job_title"]=="Manager"]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226

In [80]:
df[df["manager_id"].isnull()]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224

In [81]:
df[df["city"].isnull()]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [85]:
df.select_dtypes(int)

    emp_id  dept_id
0      101        1
1      102        2
2      103        1
3      104        3
4      105        2
5      106        1
6      107        3
7      108        2
8      109        2
9      110        3
10     111        1
11     112        2
12     113        1
13     114        3
14     115        1
15     116        2
16     117        3
17     118        1
18     119        2
19     120        3

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      20 non-null     int64
 1   name        20 non-null     object
 2   age         19 non-null     float64
 3   salary      19 non-null     float64
 4   dept_id     20 non-null     int64
 5   job_title   20 non-null     object
 6   city        19 non-null     object
 7   hire_date   20 non-null     object
 8   manager_id  17 non-null     float64
 9   email       20 non-null     object
 10  phone       20 non-null     object
dtypes: float64(3), int64(2), object(6)
memory usage: 1.8+ KB

In [90]:
df["hire_date"] = pd.to_datetime(df["hire_date"])

KeyError: 'hire_date'

In [89]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: hire_date
Non-Null Count  Dtype
--------------  -----
20 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 292.0 bytes

In [92]:
df["hire_date"] = pd.to_datetime(df["hire_date"])

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      20 non-null     int64
 1   name        20 non-null     object
 2   age         19 non-null     float64
 3   salary      19 non-null     float64
 4   dept_id     20 non-null     int64
 5   job_title   20 non-null     object
 6   city        19 non-null     object
 7   hire_date   20 non-null     datetime64[ns]
 8   manager_id  17 non-null     float64
 9   email       20 non-null     object
 10  phone       20 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(2), object(5)
memory usage: 1.8+ KB

In [95]:
df.duplicated().sum()

np.int64(0)

In [96]:
df.sort_values("salary",ascending=False)

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219

In [102]:
df.sort_values("dept_id").sort_values("salary",ascending=False)

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219

In [106]:
df["city"].unique()

array(['Pune', 'Mumbai', 'Nashik', 'pune ', 'Bengaluru', 'PUNE ', nan],
      dtype=object)

In [107]:
df["city"].value_counts()

city
Mumbai       6
Pune         5
Nashik       3
Bengaluru    3
pune         1
PUNE         1
Name: count, dtype: int64

In [110]:
df["city"]=df.loc[df["city"]=="PUNE","city"]="Pune"

In [112]:
df["city"]

0     Pune
1     Pune
2     Pune
3     Pune
4     Pune
5     Pune
6     Pune
7     Pune
8     Pune
9     Pune
10    Pune
11    Pune
12    Pune
13    Pune
14    Pune
15    Pune
16    Pune
17    Pune
18    Pune
19    Pune
Name: city, dtype: object

In [115]:
df["city"].str.strip()

0          Pune
1        Mumbai
2          Pune
3        Nashik
4        Mumbai
5          pune
6     Bengaluru
7          Pune
8        Mumbai
9        Nashik
10         Pune
11       Mumbai
12    Bengaluru
13         PUNE
14       Nashik
15       Mumbai
16         Pune
17    Bengaluru
18       Mumbai
19          NaN
Name: city, dtype: object

In [116]:
df.dropna(inplace=True)

In [117]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226

In [119]:
df.loc[df["city"]=="PUNE","city"]="Pune"

In [120]:
df["city"]

0          Pune
1        Mumbai
2          Pune
3        Nashik
4        Mumbai
7          Pune
8        Mumbai
9        Nashik
10         Pune
12    Bengaluru
13        PUNE
15       Mumbai
17    Bengaluru
18       Mumbai
Name: city, dtype: object

In [125]:
df["city"].str.strip()

0          Pune
1        Mumbai
2          Pune
3        Nashik
4        Mumbai
7          Pune
8        Mumbai
9        Nashik
10         Pune
12    Bengaluru
13         PUNE
15       Mumbai
17    Bengaluru
18       Mumbai
Name: city, dtype: object

In [129]:
df.drop(13)

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226

In [130]:
df.groupby("city").salary.sum()

city
Bengaluru    163000.0
Mumbai       449000.0
Nashik       156000.0
PUNE          83000.0
Pune         310000.0
Name: salary, dtype: float64

In [131]:
df["job_title"].value_counts()

job_title
Manager           5
Engineer          3
Analyst           2
HR Executive      2
Senior Manager    1
Data Analyst      1
Name: count, dtype: int64

In [132]:
df["salary"].nlargest()

4     125000.0
7     105000.0
12     99000.0
2      95000.0
15     92000.0
Name: salary, dtype: float64

In [135]:
df["salary"].nsmallest()

0     52000.0
10    58000.0
17    64000.0
3     68000.0
18    76000.0
Name: salary, dtype: float64

In [137]:
df["salary"].rank()

0      1.0
1      6.5
2     11.0
3      4.0
4     14.0
7     13.0
8      6.5
9      9.0
10     2.0
12    12.0
13     8.0
15    10.0
17     3.0
18     5.0
Name: salary, dtype: float64

In [138]:
df["name"].isnull().sum()

np.int64(0)

In [139]:
df.isnull().sum()

emp_id        0
name          0
age           0
salary        0
dept_id       0
job_title     0
city          0
hire_date     0
manager_id    0
email         0
phone         0
dtype: int64

In [143]:
df.randon_state(20)

AttributeError: 'DataFrame' object has no attribute 'randon_state'

In [144]:
df["Bonus"] = df["salary"]+(df["salary"]*10/100)

In [145]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone,Bonus
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210,57200.0
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211,85800.0
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655,104500.0
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789,74800.0
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212,137500.0
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215,115500.0
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211,85800.0
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217,96800.0
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218,63800.0
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220,108900.0
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221,91300.0
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223,101200.0
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225,70400.0
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226,83600.0

In [147]:
df.drop(columns="Bonus")

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226

In [154]:
df[(df["job_title"].apply(lambda x:x.split()[0])=="Senior")&(df["salary"]>10000)]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone,Bonus
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212,137500.0

In [156]:
np.where

In [160]:
department_names = {
    1: "HR",
    2: "IT",
    3: "Finance",
    4: "Sales",
    5: "Marketing"
}

df["department"] = df["dept_id"].map(department_names)

print(df[["dept_id", "department"]].head())

   dept_id department
0        1         HR
1        2         IT
2        1         HR
3        3    Finance
4        2         IT

In [161]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone,Bonus,department
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210,57200.0,HR
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211,85800.0,IT
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655,104500.0,HR
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789,74800.0,Finance
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212,137500.0,IT
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215,115500.0,IT
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211,85800.0,IT
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217,96800.0,Finance
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218,63800.0,HR
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220,108900.0,HR
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221,91300.0,Finance
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223,101200.0,IT
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225,70400.0,HR
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226,83600.0,IT

In [171]:
df=df.loc[df["city"]=="Bengaluru"].replace("Bengaluru","Bangalore",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_30344\1595304324.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df=df.loc[df["city"]=="Bengaluru"].replace("Bengaluru","Bangalore",inplace=True)

In [172]:
# df[df["city"]=="Bangalore"]df

In [173]:
df

In [178]:
df[df["city"]=="Bengaluru","city"].replace("Bengaluru','Bangalore')]

SyntaxError: unterminated string literal (detected at line 1) (1647783355.py, line 1)

In [180]:
df["city"] = df["city"].replace("Bengaluru","Bangalore")

In [181]:
df["city"]

0          Pune
1        Mumbai
2          Pune
3        Nashik
4        Mumbai
5         pune
6     Bangalore
7          Pune
8        Mumbai
9        Nashik
10         Pune
11       Mumbai
12    Bangalore
13        PUNE
14       Nashik
15       Mumbai
16         Pune
17    Bangalore
18       Mumbai
19          NaN
Name: city, dtype: object

In [182]:
df["category"].dtype

KeyError: 'category'

In [191]:
df["dept_id"]=df["dept_id"].astype("float")

In [185]:
df["email"]

0           aarav@example.com
1     priya.patil@example.com
2           rahul@example.com
3           sneha@example.com
4          vikram@example.com
5              om@example.com
6            isha@example.com
7           kunal@example.com
8     priya.patil@example.com
9           meera@example.com
10         aditya@example.com
11           neha@example.com
12          rohan@example.com
13          anaya@example.com
14          kabir@example.com
15           sana@example.com
16          arjun@example.com
17           maya@example.com
18            dev@example.com
19           tara.example.com
Name: email, dtype: object

In [192]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1.0,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2.0,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1.0,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3.0,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2.0,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
5,106,Om Pawar,26.0,61000.0,1.0,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,107,Isha Shah,NaN,72000.0,3.0,Data Analyst,Bangalore,2022-09-12,108.0,isha@example.com,9876543214
7,108,Kunal Jadhav,38.0,105000.0,2.0,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2.0,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3.0,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1.0,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
11,112,Neha Patil,45.0,NaN,2.0,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
12,113,Rohan More,30.0,99000.0,1.0,Engineer,Bangalore,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3.0,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
14,115,Kabir Pawar,28.0,47000.0,1.0,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
15,116,Sana Khan,32.0,92000.0,2.0,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3.0,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,118,Maya Rao,25.0,64000.0,1.0,Analyst,Bangalore,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2.0,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,120,Tara Singh,-2.0,500000.0,3.0,Director,NaN,2020-08-08,117.0,tara.example.com,123