In [287]:
name = "roshan pardeshi"
print(f"hellow world :-{name}")

hellow world :-roshan pardeshi

In [288]:
a = 10
b = 20
a = a+b
b = a-b
a = a-b

print(a)
print(b)

20
10

In [289]:
num = 9

if num%2==0:
    print("even")
else:
    print("odd")

odd

In [290]:
li = [10,30,40,50,50,50,40]
li1 = []
for i in li:
    if i not in li1:
        li1.append(i)

a = sorted(li1)

a[-3]

30

In [291]:
st = "roshan"

print(st[::-1])

nahsor

In [292]:
st = "rrrr"

if st==st[::-1]:
    print("palindrome")

palindrome

In [20]:
st = "datascience"
count = 0
for i in st:
    if i in "aeiou":
        count+=1
print(count)

5

In [22]:
st  = "datascience"
d1 = {}

for i in st:
    count = st.count(i)
    if i not in d1:
        d1[i]=count
print(d1)

{'d': 1, 'a': 2, 't': 1, 's': 1, 'c': 2, 'i': 1, 'e': 2, 'n': 1}

In [26]:
st = "Hellow world"

# print(st.upper())
print(st.swapcase())

hELLOW WORLD

In [29]:
st = "roshan pardeshi"

# st = st.split()
st = st.replace(" ","_")
print(st)

roshan_pardeshi

In [37]:
st = "listen"
st1 = "slinet"
count=0
a = len(st)
if len(st)==len(st1):
    for i in st:
        if i in st1:
            count+=1
    if count==a:
        print("anagrams")
    else:
        print("not anagrams")

anagrams

In [39]:
st = "aaabbccaaddr"

for i in st:
    count=st.count(i)
    if count==1:
        print(i)
        break

r

In [43]:
st = "roshan pardeshi i am final year computer engineering student at gangamai college"

st1 = st.replace(" ","_")
st1

'roshan_pardeshi_i_am_final_year_computer_engineering_student_at_gangamai_college'

In [48]:
st = "roshanpardeshi35@345"

print(st.isdigit())
print(st.isalpha())

False
False

In [54]:
st = "roshan pardeshi kusumba"

st = st.split()

for i in st:
    print(i,end="_")

roshan_pardeshi_kusumba_

In [55]:
st = "roshan pardeshi kasba peth pune i am final year computer engineering student"

st = st.split()
count =0 
for i in st:
    count+=1

print(count)

12

In [61]:
st = "pardeshi rrrosihan"
size = ""
st = st.split()
for i in st:
    if len(i)>len(size):
        size=i

print(size)

rrrosihan

In [62]:
st = "roshan pardeshi kasba peth"

print(st.capitalize())

Roshan pardeshi kasba peth

In [68]:
st11 = "aaabbccddee"
size = ""

for i in st11:
    if i not in size:
        size+=i

print("",size)

 abcde

In [69]:
st = "aaabbc"

li = []

for i in st:
    count = st.count(i)

    if i not in li:
        print(i,":",count)
        li.append(i)

a : 3
b : 2
c : 1

In [70]:
sum1 = 0
num = 12345

for i in str(num):
    sum1+=int(i)

print(sum1)

15

In [71]:
fact = 1

num = 5

for i in range(1,num+1,1):
    fact*=i
print(fact)

120

In [80]:
perfect_nu = 29
total = 0

for i in range(1,perfect_nu):
    if perfect_nu%i==0:
        total+=i

if perfect_nu==total:
    print("A number is a perfect")
else:
    print("A number is a not perfect")

A number is a not perfect

In [82]:
a = 0
b = 1
num = 10

for i in range(1,num+1,1):
    print(a)
    c = a+b
    a=b
    b=c

0
1
1
2
3
5
8
13
21
34

In [97]:
count = 0 
def prime_number(n):
    factor = 0
    num = n
    count = 0 
    for i in range(2,num,1):
        if num%2==0:
            factor+=1
    if factor==0:
        print("prime number----",num)
        count+=1
    
        
    
       
for i in range(1,101,1):
    prime_number(i)
print(count)

prime number---- 1
prime number---- 2
prime number---- 3
prime number---- 5
prime number---- 7
prime number---- 9
prime number---- 11
prime number---- 13
prime number---- 15
prime number---- 17
prime number---- 19
prime number---- 21
prime number---- 23
prime number---- 25
prime number---- 27
prime number---- 29
prime number---- 31
prime number---- 33
prime number---- 35
prime number---- 37
prime number---- 39
prime number---- 41
prime number---- 43
prime number---- 45
prime number---- 47
prime number---- 49
prime number---- 51
prime number---- 53
prime number---- 55
prime number---- 57
prime number---- 59
prime number---- 61
prime number---- 63
prime number---- 65
prime number---- 67
prime number---- 69
prime number---- 71
prime number---- 73
prime number---- 75
prime number---- 77
prime number---- 79
prime number---- 81
prime number---- 83
prime number---- 85
prime number---- 87
prime number---- 89
prime number---- 91
prime number---- 93
prime number---- 95
prime number---- 97
prime number---- 99
0

In [102]:
num = 15

for i in range(0,15):
    if i%3==0 and i%5==0:
        print("fizz Buzz number",i)
    elif i%3==0:
        print("Fizz",i)
    else:
        print("Buzz",i)

fizz Buzz number 0
Buzz 1
Buzz 2
Fizz 3
Buzz 4
Buzz 5
Fizz 6
Buzz 7
Buzz 8
Fizz 9
Buzz 10
Buzz 11
Fizz 12
Buzz 13
Buzz 14

In [1]:
import math as m

In [3]:
a = 20
b = 30
print(m.gcd(a,b))
print(m.lcm(a,b))

10
60

In [11]:
num = 375
a1 = len(str(num))

no = num
res = 0
for i in range(1,num+1,1):
    a = no%10
    res = res + a**a1
    no = no//10

if res == num:
    print("amstrong")

In [16]:
a = 5

bin(a)

'0b101'

In [17]:
num = 123
num = str(num)
print(num[::-1])

321

In [18]:
for i in range(1,11,1):
    print(5*i)

5
10
15
20
25
30
35
40
45
50

In [22]:
sum=0
for i in range(1,101,1):
    if i%2==0:
        sum+=i
print(sum)

2550

In [26]:
year = 367

if year<=365:
    print("normal year")
else:
    print("leaf year")

leaf year

In [39]:
# *
# *
# *
# *
# *
# * * * * * * * 

for i in range(0,6,1):
    for j in range(0,6,1):
        if j==1:
            print("*",end="")
        if i==5:
            print("*",end="-")

    print()

*
*
*
*
*
*-**-*-*-*-*-

In [40]:
a = 10
b = 20
choice = int(input("enter"))
match(choice):
    case 1:
        print("addition")
        print(a+b)
    case 2:
        print("sunstraction")
        print(a-b)
    case 3:
        print("division")
        print(a/b)
    case 4:
        print("multiplication")
        print(a*b)
    case 5:
        print("fewler division")
        print(a//10)
    case _:
        print("invalied choice")

enter 1

addition
30

In [41]:
li = [10,20,20,30,40,50,60,70]

li1 = []

for i in li:
    if i not in li1:
        li1.append(i)

max1 = li1[0]
for i in li1:
    if max1<i:
        max=i
li1.remove(max1)
max2 = li1[0]
for i in li1:
    if max2<i:
        max2=i

print(max2)

70

In [42]:
li = [1,2,3,4,5,3,2,3,5,6,33,1,2,3,6,7,8,9]
li1 = []

for i in li:
    if i not in li1:
        li1.append(i)
print(li1)

[1, 2, 3, 4, 5, 6, 33, 7, 8, 9]

In [46]:
li = [1,2,3,4,5,6]
li1 = li[-1]
li2 = li[-2]

li.pop()
li.pop()

li.insert(0,li1)
li.insert(1,li2)

print(li)

[6, 5, 1, 2, 3, 4]

In [69]:
li = [[1, 2], [3, [4, 5]]]
li1=[]
for i in range(0,len(li),1):
    for j in range(0,len(li[i]),1):
            li1.append(li[i][j])

print(li1)

for i in li1:
    print(i)

[1, 2, 3, [4, 5]]
1
2
3
[4, 5]

In [71]:
li = [1,2,3,4,5,6,7]
li1 = [44,55,6,7,8,9]

print(set(li).intersection(set(li1)))

{6, 7}

In [72]:
for i in li:
    li1.append(i)
print(li1)

[44, 55, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7]

In [73]:
li = [0,1,2,0,3,4,5,0,2,5,8,1]
li1 = []

count = 0
for i in li:
    if i==0:
        count+=1
    else:
        li1.append(i)

for i in range(count):
    li1.append(0)
print(li1)

[1, 2, 3, 4, 5, 2, 5, 8, 1, 0, 0, 0]

In [75]:
li = [1,2,3,7]
li1 = []
target = 9

for i in range(0,len(li),1):
    for j in range(i+1,len(li)):
        if li[i]+li[j]==target:
            li1.append((li[i],li[j]))

print(li1)

[(2, 7)]

In [77]:
li = [1,2,3,4,5,6]

li1=li.split()

AttributeError: 'list' object has no attribute 'split'

In [81]:
li = [10,30,40,50,60,80,90]

for i in range(1,len(li)+2,1):
    if i not in li:
        print(i)

1
2
3
4
5
6
7
8

In [86]:
li = [1,2,3,4,5,6,7,1,8]

for i in li:
    count = li.count(i)

    if count>1:
        print(count)
        break

2

In [87]:
li = []
for i in range(1,20,1):
    if i%2==0:
        li.append(i**2)

print(li)

[4, 16, 36, 64, 100, 144, 196, 256, 324]

In [88]:
li = [1,2,3,4,5]

li.append(10)

li.extend([1,2,3,4,5])

In [89]:
li

[1, 2, 3, 4, 5, 10, 1, 2, 3, 4, 5]

In [92]:
st = ["apply","cerry","banana","mango"]

print(sorted(st))

['apply', 'banana', 'cerry', 'mango']

In [94]:
s1 = {1,2,3,4,5}
s2 = {4,5,6,7,8}

print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s1.symmetric_difference(s2))

{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}

In [96]:
li = [10,20,30,40,50]

print(sorted(li))

[10, 20, 30, 40, 50]

In [98]:
st = "datascience"
li1 = []
for i in st:
    count = st.count(i)
    
    if count>1:
        pass
    else:
        li1.append(i)

print(li1)

['d', 't', 's', 'i', 'n']

In [121]:
d1 = {1:"roshan",2:"sonu",3:"monu"}
d2 = {}

# for i in 
a = d1.keys()
b = d1.values()
for i in d1:
    d2[i]=d1.values()

In [122]:
d2

{1: dict_values(['roshan', 'sonu', 'monu']),
 2: dict_values(['roshan', 'sonu', 'monu']),
 3: dict_values(['roshan', 'sonu', 'monu'])}

In [125]:
d1 = {1:"roshan",2:"sonu",3:"monu"}

print(sorted(d1.values()))

['monu', 'roshan', 'sonu']

In [134]:
st = "roshan pardeshi is good boy"
d1 = {}
a = st.split()
for i in range(0,len(st),1):
    
    count = st.count(st[i])

    d1[st[i]] = count

print(d1)

{'r': 2, 'o': 4, 's': 3, 'h': 2, 'a': 2, 'n': 1, ' ': 4, 'p': 1, 'd': 2, 'e': 1, 'i': 2, 'g': 1, 'b': 1, 'y': 1}

In [136]:
!pip install tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D, MaxPooling2D,
    Flatten, Dense
)

model = Sequential([
    Conv2D(32, (3, 3), activation="relu",
           input_shape=(128, 128, 3)),

    MaxPooling2D((2, 2)),

    Conv2D(64, (3, 3), activation="relu"),

    MaxPooling2D((2, 2)),

    Flatten(),

    Dense(128, activation="relu"),

    Dense(4, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

Defaulting to user installation because normal site-packages is not writeable
Collecting tensorflow
  Downloading tensorflow-2.22.0rc0-cp314-cp314-win_amd64.whl.metadata (4.6 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.5.1-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (26.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: six>=1.12.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (1.81.1)
Collecting keras-nightly>=3.12.0.dev (from tensorflow)
  Downloading keras_nightly-3.16.0.dev2026101704-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (2.4.6)
Collecting h5py~=3.15.1 (from tensorflow)
  Downloading h5py-3.15.1-cp314-cp314-win_amd64.whl.metadata (3.1 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.6.0-cp314-cp314-win_amd64.whl.metadata (8.8 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.48.0-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras-nightly>=3.12.0.dev->tensorflow)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras-nightly>=3.12.0.dev->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras-nightly>=3.12.0.dev->tensorflow)
  Downloading optree-0.20.0-cp314-cp314-win_amd64.whl.metadata (33 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras-nightly>=3.12.0.dev->tensorflow)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from rich->keras-nightly>=3.12.0.dev->tensorflow) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras-nightly>=3.12.0.dev->tensorflow)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.22.0rc0-cp314-cp314-win_amd64.whl (384.1 MB)
   ---------------------------------------- 0.0/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/384.1 MB ? eta -:--:--
   ---------------------------------------- 0.5/384.1 MB 524.6 kB/s eta 0:12:12
   ---------------------------------------- 0.5/384.1 MB 524.6 kB/s eta 0:12:12
   ---------------------------------------- 0.8/384.1 MB 582.5 kB/s eta 0:10:59
   ---------------------------------------- 0.8/384.1 MB 582.5 kB/s eta 0:10:59
   ---------------------------------------- 1.0/384.1 MB 611.6 kB/s eta 0:10:27
   ---------------------------------------- 1.0/384.1 MB 611.6 kB/s eta 0:10:27
   ---------------------------------------- 1.3/384.1 MB 637.3 kB/s eta 0:10:01
   ---------------------------------------- 1.3/384.1 MB 637.3 kB/s eta 0:10:01
   ---------------------------------------- 1.6/384.1 MB 652.5 kB/s eta 0:09:47
   ---------------------------------------- 1.6/384.1 MB 652.5 kB/s eta 0:09:47
   ---------------------------------------- 1.8/384.1 MB 655.2 kB/s eta 0:09:44
   ---------------------------------------- 2.1/384.1 MB 657.6 kB/s eta 0:09:41
   ---------------------------------------- 2.1/384.1 MB 657.6 kB/s eta 0:09:41
   ---------------------------------------- 2.4/384.1 MB 665.1 kB/s eta 0:09:34
   ---------------------------------------- 2.4/384.1 MB 665.1 kB/s eta 0:09:34
   ---------------------------------------- 2.6/384.1 MB 666.7 kB/s eta 0:09:33
   ---------------------------------------- 2.6/384.1 MB 666.7 kB/s eta 0:09:33
   ---------------------------------------- 2.9/384.1 MB 671.9 kB/s eta 0:09:28
   ---------------------------------------- 2.9/384.1 MB 671.9 kB/s eta 0:09:28
   ---------------------------------------- 3.1/384.1 MB 675.2 kB/s eta 0:09:25
   ---------------------------------------- 3.4/384.1 MB 676.7 kB/s eta 0:09:23
   ---------------------------------------- 3.4/384.1 MB 676.7 kB/s eta 0:09:23
   ---------------------------------------- 3.7/384.1 MB 680.8 kB/s eta 0:09:19
   ---------------------------------------- 3.7/384.1 MB 680.8 kB/s eta 0:09:19
   ---------------------------------------- 3.9/384.1 MB 683.2 kB/s eta 0:09:17
   ---------------------------------------- 3.9/384.1 MB 683.2 kB/s eta 0:09:17
   ---------------------------------------- 4.2/384.1 MB 685.2 kB/s eta 0:09:15
   ---------------------------------------- 4.5/384.1 MB 684.5 kB/s eta 0:09:15
   ---------------------------------------- 4.5/384.1 MB 684.5 kB/s eta 0:09:15
   ---------------------------------------- 4.7/384.1 MB 686.7 kB/s eta 0:09:13
   ---------------------------------------- 4.7/384.1 MB 686.7 kB/s eta 0:09:13
    --------------------------------------- 5.0/384.1 MB 682.6 kB/s eta 0:09:16
    --------------------------------------- 5.0/384.1 MB 682.6 kB/s eta 0:09:16
    --------------------------------------- 5.2/384.1 MB 684.7 kB/s eta 0:09:14
    --------------------------------------- 5.2/384.1 MB 684.7 kB/s eta 0:09:14
    --------------------------------------- 5.5/384.1 MB 686.8 kB/s eta 0:09:12
    --------------------------------------- 5.8/384.1 MB 688.1 kB/s eta 0:09:10
    --------------------------------------- 5.8/384.1 MB 688.1 kB/s eta 0:09:10
    --------------------------------------- 6.0/384.1 MB 689.9 kB/s eta 0:09:09
    --------------------------------------- 6.0/384.1 MB 689.9 kB/s eta 0:09:09
    --------------------------------------- 6.3/384.1 MB 692.3 kB/s eta 0:09:06
    --------------------------------------- 6.3/384.1 MB 692.3 kB/s eta 0:09:06
    --------------------------------------- 6.3/384.1 MB 692.3 kB/s eta 0:09:06
    --------------------------------------- 6.6/384.1 MB 677.8 kB/s eta 0:09:17
    --------------------------------------- 6.6/384.1 MB 677.8 kB/s eta 0:09:17
    --------------------------------------- 6.6/384.1 MB 677.8 kB/s eta 0:09:17
    --------------------------------------- 6.8/384.1 MB 658.5 kB/s eta 0:09:33
    --------------------------------------- 6.8/384.1 MB 658.5 kB/s eta 0:09:33
    --------------------------------------- 6.8/384.1 MB 658.5 kB/s eta 0:09:33
    --------------------------------------- 7.1/384.1 MB 647.4 kB/s eta 0:09:43
    --------------------------------------- 7.1/384.1 MB 647.4 kB/s eta 0:09:43
    --------------------------------------- 7.3/384.1 MB 639.4 kB/s eta 0:09:50
    --------------------------------------- 7.3/384.1 MB 639.4 kB/s eta 0:09:50
    --------------------------------------- 7.3/384.1 MB 639.4 kB/s eta 0:09:50
    --------------------------------------- 7.6/384.1 MB 631.5 kB/s eta 0:09:57
    --------------------------------------- 7.6/384.1 MB 631.5 kB/s eta 0:09:57
    --------------------------------------- 7.6/384.1 MB 631.5 kB/s eta 0:09:57
    --------------------------------------- 7.9/384.1 MB 622.6 kB/s eta 0:10:05
    --------------------------------------- 7.9/384.1 MB 622.6 kB/s eta 0:10:05
    --------------------------------------- 8.1/384.1 MB 614.4 kB/s eta 0:10:12
    --------------------------------------- 8.1/384.1 MB 614.4 kB/s eta 0:10:12
    --------------------------------------- 8.1/384.1 MB 614.4 kB/s eta 0:10:12
    --------------------------------------- 8.4/384.1 MB 607.2 kB/s eta 0:10:19
    --------------------------------------- 8.4/384.1 MB 607.2 kB/s eta 0:10:19
    --------------------------------------- 8.4/384.1 MB 607.2 kB/s eta 0:10:19
    --------------------------------------- 8.7/384.1 MB 604.4 kB/s eta 0:10:22
    --------------------------------------- 8.7/384.1 MB 604.4 kB/s eta 0:10:22
    --------------------------------------- 8.9/384.1 MB 599.7 kB/s eta 0:10:26
    --------------------------------------- 8.9/384.1 MB 599.7 kB/s eta 0:10:26
    --------------------------------------- 8.9/384.1 MB 599.7 kB/s eta 0:10:26
    --------------------------------------- 9.2/384.1 MB 593.3 kB/s eta 0:10:32
    --------------------------------------- 9.2/384.1 MB 593.3 kB/s eta 0:10:32
    --------------------------------------- 9.2/384.1 MB 593.3 kB/s eta 0:10:32
    --------------------------------------- 9.4/384.1 MB 587.7 kB/s eta 0:10:38
    --------------------------------------- 9.4/384.1 MB 587.7 kB/s eta 0:10:38
   - -------------------------------------- 9.7/384.1 MB 585.2 kB/s eta 0:10:40
   - -------------------------------------- 9.7/384.1 MB 585.2 kB/s eta 0:10:40
   - -------------------------------------- 9.7/384.1 MB 585.2 kB/s eta 0:10:40
   - ------------------------------------- 10.0/384.1 MB 582.6 kB/s eta 0:10:43
   - ------------------------------------- 10.0/384.1 MB 582.6 kB/s eta 0:10:43
   - ------------------------------------- 10.0/384.1 MB 582.6 kB/s eta 0:10:43
   - ------------------------------------- 10.2/384.1 MB 576.9 kB/s eta 0:10:49
   - ------------------------------------- 10.2/384.1 MB 576.9 kB/s eta 0:10:49
   - ------------------------------------- 10.5/384.1 MB 576.0 kB/s eta 0:10:49
   - ------------------------------------- 10.5/384.1 MB 576.0 kB/s eta 0:10:49
   - ------------------------------------- 10.5/384.1 MB 576.0 kB/s eta 0:10:49
   - ------------------------------------- 10.7/384.1 MB 572.3 kB/s eta 0:10:53
   - ------------------------------------- 10.7/384.1 MB 572.3 kB/s eta 0:10:53
   - ------------------------------------- 10.7/384.1 MB 572.3 kB/s eta 0:10:53
   - ------------------------------------- 11.0/384.1 MB 568.6 kB/s eta 0:10:57
   - ------------------------------------- 11.0/384.1 MB 568.6 kB/s eta 0:10:57
   - ------------------------------------- 11.3/384.1 MB 567.2 kB/s eta 0:10:58
   - ------------------------------------- 11.3/384.1 MB 567.2 kB/s eta 0:10:58
   - ------------------------------------- 11.3/384.1 MB 567.2 kB/s eta 0:10:58
   - ------------------------------------- 11.5/384.1 MB 561.4 kB/s eta 0:11:04
   - ------------------------------------- 11.5/384.1 MB 561.4 kB/s eta 0:11:04
   - ------------------------------------- 11.5/384.1 MB 561.4 kB/s eta 0:11:04
   - ------------------------------------- 11.8/384.1 MB 561.3 kB/s eta 0:11:04
   - ------------------------------------- 11.8/384.1 MB 561.3 kB/s eta 0:11:04
   - ------------------------------------- 12.1/384.1 MB 563.1 kB/s eta 0:11:01
   - ------------------------------------- 12.1/384.1 MB 563.1 kB/s eta 0:11:01
   - ------------------------------------- 12.3/384.1 MB 565.5 kB/s eta 0:10:58
   - ------------------------------------- 12.3/384.1 MB 565.5 kB/s eta 0:10:58
   - ------------------------------------- 12.3/384.1 MB 565.5 kB/s eta 0:10:58
   - ------------------------------------- 12.6/384.1 MB 561.4 kB/s eta 0:11:02
   - ------------------------------------- 12.6/384.1 MB 561.4 kB/s eta 0:11:02
   - ------------------------------------- 12.8/384.1 MB 560.0 kB/s eta 0:11:03
   - ------------------------------------- 12.8/384.1 MB 560.0 kB/s eta 0:11:03
   - ------------------------------------- 13.1/384.1 MB 561.6 kB/s eta 0:11:01
   - ------------------------------------- 13.1/384.1 MB 561.6 kB/s eta 0:11:01
   - ------------------------------------- 13.4/384.1 MB 563.5 kB/s eta 0:10:58
   - ------------------------------------- 13.4/384.1 MB 563.5 kB/s eta 0:10:58
   - ------------------------------------- 13.4/384.1 MB 563.5 kB/s eta 0:10:58
   - ------------------------------------- 13.6/384.1 MB 561.4 kB/s eta 0:11:00
   - ------------------------------------- 13.6/384.1 MB 561.4 kB/s eta 0:11:00
   - ------------------------------------- 13.9/384.1 MB 560.8 kB/s eta 0:11:01
   - ------------------------------------- 13.9/384.1 MB 560.8 kB/s eta 0:11:01
   - ------------------------------------- 13.9/384.1 MB 560.8 kB/s eta 0:11:01
   - ------------------------------------- 14.2/384.1 MB 557.3 kB/s eta 0:11:04
   - ------------------------------------- 14.2/384.1 MB 557.3 kB/s eta 0:11:04
   - ------------------------------------- 14.2/384.1 MB 557.3 kB/s eta 0:11:04
   - ------------------------------------- 14.4/384.1 MB 552.8 kB/s eta 0:11:09
   - ------------------------------------- 14.4/384.1 MB 552.8 kB/s eta 0:11:09
   - ------------------------------------- 14.4/384.1 MB 552.8 kB/s eta 0:11:09
   - ------------------------------------- 14.7/384.1 MB 552.1 kB/s eta 0:11:10
   - ------------------------------------- 14.7/384.1 MB 552.1 kB/s eta 0:11:10
   - ------------------------------------- 14.9/384.1 MB 550.5 kB/s eta 0:11:11
   - ------------------------------------- 14.9/384.1 MB 550.5 kB/s eta 0:11:11
   - ------------------------------------- 14.9/384.1 MB 550.5 kB/s eta 0:11:11
   - ------------------------------------- 15.2/384.1 MB 548.8 kB/s eta 0:11:13
   - ------------------------------------- 15.2/384.1 MB 548.8 kB/s eta 0:11:13
   - ------------------------------------- 15.2/384.1 MB 548.8 kB/s eta 0:11:13
   - ------------------------------------- 15.5/384.1 MB 546.3 kB/s eta 0:11:15
   - ------------------------------------- 15.5/384.1 MB 546.3 kB/s eta 0:11:15
   - ------------------------------------- 15.5/384.1 MB 546.3 kB/s eta 0:11:15
   - ------------------------------------- 15.7/384.1 MB 543.3 kB/s eta 0:11:18
   - ------------------------------------- 15.7/384.1 MB 543.3 kB/s eta 0:11:18
   - ------------------------------------- 15.7/384.1 MB 543.3 kB/s eta 0:11:18
   - ------------------------------------- 16.0/384.1 MB 541.9 kB/s eta 0:11:20
   - ------------------------------------- 16.0/384.1 MB 541.9 kB/s eta 0:11:20
   - ------------------------------------- 16.0/384.1 MB 541.9 kB/s eta 0:11:20
   - ------------------------------------- 16.3/384.1 MB 539.1 kB/s eta 0:11:23
   - ------------------------------------- 16.3/384.1 MB 539.1 kB/s eta 0:11:23
   - ------------------------------------- 16.3/384.1 MB 539.1 kB/s eta 0:11:23
   - ------------------------------------- 16.5/384.1 MB 536.4 kB/s eta 0:11:26
   - ------------------------------------- 16.5/384.1 MB 536.4 kB/s eta 0:11:26
   - ------------------------------------- 16.8/384.1 MB 536.5 kB/s eta 0:11:25
   - ------------------------------------- 16.8/384.1 MB 536.5 kB/s eta 0:11:25
   - ------------------------------------- 17.0/384.1 MB 536.3 kB/s eta 0:11:25
   - ------------------------------------- 17.0/384.1 MB 536.3 kB/s eta 0:11:25
   - ------------------------------------- 17.3/384.1 MB 535.6 kB/s eta 0:11:25
   - ------------------------------------- 17.3/384.1 MB 535.6 kB/s eta 0:11:25
   - ------------------------------------- 17.6/384.1 MB 535.3 kB/s eta 0:11:25
   - ------------------------------------- 17.6/384.1 MB 535.3 kB/s eta 0:11:25
   - ------------------------------------- 17.6/384.1 MB 535.3 kB/s eta 0:11:25
   - ------------------------------------- 17.8/384.1 MB 528.7 kB/s eta 0:11:33
   - ------------------------------------- 17.8/384.1 MB 528.7 kB/s eta 0:11:33
   - ------------------------------------- 18.1/384.1 MB 527.2 kB/s eta 0:11:35
   - ------------------------------------- 18.1/384.1 MB 527.2 kB/s eta 0:11:35
   - ------------------------------------- 18.1/384.1 MB 527.2 kB/s eta 0:11:35
   - ------------------------------------- 18.4/384.1 MB 518.7 kB/s eta 0:11:46
   - ------------------------------------- 18.4/384.1 MB 518.7 kB/s eta 0:11:46
   - ------------------------------------- 18.4/384.1 MB 518.7 kB/s eta 0:11:46
   - ------------------------------------- 18.6/384.1 MB 512.6 kB/s eta 0:11:53
   - ------------------------------------- 18.6/384.1 MB 512.6 kB/s eta 0:11:53
   - ------------------------------------- 18.6/384.1 MB 512.6 kB/s eta 0:11:53
   - ------------------------------------- 18.6/384.1 MB 512.6 kB/s eta 0:11:53
   - ------------------------------------- 18.9/384.1 MB 506.9 kB/s eta 0:12:01
   - ------------------------------------- 18.9/384.1 MB 506.9 kB/s eta 0:12:01
   - ------------------------------------- 19.1/384.1 MB 502.6 kB/s eta 0:12:07
   - ------------------------------------- 19.1/384.1 MB 502.6 kB/s eta 0:12:07
   - ------------------------------------- 19.4/384.1 MB 501.0 kB/s eta 0:12:08
   - ------------------------------------- 19.4/384.1 MB 501.0 kB/s eta 0:12:08
   - ------------------------------------- 19.7/384.1 MB 499.4 kB/s eta 0:12:10
   - ------------------------------------- 19.7/384.1 MB 499.4 kB/s eta 0:12:10
   - ------------------------------------- 19.7/384.1 MB 499.4 kB/s eta 0:12:10
   -- ------------------------------------ 19.9/384.1 MB 493.1 kB/s eta 0:12:19
   -- ------------------------------------ 19.9/384.1 MB 493.1 kB/s eta 0:12:19
   -- ------------------------------------ 19.9/384.1 MB 493.1 kB/s eta 0:12:19
   -- ------------------------------------ 20.2/384.1 MB 491.6 kB/s eta 0:12:21
   -- ------------------------------------ 20.2/384.1 MB 491.6 kB/s eta 0:12:21
   -- ------------------------------------ 20.4/384.1 MB 490.3 kB/s eta 0:12:22
   -- ------------------------------------ 20.4/384.1 MB 490.3 kB/s eta 0:12:22
   -- ------------------------------------ 20.7/384.1 MB 485.8 kB/s eta 0:12:28
   -- ------------------------------------ 20.7/384.1 MB 485.8 kB/s eta 0:12:28
   -- ------------------------------------ 21.0/384.1 MB 488.4 kB/s eta 0:12:24
   -- ------------------------------------ 21.0/384.1 MB 488.4 kB/s eta 0:12:24
   -- ------------------------------------ 21.2/384.1 MB 491.0 kB/s eta 0:12:20
   -- ------------------------------------ 21.2/384.1 MB 491.0 kB/s eta 0:12:20
   -- ------------------------------------ 21.5/384.1 MB 493.6 kB/s eta 0:12:15
   -- ------------------------------------ 21.5/384.1 MB 493.6 kB/s eta 0:12:15

  WARNING: The script wheel.exe is installed in 'C:\Users\Admin\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown-it.exe is installed in 'C:\Users\Admin\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts import_pb_to_tensorboard.exe, saved_model_cli.exe, tensorboard.exe, tf_upgrade_v2.exe, tflite_convert.exe and toco.exe are installed in 'C:\Users\Admin\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.36.2 which is incompatible.
google-api-core 2.25.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5, but you have protobuf 7.36.2 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.36.2 which is incompatible.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
model

In [1]:
import pandas as pd
import numpy as np

In [174]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\employee_practice_dataset.csv")

In [3]:
df.head()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212

In [4]:
df.shape

(20, 11)

In [5]:
df.describe()

          emp_id        age         salary    dept_id  manager_id
count   20.00000  19.000000      19.000000  20.000000   17.000000
mean   110.50000  30.684211  102947.368421   1.950000  108.529412
std      5.91608   9.866062   98397.986477   0.825578    5.363274
min    101.00000  -2.000000   47000.000000   1.000000  103.000000
25%    105.75000  27.500000   66000.000000   1.000000  105.000000
50%    110.50000  31.000000   78000.000000   2.000000  105.000000
75%    115.25000  35.500000   97000.000000   3.000000  110.000000
max    120.00000  45.000000  500000.000000   3.000000  117.000000

In [6]:
df.describe(include="object")

,name,job_title,city,hire_date,email,phone
count,20,20,19,20,20,20
unique,19,7,6,19,19,19
top,Priya Patil,Manager,Mumbai,2020-03-10,priya.patil@example.com,98765 43211
freq,2,5,6,2,2,2

In [7]:
df.tail()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [8]:
df.sample()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [9]:
df.columns.to_list()

['emp_id',
 'name',
 'age',
 'salary',
 'dept_id',
 'job_title',
 'city',
 'hire_date',
 'manager_id',
 'email',
 'phone']

In [10]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [11]:
df.set_index('manager_id')

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,email,phone
manager_id,,,,,,,,,,
103.0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,aarav@example.com,9876543210
105.0,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,priya.patil@example.com,98765 43211
117.0,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,rahul@example.com,9988776655
110.0,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,sneha@example.com,9123456789
117.0,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,vikram@example.com,9876543212
NaN,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,om@example.com,9876543213
108.0,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,isha@example.com,9876543214
105.0,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,kunal@example.com,9876543215
105.0,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,priya.patil@example.com,98765 43211
110.0,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,meera@example.com,9876543217
103.0,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,aditya@example.com,9876543218
105.0,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,neha@example.com,9876543219
117.0,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,rohan@example.com,9876543220
110.0,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,anaya@example.com,9876543221
NaN,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,kabir@example.com,9876543222
105.0,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,sana@example.com,9876543223
NaN,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,arjun@example.com,9876543224
103.0,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,maya@example.com,9876543225
105.0,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,dev@example.com,9876543226
117.0,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,tara.example.com,123

In [12]:
df.reset_index()

,index,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
5,5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
11,11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
12,12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
14,14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
15,15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [13]:
df.head()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212

In [14]:
df.tail()

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [17]:
df["name"].str.strip()

0       Aarav Sharma
1        Priya Patil
2     Rahul Deshmukh
3        Sneha Joshi
4        Vikram More
5           Om Pawar
6          Isha Shah
7       Kunal Jadhav
8        Priya Patil
9     Meera Kulkarni
10      Aditya Joshi
11        Neha Patil
12        Rohan More
13        Anaya Shah
14       Kabir Pawar
15         Sana Khan
16       Arjun Desai
17          Maya Rao
18      Dev Kulkarni
19        Tara Singh
Name: name, dtype: object

In [18]:
df[["name","age","salary"]]

              name   age    salary
0     Aarav Sharma  24.0   52000.0
1      Priya Patil  29.0   78000.0
2   Rahul Deshmukh  35.0   95000.0
3      Sneha Joshi  31.0   68000.0
4      Vikram More  42.0  125000.0
5         Om Pawar  26.0   61000.0
6        Isha Shah   NaN   72000.0
7     Kunal Jadhav  38.0  105000.0
8      Priya Patil  29.0   78000.0
9   Meera Kulkarni  33.0   88000.0
10    Aditya Joshi  27.0   58000.0
11      Neha Patil  45.0       NaN
12      Rohan More  30.0   99000.0
13      Anaya Shah  36.0   83000.0
14     Kabir Pawar  28.0   47000.0
15       Sana Khan  32.0   92000.0
16     Arjun Desai  41.0  115000.0
17        Maya Rao  25.0   64000.0
18    Dev Kulkarni  34.0   76000.0
19      Tara Singh  -2.0  500000.0

In [19]:
df.shape

(20, 11)

In [22]:
df["salary"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: salary
Non-Null Count  Dtype
--------------  -----
19 non-null     float64
dtypes: float64(1)
memory usage: 292.0 bytes

In [24]:
df.describe(include="all")

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
count,20.00000,20,19.000000,19.000000,20.000000,20,19,20,17.000000,20,20
unique,NaN,19,NaN,NaN,NaN,7,6,19,NaN,19,19
top,NaN,Priya Patil,NaN,NaN,NaN,Manager,Mumbai,2020-03-10,NaN,priya.patil@example.com,98765 43211
freq,NaN,2,NaN,NaN,NaN,5,6,2,NaN,2,2
mean,110.50000,NaN,30.684211,102947.368421,1.950000,NaN,NaN,NaN,108.529412,NaN,NaN
std,5.91608,NaN,9.866062,98397.986477,0.825578,NaN,NaN,NaN,5.363274,NaN,NaN
min,101.00000,NaN,-2.000000,47000.000000,1.000000,NaN,NaN,NaN,103.000000,NaN,NaN
25%,105.75000,NaN,27.500000,66000.000000,1.000000,NaN,NaN,NaN,105.000000,NaN,NaN
50%,110.50000,NaN,31.000000,78000.000000,2.000000,NaN,NaN,NaN,105.000000,NaN,NaN
75%,115.25000,NaN,35.500000,97000.000000,3.000000,NaN,NaN,NaN,110.000000,NaN,NaN
max,120.00000,NaN,45.000000,500000.000000,3.000000,NaN,NaN,NaN,117.000000,NaN,NaN

In [25]:
df["name"].to_list()

['Aarav Sharma',
 'Priya Patil',
 'Rahul Deshmukh',
 'Sneha Joshi',
 'Vikram More',
 'Om Pawar',
 'Isha Shah',
 'Kunal Jadhav',
 'Priya Patil',
 'Meera Kulkarni',
 'Aditya Joshi',
 'Neha Patil',
 'Rohan More',
 'Anaya Shah',
 'Kabir Pawar',
 'Sana Khan',
 'Arjun Desai',
 'Maya Rao',
 'Dev Kulkarni',
 'Tara Singh']

In [26]:
df.set_index("age")

,emp_id,name,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
age,,,,,,,,,,
24.0,101,Aarav Sharma,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
29.0,102,Priya Patil,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
35.0,103,Rahul Deshmukh,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
31.0,104,Sneha Joshi,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
42.0,105,Vikram More,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
26.0,106,Om Pawar,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
NaN,107,Isha Shah,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
38.0,108,Kunal Jadhav,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
29.0,109,Priya Patil,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
33.0,110,Meera Kulkarni,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
27.0,111,Aditya Joshi,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
45.0,112,Neha Patil,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
30.0,113,Rohan More,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
36.0,114,Anaya Shah,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
28.0,115,Kabir Pawar,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
32.0,116,Sana Khan,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
41.0,117,Arjun Desai,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
25.0,118,Maya Rao,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
34.0,119,Dev Kulkarni,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
-2.0,120,Tara Singh,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [27]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [28]:
df.reset_index()

,index,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
5,5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
11,11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
12,12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
14,14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
15,15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [32]:
df[["name","age"]]

              name   age
0     Aarav Sharma  24.0
1      Priya Patil  29.0
2   Rahul Deshmukh  35.0
3      Sneha Joshi  31.0
4      Vikram More  42.0
5         Om Pawar  26.0
6        Isha Shah   NaN
7     Kunal Jadhav  38.0
8      Priya Patil  29.0
9   Meera Kulkarni  33.0
10    Aditya Joshi  27.0
11      Neha Patil  45.0
12      Rohan More  30.0
13      Anaya Shah  36.0
14     Kabir Pawar  28.0
15       Sana Khan  32.0
16     Arjun Desai  41.0
17        Maya Rao  25.0
18    Dev Kulkarni  34.0
19      Tara Singh  -2.0

In [33]:
df.loc[5:10:1]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218

In [34]:
df.iloc[5:11:1]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218

In [35]:
df[df["salary"]>80000]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [36]:
df[(df["dept_id"]==1)&(df["salary"]>60000)]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225

In [43]:
res = df[df["city"].isin(["Pune","mumbai"])]

In [44]:
res

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224

In [47]:
df[df["salary"].isin([50000,90000])]

Empty DataFrame
Columns: [emp_id, name, age, salary, dept_id, job_title, city, hire_date, manager_id, email, phone]
Index: []

In [53]:
df[df["name"].apply(lambda x:x.startswith("A"))]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224

In [55]:
df["name"].apply(lambda x:x[0])

0     A
1     P
2     R
3     S
4     V
5     O
6     I
7     K
8     P
9     M
10    A
11    N
12    R
13    A
14    K
15    S
16    A
17    M
18    D
19    T
Name: name, dtype: object

In [57]:
df[df["salary"].query("salary">100)]

AttributeError: 'Series' object has no attribute 'query'

In [58]:
df[["name","salary"]].sort_values("salary",ascending=False).head(5)

            name    salary
19    Tara Singh  500000.0
4    Vikram More  125000.0
16   Arjun Desai  115000.0
7   Kunal Jadhav  105000.0
12    Rohan More   99000.0

In [76]:
df["job_title"].apply(lambda x:x.split()[1])

IndexError: list index out of range

In [60]:
df["job_title"]

0            Analyst
1            Manager
2           Engineer
3       HR Executive
4     Senior Manager
5            Analyst
6       Data Analyst
7            Manager
8            Manager
9       HR Executive
10          Engineer
11    Senior Manager
12          Engineer
13      Data Analyst
14           Analyst
15           Manager
16    Senior Manager
17           Analyst
18           Manager
19          Director
Name: job_title, dtype: object

In [79]:
df[df["job_title"]=="Manager"]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226

In [80]:
df[df["manager_id"].isnull()]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224

In [81]:
df[df["city"].isnull()]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [85]:
df.select_dtypes(int)

    emp_id  dept_id
0      101        1
1      102        2
2      103        1
3      104        3
4      105        2
5      106        1
6      107        3
7      108        2
8      109        2
9      110        3
10     111        1
11     112        2
12     113        1
13     114        3
14     115        1
15     116        2
16     117        3
17     118        1
18     119        2
19     120        3

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      20 non-null     int64
 1   name        20 non-null     object
 2   age         19 non-null     float64
 3   salary      19 non-null     float64
 4   dept_id     20 non-null     int64
 5   job_title   20 non-null     object
 6   city        19 non-null     object
 7   hire_date   20 non-null     object
 8   manager_id  17 non-null     float64
 9   email       20 non-null     object
 10  phone       20 non-null     object
dtypes: float64(3), int64(2), object(6)
memory usage: 1.8+ KB

In [90]:
df["hire_date"] = pd.to_datetime(df["hire_date"])

KeyError: 'hire_date'

In [89]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: hire_date
Non-Null Count  Dtype
--------------  -----
20 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 292.0 bytes

In [92]:
df["hire_date"] = pd.to_datetime(df["hire_date"])

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      20 non-null     int64
 1   name        20 non-null     object
 2   age         19 non-null     float64
 3   salary      19 non-null     float64
 4   dept_id     20 non-null     int64
 5   job_title   20 non-null     object
 6   city        19 non-null     object
 7   hire_date   20 non-null     datetime64[ns]
 8   manager_id  17 non-null     float64
 9   email       20 non-null     object
 10  phone       20 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(2), object(5)
memory usage: 1.8+ KB

In [95]:
df.duplicated().sum()

np.int64(0)

In [96]:
df.sort_values("salary",ascending=False)

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219

In [102]:
df.sort_values("dept_id").sort_values("salary",ascending=False)

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
19,120,Tara Singh,-2.0,500000.0,3,Director,NaN,2020-08-08,117.0,tara.example.com,123
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
16,117,Arjun Desai,41.0,115000.0,3,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
6,107,Isha Shah,NaN,72000.0,3,Data Analyst,Bengaluru,2022-09-12,108.0,isha@example.com,9876543214
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
5,106,Om Pawar,26.0,61000.0,1,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
14,115,Kabir Pawar,28.0,47000.0,1,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
11,112,Neha Patil,45.0,NaN,2,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219

In [106]:
df["city"].unique()

array(['Pune', 'Mumbai', 'Nashik', 'pune ', 'Bengaluru', 'PUNE ', nan],
      dtype=object)

In [107]:
df["city"].value_counts()

city
Mumbai       6
Pune         5
Nashik       3
Bengaluru    3
pune         1
PUNE         1
Name: count, dtype: int64

In [110]:
df["city"]=df.loc[df["city"]=="PUNE","city"]="Pune"

In [112]:
df["city"]

0     Pune
1     Pune
2     Pune
3     Pune
4     Pune
5     Pune
6     Pune
7     Pune
8     Pune
9     Pune
10    Pune
11    Pune
12    Pune
13    Pune
14    Pune
15    Pune
16    Pune
17    Pune
18    Pune
19    Pune
Name: city, dtype: object

In [115]:
df["city"].str.strip()

0          Pune
1        Mumbai
2          Pune
3        Nashik
4        Mumbai
5          pune
6     Bengaluru
7          Pune
8        Mumbai
9        Nashik
10         Pune
11       Mumbai
12    Bengaluru
13         PUNE
14       Nashik
15       Mumbai
16         Pune
17    Bengaluru
18       Mumbai
19          NaN
Name: city, dtype: object

In [116]:
df.dropna(inplace=True)

In [117]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226

In [119]:
df.loc[df["city"]=="PUNE","city"]="Pune"

In [120]:
df["city"]

0          Pune
1        Mumbai
2          Pune
3        Nashik
4        Mumbai
7          Pune
8        Mumbai
9        Nashik
10         Pune
12    Bengaluru
13        PUNE
15       Mumbai
17    Bengaluru
18       Mumbai
Name: city, dtype: object

In [125]:
df["city"].str.strip()

0          Pune
1        Mumbai
2          Pune
3        Nashik
4        Mumbai
7          Pune
8        Mumbai
9        Nashik
10         Pune
12    Bengaluru
13         PUNE
15       Mumbai
17    Bengaluru
18       Mumbai
Name: city, dtype: object

In [129]:
df.drop(13)

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226

In [130]:
df.groupby("city").salary.sum()

city
Bengaluru    163000.0
Mumbai       449000.0
Nashik       156000.0
PUNE          83000.0
Pune         310000.0
Name: salary, dtype: float64

In [131]:
df["job_title"].value_counts()

job_title
Manager           5
Engineer          3
Analyst           2
HR Executive      2
Senior Manager    1
Data Analyst      1
Name: count, dtype: int64

In [132]:
df["salary"].nlargest()

4     125000.0
7     105000.0
12     99000.0
2      95000.0
15     92000.0
Name: salary, dtype: float64

In [135]:
df["salary"].nsmallest()

0     52000.0
10    58000.0
17    64000.0
3     68000.0
18    76000.0
Name: salary, dtype: float64

In [137]:
df["salary"].rank()

0      1.0
1      6.5
2     11.0
3      4.0
4     14.0
7     13.0
8      6.5
9      9.0
10     2.0
12    12.0
13     8.0
15    10.0
17     3.0
18     5.0
Name: salary, dtype: float64

In [138]:
df["name"].isnull().sum()

np.int64(0)

In [139]:
df.isnull().sum()

emp_id        0
name          0
age           0
salary        0
dept_id       0
job_title     0
city          0
hire_date     0
manager_id    0
email         0
phone         0
dtype: int64

In [143]:
df.randon_state(20)

AttributeError: 'DataFrame' object has no attribute 'randon_state'

In [144]:
df["Bonus"] = df["salary"]+(df["salary"]*10/100)

In [145]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone,Bonus
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210,57200.0
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211,85800.0
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655,104500.0
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789,74800.0
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212,137500.0
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215,115500.0
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211,85800.0
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217,96800.0
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218,63800.0
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220,108900.0
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221,91300.0
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223,101200.0
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225,70400.0
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226,83600.0

In [147]:
df.drop(columns="Bonus")

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226

In [154]:
df[(df["job_title"].apply(lambda x:x.split()[0])=="Senior")&(df["salary"]>10000)]

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone,Bonus
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212,137500.0

In [156]:
np.where

In [160]:
department_names = {
    1: "HR",
    2: "IT",
    3: "Finance",
    4: "Sales",
    5: "Marketing"
}

df["department"] = df["dept_id"].map(department_names)

print(df[["dept_id", "department"]].head())

   dept_id department
0        1         HR
1        2         IT
2        1         HR
3        3    Finance
4        2         IT

In [161]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone,Bonus,department
0,101,Aarav Sharma,24.0,52000.0,1,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210,57200.0,HR
1,102,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211,85800.0,IT
2,103,Rahul Deshmukh,35.0,95000.0,1,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655,104500.0,HR
3,104,Sneha Joshi,31.0,68000.0,3,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789,74800.0,Finance
4,105,Vikram More,42.0,125000.0,2,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212,137500.0,IT
7,108,Kunal Jadhav,38.0,105000.0,2,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215,115500.0,IT
8,109,Priya Patil,29.0,78000.0,2,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211,85800.0,IT
9,110,Meera Kulkarni,33.0,88000.0,3,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217,96800.0,Finance
10,111,Aditya Joshi,27.0,58000.0,1,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218,63800.0,HR
12,113,Rohan More,30.0,99000.0,1,Engineer,Bengaluru,2020-10-09,117.0,rohan@example.com,9876543220,108900.0,HR
13,114,Anaya Shah,36.0,83000.0,3,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221,91300.0,Finance
15,116,Sana Khan,32.0,92000.0,2,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223,101200.0,IT
17,118,Maya Rao,25.0,64000.0,1,Analyst,Bengaluru,2024-02-11,103.0,maya@example.com,9876543225,70400.0,HR
18,119,Dev Kulkarni,34.0,76000.0,2,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226,83600.0,IT

In [171]:
df=df.loc[df["city"]=="Bengaluru"].replace("Bengaluru","Bangalore",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_30344\1595304324.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df=df.loc[df["city"]=="Bengaluru"].replace("Bengaluru","Bangalore",inplace=True)

In [172]:
# df[df["city"]=="Bangalore"]df

In [173]:
df

In [178]:
df[df["city"]=="Bengaluru","city"].replace("Bengaluru','Bangalore')]

SyntaxError: unterminated string literal (detected at line 1) (1647783355.py, line 1)

In [180]:
df["city"] = df["city"].replace("Bengaluru","Bangalore")

In [181]:
df["city"]

0          Pune
1        Mumbai
2          Pune
3        Nashik
4        Mumbai
5         pune
6     Bangalore
7          Pune
8        Mumbai
9        Nashik
10         Pune
11       Mumbai
12    Bangalore
13        PUNE
14       Nashik
15       Mumbai
16         Pune
17    Bangalore
18       Mumbai
19          NaN
Name: city, dtype: object

In [182]:
df["category"].dtype

KeyError: 'category'

In [191]:
df["dept_id"]=df["dept_id"].astype("float")

In [576]:
df["email"]

KeyError: 'email'

In [192]:
df

,emp_id,name,age,salary,dept_id,job_title,city,hire_date,manager_id,email,phone
0,101,Aarav Sharma,24.0,52000.0,1.0,Analyst,Pune,2022-06-15,103.0,aarav@example.com,9876543210
1,102,Priya Patil,29.0,78000.0,2.0,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
2,103,Rahul Deshmukh,35.0,95000.0,1.0,Engineer,Pune,2019-08-22,117.0,rahul@example.com,9988776655
3,104,Sneha Joshi,31.0,68000.0,3.0,HR Executive,Nashik,2021-01-05,110.0,sneha@example.com,9123456789
4,105,Vikram More,42.0,125000.0,2.0,Senior Manager,Mumbai,2017-11-19,117.0,vikram@example.com,9876543212
5,106,Om Pawar,26.0,61000.0,1.0,Analyst,pune,2023-04-01,NaN,om@example.com,9876543213
6,107,Isha Shah,NaN,72000.0,3.0,Data Analyst,Bangalore,2022-09-12,108.0,isha@example.com,9876543214
7,108,Kunal Jadhav,38.0,105000.0,2.0,Manager,Pune,2018-05-30,105.0,kunal@example.com,9876543215
8,109,Priya Patil,29.0,78000.0,2.0,Manager,Mumbai,2020-03-10,105.0,priya.patil@example.com,98765 43211
9,110,Meera Kulkarni,33.0,88000.0,3.0,HR Executive,Nashik,2021-07-18,110.0,meera@example.com,9876543217
10,111,Aditya Joshi,27.0,58000.0,1.0,Engineer,Pune,2022-02-14,103.0,aditya@example.com,9876543218
11,112,Neha Patil,45.0,NaN,2.0,Senior Manager,Mumbai,2016-12-01,105.0,neha@example.com,9876543219
12,113,Rohan More,30.0,99000.0,1.0,Engineer,Bangalore,2020-10-09,117.0,rohan@example.com,9876543220
13,114,Anaya Shah,36.0,83000.0,3.0,Data Analyst,PUNE,2019-06-21,110.0,anaya@example.com,9876543221
14,115,Kabir Pawar,28.0,47000.0,1.0,Analyst,Nashik,2023-01-16,NaN,kabir@example.com,9876543222
15,116,Sana Khan,32.0,92000.0,2.0,Manager,Mumbai,2018-09-03,105.0,sana@example.com,9876543223
16,117,Arjun Desai,41.0,115000.0,3.0,Senior Manager,Pune,2015-04-25,NaN,arjun@example.com,9876543224
17,118,Maya Rao,25.0,64000.0,1.0,Analyst,Bangalore,2024-02-11,103.0,maya@example.com,9876543225
18,119,Dev Kulkarni,34.0,76000.0,2.0,Manager,Mumbai,2021-05-17,105.0,dev@example.com,9876543226
19,120,Tara Singh,-2.0,500000.0,3.0,Director,NaN,2020-08-08,117.0,tara.example.com,123

In [577]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Admin\Downloads\massive_synthetic_healthcare_dataset.csv")

In [578]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25.0,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Endocrinology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8.0,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,Endocrinology,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5.0,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,Neurology,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6.0,Female,AB+,NaN,Public,Elective,Kidney Disease,Metformin,...,Semi-private,Cardiology,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20.0,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,Nephrology,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50495,PT011477,ADM147682,60.0,Male,AB+,Bengaluru,Employer,Elective,Hypertension,Amlodipine,...,General,Pulmonology,H087,No,Current,26.8,166.0,113.0,60.0,No
50496,PT007606,ADM133761,24.0,Female,A+,Nashik,Private,Emergency,Arthritis,Amlodipine,...,Semi-private,Orthopedics,H078,No,Never,27.9,182.0,NaN,118.0,No
50497,PT009866,ADM135390,92.0,Female,O-,Hyderabad,Private,Elective,Kidney Disease,NaN,...,General,Orthopedics,H057,No,Never,31.3,153.0,58.0,110.0,Yes
50498,PT006030,ADM128565,14.0,Other,A-,Nashik,Employer,Elective,Diabetes,Paracetamol,...,Semi-private,Endocrinology,H119,No,Current,29.3,123.0,73.0,97.0,Yes
50499,PT014577,ADM133575,14.0,Female,AB+,Mumbai,NaN,Emergency,Cancer,Ibuprofen,...,Private,Nephrology,H114,No,Current,20.4,104.0,75.0,117.0,Yes

In [579]:
df.head()

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25.0,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Endocrinology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8.0,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,Endocrinology,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5.0,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,Neurology,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6.0,Female,AB+,NaN,Public,Elective,Kidney Disease,Metformin,...,Semi-private,Cardiology,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20.0,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,Nephrology,H006,No,Never,33.1,145.0,105.0,137.0,Yes

In [580]:
df.sample()

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
7559,PT007121,ADM107559,67.0,Female,A+,Chennai,Private,Emergency,Hypertension,Ibuprofen,...,ICU,Nephrology,H061,No,Former,29.5,110.0,82.0,134.0,Yes

In [581]:
df["age"]=df["age"].apply(lambda x:x*(-1) if x<0 else x*1)

In [582]:
df[df["age"]<0]

Empty DataFrame
Columns: [patient_id, admission_id, age, gender, blood_type, city, insurance_provider, admission_type, medical_condition, medication, test_results, length_of_stay_days, admission_date, discharge_date, billing_amount_inr, room_type, doctor_specialty, hospital_id, readmission_30_days, smoking_status, bmi, systolic_bp, diastolic_bp, heart_rate_bpm, followup_completed]
Index: []

[0 rows x 25 columns]

In [583]:
df.isnull().sum()

patient_id                0
admission_id              0
age                     759
gender                  404
blood_type             1257
city                    608
insurance_provider     1769
admission_type            0
medical_condition       903
medication             7440
test_results           1262
length_of_stay_days       0
admission_date            0
discharge_date          403
billing_amount_inr     1008
room_type               756
doctor_specialty       1011
hospital_id               0
readmission_30_days       0
smoking_status         1509
bmi                    1771
systolic_bp            1013
diastolic_bp           1009
heart_rate_bpm          908
followup_completed     1268
dtype: int64

In [584]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50500 entries, 0 to 50499
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           50500 non-null  object
 1   admission_id         50500 non-null  object
 2   age                  49741 non-null  float64
 3   gender               50096 non-null  object
 4   blood_type           49243 non-null  object
 5   city                 49892 non-null  object
 6   insurance_provider   48731 non-null  object
 7   admission_type       50500 non-null  object
 8   medical_condition    49597 non-null  object
 9   medication           43060 non-null  object
 10  test_results         49238 non-null  object
 11  length_of_stay_days  50500 non-null  int64
 12  admission_date       50500 non-null  object
 13  discharge_date       50097 non-null  object
 14  billing_amount_inr   49492 non-null  float64
 15  room_type            49744 non-null  object
 16  doctor_specialty     49489 non-null  object
 17  hospital_id          50500 non-null  object
 18  readmission_30_days  50500 non-null  object
 19  smoking_status       48991 non-null  object
 20  bmi                  48729 non-null  float64
 21  systolic_bp          49487 non-null  float64
 22  diastolic_bp         49491 non-null  float64
 23  heart_rate_bpm       49592 non-null  float64
 24  followup_completed   49232 non-null  object
dtypes: float64(6), int64(1), object(18)
memory usage: 9.6+ MB

In [585]:
df["age"] = df["age"].fillna(df["age"].mean())

In [586]:
df.duplicated().sum()

np.int64(500)

In [587]:
df.drop_duplicates(inplace=True)

In [588]:
df.duplicated().sum()

np.int64(0)

In [589]:
df.describe()

,age,length_of_stay_days,billing_amount_inr,bmi,systolic_bp,diastolic_bp,heart_rate_bpm
count,50000.000000,50000.000000,4.900000e+04,48250.000000,49000.000000,49000.000000,49101.000000
mean,48.070237,11.029240,3.583434e+04,26.569198,137.760245,85.001122,92.422700
std,27.201580,7.174545,4.821472e+04,5.815069,30.619878,20.528050,27.597666
min,0.000000,-2.000000,-5.000000e+02,4.200000,20.000000,10.000000,5.000000
25%,25.000000,6.000000,2.295100e+04,22.600000,111.000000,67.000000,69.000000
50%,48.079813,11.000000,3.290772e+04,26.600000,138.000000,85.000000,92.000000
75%,72.000000,16.000000,4.542577e+04,30.500000,164.000000,103.000000,116.000000
max,150.000000,800.000000,9.999999e+06,120.500000,350.000000,220.000000,300.000000

In [590]:
df.columns

Index(['patient_id', 'admission_id', 'age', 'gender', 'blood_type', 'city',
       'insurance_provider', 'admission_type', 'medical_condition',
       'medication', 'test_results', 'length_of_stay_days', 'admission_date',
       'discharge_date', 'billing_amount_inr', 'room_type', 'doctor_specialty',
       'hospital_id', 'readmission_30_days', 'smoking_status', 'bmi',
       'systolic_bp', 'diastolic_bp', 'heart_rate_bpm', 'followup_completed'],
      dtype='object')

In [591]:
a = df["gender"].mode()

In [592]:
df["gender"] = df["gender"].fillna(a)

In [593]:
df.isnull().sum()

patient_id                0
admission_id              0
age                       0
gender                  400
blood_type             1250
city                    600
insurance_provider     1750
admission_type            0
medical_condition       899
medication             7373
test_results           1250
length_of_stay_days       0
admission_date            0
discharge_date          400
billing_amount_inr     1000
room_type               750
doctor_specialty       1000
hospital_id               0
readmission_30_days       0
smoking_status         1500
bmi                    1750
systolic_bp            1000
diastolic_bp           1000
heart_rate_bpm          899
followup_completed     1250
dtype: int64

In [594]:
df.columns

Index(['patient_id', 'admission_id', 'age', 'gender', 'blood_type', 'city',
       'insurance_provider', 'admission_type', 'medical_condition',
       'medication', 'test_results', 'length_of_stay_days', 'admission_date',
       'discharge_date', 'billing_amount_inr', 'room_type', 'doctor_specialty',
       'hospital_id', 'readmission_30_days', 'smoking_status', 'bmi',
       'systolic_bp', 'diastolic_bp', 'heart_rate_bpm', 'followup_completed'],
      dtype='object')

In [595]:
df.shape

(50000, 25)

In [596]:
df.columns

Index(['patient_id', 'admission_id', 'age', 'gender', 'blood_type', 'city',
       'insurance_provider', 'admission_type', 'medical_condition',
       'medication', 'test_results', 'length_of_stay_days', 'admission_date',
       'discharge_date', 'billing_amount_inr', 'room_type', 'doctor_specialty',
       'hospital_id', 'readmission_30_days', 'smoking_status', 'bmi',
       'systolic_bp', 'diastolic_bp', 'heart_rate_bpm', 'followup_completed'],
      dtype='object')

In [597]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           50000 non-null  object
 1   admission_id         50000 non-null  object
 2   age                  50000 non-null  float64
 3   gender               49600 non-null  object
 4   blood_type           48750 non-null  object
 5   city                 49400 non-null  object
 6   insurance_provider   48250 non-null  object
 7   admission_type       50000 non-null  object
 8   medical_condition    49101 non-null  object
 9   medication           42627 non-null  object
 10  test_results         48750 non-null  object
 11  length_of_stay_days  50000 non-null  int64
 12  admission_date       50000 non-null  object
 13  discharge_date       49600 non-null  object
 14  billing_amount_inr   49000 non-null  float64
 15  room_type            49250 non-null  object
 16  doctor_specialty     49000 non-null  object
 17  hospital_id          50000 non-null  object
 18  readmission_30_days  50000 non-null  object
 19  smoking_status       48500 non-null  object
 20  bmi                  48250 non-null  float64
 21  systolic_bp          49000 non-null  float64
 22  diastolic_bp         49000 non-null  float64
 23  heart_rate_bpm       49101 non-null  float64
 24  followup_completed   48750 non-null  object
dtypes: float64(6), int64(1), object(18)
memory usage: 9.9+ MB

In [598]:
df["discharge_date"] = pd.to_datetime(df["discharge_date"],format="mixed")

In [599]:
# df["admission_date"] = pd.to_datetime(df["admission_date"],format="mixed")
df["admission_date"].sample(220)

4587     2022-05-26
23874    2023-05-26
489      2022-02-11
17014    2025-11-03
30221    2024-03-24
            ...
48413    2022-11-09
21786    2022-02-03
17017    2023-10-28
35643    2022-09-07
34534    2023-04-20
Name: admission_date, Length: 220, dtype: object

In [600]:
df.isnull().sum()

patient_id                0
admission_id              0
age                       0
gender                  400
blood_type             1250
city                    600
insurance_provider     1750
admission_type            0
medical_condition       899
medication             7373
test_results           1250
length_of_stay_days       0
admission_date            0
discharge_date          400
billing_amount_inr     1000
room_type               750
doctor_specialty       1000
hospital_id               0
readmission_30_days       0
smoking_status         1500
bmi                    1750
systolic_bp            1000
diastolic_bp           1000
heart_rate_bpm          899
followup_completed     1250
dtype: int64

In [601]:

a = df["smoking_status"].mode()

df["smoking_status"] = df["smoking_status"].fillna(a)

In [602]:
df.loc[df["smoking_status"].isnull(),"smoking_status"]=a

In [603]:
df.isnull().sum()

patient_id                0
admission_id              0
age                       0
gender                  400
blood_type             1250
city                    600
insurance_provider     1750
admission_type            0
medical_condition       899
medication             7373
test_results           1250
length_of_stay_days       0
admission_date            0
discharge_date          400
billing_amount_inr     1000
room_type               750
doctor_specialty       1000
hospital_id               0
readmission_30_days       0
smoking_status         1500
bmi                    1750
systolic_bp            1000
diastolic_bp           1000
heart_rate_bpm          899
followup_completed     1250
dtype: int64

In [604]:
df.groupby("smoking_status")["admission_id"].count()

smoking_status
Current     8777
Former      9759
Never      25121
Unknown     4843
Name: admission_id, dtype: int64

In [605]:
a

0    Never
Name: smoking_status, dtype: object

In [606]:
# df["smoking_status"]=df.loc[df["smoking_status"].isnull(),"smoking_status"]=a
df["smoking_status"]

0         Former
1          Never
2         Former
3        Current
4          Never
          ...
49995     Former
49996      Never
49997     Former
49998     Former
49999    Current
Name: smoking_status, Length: 50000, dtype: object

In [607]:
df.isnull().sum()

patient_id                0
admission_id              0
age                       0
gender                  400
blood_type             1250
city                    600
insurance_provider     1750
admission_type            0
medical_condition       899
medication             7373
test_results           1250
length_of_stay_days       0
admission_date            0
discharge_date          400
billing_amount_inr     1000
room_type               750
doctor_specialty       1000
hospital_id               0
readmission_30_days       0
smoking_status         1500
bmi                    1750
systolic_bp            1000
diastolic_bp           1000
heart_rate_bpm          899
followup_completed     1250
dtype: int64

In [608]:
df["smoking_status"].value_counts()

smoking_status
Never      25121
Former      9759
Current     8777
Unknown     4843
Name: count, dtype: int64

In [609]:
df[df["smoking_status"]=="Unknown"]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
6,PT002061,ADM100006,1.0,Female,B+,Pune,NaN,Emergency,Hypertension,Albuterol,...,Semi-private,Nephrology,H075,No,Unknown,26.5,162.0,103.0,81.0,No
16,PT001855,ADM100016,16.0,Female,B+,Nagpur,Private,Emergency,Pneumonia,Albuterol,...,ICU,Pulmonology,H031,No,Unknown,22.3,99.0,116.0,92.0,Yes
17,PT003594,ADM100017,36.0,female,O+,Nagpur,Private,Emergency,Hypertension,NaN,...,General,Cardiology,H021,No,Unknown,33.1,125.0,100.0,83.0,Yes
41,PT015225,ADM100041,34.0,Male,O-,Pune,Private,Emergency,Asthma,Atorvastatin,...,Semi-private,General Medicine,H045,No,Unknown,28.1,165.0,59.0,126.0,Yes
57,PT007631,ADM100057,47.0,Female,O-,Nashik,Public,Emergency,Hypertension,Metformin,...,Private,General Medicine,H061,No,Unknown,28.0,109.0,62.0,69.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49923,PT003927,ADM149923,89.0,Male,A-,Chennai,Private,Elective,Heart disease,NaN,...,General,Endocrinology,H059,No,Unknown,31.5,186.0,101.0,52.0,Yes
49955,PT007571,ADM149955,1.0,Male,O+,Nagpur,Public,Emergency,Pneumonia,Paracetamol,...,General,General Medicine,H115,No,Unknown,32.1,116.0,94.0,90.0,Yes
49967,PT005383,ADM149967,38.0,Female,O-,Kolkata,Public,Urgent,Arthritis,Albuterol,...,General,Oncology,H111,No,Unknown,32.8,113.0,89.0,113.0,Yes
49973,PT002843,ADM149973,10.0,Female,A-,Hyderabad,Public,Emergency,Migraine,Amoxicillin,...,Private,Neurology,H119,No,Unknown,28.0,98.0,74.0,105.0,No
49975,PT002148,ADM149975,80.0,Female,B-,Pune,Self-pay,Elective,Kidney Disease,NaN,...,General,Pulmonology,H019,No,Unknown,NaN,107.0,108.0,73.0,Yes

In [610]:
df.isnull().sum()

patient_id                0
admission_id              0
age                       0
gender                  400
blood_type             1250
city                    600
insurance_provider     1750
admission_type            0
medical_condition       899
medication             7373
test_results           1250
length_of_stay_days       0
admission_date            0
discharge_date          400
billing_amount_inr     1000
room_type               750
doctor_specialty       1000
hospital_id               0
readmission_30_days       0
smoking_status         1500
bmi                    1750
systolic_bp            1000
diastolic_bp           1000
heart_rate_bpm          899
followup_completed     1250
dtype: int64

In [611]:
a = df["smoking_status"].mode()

In [612]:
a[0]

'Never'

In [613]:
df["smoking_status"] = df["smoking_status"].fillna(a[0])

In [614]:
df.isnull().sum()

patient_id                0
admission_id              0
age                       0
gender                  400
blood_type             1250
city                    600
insurance_provider     1750
admission_type            0
medical_condition       899
medication             7373
test_results           1250
length_of_stay_days       0
admission_date            0
discharge_date          400
billing_amount_inr     1000
room_type               750
doctor_specialty       1000
hospital_id               0
readmission_30_days       0
smoking_status            0
bmi                    1750
systolic_bp            1000
diastolic_bp           1000
heart_rate_bpm          899
followup_completed     1250
dtype: int64

In [615]:
df["systolic_bp"] = df["systolic_bp"].fillna(df["systolic_bp"].mean())       
df["diastolic_bp"] = df["diastolic_bp"].fillna(df["diastolic_bp"].median())

In [616]:
df.isnull().sum()

patient_id                0
admission_id              0
age                       0
gender                  400
blood_type             1250
city                    600
insurance_provider     1750
admission_type            0
medical_condition       899
medication             7373
test_results           1250
length_of_stay_days       0
admission_date            0
discharge_date          400
billing_amount_inr     1000
room_type               750
doctor_specialty       1000
hospital_id               0
readmission_30_days       0
smoking_status            0
bmi                    1750
systolic_bp               0
diastolic_bp              0
heart_rate_bpm          899
followup_completed     1250
dtype: int64

In [617]:
df["gender"].mode()

0    Male
Name: gender, dtype: object

In [618]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25.0,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Endocrinology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8.0,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,Endocrinology,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5.0,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,Neurology,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6.0,Female,AB+,NaN,Public,Elective,Kidney Disease,Metformin,...,Semi-private,Cardiology,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20.0,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,Nephrology,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86.0,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,Endocrinology,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26.0,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,Oncology,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58.0,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,Cardiology,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47.0,Female,A+,Delhi,Employer,Emergency,Hypertension,NaN,...,Private,General Medicine,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43.0,Female,AB-,Nashik,Public,Urgent,Pneumonia,NaN,...,General,Pulmonology,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [619]:
a = df["gender"].mode()

In [620]:
df["gender"] = df["gender"].fillna(a[0])

In [621]:
df.isnull().sum()

patient_id                0
admission_id              0
age                       0
gender                    0
blood_type             1250
city                    600
insurance_provider     1750
admission_type            0
medical_condition       899
medication             7373
test_results           1250
length_of_stay_days       0
admission_date            0
discharge_date          400
billing_amount_inr     1000
room_type               750
doctor_specialty       1000
hospital_id               0
readmission_30_days       0
smoking_status            0
bmi                    1750
systolic_bp               0
diastolic_bp              0
heart_rate_bpm          899
followup_completed     1250
dtype: int64

In [622]:
a = df["medication"].mode()

In [623]:
df["medication"] = df["medication"].fillna(a[0])

In [624]:
df.isnull().sum()

patient_id                0
admission_id              0
age                       0
gender                    0
blood_type             1250
city                    600
insurance_provider     1750
admission_type            0
medical_condition       899
medication                0
test_results           1250
length_of_stay_days       0
admission_date            0
discharge_date          400
billing_amount_inr     1000
room_type               750
doctor_specialty       1000
hospital_id               0
readmission_30_days       0
smoking_status            0
bmi                    1750
systolic_bp               0
diastolic_bp              0
heart_rate_bpm          899
followup_completed     1250
dtype: int64

In [625]:
df["doctor_specialty"] = df["doctor_specialty"].mode()

In [626]:
df.isnull().sum()

patient_id                 0
admission_id               0
age                        0
gender                     0
blood_type              1250
city                     600
insurance_provider      1750
admission_type             0
medical_condition        899
medication                 0
test_results            1250
length_of_stay_days        0
admission_date             0
discharge_date           400
billing_amount_inr      1000
room_type                750
doctor_specialty       49999
hospital_id                0
readmission_30_days        0
smoking_status             0
bmi                     1750
systolic_bp                0
diastolic_bp               0
heart_rate_bpm           899
followup_completed      1250
dtype: int64

In [627]:
df["medical_condition"].value_counts().head(1)

medical_condition
Hypertension    8636
Name: count, dtype: int64

In [628]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25.0,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8.0,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5.0,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6.0,Female,AB+,NaN,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20.0,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86.0,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26.0,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58.0,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47.0,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43.0,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [629]:

df["admission_type"].value_counts()

admission_type
Emergency    20860
Elective     17628
Urgent       11512
Name: count, dtype: int64

In [630]:
df["age"] = df["age"].astype("int")

In [631]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,NaN,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [632]:
df["city"].isnull().sum()

np.int64(600)

In [633]:
a = df["city"].mode()

In [634]:
a

0    Chennai
Name: city, dtype: object

In [635]:
df[df["city"].isnull()]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
3,PT017829,ADM100003,6,Female,AB+,NaN,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
5,PT009640,ADM100005,43,Female,A-,NaN,Public,Urgent,NaN,Amoxicillin,...,General,NaN,H094,No,Never,34.1,120.0,81.0,74.0,Yes
62,PT007629,ADM100062,38,Male,AB+,NaN,Employer,Urgent,Hypertension,Amoxicillin,...,General,NaN,H063,No,Never,30.6,97.0,79.0,NaN,Yes
77,PT017513,ADM100077,58,Male,A+,NaN,Self-pay,Elective,Heart Disease,Ibuprofen,...,General,NaN,H092,No,Former,33.8,181.0,84.0,48.0,Yes
170,PT004534,ADM100170,86,Male,A+,NaN,Public,Elective,Heart Disease,Amoxicillin,...,Private,NaN,H098,No,Former,27.1,129.0,90.0,59.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49837,PT015725,ADM149837,17,Female,B+,NaN,Government,Elective,Diabetes,Amoxicillin,...,Semi-private,NaN,H066,Yes,Never,25.3,93.0,69.0,NaN,No
49864,PT014548,ADM149864,79,Male,AB+,NaN,Employer,Elective,Diabetes,Metformin,...,Private,NaN,H096,No,Never,25.1,136.0,53.0,105.0,No
49879,PT003262,ADM149879,24,Male,A+,NaN,Self-pay,Emergency,Asthma,Metformin,...,General,NaN,H066,No,Never,28.1,154.0,102.0,88.0,Yes
49883,PT017184,ADM149883,92,Male,AB+,NaN,Self-pay,Elective,Diabetes,Atorvastatin,...,Semi-private,NaN,H072,Yes,Never,32.8,155.0,76.0,126.0,Yes
49911,PT000770,ADM149911,53,Other,O-,NaN,Government,Elective,Heart Disease,Metformin,...,General,NaN,H105,No,Former,28.8,132.0,116.0,98.0,No

In [636]:
df["city"] = df["city"].fillna("Unknow")

In [637]:
df.isnull().sum()

patient_id                 0
admission_id               0
age                        0
gender                     0
blood_type              1250
city                       0
insurance_provider      1750
admission_type             0
medical_condition        899
medication                 0
test_results            1250
length_of_stay_days        0
admission_date             0
discharge_date           400
billing_amount_inr      1000
room_type                750
doctor_specialty       49999
hospital_id                0
readmission_30_days        0
smoking_status             0
bmi                     1750
systolic_bp                0
diastolic_bp               0
heart_rate_bpm           899
followup_completed      1250
dtype: int64

In [638]:
df.head()

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes

In [639]:
df.tail(15)

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
49985,PT014727,ADM149985,93,Female,A-,Nagpur,Employer,Urgent,Arthritis,Metformin,...,General,NaN,H045,Yes,Former,30.9,128.0,88.0,NaN,Yes
49986,PT016968,ADM149986,53,Male,AB+,Delhi,Private,Emergency,Arthritis,Amoxicillin,...,Semi-private,NaN,H112,No,Never,31.2,188.0,85.0,48.0,Yes
49987,PT006882,ADM149987,79,Male,B+,Mumbai,Private,Elective,Diabetes,Ibuprofen,...,Private,NaN,H093,No,Never,37.4,162.0,91.0,134.0,Yes
49988,PT012147,ADM149988,42,Other,B+,Chennai,Employer,Urgent,Heart Disease,Amoxicillin,...,General,NaN,H081,No,Former,26.0,159.0,59.0,77.0,Yes
49989,PT006713,ADM149989,66,Female,O-,Mumbai,Private,Elective,NaN,Amlodipine,...,Private,NaN,H011,No,Never,28.5,97.0,109.0,74.0,Yes
49990,PT011329,ADM149990,49,Female,B+,Nashik,Private,Emergency,Cancer,Atorvastatin,...,Semi-private,NaN,H019,No,Never,22.8,87.0,104.0,76.0,No
49991,PT014795,ADM149991,20,Male,AB-,Jaipur,Public,Urgent,Diabetes,Atorvastatin,...,Semi-private,NaN,H052,No,Never,25.7,161.0,112.0,133.0,Yes
49992,PT009040,ADM149992,90,Female,AB-,Nagpur,Employer,Emergency,Kidney Disease,Amlodipine,...,Semi-private,NaN,H011,No,Never,33.9,90.0,72.0,82.0,Yes
49993,PT007753,ADM149993,46,Male,A+,Nashik,Private,Elective,Healthy,Metformin,...,Semi-private,NaN,H022,No,Never,35.3,161.0,102.0,48.0,Yes
49994,PT017587,ADM149994,22,Female,O+,Pune,Private,Urgent,Heart Disease,Amlodipine,...,Semi-private,NaN,H085,No,Former,30.1,113.0,91.0,85.0,Yes
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [640]:
df.shape

(50000, 25)

In [641]:
df.columns

Index(['patient_id', 'admission_id', 'age', 'gender', 'blood_type', 'city',
       'insurance_provider', 'admission_type', 'medical_condition',
       'medication', 'test_results', 'length_of_stay_days', 'admission_date',
       'discharge_date', 'billing_amount_inr', 'room_type', 'doctor_specialty',
       'hospital_id', 'readmission_30_days', 'smoking_status', 'bmi',
       'systolic_bp', 'diastolic_bp', 'heart_rate_bpm', 'followup_completed'],
      dtype='object')

In [642]:
df.dtypes

patient_id                     object
admission_id                   object
age                             int64
gender                         object
blood_type                     object
city                           object
insurance_provider             object
admission_type                 object
medical_condition              object
medication                     object
test_results                   object
length_of_stay_days             int64
admission_date                 object
discharge_date         datetime64[ns]
billing_amount_inr            float64
room_type                      object
doctor_specialty               object
hospital_id                    object
readmission_30_days            object
smoking_status                 object
bmi                           float64
systolic_bp                   float64
diastolic_bp                  float64
heart_rate_bpm                float64
followup_completed             object
dtype: object

In [643]:
df.sample(20)

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
36132,PT012767,ADM136132,94,Male,B+,Chennai,NaN,Emergency,Hypertension,Metformin,...,Semi-private,NaN,H024,No,Former,36.5,132.000000,74.0,90.0,No
37599,PT006570,ADM137599,54,Female,A+,Mumbai,Private,Emergency,Heart Disease,Albuterol,...,General,NaN,H118,No,Current,16.2,166.000000,75.0,74.0,No
24907,PT008579,ADM124907,17,Male,B-,Chennai,Employer,Elective,Heart Disease,Amlodipine,...,General,NaN,H031,No,Current,27.2,111.000000,85.0,105.0,NaN
21870,PT001474,ADM121870,85,Male,A-,Bengaluru,Private,Emergency,Arthritis,Paracetamol,...,Semi-private,NaN,H097,No,Former,24.8,131.000000,92.0,133.0,No
22669,PT002753,ADM122669,89,Female,AB-,Jaipur,Government,Emergency,Healthy,Amoxicillin,...,Semi-private,NaN,H035,No,Unknown,21.2,140.000000,50.0,107.0,Yes
6574,PT014432,ADM106574,83,female,AB-,Hyderabad,Public,Elective,Heart Disease,Insulin,...,General,NaN,H051,No,Unknown,17.9,171.000000,102.0,80.0,Yes
16240,PT003666,ADM116240,85,Male,B+,Delhi,Public,Emergency,Diabetes,Amlodipine,...,Private,NaN,H068,No,Never,15.1,137.760245,115.0,133.0,Yes
33643,PT015992,ADM133643,59,Female,B-,Delhi,Self-pay,Emergency,Diabetes,Atorvastatin,...,Semi-private,NaN,H093,No,Never,NaN,117.000000,85.0,91.0,No
19500,PT004830,ADM119500,37,Male,AB-,Nagpur,Public,Elective,Heart Disease,Amoxicillin,...,Semi-private,NaN,H053,No,Former,30.6,123.000000,59.0,82.0,No
4703,PT004976,ADM104703,26,Female,A+,Delhi,Employer,Urgent,Heart Disease,Paracetamol,...,General,NaN,H098,No,Never,27.2,165.000000,71.0,117.0,Yes
44201,PT011002,ADM144201,75,Female,A+,Nashik,Private,Elective,Hypertension,Amoxicillin,...,Semi-private,NaN,H018,No,Former,17.0,158.000000,73.0,85.0,Yes
8344,PT005302,ADM108344,76,Male,B-,Jaipur,Government,Urgent,Heart Disease,Insulin,...,Private,NaN,H087,No,Current,26.0,163.000000,118.0,NaN,No
49516,PT005747,ADM149516,42,Male,AB+,Chennai,Private,Emergency,Asthma,Amoxicillin,...,General,NaN,H003,No,Never,28.3,153.000000,59.0,50.0,Yes
12740,PT014266,ADM112740,36,Female,B+,Kolkata,Public,Emergency,Heart Disease,Albuterol,...,General,NaN,H112,No,Unknown,36.7,190.000000,55.0,94.0,Yes
34753,PT009286,ADM134753,75,Female,B+,Kolkata,Private,Urgent,Arthritis,Insulin,...,Semi-private,NaN,H054,Yes,Unknown,32.6,123.000000,106.0,51.0,Yes
30204,PT016430,ADM130204,3,Male,A+,Mumbai,Private,Emergency,Diabetes,Amoxicillin,...,General,NaN,H091,No,Current,22.7,118.000000,117.0,85.0,Yes
30158,PT008564,ADM130158,25,Male,A-,Nagpur,Employer,Elective,Diabetes,Amoxicillin,...,Semi-private,NaN,H078,No,Current,26.6,126.000000,73.0,57.0,Yes
26195,PT002585,ADM126195,80,Female,AB+,Pune,Private,Emergency,Diabetes,Amlodipine,...,General,NaN,H111,No,Never,23.6,149.000000,58.0,54.0,No
41454,PT000094,ADM141454,94,Male,O-,Delhi,Employer,Elective,Kidney Disease,Amoxicillin,...,Semi-private,NaN,H109,No,Former,NaN,98.000000,107.0,138.0,No
12855,PT005498,ADM112855,84,Male,AB+,Mumbai,Employer,Emergency,Arthritis,Albuterol,...,General,NaN,H038,No,Current,23.1,125.000000,51.0,68.0,No

In [644]:
df.describe()

,age,length_of_stay_days,discharge_date,billing_amount_inr,bmi,systolic_bp,diastolic_bp,heart_rate_bpm
count,50000.000000,50000.000000,49600,4.900000e+04,48250.000000,50000.000000,50000.000000,49101.000000
mean,48.069040,11.029240,2023-07-17 03:31:40.451612928,3.583434e+04,26.569198,137.760245,85.001100,92.422700
min,0.000000,-2.000000,2021-01-04 00:00:00,-5.000000e+02,4.200000,20.000000,10.000000,5.000000
25%,25.000000,6.000000,2022-04-14 00:00:00,2.295100e+04,22.600000,112.000000,67.000000,69.000000
50%,48.000000,11.000000,2023-07-20 00:00:00,3.290772e+04,26.600000,137.760245,85.000000,92.000000
75%,72.000000,16.000000,2024-10-17 00:00:00,4.542577e+04,30.500000,164.000000,102.000000,116.000000
max,150.000000,800.000000,2026-07-01 00:00:00,9.999999e+06,120.500000,350.000000,220.000000,300.000000
std,27.201581,7.174545,NaN,4.821472e+04,5.815069,30.312126,20.321728,27.597666

In [645]:
df["gender"].unique

<bound method Series.unique of 0          Male
1        Female
2          Male
3        Female
4        Female
          ...
49995    Female
49996    Female
49997      Male
49998    Female
49999    Female
Name: gender, Length: 50000, dtype: object>

In [646]:
df.isnull().sum()

patient_id                 0
admission_id               0
age                        0
gender                     0
blood_type              1250
city                       0
insurance_provider      1750
admission_type             0
medical_condition        899
medication                 0
test_results            1250
length_of_stay_days        0
admission_date             0
discharge_date           400
billing_amount_inr      1000
room_type                750
doctor_specialty       49999
hospital_id                0
readmission_30_days        0
smoking_status             0
bmi                     1750
systolic_bp                0
diastolic_bp               0
heart_rate_bpm           899
followup_completed      1250
dtype: int64

In [647]:
df.isnull().sum()

patient_id                 0
admission_id               0
age                        0
gender                     0
blood_type              1250
city                       0
insurance_provider      1750
admission_type             0
medical_condition        899
medication                 0
test_results            1250
length_of_stay_days        0
admission_date             0
discharge_date           400
billing_amount_inr      1000
room_type                750
doctor_specialty       49999
hospital_id                0
readmission_30_days        0
smoking_status             0
bmi                     1750
systolic_bp                0
diastolic_bp               0
heart_rate_bpm           899
followup_completed      1250
dtype: int64

In [648]:
df.isnull().mean()

patient_id             0.00000
admission_id           0.00000
age                    0.00000
gender                 0.00000
blood_type             0.02500
city                   0.00000
insurance_provider     0.03500
admission_type         0.00000
medical_condition      0.01798
medication             0.00000
test_results           0.02500
length_of_stay_days    0.00000
admission_date         0.00000
discharge_date         0.00800
billing_amount_inr     0.02000
room_type              0.01500
doctor_specialty       0.99998
hospital_id            0.00000
readmission_30_days    0.00000
smoking_status         0.00000
bmi                    0.03500
systolic_bp            0.00000
diastolic_bp           0.00000
heart_rate_bpm         0.01798
followup_completed     0.02500
dtype: float64

In [649]:
df[df.isnull()==1]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [650]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [651]:
df[df["age"].isnull()]

Empty DataFrame
Columns: [patient_id, admission_id, age, gender, blood_type, city, insurance_provider, admission_type, medical_condition, medication, test_results, length_of_stay_days, admission_date, discharge_date, billing_amount_inr, room_type, doctor_specialty, hospital_id, readmission_30_days, smoking_status, bmi, systolic_bp, diastolic_bp, heart_rate_bpm, followup_completed]
Index: []

[0 rows x 25 columns]

In [652]:
df["medical_condition"].value_counts()

medical_condition
Hypertension      8636
Diabetes          7554
Heart Disease     5768
Asthma            4888
Pneumonia         4355
Migraine          3945
Arthritis         3881
Healthy           3860
Kidney Disease    2949
Cancer            2474
HYPERTENSION       309
 diabetes          283
Heart disease      199
Name: count, dtype: int64

In [653]:
df["smoking_status"].value_counts()

smoking_status
Never      26621
Former      9759
Current     8777
Unknown     4843
Name: count, dtype: int64

In [654]:
df["smoking_status"].value_counts()

smoking_status
Never      26621
Former      9759
Current     8777
Unknown     4843
Name: count, dtype: int64

In [655]:
df["smoking_status"]=df["smoking_status"].replace("Unknown",np.nan)

In [656]:
df["smoking_status"].value_counts()

smoking_status
Never      26621
Former      9759
Current     8777
Name: count, dtype: int64

In [657]:
df["smoking_status"]

0         Former
1          Never
2         Former
3        Current
4          Never
          ...
49995     Former
49996      Never
49997     Former
49998     Former
49999    Current
Name: smoking_status, Length: 50000, dtype: object

In [658]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [659]:
df["city"]=df["city"].str.strip()

In [660]:
df["city"]

0           Nashik
1          Chennai
2        Bengaluru
3           Unknow
4           Nashik
           ...
49995      Chennai
49996       Nagpur
49997       Nagpur
49998        Delhi
49999       Nashik
Name: city, Length: 50000, dtype: object

In [661]:
df["gender"] = df["gender"].replace({"male":1,"female":0})

In [662]:
df["gender"]

0          Male
1        Female
2          Male
3        Female
4        Female
          ...
49995    Female
49996    Female
49997      Male
49998    Female
49999    Female
Name: gender, Length: 50000, dtype: object

In [663]:
df[df["bmi"].isnull() & df["blood_type"].isnull()]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
1741,PT001414,ADM101741,68,female,NaN,Jaipur,Private,Elective,Heart Disease,Amlodipine,...,General,NaN,H089,No,Never,NaN,110.0,50.0,114.0,Yes
1970,PT014257,ADM101970,38,Female,NaN,Nashik,Government,Emergency,Hypertension,Amoxicillin,...,General,NaN,H042,No,NaN,NaN,88.0,53.0,96.0,Yes
2971,PT003684,ADM102971,21,Male,NaN,Delhi,Government,Urgent,Asthma,Amoxicillin,...,Semi-private,NaN,H002,Yes,Never,NaN,85.0,56.0,102.0,Yes
4938,PT000801,ADM104938,4,Male,NaN,Mumbai,Employer,Urgent,Heart Disease,Metformin,...,Private,NaN,H077,No,NaN,NaN,181.0,87.0,129.0,Yes
6320,PT004898,ADM106320,3,Female,NaN,Chennai,Public,Emergency,Diabetes,Amlodipine,...,General,NaN,H035,Yes,Never,NaN,103.0,79.0,100.0,Yes
6656,PT008693,ADM106656,62,Female,NaN,Bengaluru,Employer,Emergency,Heart Disease,Metformin,...,General,NaN,H029,No,Never,NaN,140.0,104.0,71.0,No
7409,PT009531,ADM107409,80,Male,NaN,Pune,Self-pay,Emergency,Cancer,Atorvastatin,...,Private,NaN,H020,No,Current,NaN,111.0,84.0,69.0,Yes
11427,PT011504,ADM111427,86,Male,NaN,Jaipur,Public,Urgent,Migraine,Atorvastatin,...,Private,NaN,H038,Yes,Never,NaN,169.0,50.0,78.0,Yes
14004,PT007615,ADM114004,21,Male,NaN,Jaipur,NaN,Urgent,Healthy,Amlodipine,...,General,NaN,H087,No,Never,NaN,92.0,120.0,49.0,No
15790,PT003131,ADM115790,64,Female,NaN,Kolkata,Self-pay,Elective,Asthma,Amoxicillin,...,General,NaN,H020,No,Former,NaN,124.0,102.0,103.0,No
18463,PT011807,ADM118463,36,Female,NaN,Chennai,Public,Urgent,Diabetes,Amoxicillin,...,Private,NaN,H072,No,Never,NaN,173.0,100.0,103.0,Yes
19817,PT005256,ADM119817,78,Female,NaN,Hyderabad,Employer,Emergency,Arthritis,Amoxicillin,...,General,NaN,H110,No,NaN,NaN,94.0,51.0,98.0,Yes
20162,PT002568,ADM120162,94,Male,NaN,Hyderabad,Employer,Urgent,Kidney Disease,Amoxicillin,...,General,NaN,H052,No,Former,NaN,98.0,84.0,76.0,No
21987,PT009234,ADM121987,76,Female,NaN,Delhi,Public,Urgent,Heart disease,Amoxicillin,...,Private,NaN,H119,No,Former,NaN,140.0,70.0,85.0,No
22246,PT013381,ADM122246,37,Female,NaN,Nashik,Self-pay,Emergency,Pneumonia,Paracetamol,...,Private,NaN,H020,No,Current,NaN,110.0,85.0,124.0,NaN
22291,PT005492,ADM122291,14,Female,NaN,Unknow,Government,Elective,Diabetes,Paracetamol,...,Semi-private,NaN,H051,No,Former,NaN,185.0,107.0,82.0,Yes
24176,PT006310,ADM124176,64,Male,NaN,Delhi,Self-pay,Emergency,Healthy,Albuterol,...,General,NaN,H104,No,Former,NaN,123.0,84.0,137.0,Yes
26341,PT009259,ADM126341,92,Male,NaN,Delhi,Private,Emergency,Diabetes,Amlodipine,...,Semi-private,NaN,H025,No,Never,NaN,186.0,52.0,59.0,Yes
26957,PT009377,ADM126957,22,Female,NaN,Chennai,Private,Emergency,Heart Disease,Amoxicillin,...,Semi-private,NaN,H059,No,Never,NaN,130.0,72.0,71.0,No
29053,PT015465,ADM129053,73,Male,NaN,Hyderabad,Self-pay,Emergency,Pneumonia,Insulin,...,ICU,NaN,H033,No,Never,NaN,145.0,88.0,109.0,Yes
33226,PT016054,ADM133226,93,Female,NaN,Nagpur,Employer,Elective,Healthy,Amoxicillin,...,NaN,NaN,H034,No,NaN,NaN,94.0,66.0,95.0,Yes
34549,PT004479,ADM134549,70,Female,NaN,Kolkata,Private,Elective,Arthritis,Amoxicillin,...,General,NaN,H061,No,Never,NaN,137.0,58.0,59.0,Yes
35499,PT006037,ADM135499,77,Male,NaN,Bengaluru,Public,Urgent,NaN,Amoxicillin,...,Semi-private,NaN,H086,Yes,NaN,NaN,167.0,120.0,119.0,Yes
35981,PT007819,ADM135981,32,Female,NaN,Chennai,Self-pay,Elective,Diabetes,Ibuprofen,...,General,NaN,H022,No,Never,NaN,87.0,113.0,46.0,Yes
36656,PT014632,ADM136656,7,Male,NaN,Nashik,Private,Elective,Asthma,Insulin,...,Private,NaN,H081,No,Never,NaN,169.0,70.0,45.0,Yes
36775,PT017716,ADM136775,13,Female,NaN,Bengaluru,Employer,Elective,diabetes,Amlodipine,...,General,NaN,H024,No,Never,NaN,137.0,115.0,47.0,Yes
38691,PT002420,ADM138691,72,Male,NaN,Jaipur,Private,Elective,Hypertension,Paracetamol,...,General,NaN,H046,No,Current,NaN,150.0,107.0,110.0,No
39084,PT003058,ADM139084,88,Female,NaN,Jaipur,Employer,Emergency,Heart Disease,Metformin,...,Private,NaN,H052,No,Never,NaN,147.0,105.0,67.0,Yes
39671,PT005036,ADM139671,64,Female,NaN,Kolkata,Public,Urgent,Heart Disease,Albuterol,...,General,NaN,H065,No,Current,NaN,132.0,92.0,137.0,Yes
40121,PT010153,ADM140121,86,Female,NaN,Pune,Private,Elective,Pneumonia,Amoxicillin,...,Private,NaN,H069,No,Former,NaN,159.0,107.0,131.0,Yes
42888,PT006956,ADM142888,52,Male,NaN,Nagpur,Self-pay,Elective,Asthma,Paracetamol,...,Semi-private,NaN,H004,No,Never,NaN,179.0,118.0,136.0,Yes
42976,PT013116,ADM142976,52,Female,NaN,Chennai,Public,Emergency,Migraine,Amlodipine,...,Semi-private,NaN,H096,No,Never,NaN,180.0,81.0,80.0,No
43727,PT015341,ADM143727,7,Female,NaN,Chennai,Employer,Elective,Hypertension,Albuterol,...,ICU,NaN,H076,No,Never,NaN,121.0,117.0,91.0,Yes
43786,PT011897,ADM143786,3,Female,NaN,Jaipur,Employer,Elective,Pneumonia,Insulin,...,General,NaN,H043,No,Never,NaN,107.0,72.0,53.0,Yes
46980,PT000687,ADM146980,8,Male,NaN,Delhi,Public,Urgent,Asthma,Insulin,...,NaN,NaN,H068,No,Never,NaN,171.0,75.0,83.0,Yes
47179,PT004327,ADM147179,75,Female,NaN,Chennai,Private,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H013,No,Never,NaN,138.0,60.0,68.0,Yes
47730,PT006541,ADM147730,55,Female,NaN,Delhi,Private,Urgent,Hypertension,Amoxicillin,...,Semi-private,NaN,H089,No,Current,NaN,101.0,53.0,99.0,Yes
49605,PT004538,ADM149605,1,Male,NaN,Nashik,Private,Emergency,Heart Disease,Insulin,...,Semi-private,NaN,H055,No,Never,NaN,145.0,111.0,95.0,Yes
49969,PT011498,ADM149969,79,Male,NaN,Bengaluru,Public,Urgent,Diabetes,Insulin,...,General,NaN,H037,No,Current,NaN,150.0,74.0,86.0,Yes

In [664]:
df1 = df.copy()

In [665]:
df1.dropna(inplace=True)

In [666]:
df1.shape

(1, 25)

In [667]:
df1

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes

In [668]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [669]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Length: 50000, dtype: bool

In [670]:
df[df.duplicated()]

Empty DataFrame
Columns: [patient_id, admission_id, age, gender, blood_type, city, insurance_provider, admission_type, medical_condition, medication, test_results, length_of_stay_days, admission_date, discharge_date, billing_amount_inr, room_type, doctor_specialty, hospital_id, readmission_30_days, smoking_status, bmi, systolic_bp, diastolic_bp, heart_rate_bpm, followup_completed]
Index: []

[0 rows x 25 columns]

In [671]:
df.drop_duplicates()

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [672]:
df["admission_id"].duplicated().sum()

np.int64(0)

In [673]:
df["patient_id"].duplicated().sum()

np.int64(33105)

In [674]:
df[df["patient_id"].duplicated()]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
217,PT015225,ADM100217,18,Female,O+,Pune,Public,Elective,Arthritis,Insulin,...,Private,NaN,H086,No,Never,25.3,164.0,119.0,117.0,No
289,PT001069,ADM100289,88,Male,O+,Nagpur,Private,Urgent,Hypertension,Atorvastatin,...,Semi-private,NaN,H104,No,Current,25.9,94.0,111.0,122.0,Yes
313,PT001069,ADM100313,68,Female,A+,Pune,Private,Elective,Diabetes,Ibuprofen,...,Semi-private,NaN,H045,No,Current,29.8,143.0,99.0,85.0,Yes
362,PT001988,ADM100362,42,Female,A+,Chennai,Private,Emergency,Hypertension,Insulin,...,Private,NaN,H115,No,Never,32.3,134.0,78.0,46.0,Yes
400,PT004267,ADM100400,78,Male,AB+,Delhi,Private,Urgent,Heart Disease,Paracetamol,...,Semi-private,NaN,H058,No,Never,24.4,99.0,87.0,68.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [675]:
df["hospital_id"].unique()

array(['H062', 'H007', 'H004', 'H113', 'H006', 'H094', 'H075', 'H118',
       'H045', 'H105', 'H100', 'H074', 'H106', 'H119', 'H031', 'H021',
       'H069', 'H112', 'H049', 'H013', 'H043', 'H104', 'H005', 'H077',
       'H063', 'H038', 'H029', 'H016', 'H101', 'H060', 'H098', 'H024',
       'H052', 'H053', 'H054', 'H109', 'H020', 'H055', 'H065', 'H026',
       'H102', 'H097', 'H061', 'H039', 'H064', 'H032', 'H079', 'H025',
       'H056', 'H050', 'H037', 'H041', 'H092', 'H009', 'H019', 'H047',
       'H058', 'H110', 'H018', 'H035', 'H076', 'H051', 'H072', 'H057',
       'H010', 'H083', 'H003', 'H066', 'H048', 'H091', 'H040', 'H088',
       'H073', 'H107', 'H111', 'H080', 'H014', 'H078', 'H034', 'H012',
       'H017', 'H071', 'H070', 'H082', 'H085', 'H103', 'H044', 'H022',
       'H114', 'H090', 'H059', 'H002', 'H096', 'H011', 'H115', 'H093',
       'H116', 'H008', 'H086', 'H120', 'H084', 'H023', 'H046', 'H108',
       'H067', 'H015', 'H027', 'H028', 'H117', 'H081', 'H001', 'H087',
       'H042', 'H099', 'H095', 'H030', 'H033', 'H068', 'H089', 'H036'],
      dtype=object)

In [676]:
df.select_dtypes("object")

,patient_id,admission_id,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,test_results,admission_date,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,followup_completed
0,PT008667,ADM100000,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,Normal,2022-09-17,General,Cardiology,H062,No,Former,Yes
1,PT013387,ADM100001,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,Normal,2022-04-07,General,NaN,H007,No,Never,Yes
2,PT008428,ADM100002,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,Normal,2024-02-18,General,NaN,H004,No,Former,Yes
3,PT017829,ADM100003,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,Abnormal,2024-09-09,Semi-private,NaN,H113,No,Current,Yes
4,PT000695,ADM100004,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,Abnormal,2023-04-23,General,NaN,H006,No,Never,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,Abnormal,2021-02-28,General,NaN,H092,No,Former,No
49996,PT004394,ADM149996,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,Inconclusive,2025-06-04,General,NaN,H051,No,Never,Yes
49997,PT010132,ADM149997,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,Abnormal,2024-06-10,Semi-private,NaN,H108,No,Former,Yes
49998,PT014268,ADM149998,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,Normal,2022-01-08,Private,NaN,H050,No,Former,Yes
49999,PT007753,ADM149999,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,Normal,2023-09-30,General,NaN,H044,No,Current,Yes

In [677]:
df = df.apply(lambda x:x.str.strip()  if x.dtypes=="object" else x)

In [678]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [679]:
# df["city"] = df["city"].replace({
#     "
df.loc[df["city"]=="MUMBAI","city"]="Mumbai"

In [680]:
df["city"].value_counts()

city
Chennai      5065
Bengaluru    5016
Kolkata      4953
Nagpur       4940
Hyderabad    4937
Jaipur       4922
Pune         4915
Mumbai       4863
Delhi        4850
Nashik       4742
Unknow        600
nashik        197
Name: count, dtype: int64

In [681]:
df.loc[df["city"]=="nashik","city"]="Nashik"

In [682]:
df.rename(columns={"diabetes":"Diabetes"},inplace=True)

In [683]:
df["medical_condition"].replace("diabetes","Diabetes",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_27196\2440384171.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["medical_condition"].replace("diabetes","Diabetes",inplace=True)

In [514]:
df["medical_condition"].value_counts()

medical_condition
Hypertension      8636
Diabetes          7837
Heart Disease     5768
Asthma            4888
Pneumonia         4355
Migraine          3945
Arthritis         3881
Healthy           3860
Kidney Disease    2949
Cancer            2474
HYPERTENSION       309
Heart disease      199
Name: count, dtype: int64

In [515]:
df.loc[df["insurance_provider"]=="Self-pay","insurance_provider"]="Self Pay"

In [516]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8,Female,A+,Chennai,Self Pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [531]:
df["medication"].sample(5).str.strip().replace("medication",np.nan)

18476     Amoxicillin
38358       Ibuprofen
8314     Atorvastatin
29142    Atorvastatin
45089         Insulin
Name: medication, dtype: object

In [532]:
df

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes
1,PT013387,ADM100001,8,Female,A+,Chennai,Self Pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes
49997,PT010132,ADM149997,58,Male,A+,Nagpur,Public,Elective,Cancer,Amlodipine,...,Semi-private,NaN,H108,No,Former,20.5,142.0,102.0,133.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [533]:
df["medication"].isnull().sum()

np.int64(0)

In [534]:
df["room_type"].value_counts()

room_type
General         22179
Semi-private    13268
Private          9924
ICU              3879
Name: count, dtype: int64

In [537]:
df[df["city"]=="Pune"]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
6,PT002061,ADM100006,1,Female,B+,Pune,NaN,Emergency,Hypertension,Albuterol,...,Semi-private,NaN,H075,No,NaN,26.5,162.0,103.0,81.0,No
40,PT008607,ADM100040,54,MALE,B-,Pune,Government,Urgent,Hypertension,Atorvastatin,...,General,NaN,H063,No,Never,23.5,156.0,101.0,80.0,No
41,PT015225,ADM100041,34,Male,O-,Pune,Private,Emergency,Asthma,Atorvastatin,...,Semi-private,NaN,H045,No,NaN,28.1,165.0,59.0,126.0,Yes
48,PT008664,ADM100048,46,Male,A-,Pune,Private,Elective,Arthritis,Metformin,...,General,NaN,H105,No,Never,26.1,135.0,62.0,80.0,No
59,PT007627,ADM100059,5,Female,AB+,Pune,Private,Elective,Kidney Disease,Metformin,...,ICU,NaN,H064,No,Never,14.2,142.0,92.0,68.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49953,PT001969,ADM149953,24,Male,A-,Pune,Private,Elective,HYPERTENSION,Amlodipine,...,General,NaN,H079,Yes,Never,28.1,182.0,118.0,117.0,Yes
49963,PT014303,ADM149963,19,Female,O-,Pune,Self Pay,Emergency,Arthritis,Ibuprofen,...,Semi-private,NaN,H014,No,Never,23.7,174.0,64.0,97.0,Yes
49975,PT002148,ADM149975,80,Female,B-,Pune,Self Pay,Elective,Kidney Disease,Amoxicillin,...,General,NaN,H019,No,NaN,NaN,107.0,108.0,73.0,Yes
49976,PT002615,ADM149976,78,Female,NaN,Pune,Private,Elective,Hypertension,Albuterol,...,General,NaN,H042,Yes,Never,31.0,152.0,85.0,101.0,No
49994,PT017587,ADM149994,22,Female,O+,Pune,Private,Urgent,Heart Disease,Amlodipine,...,Semi-private,NaN,H085,No,Former,30.1,113.0,91.0,85.0,Yes

In [538]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           50000 non-null  object
 1   admission_id         50000 non-null  object
 2   age                  50000 non-null  int64
 3   gender               50000 non-null  object
 4   blood_type           48750 non-null  object
 5   city                 50000 non-null  object
 6   insurance_provider   48250 non-null  object
 7   admission_type       50000 non-null  object
 8   medical_condition    49101 non-null  object
 9   medication           50000 non-null  object
 10  test_results         48750 non-null  object
 11  length_of_stay_days  50000 non-null  int64
 12  admission_date       50000 non-null  object
 13  discharge_date       49600 non-null  datetime64[ns]
 14  billing_amount_inr   49000 non-null  float64
 15  room_type            49250 non-null  object
 16  doctor_specialty     1 non-null      object
 17  hospital_id          50000 non-null  object
 18  readmission_30_days  50000 non-null  object
 19  smoking_status       45157 non-null  object
 20  bmi                  48250 non-null  float64
 21  systolic_bp          50000 non-null  float64
 22  diastolic_bp         50000 non-null  float64
 23  heart_rate_bpm       49101 non-null  float64
 24  followup_completed   48750 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(2), object(17)
memory usage: 9.9+ MB

In [545]:
df["admission_date"] = pd.to_datetime("admission_date",format="mixed")

DateParseError: Unknown datetime string format, unable to parse: admission_date, at position 0

In [546]:
df["admission_date"]

0        2022-09-17
1        2022-04-07
2        2024-02-18
3        2024-09-09
4        2023-04-23
            ...
49995    2021-02-28
49996    2025-06-04
49997    2024-06-10
49998    2022-01-08
49999    2023-09-30
Name: admission_date, Length: 50000, dtype: object

In [550]:
df["admission_date"] = pd.to_datetime("admission_date",errors="coerce")

In [553]:
df["admission_date"].sample()

25341   NaT
Name: admission_date, dtype: datetime64[ns]

In [560]:
df["billing_amount_inr"].dropna()

0        45076.90
1        47498.23
2        54897.42
3        15146.15
4        13819.58
           ...
49995    62355.09
49996    30268.52
49997    35319.65
49998    44662.59
49999    34916.35
Name: billing_amount_inr, Length: 49000, dtype: float64

In [562]:
df.shape

(50000, 25)

In [563]:
df["bmi"]

0        20.8
1        45.7
2        22.4
3        25.8
4        33.1
         ...
49995    20.9
49996    40.3
49997    20.5
49998    18.8
49999    29.9
Name: bmi, Length: 50000, dtype: float64

In [566]:
df[df["systolic_bp"] < df["diastolic_bp"]].shape

(4021, 25)

In [686]:
df["discharge_date"].astype("datetime64[ns]")

0       2022-09-21
1       2022-04-21
2       2024-02-26
3       2024-09-29
4       2023-04-25
           ...
49995   2021-03-03
49996   2025-06-07
49997   2024-06-16
49998   2022-01-24
49999   2023-10-11
Name: discharge_date, Length: 50000, dtype: datetime64[ns]

In [572]:
df

0       2022-09-21
1       2022-04-21
2       2024-02-26
3       2024-09-29
4       2023-04-25
           ...
49995   2021-03-03
49996   2025-06-07
49997   2024-06-16
49998   2022-01-24
49999   2023-10-11
Name: discharge_date, Length: 50000, dtype: datetime64[ns]

In [573]:
df1

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
0,PT008667,ADM100000,25,Male,B+,Nashik,Public,Elective,Asthma,Amlodipine,...,General,Cardiology,H062,No,Former,20.8,97.0,66.0,78.0,Yes

In [575]:
df1[df1["age"]>60]

Empty DataFrame
Columns: [patient_id, admission_id, age, gender, blood_type, city, insurance_provider, admission_type, medical_condition, medication, test_results, length_of_stay_days, admission_date, discharge_date, billing_amount_inr, room_type, doctor_specialty, hospital_id, readmission_30_days, smoking_status, bmi, systolic_bp, diastolic_bp, heart_rate_bpm, followup_completed]
Index: []

[0 rows x 25 columns]

In [688]:
df[df["age"]>60]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
7,PT003154,ADM100007,92,Female,AB-,Chennai,Private,Emergency,Heart Disease,Amlodipine,...,General,NaN,H118,No,Current,NaN,185.0,71.0,60.0,Yes
8,PT002015,ADM100008,75,Female,AB-,Kolkata,Public,Elective,Hypertension,Paracetamol,...,General,NaN,H045,Yes,Never,12.0,98.0,72.0,92.0,No
12,PT007891,ADM100012,66,Female,B-,Mumbai,Private,Emergency,Heart Disease,Amoxicillin,...,Private,NaN,H074,No,Never,32.7,89.0,87.0,57.0,Yes
13,PT010044,ADM100013,75,Male,O-,Bengaluru,Government,Elective,Hypertension,Atorvastatin,...,General,NaN,H007,No,Former,32.9,163.0,103.0,130.0,Yes
27,PT001469,ADM100027,65,Female,A-,Mumbai,Employer,Elective,Hypertension,Metformin,...,NaN,NaN,H005,No,Never,19.8,183.0,97.0,50.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49985,PT014727,ADM149985,93,Female,A-,Nagpur,Employer,Urgent,Arthritis,Metformin,...,General,NaN,H045,Yes,Former,30.9,128.0,88.0,NaN,Yes
49987,PT006882,ADM149987,79,Male,B+,Mumbai,Private,Elective,Diabetes,Ibuprofen,...,Private,NaN,H093,No,Never,37.4,162.0,91.0,134.0,Yes
49989,PT006713,ADM149989,66,Female,O-,Mumbai,Private,Elective,NaN,Amlodipine,...,Private,NaN,H011,No,Never,28.5,97.0,109.0,74.0,Yes
49992,PT009040,ADM149992,90,Female,AB-,Nagpur,Employer,Emergency,Kidney Disease,Amlodipine,...,Semi-private,NaN,H011,No,Never,33.9,90.0,72.0,82.0,Yes
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No

In [689]:
df[df["medical_condition"]=="Diabetes"]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
15,PT014994,ADM100015,7,Male,B-,Bengaluru,Self-pay,Emergency,Diabetes,Atorvastatin,...,Semi-private,NaN,H119,No,Current,21.3,101.0,58.0,71.0,No
28,PT013565,ADM100028,49,Female,A+,Nagpur,Public,Emergency,Diabetes,Atorvastatin,...,NaN,NaN,H021,No,Never,28.4,177.0,83.0,NaN,No
34,PT006573,ADM100034,37,Male,B+,Kolkata,Public,Emergency,Diabetes,Amlodipine,...,Private,NaN,H119,No,Never,25.1,179.0,76.0,48.0,Yes
35,PT000960,ADM100035,13,Male,AB-,Nashik,NaN,Urgent,Diabetes,Paracetamol,...,Semi-private,NaN,H038,No,Current,26.0,160.0,110.0,138.0,Yes
39,PT007180,ADM100039,3,Male,AB+,Mumbai,Self-pay,Emergency,Diabetes,Albuterol,...,General,NaN,H060,No,Never,30.7,181.0,65.0,99.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49974,PT011128,ADM149974,66,Male,AB-,Hyderabad,Government,Emergency,Diabetes,Amoxicillin,...,Semi-private,NaN,H096,No,Current,34.9,147.0,67.0,51.0,Yes
49980,PT011899,ADM149980,74,Male,A+,Hyderabad,Private,Emergency,Diabetes,Metformin,...,Semi-private,NaN,H081,No,Former,19.8,145.0,100.0,100.0,No
49984,PT007175,ADM149984,30,Female,A-,Nagpur,Public,Urgent,Diabetes,Amoxicillin,...,Private,NaN,H080,No,Current,24.5,146.0,101.0,99.0,No
49987,PT006882,ADM149987,79,Male,B+,Mumbai,Private,Elective,Diabetes,Ibuprofen,...,Private,NaN,H093,No,Never,37.4,162.0,91.0,134.0,Yes
49991,PT014795,ADM149991,20,Male,AB-,Jaipur,Public,Urgent,Diabetes,Atorvastatin,...,Semi-private,NaN,H052,No,Never,25.7,161.0,112.0,133.0,Yes

In [690]:
df[df["billing_amount_inr"]>50000]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
9,PT003083,ADM100009,16,Female,O-,Hyderabad,Private,Urgent,Arthritis,Paracetamol,...,General,NaN,H105,No,Never,26.4,99.0,116.0,68.0,No
17,PT003594,ADM100017,36,female,O+,Nagpur,Private,Emergency,Hypertension,Amoxicillin,...,General,NaN,H021,No,NaN,33.1,125.0,100.0,83.0,Yes
30,PT017748,ADM100030,54,Male,AB+,Kolkata,Public,Emergency,Heart Disease,Insulin,...,ICU,NaN,H104,No,Never,32.5,188.0,54.0,68.0,No
34,PT006573,ADM100034,37,Male,B+,Kolkata,Public,Emergency,Diabetes,Amlodipine,...,Private,NaN,H119,No,Never,25.1,179.0,76.0,48.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49979,PT016481,ADM149979,54,Male,A+,Kolkata,Employer,Emergency,Pneumonia,Amoxicillin,...,General,NaN,H057,No,Current,16.0,129.0,88.0,47.0,Yes
49980,PT011899,ADM149980,74,Male,A+,Hyderabad,Private,Emergency,Diabetes,Metformin,...,Semi-private,NaN,H081,No,Former,19.8,145.0,100.0,100.0,No
49988,PT012147,ADM149988,42,Other,B+,Chennai,Employer,Urgent,Heart Disease,Amoxicillin,...,General,NaN,H081,No,Former,26.0,159.0,59.0,77.0,Yes
49989,PT006713,ADM149989,66,Female,O-,Mumbai,Private,Elective,NaN,Amlodipine,...,Private,NaN,H011,No,Never,28.5,97.0,109.0,74.0,Yes
49995,PT007878,ADM149995,86,Female,AB+,Chennai,Private,Urgent,Hypertension,Paracetamol,...,General,NaN,H092,No,Former,20.9,171.0,70.0,125.0,No

In [692]:
df[df["length_of_stay_days"]>7]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
1,PT013387,ADM100001,8,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
2,PT008428,ADM100002,5,Male,A-,Bengaluru,Public,Elective,Pneumonia,Metformin,...,General,NaN,H004,No,Former,22.4,161.0,90.0,98.0,Yes
3,PT017829,ADM100003,6,Female,AB+,Unknow,Public,Elective,Kidney Disease,Metformin,...,Semi-private,NaN,H113,No,Current,25.8,121.0,52.0,99.0,Yes
5,PT009640,ADM100005,43,Female,A-,Unknow,Public,Urgent,NaN,Amoxicillin,...,General,NaN,H094,No,Never,34.1,120.0,81.0,74.0,Yes
7,PT003154,ADM100007,92,Female,AB-,Chennai,Private,Emergency,Heart Disease,Amlodipine,...,General,NaN,H118,No,Current,NaN,185.0,71.0,60.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49992,PT009040,ADM149992,90,Female,AB-,Nagpur,Employer,Emergency,Kidney Disease,Amlodipine,...,Semi-private,NaN,H011,No,Never,33.9,90.0,72.0,82.0,Yes
49993,PT007753,ADM149993,46,Male,A+,Nashik,Private,Elective,Healthy,Metformin,...,Semi-private,NaN,H022,No,Never,35.3,161.0,102.0,48.0,Yes
49994,PT017587,ADM149994,22,Female,O+,Pune,Private,Urgent,Heart Disease,Amlodipine,...,Semi-private,NaN,H085,No,Former,30.1,113.0,91.0,85.0,Yes
49998,PT014268,ADM149998,47,Female,A+,Delhi,Employer,Emergency,Hypertension,Amoxicillin,...,Private,NaN,H050,No,Former,18.8,147.0,72.0,93.0,Yes
49999,PT007753,ADM149999,43,Female,AB-,Nashik,Public,Urgent,Pneumonia,Amoxicillin,...,General,NaN,H044,No,Current,29.9,116.0,108.0,71.0,Yes

In [693]:
df[df["readmission_30_days"]=="Yes"]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
8,PT002015,ADM100008,75,Female,AB-,Kolkata,Public,Elective,Hypertension,Paracetamol,...,General,NaN,H045,Yes,Never,12.0,98.000000,72.0,92.0,No
18,PT007131,ADM100018,11,Male,O+,Bengaluru,Private,Elective,Kidney Disease,Amoxicillin,...,General,NaN,H069,Yes,Former,29.2,159.000000,91.0,53.0,No
21,PT003060,ADM100021,22,Female,AB+,Jaipur,Public,Emergency,NaN,Atorvastatin,...,Semi-private,NaN,H049,Yes,Current,36.1,174.000000,94.0,112.0,Yes
25,PT015334,ADM100025,43,Female,A+,Jaipur,Public,Emergency,Heart disease,Metformin,...,ICU,NaN,H075,Yes,Never,26.7,101.000000,95.0,123.0,Yes
33,PT016835,ADM100033,93,Male,O-,Mumbai,Government,Elective,Pneumonia,Amlodipine,...,Semi-private,NaN,H063,Yes,Never,21.1,137.760245,113.0,76.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49953,PT001969,ADM149953,24,Male,A-,Pune,Private,Elective,HYPERTENSION,Amlodipine,...,General,NaN,H079,Yes,Never,28.1,182.000000,118.0,117.0,Yes
49962,PT011268,ADM149962,6,Male,O-,Nashik,Private,Emergency,Arthritis,Amoxicillin,...,Private,NaN,H008,Yes,Never,30.0,145.000000,74.0,74.0,Yes
49971,PT008727,ADM149971,73,Female,A-,Bengaluru,Self-pay,Emergency,Heart Disease,Amlodipine,...,Semi-private,NaN,H090,Yes,Former,25.2,186.000000,85.0,56.0,Yes
49976,PT002615,ADM149976,78,Female,NaN,Pune,Private,Elective,Hypertension,Albuterol,...,General,NaN,H042,Yes,Never,31.0,152.000000,85.0,101.0,No
49985,PT014727,ADM149985,93,Female,A-,Nagpur,Employer,Urgent,Arthritis,Metformin,...,General,NaN,H045,Yes,Former,30.9,128.000000,88.0,NaN,Yes

In [694]:
df["doctor_specialty"].isnull().mean()

np.float64(0.99998)

In [696]:
df.columns

Index(['patient_id', 'admission_id', 'age', 'gender', 'blood_type', 'city',
       'insurance_provider', 'admission_type', 'medical_condition',
       'medication', 'test_results', 'length_of_stay_days', 'admission_date',
       'discharge_date', 'billing_amount_inr', 'room_type', 'doctor_specialty',
       'hospital_id', 'readmission_30_days', 'smoking_status', 'bmi',
       'systolic_bp', 'diastolic_bp', 'heart_rate_bpm', 'followup_completed'],
      dtype='object')

In [697]:
df[df['bmi']>30]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
1,PT013387,ADM100001,8,Female,A+,Chennai,Self-pay,Emergency,Hypertension,Atorvastatin,...,General,NaN,H007,No,Never,45.7,181.0,50.0,64.0,Yes
4,PT000695,ADM100004,20,Female,O-,Nashik,Private,Elective,Hypertension,Metformin,...,General,NaN,H006,No,Never,33.1,145.0,105.0,137.0,Yes
5,PT009640,ADM100005,43,Female,A-,Unknow,Public,Urgent,NaN,Amoxicillin,...,General,NaN,H094,No,Never,34.1,120.0,81.0,74.0,Yes
12,PT007891,ADM100012,66,Female,B-,Mumbai,Private,Emergency,Heart Disease,Amoxicillin,...,Private,NaN,H074,No,Never,32.7,89.0,87.0,57.0,Yes
13,PT010044,ADM100013,75,Male,O-,Bengaluru,Government,Elective,Hypertension,Atorvastatin,...,General,NaN,H007,No,Former,32.9,163.0,103.0,130.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49987,PT006882,ADM149987,79,Male,B+,Mumbai,Private,Elective,Diabetes,Ibuprofen,...,Private,NaN,H093,No,Never,37.4,162.0,91.0,134.0,Yes
49992,PT009040,ADM149992,90,Female,AB-,Nagpur,Employer,Emergency,Kidney Disease,Amlodipine,...,Semi-private,NaN,H011,No,Never,33.9,90.0,72.0,82.0,Yes
49993,PT007753,ADM149993,46,Male,A+,Nashik,Private,Elective,Healthy,Metformin,...,Semi-private,NaN,H022,No,Never,35.3,161.0,102.0,48.0,Yes
49994,PT017587,ADM149994,22,Female,O+,Pune,Private,Urgent,Heart Disease,Amlodipine,...,Semi-private,NaN,H085,No,Former,30.1,113.0,91.0,85.0,Yes
49996,PT004394,ADM149996,26,Female,AB-,Nagpur,Private,Elective,Pneumonia,Atorvastatin,...,General,NaN,H051,No,Never,40.3,109.0,52.0,134.0,Yes

In [698]:
df.sort_values("billing_amount_inr").head()

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
39326,PT001284,ADM139326,22,Other,AB+,Delhi,Private,Emergency,Hypertension,Paracetamol,...,Semi-private,NaN,H023,Yes,Current,NaN,180.0,55.0,132.0,Yes
43750,PT013763,ADM143750,2,Female,B-,Jaipur,Private,Emergency,NaN,Atorvastatin,...,NaN,NaN,H108,No,NaN,24.7,120.0,66.0,NaN,Yes
35188,PT011629,ADM135188,3,Female,B+,Jaipur,Public,Urgent,Kidney Disease,Amoxicillin,...,Semi-private,NaN,H012,No,Never,21.5,112.0,82.0,48.0,Yes
47887,PT012047,ADM147887,81,Female,AB+,Pune,Public,Elective,Arthritis,Albuterol,...,Private,NaN,H048,No,Never,28.7,107.0,59.0,96.0,No
42608,PT013869,ADM142608,21,Female,AB+,Chennai,Private,Urgent,Cancer,Paracetamol,...,General,NaN,H003,No,Former,28.2,158.0,89.0,57.0,Yes

In [699]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           50000 non-null  object
 1   admission_id         50000 non-null  object
 2   age                  50000 non-null  int64
 3   gender               50000 non-null  object
 4   blood_type           48750 non-null  object
 5   city                 50000 non-null  object
 6   insurance_provider   48250 non-null  object
 7   admission_type       50000 non-null  object
 8   medical_condition    49101 non-null  object
 9   medication           50000 non-null  object
 10  test_results         48750 non-null  object
 11  length_of_stay_days  50000 non-null  int64
 12  admission_date       50000 non-null  object
 13  discharge_date       49600 non-null  datetime64[ns]
 14  billing_amount_inr   49000 non-null  float64
 15  room_type            49250 non-null  object
 16  doctor_specialty     1 non-null      object
 17  hospital_id          50000 non-null  object
 18  readmission_30_days  50000 non-null  object
 19  smoking_status       45157 non-null  object
 20  bmi                  48250 non-null  float64
 21  systolic_bp          50000 non-null  float64
 22  diastolic_bp         50000 non-null  float64
 23  heart_rate_bpm       49101 non-null  float64
 24  followup_completed   48750 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(2), object(17)
memory usage: 9.9+ MB

In [700]:
df[(df["city"]=="Pune")&(df["room_type"]=="Private")]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
70,PT017202,ADM100070,41,Male,A+,Pune,Private,Emergency,Arthritis,Amlodipine,...,Private,NaN,H004,No,Former,27.5,137.0,102.0,91.0,Yes
95,PT017951,ADM100095,2,Female,AB+,Pune,Employer,Emergency,Pneumonia,Insulin,...,Private,NaN,H010,Yes,Current,21.8,151.0,55.0,123.0,Yes
143,PT014558,ADM100143,29,female,B-,Pune,Employer,Emergency,Hypertension,Amlodipine,...,Private,NaN,H070,No,Former,23.5,105.0,63.0,133.0,No
164,PT009175,ADM100164,78,Female,B+,Pune,Private,Elective,Asthma,Ibuprofen,...,Private,NaN,H009,Yes,Current,20.6,190.0,81.0,125.0,No
167,PT015715,ADM100167,80,Female,B+,Pune,Private,Urgent,Cancer,Amoxicillin,...,Private,NaN,H059,No,Never,36.3,174.0,97.0,129.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49798,PT010106,ADM149798,67,Female,O+,Pune,Public,Urgent,Asthma,Ibuprofen,...,Private,NaN,H113,No,Never,NaN,116.0,84.0,126.0,Yes
49836,PT010762,ADM149836,65,Female,B-,Pune,Public,Emergency,Heart Disease,Atorvastatin,...,Private,NaN,H053,No,Current,23.0,149.0,65.0,118.0,Yes
49846,PT013314,ADM149846,3,Male,B-,Pune,Private,Emergency,Asthma,Metformin,...,Private,NaN,H115,No,Current,32.0,175.0,110.0,46.0,Yes
49929,PT004614,ADM149929,45,Male,A-,Pune,Private,Elective,Pneumonia,Insulin,...,Private,NaN,H103,No,Current,26.0,165.0,92.0,97.0,Yes
49949,PT012579,ADM149949,26,Male,B+,Pune,Employer,Urgent,Hypertension,Amlodipine,...,Private,NaN,H097,No,Never,30.5,132.0,72.0,75.0,Yes

In [703]:
df[(df["test_results"]=="Abnormal")&(df["readmission_30_days"]=="Yes")]

,patient_id,admission_id,age,gender,blood_type,city,insurance_provider,admission_type,medical_condition,medication,...,room_type,doctor_specialty,hospital_id,readmission_30_days,smoking_status,bmi,systolic_bp,diastolic_bp,heart_rate_bpm,followup_completed
8,PT002015,ADM100008,75,Female,AB-,Kolkata,Public,Elective,Hypertension,Paracetamol,...,General,NaN,H045,Yes,Never,12.0,98.000000,72.0,92.0,No
21,PT003060,ADM100021,22,Female,AB+,Jaipur,Public,Emergency,NaN,Atorvastatin,...,Semi-private,NaN,H049,Yes,Current,36.1,174.000000,94.0,112.0,Yes
25,PT015334,ADM100025,43,Female,A+,Jaipur,Public,Emergency,Heart disease,Metformin,...,ICU,NaN,H075,Yes,Never,26.7,101.000000,95.0,123.0,Yes
33,PT016835,ADM100033,93,Male,O-,Mumbai,Government,Elective,Pneumonia,Amlodipine,...,Semi-private,NaN,H063,Yes,Never,21.1,137.760245,113.0,76.0,Yes
44,PT013099,ADM100044,74,Male,A-,Delhi,Private,Urgent,Cancer,Amoxicillin,...,Semi-private,NaN,H052,Yes,Never,25.8,99.000000,78.0,104.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49946,PT009869,ADM149946,2,Male,NaN,Nagpur,Private,Urgent,Kidney Disease,Paracetamol,...,Private,NaN,H021,Yes,Never,16.5,92.000000,74.0,46.0,Yes
49950,PT005874,ADM149950,30,Male,B+,Nagpur,Public,Emergency,Kidney Disease,Insulin,...,ICU,NaN,H049,Yes,Never,28.2,153.000000,101.0,96.0,No
49962,PT011268,ADM149962,6,Male,O-,Nashik,Private,Emergency,Arthritis,Amoxicillin,...,Private,NaN,H008,Yes,Never,30.0,145.000000,74.0,74.0,Yes
49976,PT002615,ADM149976,78,Female,NaN,Pune,Private,Elective,Hypertension,Albuterol,...,General,NaN,H042,Yes,Never,31.0,152.000000,85.0,101.0,No
49985,PT014727,ADM149985,93,Female,A-,Nagpur,Employer,Urgent,Arthritis,Metformin,...,General,NaN,H045,Yes,Former,30.9,128.000000,88.0,NaN,Yes

In [711]:
d = pd.cut(bins="Age_group")

TypeError: cut() missing 1 required positional argument: 'x'

In [712]:
df.columns

Index(['patient_id', 'admission_id', 'age', 'gender', 'blood_type', 'city',
       'insurance_provider', 'admission_type', 'medical_condition',
       'medication', 'test_results', 'length_of_stay_days', 'admission_date',
       'discharge_date', 'billing_amount_inr', 'room_type', 'doctor_specialty',
       'hospital_id', 'readmission_30_days', 'smoking_status', 'bmi',
       'systolic_bp', 'diastolic_bp', 'heart_rate_bpm', 'followup_completed'],
      dtype='object')

In [717]:
df['discharge_date'].dt.month

0         9.0
1         4.0
2         2.0
3         9.0
4         4.0
         ...
49995     3.0
49996     6.0
49997     6.0
49998     1.0
49999    10.0
Name: discharge_date, Length: 50000, dtype: float64