In [1]:
import pandas as pd

In [2]:
data = {
    'id':[1,2,3,4,5],
    'name':["roshan","tushar","swarup","krishna","pratik"],
    'marks':[45,43,46,34,24],
    'city':['pune','dhule','solapur','amlner','mumbai']
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   id     name  marks     city
0   1   roshan     45     pune
1   2   tushar     43    dhule
2   3   swarup     46  solapur
3   4  krishna     34   amlner
4   5   pratik     24   mumbai

In [10]:
df.name

0     roshan
1     tushar
2     swarup
3    krishna
4     pratik
Name: name, dtype: object

In [11]:
df.marks

0    45
1    43
2    46
3    34
4    24
Name: marks, dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   name    5 non-null      object
 2   marks   5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [13]:
df.describe()

             id      marks
count  5.000000   5.000000
mean   3.000000  38.400000
std    1.581139   9.343447
min    1.000000  24.000000
25%    2.000000  34.000000
50%    3.000000  43.000000
75%    4.000000  45.000000
max    5.000000  46.000000

In [14]:
df["marks"].var()

np.float64(87.3)

In [15]:
df["marks"].std()

np.float64(9.343446901438462)

In [16]:
df.name

0     roshan
1     tushar
2     swarup
3    krishna
4     pratik
Name: name, dtype: object

In [17]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [18]:
df.values

array([[1, 'roshan', 45, 'pune'],
       [2, 'tushar', 43, 'dhule'],
       [3, 'swarup', 46, 'solapur'],
       [4, 'krishna', 34, 'amlner'],
       [5, 'pratik', 24, 'mumbai']], dtype=object)

In [19]:
df["marks"].sum()

np.int64(192)

In [20]:
df['id'].count()

np.int64(5)

In [21]:
df

   id     name  marks     city
0   1   roshan     45     pune
1   2   tushar     43    dhule
2   3   swarup     46  solapur
3   4  krishna     34   amlner
4   5   pratik     24   mumbai

In [22]:
df["name"].value_counts()

name
roshan     1
tushar     1
swarup     1
krishna    1
pratik     1
Name: count, dtype: int64

In [24]:
df["marks"].mean()

np.float64(38.4)

In [25]:
df["marks"].median()

np.float64(43.0)

In [26]:
df["marks"].mode()

0    24
1    34
2    43
3    45
4    46
Name: marks, dtype: int64

In [27]:
df.sample()

   id    name  marks     city
2   3  swarup     46  solapur

In [28]:
df.head()

   id     name  marks     city
0   1   roshan     45     pune
1   2   tushar     43    dhule
2   3   swarup     46  solapur
3   4  krishna     34   amlner
4   5   pratik     24   mumbai

In [31]:
df["marks"].sort_values(axis=0,ascending=False).head(2).tail(1)

0    45
Name: marks, dtype: int64

In [32]:
df.loc[0]

id            1
name     roshan
marks        45
city       pune
Name: 0, dtype: object

In [33]:
df

   id     name  marks     city
0   1   roshan     45     pune
1   2   tushar     43    dhule
2   3   swarup     46  solapur
3   4  krishna     34   amlner
4   5   pratik     24   mumbai

In [39]:
df.loc[4]

id            5
name     pratik
marks        24
city     mumbai
Name: 4, dtype: object

In [40]:
df.loc[0:2:1,"name"]

0    roshan
1    tushar
2    swarup
Name: name, dtype: object

In [41]:
df.loc[0::1,"name":"marks":1]

      name  marks
0   roshan     45
1   tushar     43
2   swarup     46
3  krishna     34
4   pratik     24

In [42]:
df

   id     name  marks     city
0   1   roshan     45     pune
1   2   tushar     43    dhule
2   3   swarup     46  solapur
3   4  krishna     34   amlner
4   5   pratik     24   mumbai

In [43]:
df.loc[0::1,"name":"city":2]

      name     city
0   roshan     pune
1   tushar    dhule
2   swarup  solapur
3  krishna   amlner
4   pratik   mumbai

In [44]:
df.loc[0::1,"id":"marks":2]

   id  marks
0   1     45
1   2     43
2   3     46
3   4     34
4   5     24

In [45]:
data = pd.read_csv("matches.csv")

In [46]:
data

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [53]:
data.loc[0::1,"city":"winner":8].sort_values("city").head()

          city               winner
460  Abu Dhabi     Rajasthan Royals
471  Abu Dhabi      Kings XI Punjab
470  Abu Dhabi     Rajasthan Royals
464  Abu Dhabi  Chennai Super Kings
459  Abu Dhabi      Kings XI Punjab

In [54]:
df

   id     name  marks     city
0   1   roshan     45     pune
1   2   tushar     43    dhule
2   3   swarup     46  solapur
3   4  krishna     34   amlner
4   5   pratik     24   mumbai

In [55]:
df.iloc[0::1,2:3:1]

   marks
0     45
1     43
2     46
3     34
4     24

In [56]:
df

   id     name  marks     city
0   1   roshan     45     pune
1   2   tushar     43    dhule
2   3   swarup     46  solapur
3   4  krishna     34   amlner
4   5   pratik     24   mumbai

In [57]:
df.iloc[1:4:1,0:3:1]

   id     name  marks
1   2   tushar     43
2   3   swarup     46
3   4  krishna     34

In [58]:
df.iloc[0:1:1]

   id    name  marks  city
0   1  roshan     45  pune

In [60]:
df.iloc[3:5:1,1:3:1]

      name  marks
3  krishna     34
4   pratik     24

In [61]:
students_data = {
                    "rn":[1,2,3,4,5,6,7,8,9,10,1],
                    "name":["abc","def","ghi","jkl","mno","pqr","stu","vwx","xyz","qqq","abc"],
                    "marks":[10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0,10.0],
                    "addr":["pune","karvenagar","akurdi","pimpri","baner","bavdhan","kothrud","nagar","ravet","mumbai","pune"],
                    "attd":[True,False,True,False,True,False,True,False,True,False,False]
                }

df2=pd.DataFrame(students_data)

In [63]:
df2.values

array([[1, 'abc', 10.0, 'pune', True],
       [2, 'def', 20.0, 'karvenagar', False],
       [3, 'ghi', 30.0, 'akurdi', True],
       [4, 'jkl', 40.0, 'pimpri', False],
       [5, 'mno', 50.0, 'baner', True],
       [6, 'pqr', 60.0, 'bavdhan', False],
       [7, 'stu', 70.0, 'kothrud', True],
       [8, 'vwx', 80.0, 'nagar', False],
       [9, 'xyz', 90.0, 'ravet', True],
       [10, 'qqq', 100.0, 'mumbai', False],
       [1, 'abc', 10.0, 'pune', False]], dtype=object)

In [64]:
df2.index

RangeIndex(start=0, stop=11, step=1)

In [65]:
df2.name

0     abc
1     def
2     ghi
3     jkl
4     mno
5     pqr
6     stu
7     vwx
8     xyz
9     qqq
10    abc
Name: name, dtype: object

In [66]:
df2

    rn name  marks        addr   attd
0    1  abc   10.0        pune   True
1    2  def   20.0  karvenagar  False
2    3  ghi   30.0      akurdi   True
3    4  jkl   40.0      pimpri  False
4    5  mno   50.0       baner   True
5    6  pqr   60.0     bavdhan  False
6    7  stu   70.0     kothrud   True
7    8  vwx   80.0       nagar  False
8    9  xyz   90.0       ravet   True
9   10  qqq  100.0      mumbai  False
10   1  abc   10.0        pune  False

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   name    5 non-null      object
 2   marks   5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [68]:
df.describe()

             id      marks
count  5.000000   5.000000
mean   3.000000  38.400000
std    1.581139   9.343447
min    1.000000  24.000000
25%    2.000000  34.000000
50%    3.000000  43.000000
75%    4.000000  45.000000
max    5.000000  46.000000

In [70]:
df2.sample()

   rn name  marks    addr   attd
3   4  jkl   40.0  pimpri  False

In [71]:
df2.head()

   rn name  marks        addr   attd
0   1  abc   10.0        pune   True
1   2  def   20.0  karvenagar  False
2   3  ghi   30.0      akurdi   True
3   4  jkl   40.0      pimpri  False
4   5  mno   50.0       baner   True

In [73]:
df2["marks"].mean()

np.float64(50.90909090909091)

In [74]:
df2["marks"].sum()

np.float64(560.0)

In [75]:
df2["name"].count()

np.int64(11)

In [76]:
df2["marks"].hasnans

False

In [77]:
df2

    rn name  marks        addr   attd
0    1  abc   10.0        pune   True
1    2  def   20.0  karvenagar  False
2    3  ghi   30.0      akurdi   True
3    4  jkl   40.0      pimpri  False
4    5  mno   50.0       baner   True
5    6  pqr   60.0     bavdhan  False
6    7  stu   70.0     kothrud   True
7    8  vwx   80.0       nagar  False
8    9  xyz   90.0       ravet   True
9   10  qqq  100.0      mumbai  False
10   1  abc   10.0        pune  False

In [78]:
df2["attd"].value_counts()

attd
False    6
True     5
Name: count, dtype: int64

In [79]:
df2[["name","marks","attd"]]

   name  marks   attd
0   abc   10.0   True
1   def   20.0  False
2   ghi   30.0   True
3   jkl   40.0  False
4   mno   50.0   True
5   pqr   60.0  False
6   stu   70.0   True
7   vwx   80.0  False
8   xyz   90.0   True
9   qqq  100.0  False
10  abc   10.0  False

In [81]:
df2.loc[0:6:1,"name":"attd":1]

  name  marks        addr   attd
0  abc   10.0        pune   True
1  def   20.0  karvenagar  False
2  ghi   30.0      akurdi   True
3  jkl   40.0      pimpri  False
4  mno   50.0       baner   True
5  pqr   60.0     bavdhan  False
6  stu   70.0     kothrud   True

In [86]:
df2["name"].dtype

dtype('O')

In [87]:
df2["marks"].dtype

dtype('float64')

In [85]:
print(type(df2))

<class 'pandas.core.frame.DataFrame'>

In [88]:
df2

    rn name  marks        addr   attd
0    1  abc   10.0        pune   True
1    2  def   20.0  karvenagar  False
2    3  ghi   30.0      akurdi   True
3    4  jkl   40.0      pimpri  False
4    5  mno   50.0       baner   True
5    6  pqr   60.0     bavdhan  False
6    7  stu   70.0     kothrud   True
7    8  vwx   80.0       nagar  False
8    9  xyz   90.0       ravet   True
9   10  qqq  100.0      mumbai  False
10   1  abc   10.0        pune  False

In [89]:
df["marks"].mean()

np.float64(38.4)

In [90]:
df["marks"].max()

np.int64(46)

In [91]:
df["marks"].min()

np.int64(24)

In [92]:
df["marks"].sort_values(ascending=False).head(2).tail(1)

0    45
Name: marks, dtype: int64

In [94]:
# for i in df["marks"]:
#     if i>60:
#         print(i)

In [95]:
df2

    rn name  marks        addr   attd
0    1  abc   10.0        pune   True
1    2  def   20.0  karvenagar  False
2    3  ghi   30.0      akurdi   True
3    4  jkl   40.0      pimpri  False
4    5  mno   50.0       baner   True
5    6  pqr   60.0     bavdhan  False
6    7  stu   70.0     kothrud   True
7    8  vwx   80.0       nagar  False
8    9  xyz   90.0       ravet   True
9   10  qqq  100.0      mumbai  False
10   1  abc   10.0        pune  False

In [96]:
df2.shape

(11, 5)

In [97]:
students_data = {
                    "rn":[1,2,3,4,5,6,7,8,9,10,1],
                    "name":["abc","def","ghi","jkl","mno","pqr","stu","vwx","xyz","qqq","abc"],
                    "marks":[10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0,10.0],
                    "addr":["pune","karvenagar","akurdi","pimpri","baner","bavdhan","kothrud","nagar","ravet","mumbai","pune"],
                    "attd":[True,False,True,False,True,False,True,False,True,False,False]
                }

df=pd.DataFrame(students_data)

In [98]:
df.head()

   rn name  marks        addr   attd
0   1  abc   10.0        pune   True
1   2  def   20.0  karvenagar  False
2   3  ghi   30.0      akurdi   True
3   4  jkl   40.0      pimpri  False
4   5  mno   50.0       baner   True

In [99]:
df.tail()

    rn name  marks     addr   attd
6    7  stu   70.0  kothrud   True
7    8  vwx   80.0    nagar  False
8    9  xyz   90.0    ravet   True
9   10  qqq  100.0   mumbai  False
10   1  abc   10.0     pune  False

In [100]:
df.shape

(11, 5)

In [102]:
df.columns

Index(['rn', 'name', 'marks', 'addr', 'attd'], dtype='object')

In [103]:
df["marks"].dtype

dtype('float64')

In [104]:
df["name"].dtype

dtype('O')

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rn      11 non-null     int64
 1   name    11 non-null     object
 2   marks   11 non-null     float64
 3   addr    11 non-null     object
 4   attd    11 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(2)
memory usage: 495.0+ bytes

In [106]:
df.describe()

              rn       marks
count  11.000000   11.000000
mean    5.090909   50.909091
std     3.176619   31.766191
min     1.000000   10.000000
25%     2.500000   25.000000
50%     5.000000   50.000000
75%     7.500000   75.000000
max    10.000000  100.000000

In [107]:
df.size

55

In [108]:
df.index

RangeIndex(start=0, stop=11, step=1)

In [109]:
df["name"]

0     abc
1     def
2     ghi
3     jkl
4     mno
5     pqr
6     stu
7     vwx
8     xyz
9     qqq
10    abc
Name: name, dtype: object

In [111]:
df[["name","marks"]]

   name  marks
0   abc   10.0
1   def   20.0
2   ghi   30.0
3   jkl   40.0
4   mno   50.0
5   pqr   60.0
6   stu   70.0
7   vwx   80.0
8   xyz   90.0
9   qqq  100.0
10  abc   10.0

In [112]:
df.iloc[0:5:1]

   rn name  marks        addr   attd
0   1  abc   10.0        pune   True
1   2  def   20.0  karvenagar  False
2   3  ghi   30.0      akurdi   True
3   4  jkl   40.0      pimpri  False
4   5  mno   50.0       baner   True

In [113]:
df.iloc[0:3:1,0::1]

   rn name  marks        addr   attd
0   1  abc   10.0        pune   True
1   2  def   20.0  karvenagar  False
2   3  ghi   30.0      akurdi   True

In [114]:
df.loc[0:5:1,"name":"addr":2]

  name        addr
0  abc        pune
1  def  karvenagar
2  ghi      akurdi
3  jkl      pimpri
4  mno       baner
5  pqr     bavdhan

In [117]:
df.sort_values("marks")

    rn name  marks        addr   attd
0    1  abc   10.0        pune   True
10   1  abc   10.0        pune  False
1    2  def   20.0  karvenagar  False
2    3  ghi   30.0      akurdi   True
3    4  jkl   40.0      pimpri  False
4    5  mno   50.0       baner   True
5    6  pqr   60.0     bavdhan  False
6    7  stu   70.0     kothrud   True
7    8  vwx   80.0       nagar  False
8    9  xyz   90.0       ravet   True
9   10  qqq  100.0      mumbai  False

In [118]:
df["marks"].sort_values(ascending=False)

9     100.0
8      90.0
7      80.0
6      70.0
5      60.0
4      50.0
3      40.0
2      30.0
1      20.0
0      10.0
10     10.0
Name: marks, dtype: float64

In [119]:
df.sort_values("name")

    rn name  marks        addr   attd
0    1  abc   10.0        pune   True
10   1  abc   10.0        pune  False
1    2  def   20.0  karvenagar  False
2    3  ghi   30.0      akurdi   True
3    4  jkl   40.0      pimpri  False
4    5  mno   50.0       baner   True
5    6  pqr   60.0     bavdhan  False
9   10  qqq  100.0      mumbai  False
6    7  stu   70.0     kothrud   True
7    8  vwx   80.0       nagar  False
8    9  xyz   90.0       ravet   True

In [121]:
df["marks"].mean()

np.float64(50.90909090909091)

In [122]:
df["marks"].max()

np.float64(100.0)

In [123]:
df["marks"].min()

np.float64(10.0)

In [124]:
df["marks"].sum()

np.float64(560.0)

In [127]:
df.sort_values("marks",ascending=False).head(1)

   rn name  marks    addr   attd
9  10  qqq  100.0  mumbai  False

In [128]:
df

    rn name  marks        addr   attd
0    1  abc   10.0        pune   True
1    2  def   20.0  karvenagar  False
2    3  ghi   30.0      akurdi   True
3    4  jkl   40.0      pimpri  False
4    5  mno   50.0       baner   True
5    6  pqr   60.0     bavdhan  False
6    7  stu   70.0     kothrud   True
7    8  vwx   80.0       nagar  False
8    9  xyz   90.0       ravet   True
9   10  qqq  100.0      mumbai  False
10   1  abc   10.0        pune  False

In [129]:
df["marks"].sort_values(ascending=False)

9     100.0
8      90.0
7      80.0
6      70.0
5      60.0
4      50.0
3      40.0
2      30.0
1      20.0
0      10.0
10     10.0
Name: marks, dtype: float64

In [130]:
df

    rn name  marks        addr   attd
0    1  abc   10.0        pune   True
1    2  def   20.0  karvenagar  False
2    3  ghi   30.0      akurdi   True
3    4  jkl   40.0      pimpri  False
4    5  mno   50.0       baner   True
5    6  pqr   60.0     bavdhan  False
6    7  stu   70.0     kothrud   True
7    8  vwx   80.0       nagar  False
8    9  xyz   90.0       ravet   True
9   10  qqq  100.0      mumbai  False
10   1  abc   10.0        pune  False

In [131]:
df["attd"].value_counts()

attd
False    6
True     5
Name: count, dtype: int64

In [134]:
df.sort_values("marks",ascending=False).head(1).tail(1)

   rn name  marks    addr   attd
9  10  qqq  100.0  mumbai  False

In [135]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

In [136]:
arr

array([10, 20, 30, 40, 50, 60])

In [137]:
arr.shape

(6,)

In [142]:
import numpy as np
arr1 = np.zeros((3,3))

In [143]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [144]:
arr2 = np.ones((3,3))

In [145]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [146]:
arr3 = np.arange(2,20,2)

In [147]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [150]:
arr = np.random.randint(1,12,(3,4))

In [151]:
arr

array([[ 1,  4,  2,  9],
       [ 6, 10,  7,  6],
       [ 5, 11,  3,  7]], dtype=int32)

In [152]:
arr[0:1:1,0:3:1]

array([[1, 4, 2]], dtype=int32)

In [153]:
arr[2:3:1,1:4:1]

array([[11,  3,  7]], dtype=int32)

In [156]:
arr[-1:-2:-1,-3::1]

array([[11,  3,  7]], dtype=int32)

In [157]:
arr>30

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [160]:
arr[0][1]=35

In [161]:
arr

array([[ 1, 35,  2,  9],
       [ 6, 10,  7,  6],
       [ 5, 11,  3,  7]], dtype=int32)

In [166]:
arr>30
arr[1][1]=40

In [167]:
arr[arr>30]=100

In [168]:
arr

array([[  1, 100,   2,   9],
       [  6, 100,   7,   6],
       [  5,  11,   3,   7]], dtype=int32)

In [ ]:
$pip install django

In [ ]:
!pip install django

In [171]:
arr

array([[  1, 100,   2,   9],
       [  6, 100,   7,   6],
       [  5,  11,   3,   7]], dtype=int32)

In [172]:
np.mean(arr)

np.float64(21.416666666666668)

In [173]:
np.median(arr)

np.float64(6.5)

In [174]:
from scipy import stats

In [175]:
stats.mode(arr)

ModeResult(mode=array([  1, 100,   2,   6], dtype=int32), count=array([1, 2, 1, 1]))

In [177]:
np.std(arr)

np.float64(35.245468581869574)

In [178]:
np.var(arr)

np.float64(1242.2430555555554)

In [179]:
arr+5

array([[  6, 105,   7,  14],
       [ 11, 105,  12,  11],
       [ 10,  16,   8,  12]], dtype=int32)

In [180]:
arr*3

array([[  3, 300,   6,  27],
       [ 18, 300,  21,  18],
       [ 15,  33,   9,  21]], dtype=int32)

In [181]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [182]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([3,4,5,6,5])
arr+arr1

array([ 4,  6,  8, 10, 10])

In [184]:
arr2 = np.random.randint(1,50,(3,3))

In [185]:
arr2

array([[39, 35, 17],
       [17, 23, 37],
       [46, 18, 48]], dtype=int32)

In [187]:
arr2[0::1].sum()

np.int64(280)

In [190]:
arr2[0::1,0:1:1].sum()

np.int64(102)

In [191]:
arr4 = np.array([1,2,-1,-3,2,4,-2,9,-10])

In [193]:
arr4[arr4<0]=0

In [194]:
arr4

array([1, 2, 0, 0, 2, 4, 0, 9, 0])

In [195]:
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Neha", "Karan"],
    "Department": ["IT", "HR", "IT", "Sales", "HR", "Sales"],
    "Age": [22, 25, 24, 23, None, 26],
    "Salary": [50000, 40000, 60000, 35000, 55000, 45000],
    "City": ["Pune", "Mumbai", "Pune", "Nashik", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)

In [196]:
df

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune
3  Sneha      Sales  23.0   35000  Nashik
4   Neha         HR   NaN   55000  Mumbai
5  Karan      Sales  26.0   45000    Pune

In [198]:
df["Age"] = df["Age"].dropna()

In [199]:
df["Age"]

0    22.0
1    25.0
2    24.0
3    23.0
4     NaN
5    26.0
Name: Age, dtype: float64

In [200]:
df.head(3)

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune

In [202]:
df.shape

(6, 5)

In [203]:
df.columns

Index(['Name', 'Department', 'Age', 'Salary', 'City'], dtype='object')

In [206]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [207]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Department  6 non-null      object
 2   Age         5 non-null      float64
 3   Salary      6 non-null      int64
 4   City        6 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 372.0+ bytes

In [208]:
df.describe()

             Age        Salary
count   5.000000      6.000000
mean   24.000000  47500.000000
std     1.581139   9354.143467
min    22.000000  35000.000000
25%    23.000000  41250.000000
50%    24.000000  47500.000000
75%    25.000000  53750.000000
max    26.000000  60000.000000

In [210]:
Q1 = 23.00
Q3 = 24.00
Q2 = 25.00

In [211]:
IQR = Q3-Q1

In [212]:
IQR

1.0

In [213]:
L = Q1-1.5*(IQR)

In [214]:
L

21.5

In [217]:
H = Q3+1.5*(IQR)

In [218]:
H

25.5

In [219]:
df

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune
3  Sneha      Sales  23.0   35000  Nashik
4   Neha         HR   NaN   55000  Mumbai
5  Karan      Sales  26.0   45000    Pune

In [220]:
df.loc[0:4:1]

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune
3  Sneha      Sales  23.0   35000  Nashik
4   Neha         HR   NaN   55000  Mumbai

In [222]:
df[["Name","Salary"]]

    Name  Salary
0   Amit   50000
1  Priya   40000
2  Rahul   60000
3  Sneha   35000
4   Neha   55000
5  Karan   45000

In [224]:
df.iloc[0:3:1]

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune

In [227]:
df[df["Salary"]>45000]

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
2  Rahul         IT  24.0   60000    Pune
4   Neha         HR   NaN   55000  Mumbai

In [229]:
df.groupby("Department")["Salary"].sum()

Department
HR        95000
IT       110000
Sales     80000
Name: Salary, dtype: int64

In [230]:
df[df["Salary"]<40000]

    Name Department   Age  Salary    City
3  Sneha      Sales  23.0   35000  Nashik

In [236]:
mark = df["Department"]=="IT"
marks = df["Salary"]>45000
df[mark & marks]

    Name Department   Age  Salary  City
0   Amit         IT  22.0   50000  Pune
2  Rahul         IT  24.0   60000  Pune

In [238]:
df.isnull()

    Name  Department    Age  Salary   City
0  False       False  False   False  False
1  False       False  False   False  False
2  False       False  False   False  False
3  False       False  False   False  False
4  False       False   True   False  False
5  False       False  False   False  False

In [239]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [240]:
df

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune
3  Sneha      Sales  23.0   35000  Nashik
4   Neha         HR  24.0   55000  Mumbai
5  Karan      Sales  26.0   45000    Pune

In [242]:
df.sort_values("Salary")

    Name Department   Age  Salary    City
3  Sneha      Sales  23.0   35000  Nashik
1  Priya         HR  25.0   40000  Mumbai
5  Karan      Sales  26.0   45000    Pune
0   Amit         IT  22.0   50000    Pune
4   Neha         HR  24.0   55000  Mumbai
2  Rahul         IT  24.0   60000    Pune

In [243]:
df["Department"].value_counts()

Department
IT       2
HR       2
Sales    2
Name: count, dtype: int64

In [244]:
df.groupby("Department")["Salary"].mean()

Department
HR       47500.0
IT       55000.0
Sales    40000.0
Name: Salary, dtype: float64

In [245]:
df.groupby("City")["Name"].count()

City
Mumbai    2
Nashik    1
Pune      3
Name: Name, dtype: int64

In [248]:
df.groupby("Name")["Salary"].max().head(1)

Name
Amit    50000
Name: Salary, dtype: int64

In [249]:
df.rename(columns={"City":"Place"})

    Name Department   Age  Salary   Place
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune
3  Sneha      Sales  23.0   35000  Nashik
4   Neha         HR  24.0   55000  Mumbai
5  Karan      Sales  26.0   45000    Pune

In [250]:
df.rename(columns={"Salary":"Monthly_Salary"})

    Name Department   Age  Monthly_Salary    City
0   Amit         IT  22.0           50000    Pune
1  Priya         HR  25.0           40000  Mumbai
2  Rahul         IT  24.0           60000    Pune
3  Sneha      Sales  23.0           35000  Nashik
4   Neha         HR  24.0           55000  Mumbai
5  Karan      Sales  26.0           45000    Pune

In [251]:
df

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune
3  Sneha      Sales  23.0   35000  Nashik
4   Neha         HR  24.0   55000  Mumbai
5  Karan      Sales  26.0   45000    Pune

In [252]:
df.notna()

   Name  Department   Age  Salary  City
0  True        True  True    True  True
1  True        True  True    True  True
2  True        True  True    True  True
3  True        True  True    True  True
4  True        True  True    True  True
5  True        True  True    True  True

In [253]:
df

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune
3  Sneha      Sales  23.0   35000  Nashik
4   Neha         HR  24.0   55000  Mumbai
5  Karan      Sales  26.0   45000    Pune

In [254]:
df["Department"].duplicated()

0    False
1    False
2     True
3    False
4     True
5     True
Name: Department, dtype: bool

In [259]:
df

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune
3  Sneha      Sales  23.0   35000  Nashik
4   Neha         HR  24.0   55000  Mumbai
5  Karan      Sales  26.0   45000    Pune

In [260]:
import pandas as pd
import numpy as np

s = pd.Series([10, 20, np.nan, 40, 50, np.nan, 70, 80, np.nan, 100])

print(s)

0     10.0
1     20.0
2      NaN
3     40.0
4     50.0
5      NaN
6     70.0
7     80.0
8      NaN
9    100.0
dtype: float64

In [261]:
for i in s:
    print(i)

10.0
20.0
nan
40.0
50.0
nan
70.0
80.0
nan
100.0

In [262]:
df

    Name Department   Age  Salary    City
0   Amit         IT  22.0   50000    Pune
1  Priya         HR  25.0   40000  Mumbai
2  Rahul         IT  24.0   60000    Pune
3  Sneha      Sales  23.0   35000  Nashik
4   Neha         HR  24.0   55000  Mumbai
5  Karan      Sales  26.0   45000    Pune

In [263]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Department  6 non-null      object
 2   Age         6 non-null      float64
 3   Salary      6 non-null      int64
 4   City        6 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 372.0+ bytes

In [5]:

df[df["Salary"]>50000]

KeyError: 'Salary'

In [6]:
df

   id     name  marks     city
0   1   roshan     45     pune
1   2   tushar     43    dhule
2   3   swarup     46  solapur
3   4  krishna     34   amlner
4   5   pratik     24   mumbai

In [10]:
df["marks"].mean()

np.float64(38.4)

In [12]:
df["marks"].var()

np.float64(87.3)

In [15]:
import numpy as np
df4 = np.percentile(df["marks"],25)

In [16]:
df4

np.float64(34.0)

In [17]:
df.describe()

             id      marks
count  5.000000   5.000000
mean   3.000000  38.400000
std    1.581139   9.343447
min    1.000000  24.000000
25%    2.000000  34.000000
50%    3.000000  43.000000
75%    4.000000  45.000000
max    5.000000  46.000000

In [21]:
# strong number

In [26]:
def factorials(n):
    fact = 1
    for i in range(1,n+1,1):
        fact*=i
    return fact

num = 14
sum1 = 0
for i in str(num):
    sum1+=factorials(int(i))

if sum1==num:
    print("strong number",sum1)
else:
    print("no strong number")

no strong number

In [30]:
num = 111111

no = num 

rev = 0

while no>0:
    a = no%10
    rev = rev*10+a
    no = no//10

if rev == num:
    print("palindrome number")
else:
    print("not palindrome number")

palindrome number

In [36]:
num = 370

a = len(str(num))
cube = 0
no = num

for i in range(1,num+1,1):
    a1 = no%10
    cube = cube + a1**a
    no = no//10
    
if num==cube:
    print("amstrong number")

amstrong number

In [42]:
li = [2,7,8,4,2,1]

li2 = []
target = 9 
for i in range(0,len(li),1):
    for j in range(i+1,len(li)):
        if li[i]+li[j]==target:
            li2.append({li[i],li[j]})
            

print(type(li2))

<class 'list'>

In [47]:
st = "datasceiance"

st1 = ""

for i in st:
    count = st.count(i)

    if i not in st1:
        print(i," -:- ",count)
        st1+=i

d  -:-  1
a  -:-  3
t  -:-  1
s  -:-  1
c  -:-  2
e  -:-  2
i  -:-  1
n  -:-  1

In [52]:
st = "datascience"

for i in range(len(st)-1,-1,-1):
    print(st[i],end=" ")

e c n e i c s a t a d

In [53]:
def addition(a,b):
    return a+b

addition(20,30)

50

In [56]:
li = [1,2,3,4,5,6,7,8]

res = list(map(lambda x:x**2,li))

In [57]:
res

[1, 4, 9, 16, 25, 36, 49, 64]

In [58]:
res1 = list(filter(lambda x:x%2==0,li))

In [59]:
res1

[2, 4, 6, 8]

In [64]:
def NegativeError(Exception):
    pass

In [65]:
try:
    a = -1
    if a<0:
        raise NegativeError
except NegativeError:
    print("error")

TypeError: catching classes that do not inherit from BaseException is not allowed