In [1]:
import pandas as pd

In [2]:
salary = pd.Series(
    [
        25000, 35000, 42000, 30000, 55000,
        28000, 45000, 38000, 62000, 32000,
        41000, 29000, 75000, 36000, 48000,
    ],
    
    index=[
        "Amit", "Rahul", "Priya", "Sneha", "Vikas",
        "Neha", "Rohan", "Pooja", "Karan", "Anjali",
        "Suresh", "Meena", "Arjun", "Kavita", "Nikhil",
    ],
    
    name="Monthly Salary"
)

In [3]:
salary

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan     45000
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [4]:
salary.index

Index(['Amit', 'Rahul', 'Priya', 'Sneha', 'Vikas', 'Neha', 'Rohan', 'Pooja',
       'Karan', 'Anjali', 'Suresh', 'Meena', 'Arjun', 'Kavita', 'Nikhil'],
      dtype='object')

In [5]:
salary.values

array([25000, 35000, 42000, 30000, 55000, 28000, 45000, 38000, 62000,
       32000, 41000, 29000, 75000, 36000, 48000])

In [6]:
salary.name

'Monthly Salary'

In [7]:
salary.empty

False

In [8]:
salary.hasnans

False

In [9]:
salary.sort_values()

Amit      25000
Neha      28000
Meena     29000
Sneha     30000
Anjali    32000
Rahul     35000
Kavita    36000
Pooja     38000
Suresh    41000
Priya     42000
Rohan     45000
Nikhil    48000
Vikas     55000
Karan     62000
Arjun     75000
Name: Monthly Salary, dtype: int64

In [10]:
salary.head()

Amit     25000
Rahul    35000
Priya    42000
Sneha    30000
Vikas    55000
Name: Monthly Salary, dtype: int64

In [11]:
salary.head(10)

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan     45000
Pooja     38000
Karan     62000
Anjali    32000
Name: Monthly Salary, dtype: int64

In [16]:
salary.tail()

Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [17]:
salary.info()

<class 'pandas.core.series.Series'>
Index: 15 entries, Amit to Nikhil
Series name: Monthly Salary
Non-Null Count  Dtype
--------------  -----
15 non-null     int64
dtypes: int64(1)
memory usage: 796.0+ bytes

In [18]:
salary.sort_values(ascending=False)

Arjun     75000
Karan     62000
Vikas     55000
Nikhil    48000
Rohan     45000
Priya     42000
Suresh    41000
Pooja     38000
Kavita    36000
Rahul     35000
Anjali    32000
Sneha     30000
Meena     29000
Neha      28000
Amit      25000
Name: Monthly Salary, dtype: int64

In [19]:
salary.value_counts(ascending=False).head(1)

Monthly Salary
25000    1
Name: count, dtype: int64

In [22]:
salary.sort_values(ascending=False).head(2).tail(1)

Karan    62000
Name: Monthly Salary, dtype: int64

In [23]:
salary

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan     45000
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [24]:
salary.info()

<class 'pandas.core.series.Series'>
Index: 15 entries, Amit to Nikhil
Series name: Monthly Salary
Non-Null Count  Dtype
--------------  -----
15 non-null     int64
dtypes: int64(1)
memory usage: 796.0+ bytes

In [26]:
salary.describe()

count       15.00000
mean     41400.00000
std      13881.12799
min      25000.00000
25%      31000.00000
50%      38000.00000
75%      46500.00000
max      75000.00000
Name: Monthly Salary, dtype: float64

In [30]:
s = salary.mean()

In [28]:
salary.median()

np.float64(38000.0)

In [29]:
salary.mode()

0     25000
1     28000
2     29000
3     30000
4     32000
5     35000
6     36000
7     38000
8     41000
9     42000
10    45000
11    48000
12    55000
13    62000
14    75000
Name: Monthly Salary, dtype: int64

In [33]:
salary.count()

np.int64(15)

In [34]:
salary.sum()

np.int64(621000)

In [35]:
salary.max()

np.int64(75000)

In [36]:
salary.min()

np.int64(25000)

In [37]:
salary.sort_index()

Amit      25000
Anjali    32000
Arjun     75000
Karan     62000
Kavita    36000
Meena     29000
Neha      28000
Nikhil    48000
Pooja     38000
Priya     42000
Rahul     35000
Rohan     45000
Sneha     30000
Suresh    41000
Vikas     55000
Name: Monthly Salary, dtype: int64

In [38]:
salary.sort_index(ascending=False)

Vikas     55000
Suresh    41000
Sneha     30000
Rohan     45000
Rahul     35000
Priya     42000
Pooja     38000
Nikhil    48000
Neha      28000
Meena     29000
Kavita    36000
Karan     62000
Arjun     75000
Anjali    32000
Amit      25000
Name: Monthly Salary, dtype: int64

In [39]:
salary.sample(10)

Kavita    36000
Neha      28000
Suresh    41000
Priya     42000
Pooja     38000
Amit      25000
Meena     29000
Rohan     45000
Sneha     30000
Rahul     35000
Name: Monthly Salary, dtype: int64

In [40]:
salary.sample(3)

Rahul    35000
Meena    29000
Vikas    55000
Name: Monthly Salary, dtype: int64

In [41]:
data = pd.read_csv("matches.csv")

In [42]:
data.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    object
 3   date             636 non-null    object
 4   team1            636 non-null    object
 5   team2            636 non-null    object
 6   toss_winner      636 non-null    object
 7   toss_decision    636 non-null    object
 8   result           636 non-null    object
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    object
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    object
 14  venue            636 non-null    object
 15  umpire1          635 non-null    object
 16  umpire2          635 non-null    object
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), object(12)
memory usage: 89.6+ KB

In [44]:
data.describe()

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,636.000000,636.000000,636.000000,636.000000,636.000000,0.0
mean,318.500000,2012.490566,0.025157,13.682390,3.372642,NaN
std,183.741666,2.773026,0.156726,23.908877,3.420338,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,159.750000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,318.500000,2012.000000,0.000000,0.000000,4.000000,NaN
75%,477.250000,2015.000000,0.000000,20.000000,7.000000,NaN
max,636.000000,2017.000000,1.000000,146.000000,10.000000,NaN

In [45]:
data.sample()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
613,614,2016,Kolkata,2016-05-08,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,5,P Kumar,Eden Gardens,M Erasmus,RJ Tucker,NaN

In [46]:
salary

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan     45000
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [48]:
salary.mean

<bound method Series.mean of Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan     45000
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64>

In [51]:
salary.median()

np.float64(38000.0)

In [52]:
## sort_values()
## sort_index()
## sort_values(ascending=False)
## sort_index(ascending=Fasle)
## series.index
## series.values
## series.name
## series.empty
## series.hasnans
## series.dtype
## series.value_counts()
## series.sample(n)
## series.head()
## series.tail()
## series.info()
## series.describe()
## series.mean()
## series.median()
## series.mode()
## series.var()
## series.std()

In [53]:
salary.var()

np.float64(192685714.2857143)

In [54]:
salary.std()

np.float64(13881.127990394523)

In [55]:
salary.describe()

count       15.00000
mean     41400.00000
std      13881.12799
min      25000.00000
25%      31000.00000
50%      38000.00000
75%      46500.00000
max      75000.00000
Name: Monthly Salary, dtype: float64

In [58]:
salary[0:3:1][0:1:1]

Amit    25000
Name: Monthly Salary, dtype: int64

In [59]:
salary

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan     45000
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [60]:
salary.count()

np.int64(15)

In [61]:
salary.mean()

np.float64(41400.0)

In [62]:
salary.median()

np.float64(38000.0)

In [63]:
salary.mode()

0     25000
1     28000
2     29000
3     30000
4     32000
5     35000
6     36000
7     38000
8     41000
9     42000
10    45000
11    48000
12    55000
13    62000
14    75000
Name: Monthly Salary, dtype: int64

In [65]:
salary.sort_values()

Amit      25000
Neha      28000
Meena     29000
Sneha     30000
Anjali    32000
Rahul     35000
Kavita    36000
Pooja     38000
Suresh    41000
Priya     42000
Rohan     45000
Nikhil    48000
Vikas     55000
Karan     62000
Arjun     75000
Name: Monthly Salary, dtype: int64

In [67]:
salary.sort_values(ascending=False)

Arjun     75000
Karan     62000
Vikas     55000
Nikhil    48000
Rohan     45000
Priya     42000
Suresh    41000
Pooja     38000
Kavita    36000
Rahul     35000
Anjali    32000
Sneha     30000
Meena     29000
Neha      28000
Amit      25000
Name: Monthly Salary, dtype: int64

In [69]:
salary.values

array([25000, 35000, 42000, 30000, 55000, 28000, 45000, 38000, 62000,
       32000, 41000, 29000, 75000, 36000, 48000])

In [70]:
salary.index

Index(['Amit', 'Rahul', 'Priya', 'Sneha', 'Vikas', 'Neha', 'Rohan', 'Pooja',
       'Karan', 'Anjali', 'Suresh', 'Meena', 'Arjun', 'Kavita', 'Nikhil'],
      dtype='object')

In [71]:
salary.dtype

dtype('int64')

In [72]:
salary.empty

False

In [75]:
salary.hasnans

False

In [76]:
salary.var()

np.float64(192685714.2857143)

In [77]:
salary.std()

np.float64(13881.127990394523)

In [78]:
salary.sort_index(ascending=False)

Vikas     55000
Suresh    41000
Sneha     30000
Rohan     45000
Rahul     35000
Priya     42000
Pooja     38000
Nikhil    48000
Neha      28000
Meena     29000
Kavita    36000
Karan     62000
Arjun     75000
Anjali    32000
Amit      25000
Name: Monthly Salary, dtype: int64

In [80]:
salary.value_counts()

Monthly Salary
25000    1
35000    1
42000    1
30000    1
55000    1
28000    1
45000    1
38000    1
62000    1
32000    1
41000    1
29000    1
75000    1
36000    1
48000    1
Name: count, dtype: int64

In [82]:
salary.values

array([25000, 35000, 42000, 30000, 55000, 28000, 45000, 38000, 62000,
       32000, 41000, 29000, 75000, 36000, 48000])

In [83]:
salary.info()

<class 'pandas.core.series.Series'>
Index: 15 entries, Amit to Nikhil
Series name: Monthly Salary
Non-Null Count  Dtype
--------------  -----
15 non-null     int64
dtypes: int64(1)
memory usage: 796.0+ bytes

In [84]:
salary.describe()

count       15.00000
mean     41400.00000
std      13881.12799
min      25000.00000
25%      31000.00000
50%      38000.00000
75%      46500.00000
max      75000.00000
Name: Monthly Salary, dtype: float64

In [91]:
data1 = pd.read_csv(r"C:\Users\Admin\Downloads\admissions.csv").squeeze()

In [92]:
data1

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: admissions, Length: 215, dtype: int64

In [93]:
data.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [95]:
data1.head()

0     1
1    23
2    13
3    12
4     1
Name: admissions, dtype: int64

In [96]:
data.tail()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [97]:
data1.tail()

210     0
211    20
212    73
213    25
214     7
Name: admissions, dtype: int64

In [99]:
data1.values

array([  1,  23,  13,  12,   1,   9,  34,   0,  21,   3,  10,  38,   3,
        11,  50,   2,  22,  19,  16,  15,  20,  38,  19,  24,   7,   2,
        16,  17,  24,  38,  34,  42,  13,  58,   3,  14,  37,   9,  23,
        12,  71,  35,  30,  56,  67,  27,  27,  39,  15,  11,  31,  70,
         8,  35,   8,   6,  57,  22,  16,   4,  16,  18,  45,   9,  36,
         9,   3,  73,  42,  24,  51,  35,  58,  65,   1,  11,   1,  32,
        25,  57,  93,  99,  17,  14,  56,  49,   0,  31,  21,   4,   0,
        35,   0,   4,  10,  27,  67,  38,  73,  13,  41,  18,  51,  62,
        35,   1,  34,  48,  32,  82,  19,  44,   1,  12,  12,  75,  79,
        33,  80, 100,  14,  52, 108,  20,   7, 109,  75, 113,  54,   0,
        54,  62,  28,  64,   0,  10,  55,  20,   6,   5,  58,  31,  21,
        57,  92,  30,  18,  68,  32,   8,  39,  70,  48,  12,   4,   6,
        46,   3,  23,  84,  41,  67,   8, 100,   9,  13,  23,  25,  16,
        18,   9,   7,  29,   1,  72,  43,  43,  90,  48,  14,  33,  50,
         8,   6,  33,  33,   5,  72,   8,  12,  35,   5,  25,   5,   4,
        25,  51,  53,  39,  41,  12,   5,  48,   1,  12,   0,   0,   9,
        58,  30,   0,  20,  73,  25,   7])

In [101]:
data1.index

RangeIndex(start=0, stop=215, step=1)

In [103]:
data1.dtype

dtype('int64')

In [104]:
data1.value_counts()

admissions
0     9
1     8
12    8
9     7
8     6
     ..
46    1
29    1
84    1
90    1
53    1
Name: count, Length: 78, dtype: int64

In [105]:
data1.info()

<class 'pandas.core.series.Series'>
RangeIndex: 215 entries, 0 to 214
Series name: admissions
Non-Null Count  Dtype
--------------  -----
215 non-null    int64
dtypes: int64(1)
memory usage: 1.8 KB

In [107]:
data1.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: admissions, dtype: float64

In [108]:
data1.sample(12)

99     13
144    92
130    54
201     5
112     1
212    73
170     9
92      0
16     22
178    48
42     30
191     5
Name: admissions, dtype: int64

In [109]:
data1.shape

(215,)

In [110]:
data1.tail()

210     0
211    20
212    73
213    25
214     7
Name: admissions, dtype: int64

In [111]:
data1.head()

0     1
1    23
2    13
3    12
4     1
Name: admissions, dtype: int64

In [113]:
data1.value_counts().head()

admissions
0     9
1     8
12    8
9     7
8     6
Name: count, dtype: int64

In [115]:
data1.mean()

np.float64(30.855813953488372)

In [116]:
data1.median()

np.float64(24.0)

In [117]:
data1.mode()

0    0
Name: admissions, dtype: int64

In [119]:
data1.sort_values(ascending=False)

127    113
125    109
122    108
119    100
163    100
      ...
92       0
129      0
205      0
206      0
210      0
Name: admissions, Length: 215, dtype: int64

In [120]:
data1.sort_values()

7        0
86       0
92       0
90       0
205      0
      ...
163    100
119    100
122    108
125    109
127    113
Name: admissions, Length: 215, dtype: int64

In [122]:
data1.sort_index()

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: admissions, Length: 215, dtype: int64

In [123]:
data1.var()

np.float64(688.0024777222343)

In [125]:
data1.std()

np.float64(26.22980132830278)

In [126]:
salary

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan     45000
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [127]:
salary.head(7)

Amit     25000
Rahul    35000
Priya    42000
Sneha    30000
Vikas    55000
Neha     28000
Rohan    45000
Name: Monthly Salary, dtype: int64

In [128]:
salary.tail()

Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [129]:
salary.index

Index(['Amit', 'Rahul', 'Priya', 'Sneha', 'Vikas', 'Neha', 'Rohan', 'Pooja',
       'Karan', 'Anjali', 'Suresh', 'Meena', 'Arjun', 'Kavita', 'Nikhil'],
      dtype='object')

In [130]:
salary.values

array([25000, 35000, 42000, 30000, 55000, 28000, 45000, 38000, 62000,
       32000, 41000, 29000, 75000, 36000, 48000])

In [135]:
# salary["Priya"]
salary

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan     45000
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [137]:
salary[["Amit","Sneha","Neha"]]

Amit     25000
Sneha    30000
Neha     28000
Name: Monthly Salary, dtype: int64

In [138]:
salary[5]

C:\Users\Admin\AppData\Local\Temp\ipykernel_12212\315590631.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  salary[5]

np.int64(28000)

In [139]:
salary[3]

C:\Users\Admin\AppData\Local\Temp\ipykernel_12212\1752580820.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  salary[3]

np.int64(30000)

In [140]:
salary

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan     45000
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [141]:
salary["Rohan"]=4

In [142]:
salary

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan         4
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [143]:
salary

Amit      25000
Rahul     35000
Priya     42000
Sneha     30000
Vikas     55000
Neha      28000
Rohan         4
Pooja     38000
Karan     62000
Anjali    32000
Suresh    41000
Meena     29000
Arjun     75000
Kavita    36000
Nikhil    48000
Name: Monthly Salary, dtype: int64

In [144]:
salary[::-1]

Nikhil    48000
Kavita    36000
Arjun     75000
Meena     29000
Suresh    41000
Anjali    32000
Karan     62000
Pooja     38000
Rohan         4
Neha      28000
Vikas     55000
Sneha     30000
Priya     42000
Rahul     35000
Amit      25000
Name: Monthly Salary, dtype: int64

In [145]:
salary.sum()

np.int64(576004)

In [146]:
salary.mean()

np.float64(38400.26666666667)

In [147]:
salary.min()

np.int64(4)

In [148]:
salary.max()

np.int64(75000)

In [149]:
salary.median()

np.float64(36000.0)

In [150]:
salary.std()

np.float64(17450.527652549103)

In [156]:
for i in salary:
    if i>50000:
        print(i)

55000
62000
75000

In [157]:
for i in salary:
    if i>30000 and i<50000:
        print(i)

35000
42000
38000
32000
41000
36000
48000

In [162]:
a = salary.mean()
a

np.float64(38400.26666666667)

In [169]:
for i in salary.values:
    if i>a:
        print(i)

42000
55000
62000
41000
75000
48000

In [177]:
s = salary+(salary*10/100)

In [178]:
s

Amit      27500.0
Rahul     38500.0
Priya     46200.0
Sneha     33000.0
Vikas     60500.0
Neha      30800.0
Rohan         4.4
Pooja     41800.0
Karan     68200.0
Anjali    35200.0
Suresh    45100.0
Meena     31900.0
Arjun     82500.0
Kavita    39600.0
Nikhil    52800.0
Name: Monthly Salary, dtype: float64

In [182]:
li = []
for i in salary:
    if i>40000:
        print(i)

42000
55000
62000
41000
75000
48000

In [183]:
salary.values>40000

array([False, False,  True, False,  True, False, False, False,  True,
       False,  True, False,  True, False,  True])

In [185]:
pd.__version__

'2.3.3'

In [186]:
import numpy as np

In [187]:
np.__version__

'2.2.6'

In [188]:
marks = pd.Series(
    [78, 92, 65, 88, 45, 96, 72, 59, 84, 91],
    index=[
        "Amit", "Priya", "Rahul", "Sneha", "Karan",
        "Neha", "Rohan", "Pooja", "Arjun", "Meera"
    ],
    name="Marks"
)

In [189]:
marks

Amit     78
Priya    92
Rahul    65
Sneha    88
Karan    45
Neha     96
Rohan    72
Pooja    59
Arjun    84
Meera    91
Name: Marks, dtype: int64

In [190]:
marks.min()

np.int64(45)

In [191]:
marks.max()

np.int64(96)

In [195]:
marks>75 
marks.count()

np.int64(10)

In [196]:
marks.info()

<class 'pandas.core.series.Series'>
Index: 10 entries, Amit to Meera
Series name: Marks
Non-Null Count  Dtype
--------------  -----
10 non-null     int64
dtypes: int64(1)
memory usage: 460.0+ bytes

In [197]:
marks.describe()

count    10.000000
mean     77.000000
std      16.566365
min      45.000000
25%      66.750000
50%      81.000000
75%      90.250000
max      96.000000
Name: Marks, dtype: float64

In [198]:
marks.dtype

dtype('int64')

In [199]:
marks.hasnans

False

In [200]:
marks

Amit     78
Priya    92
Rahul    65
Sneha    88
Karan    45
Neha     96
Rohan    72
Pooja    59
Arjun    84
Meera    91
Name: Marks, dtype: int64

In [201]:
marks.sort_values()

Karan    45
Pooja    59
Rahul    65
Rohan    72
Amit     78
Arjun    84
Sneha    88
Meera    91
Priya    92
Neha     96
Name: Marks, dtype: int64

In [202]:
marks.sort_values(ascending=False)

Neha     96
Priya    92
Meera    91
Sneha    88
Arjun    84
Amit     78
Rohan    72
Rahul    65
Pooja    59
Karan    45
Name: Marks, dtype: int64

In [203]:
marks.values+5

array([ 83,  97,  70,  93,  50, 101,  77,  64,  89,  96])

In [208]:
for i in range(0,len(marks),1):
    if marks[i]<60:
        marks[i]=60

C:\Users\Admin\AppData\Local\Temp\ipykernel_12212\4138048527.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if marks[i]<60:
C:\Users\Admin\AppData\Local\Temp\ipykernel_12212\4138048527.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks[i]=60

In [209]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

In [210]:
arr

array([10, 20, 30, 40, 50])

In [211]:
arr.shape

(5,)

In [212]:
arr.ndim

1

In [213]:
arr*2

array([ 20,  40,  60,  80, 100])

In [214]:
arr.sum()

np.int64(150)

In [215]:
arr.mean()

np.float64(30.0)

In [217]:
np.median(arr)

np.float64(30.0)

In [218]:
arr.min()

np.int64(10)

In [219]:
arr.max()

np.int64(50)

In [220]:
import numpy as np

arr = np.array([12, 24, 36, 48, 60, 72, 84, 96, 108])

In [221]:
arr

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108])

In [222]:
arr[0]

np.int64(12)

In [223]:
arr[-1]

np.int64(108)

In [224]:
arr[2:6:1]

array([36, 48, 60, 72])

In [225]:
arr[2]

np.int64(36)

In [226]:
arr[3]=100

In [227]:
arr

array([ 12,  24,  36, 100,  60,  72,  84,  96, 108])

In [234]:
arr1 = np.random.randint(arr[0],arr[-1],(3,3))

In [230]:
np.random.randint(1,23,1)

array([5], dtype=int32)

In [235]:
arr1

array([[88, 30, 18],
       [63, 13, 75],
       [41, 70, 52]], dtype=int32)

In [237]:
arr1[0]

array([88, 30, 18], dtype=int32)

In [239]:
np.save(r"D:\demo_python",arr1)

In [240]:
np

In [241]:
arr1.shape

(3, 3)

In [245]:
arr1[-1][-1]

np.int32(52)

In [246]:
import pandas as pd
import numpy as np

s = pd.Series(
    [10, 20, 30, np.nan, 50, 20, 70, 10],
    index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    name='Marks'
)

In [247]:
s

a    10.0
b    20.0
c    30.0
d     NaN
e    50.0
f    20.0
g    70.0
h    10.0
Name: Marks, dtype: float64

In [248]:
s.size

8

In [249]:
s.ndim

1

In [250]:
s.shape

(8,)

In [251]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object')

In [252]:
s.values

array([10., 20., 30., nan, 50., 20., 70., 10.])

In [253]:
s.dtype

dtype('float64')

In [254]:
s.name

'Marks'

In [255]:
s.empty

False

In [256]:
s.nbytes

64

In [257]:
a.array

AttributeError: 'numpy.float64' object has no attribute 'array'

In [258]:
s.axis

AttributeError: 'Series' object has no attribute 'axis'

In [259]:
import pandas as pd
import numpy as np

s = pd.Series(
    [15, 25, 35, np.nan, 45, 25, 55, 15],
    index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    name='Marks'
)

In [260]:
s

a    15.0
b    25.0
c    35.0
d     NaN
e    45.0
f    25.0
g    55.0
h    15.0
Name: Marks, dtype: float64

In [261]:
s.info()

<class 'pandas.core.series.Series'>
Index: 8 entries, a to h
Series name: Marks
Non-Null Count  Dtype
--------------  -----
7 non-null      float64
dtypes: float64(1)
memory usage: 428.0+ bytes

In [262]:
s.describe()

count     7.000000
mean     30.714286
std      15.118579
min      15.000000
25%      20.000000
50%      25.000000
75%      40.000000
max      55.000000
Name: Marks, dtype: float64

In [263]:
s.shape

(8,)

In [264]:
s.ndim

1

In [265]:
s.name

'Marks'

In [266]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object')

In [267]:
s.values

array([15., 25., 35., nan, 45., 25., 55., 15.])

In [268]:
s.head(4)

a    15.0
b    25.0
c    35.0
d     NaN
Name: Marks, dtype: float64

In [269]:
s.tail(4)

e    45.0
f    25.0
g    55.0
h    15.0
Name: Marks, dtype: float64

In [270]:
s.mean()

np.float64(30.714285714285715)

In [271]:
s.median()

np.float64(25.0)

In [272]:
s.mode()

0    15.0
1    25.0
Name: Marks, dtype: float64

In [274]:
s.info()

<class 'pandas.core.series.Series'>
Index: 8 entries, a to h
Series name: Marks
Non-Null Count  Dtype
--------------  -----
7 non-null      float64
dtypes: float64(1)
memory usage: 428.0+ bytes

In [275]:
for i in s:
    if i>25:
        print(i)

35.0
45.0
55.0

In [276]:
s

a    15.0
b    25.0
c    35.0
d     NaN
e    45.0
f    25.0
g    55.0
h    15.0
Name: Marks, dtype: float64

In [278]:
s["d"]=20

In [279]:
s

a    15.0
b    25.0
c    35.0
d    20.0
e    45.0
f    25.0
g    55.0
h    15.0
Name: Marks, dtype: float64

In [282]:
s.hasnans

False

In [284]:
s[4:5:1]

e    45.0
Name: Marks, dtype: float64

In [285]:
s.iloc[1:3:1]

b    25.0
c    35.0
Name: Marks, dtype: float64

In [287]:
s.describe()

count     8.000000
mean     29.375000
std      14.500616
min      15.000000
25%      18.750000
50%      25.000000
75%      37.500000
max      55.000000
Name: Marks, dtype: float64

In [288]:
s.sum()

np.float64(235.0)

In [289]:
s.mean()

np.float64(29.375)

In [290]:
s.median()

np.float64(25.0)

In [291]:
s.mode()

0    15.0
1    25.0
Name: Marks, dtype: float64

In [292]:
s.cumsum()

a     15.0
b     40.0
c     75.0
d     95.0
e    140.0
f    165.0
g    220.0
h    235.0
Name: Marks, dtype: float64

In [293]:
s

a    15.0
b    25.0
c    35.0
d    20.0
e    45.0
f    25.0
g    55.0
h    15.0
Name: Marks, dtype: float64

In [295]:
s.idmax()

AttributeError: 'Series' object has no attribute 'idmax'

In [296]:
s

a    15.0
b    25.0
c    35.0
d    20.0
e    45.0
f    25.0
g    55.0
h    15.0
Name: Marks, dtype: float64

In [319]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Vikas', 'Neha'],
    'Age': [21, 22, 20, 23, np.nan, 21],
    'Department': ['IT', 'HR', 'IT', 'Sales', 'HR', 'IT'],
    'Salary': [25000, 30000, 22000, 35000, 28000, np.nan],
    'Experience': [1, 2, 1, 3, 2, 1]
}

df = pd.DataFrame(data)

In [298]:
data

{'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Vikas', 'Neha'],
 'Age': [21, 22, 20, 23, nan, 21],
 'Department': ['IT', 'HR', 'IT', 'Sales', 'HR', 'IT'],
 'Salary': [25000, 30000, 22000, 35000, 28000, nan],
 'Experience': [1, 2, 1, 3, 2, 1]}

In [299]:
df

    Name   Age Department   Salary  Experience
0   Amit  21.0         IT  25000.0           1
1  Priya  22.0         HR  30000.0           2
2  Rahul  20.0         IT  22000.0           1
3  Sneha  23.0      Sales  35000.0           3
4  Vikas   NaN         HR  28000.0           2
5   Neha  21.0         IT      NaN           1

In [300]:
df.head(3)

    Name   Age Department   Salary  Experience
0   Amit  21.0         IT  25000.0           1
1  Priya  22.0         HR  30000.0           2
2  Rahul  20.0         IT  22000.0           1

In [301]:
df.tail()

    Name   Age Department   Salary  Experience
1  Priya  22.0         HR  30000.0           2
2  Rahul  20.0         IT  22000.0           1
3  Sneha  23.0      Sales  35000.0           3
4  Vikas   NaN         HR  28000.0           2
5   Neha  21.0         IT      NaN           1

In [302]:
df.shape

(6, 5)

In [304]:
df.columns

Index(['Name', 'Age', 'Department', 'Salary', 'Experience'], dtype='object')

In [305]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
 4   Experience  6 non-null      int64
dtypes: float64(2), int64(1), object(2)
memory usage: 372.0+ bytes

In [309]:
df["Salary"].dtype

dtype('float64')

In [310]:
df.describe()

             Age        Salary  Experience
count   5.000000      5.000000    6.000000
mean   21.400000  28000.000000    1.666667
std     1.140175   4949.747468    0.816497
min    20.000000  22000.000000    1.000000
25%    21.000000  25000.000000    1.000000
50%    21.000000  28000.000000    1.500000
75%    22.000000  30000.000000    2.000000
max    23.000000  35000.000000    3.000000

In [311]:
df.count()

Name          6
Age           5
Department    6
Salary        5
Experience    6
dtype: int64

In [312]:
df.isnull().sum()

Name          0
Age           1
Department    0
Salary        1
Experience    0
dtype: int64

In [313]:
a = df["Age"].mean()

In [314]:
a

np.float64(21.4)

In [318]:
df

    Name   Age Department   Salary  Experience  21.0  22.0  20.0  23.0  NaN
0   Amit  21.0         IT  25000.0           1    10    10    10    10   10
1  Priya  22.0         HR  30000.0           2    10    10    10    10   10
2  Rahul  20.0         IT  22000.0           1    10    10    10    10   10
3  Sneha  23.0      Sales  35000.0           3    10    10    10    10   10
4  Vikas   NaN         HR  28000.0           2    10    10    10    10   10
5   Neha  21.0         IT      NaN           1    10    10    10    10   10

In [320]:
a

np.float64(21.4)

In [321]:
df

    Name   Age Department   Salary  Experience
0   Amit  21.0         IT  25000.0           1
1  Priya  22.0         HR  30000.0           2
2  Rahul  20.0         IT  22000.0           1
3  Sneha  23.0      Sales  35000.0           3
4  Vikas   NaN         HR  28000.0           2
5   Neha  21.0         IT      NaN           1

In [328]:
for i in df["Age"]:
    if df[i].empty:
        df[i]=a
    else:
        print(i)

KeyError: 21.0

In [323]:
df

    Name   Age Department   Salary  Experience
0   Amit  21.0         IT  25000.0           1
1  Priya  22.0         HR  30000.0           2
2  Rahul  20.0         IT  22000.0           1
3  Sneha  23.0      Sales  35000.0           3
4  Vikas   NaN         HR  28000.0           2
5   Neha  21.0         IT      NaN           1

In [329]:
df

    Name   Age Department   Salary  Experience
0   Amit  21.0         IT  25000.0           1
1  Priya  22.0         HR  30000.0           2
2  Rahul  20.0         IT  22000.0           1
3  Sneha  23.0      Sales  35000.0           3
4  Vikas   NaN         HR  28000.0           2
5   Neha  21.0         IT      NaN           1

In [331]:
mark = df["Salary"]>25000
df[mark]

    Name   Age Department   Salary  Experience
1  Priya  22.0         HR  30000.0           2
3  Sneha  23.0      Sales  35000.0           3
4  Vikas   NaN         HR  28000.0           2

In [332]:
df[["Name","Salary"]]

    Name   Salary
0   Amit  25000.0
1  Priya  30000.0
2  Rahul  22000.0
3  Sneha  35000.0
4  Vikas  28000.0
5   Neha      NaN

In [336]:
mark = df["Department"]=="IT"

df[mark]

    Name   Age Department   Salary  Experience
0   Amit  21.0         IT  25000.0           1
2  Rahul  20.0         IT  22000.0           1
5   Neha  21.0         IT      NaN           1

In [341]:
df["Salary"].sort_values(ascending=False).head().tail(1)

2    22000.0
Name: Salary, dtype: float64

In [347]:
df.groupby("Department").mean(numeric_only=True)

                  Age   Salary  Experience
Department
HR          22.000000  29000.0         2.0
IT          20.666667  23500.0         1.0
Sales       23.000000  35000.0         3.0

In [351]:
arr1.cumsum()

array([ 88, 118, 136, 199, 212, 287, 328, 398, 450])