In [2]:
import pandas as pd

In [2]:
data = pd.read_csv("matches.csv")

In [3]:
data.index

RangeIndex(start=0, stop=636, step=1)

In [4]:
data.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [5]:
data.values

array([[1, 2017, 'Hyderabad', ..., 'AY Dandekar', 'NJ Llong', nan],
       [2, 2017, 'Pune', ..., 'A Nand Kishore', 'S Ravi', nan],
       [3, 2017, 'Rajkot', ..., 'Nitin Menon', 'CK Nandan', nan],
       ...,
       [634, 2016, 'Delhi', ..., 'M Erasmus', 'C Shamshuddin', nan],
       [635, 2016, 'Delhi', ..., 'M Erasmus', 'CK Nandan', nan],
       [636, 2016, 'Bangalore', ..., 'HDPK Dharmasena', 'BNJ Oxenford',
        nan]], shape=(636, 18), dtype=object)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    object
 3   date             636 non-null    object
 4   team1            636 non-null    object
 5   team2            636 non-null    object
 6   toss_winner      636 non-null    object
 7   toss_decision    636 non-null    object
 8   result           636 non-null    object
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    object
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    object
 14  venue            636 non-null    object
 15  umpire1          635 non-null    object
 16  umpire2          635 non-null    object
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), object(12)
memory usage: 89.6+ KB

In [7]:
data.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [12]:
data.drop(columns={"umpire2","umpire3"},inplace=True)

In [19]:
data.drop(columns="umpire1",inplace=True)

In [20]:
data

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal"
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium

In [21]:
df = data.iloc[0:100:1,0:12:1]

In [23]:
df.shape

(100, 12)

In [27]:
df["win_by_runs"].hasnans

False

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             100 non-null    int64
 1   season         100 non-null    int64
 2   city           100 non-null    object
 3   date           100 non-null    object
 4   team1          100 non-null    object
 5   team2          100 non-null    object
 6   toss_winner    100 non-null    object
 7   toss_decision  100 non-null    object
 8   result         100 non-null    object
 9   dl_applied     100 non-null    int64
 10  winner         100 non-null    object
 11  win_by_runs    100 non-null    int64
dtypes: int64(4), object(8)
memory usage: 9.5+ KB

In [33]:
df["season"].astype("float")

0     2017.0
1     2017.0
2     2017.0
3     2017.0
4     2017.0
       ...
95    2008.0
96    2008.0
97    2008.0
98    2008.0
99    2008.0
Name: season, Length: 100, dtype: float64

In [36]:
df.select_dtypes("object").shape

(100, 8)

In [37]:
data1 = pd.read_json(r"C:\Users\Admin\Downloads\iris.json",lines=True)

In [38]:
data1

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [45]:
dat2 = pd.read_excel(r"C:\Users\Admin\Downloads\Cola.xlsx")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [52]:
data = pd.read_csv("netflex1.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'netflex1.csv'

In [5]:
df2 = pd.read_csv(r"C:\Users\Admin\Downloads\netflex1.csv")

In [6]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,NaN,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,NaN,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [7]:
df2.head(2)

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True

In [9]:
df2.tail()

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,NaN,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,NaN,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [10]:
df2.sample()

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
27,s28,Null Movie,Movie,2020,NaN,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False

In [13]:
df2.select_dtypes(int).max()

release_year      2022
votes           650000
actors_count        20
dtype: int64

In [14]:
df2.select_dtypes(int).min()

release_year     2010
votes           15000
actors_count        5
dtype: int64

In [15]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,NaN,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,NaN,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [18]:
df2.agg(sum_vote = ["vates","sum"],sum_of_budgets=["budget_million","sum"])

TypeError: Must provide 'func' or tuples of '(column, aggfunc).

In [20]:
df2["votes"].sum()

np.int64(6375000)

In [21]:
df2["budget_million"].sum()

np.float64(1124.0)

In [22]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,NaN,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,NaN,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [23]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   show_id           30 non-null     object
 1   title             30 non-null     object
 2   type              30 non-null     object
 3   release_year      30 non-null     int64
 4   added_to_netflix  29 non-null     object
 5   country           29 non-null     object
 6   duration          30 non-null     object
 7   genre             30 non-null     object
 8   rating            30 non-null     object
 9   imdb_rating       29 non-null     float64
 10  votes             30 non-null     int64
 11  language          29 non-null     object
 12  category          30 non-null     object
 13  actors_count      30 non-null     int64
 14  budget_million    29 non-null     float64
 15  has_won_award     30 non-null     object
dtypes: float64(2), int64(3), object(11)
memory usage: 3.9+ KB

In [24]:
df2["title"].head(20)

0        Stranger Things
1            Money Heist
2           The Irishman
3             Extraction
4           Sacred Games
5            Kabir Singh
6                   Dark
7               Bird Box
8               Darlings
9                 Guilty
10           Delhi Crime
11             The Crown
12          Enola Holmes
13              Mirzapur
14                 Tenet
15                  Ludo
16            Squid Game
17    All of Us Are Dead
18       The White Tiger
19               Lucifer
Name: title, dtype: object

In [30]:
df2["imdb_rating"].mode()

0    7.0
Name: imdb_rating, dtype: float64

In [31]:
df2.describe()

       release_year  imdb_rating          votes  actors_count  budget_million
count     30.000000    29.000000      30.000000     30.000000       29.000000
mean    2018.866667     7.510345  212500.000000      9.633333       38.758621
std        2.473770     0.863690  191855.504176      3.566930       43.309233
min     2010.000000     5.600000   15000.000000      5.000000        6.000000
25%     2017.250000     7.000000   51000.000000      7.000000       14.000000
50%     2019.500000     7.400000  132500.000000      9.000000       22.000000
75%     2020.000000     8.200000  357500.000000     11.750000       45.000000
max     2022.000000     8.800000  650000.000000     20.000000      200.000000

In [32]:
df2.empty

False

In [34]:
df2["imdb_rating"].empty

False

In [35]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,NaN,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,NaN,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [36]:
df2.isnull()

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False
28,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False
29,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False

In [41]:
df2["country"] = df2["country"].fillna("India")

In [42]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,NaN,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [47]:
df2.loc[df2["show_id"]==s28,"added_to_netflix"]="12-05-2006"

NameError: name 's28' is not defined

In [48]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   show_id           30 non-null     object
 1   title             30 non-null     object
 2   type              30 non-null     object
 3   release_year      30 non-null     int64
 4   added_to_netflix  30 non-null     object
 5   country           30 non-null     object
 6   duration          30 non-null     object
 7   genre             30 non-null     object
 8   rating            30 non-null     object
 9   imdb_rating       29 non-null     float64
 10  votes             30 non-null     int64
 11  language          29 non-null     object
 12  category          30 non-null     object
 13  actors_count      30 non-null     int64
 14  budget_million    29 non-null     float64
 15  has_won_award     30 non-null     object
dtypes: float64(2), int64(3), object(11)
memory usage: 3.9+ KB

In [49]:
df2.sort_values("imdb_rating",ascending=False)

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [50]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   show_id           30 non-null     object
 1   title             30 non-null     object
 2   type              30 non-null     object
 3   release_year      30 non-null     int64
 4   added_to_netflix  30 non-null     object
 5   country           30 non-null     object
 6   duration          30 non-null     object
 7   genre             30 non-null     object
 8   rating            30 non-null     object
 9   imdb_rating       29 non-null     float64
 10  votes             30 non-null     int64
 11  language          29 non-null     object
 12  category          30 non-null     object
 13  actors_count      30 non-null     int64
 14  budget_million    29 non-null     float64
 15  has_won_award     30 non-null     object
dtypes: float64(2), int64(3), object(11)
memory usage: 3.9+ KB

In [62]:
df2.sort_values(by=["genre","country"])

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate

In [63]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   show_id           30 non-null     object
 1   title             30 non-null     object
 2   type              30 non-null     object
 3   release_year      30 non-null     int64
 4   added_to_netflix  30 non-null     object
 5   country           30 non-null     object
 6   duration          30 non-null     object
 7   genre             30 non-null     object
 8   rating            30 non-null     object
 9   imdb_rating       29 non-null     float64
 10  votes             30 non-null     int64
 11  language          29 non-null     object
 12  category          30 non-null     object
 13  actors_count      30 non-null     int64
 14  budget_million    29 non-null     float64
 15  has_won_award     30 non-null     object
dtypes: float64(2), int64(3), object(11)
memory usage: 3.9+ KB

In [65]:
df2.sort_values("budget_million",ascending=False)

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False

In [66]:
df2.iloc[0:20:1,0:10:1]

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1

In [71]:
df2[["title","votes"]].sort_values("votes",ascending=False).head(3)

              title   votes
0   Stranger Things  650000
25      Money Heist  550000
1       Money Heist  550000

In [74]:
df2[df2["country"]=="India"]

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False

In [75]:
df2.iloc[10:21:1]

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True

In [77]:
df2.iloc[0::1,0:3:1].head()

  show_id            title     type
0      s1  Stranger Things  TV Show
1      s2      Money Heist  TV Show
2      s3     The Irishman    Movie
3      s4       Extraction    Movie
4      s5     Sacred Games  TV Show

In [79]:
df2["country"].value_counts().head(1)

country
United States    9
Name: count, dtype: int64

In [83]:
df2[df2["genre"]=="Drama"].index

Index([5, 8, 9, 10, 11, 15, 18, 23, 27, 28, 29], dtype='int64')

In [86]:
df2.select_dtypes("int")

    release_year   votes  actors_count
0           2016  650000            14
1           2017  550000            12
2           2019  320000            20
3           2020  210000            10
4           2018  190000            11
5           2019   92000             7
6           2017  410000            10
7           2018  280000             9
8           2022   45000             6
9           2020   38000             5
10          2019   87000             8
11          2016  185000            15
12          2020  140000             8
13          2018   95000             7
14          2020  510000            15
15          2020   43000             7
16          2021  480000            12
17          2022  120000             9
18          2021   60000             6
19          2016  410000            15
20          2022  370000            10
21          2021   54000             6
22          2020   15000             5
23          2017  125000            11
24          2021   28000             6
25          2017  550000            12
26          2020  210000            10
27          2020   30000             8
28          2019   28000             7
29          2010   50000             8

In [87]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [89]:
df2.loc[df2["title"]=="Money Heist","rating"]="Tv-28"

In [90]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [92]:
df2.groupby("country")["votes"].sum().sort_values(ascending=False).head(1)

country
United States    2530000
Name: votes, dtype: int64

In [93]:
df2[(df2["country"]=="India") & (df2["imdb_rating"]>=4.5)]

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False

In [96]:
df2.groupby("release_year")["type"].count()

release_year
2010    1
2016    3
2017    4
2018    3
2019    4
2020    8
2021    4
2022    3
Name: type, dtype: int64

In [97]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [98]:
df2.drop(29)

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False

In [101]:
df2.groupby("genre").budget_million.agg("mean")

genre
Action       50.666667
Animation     6.000000
Comedy       40.000000
Crime        81.333333
Drama        21.300000
Horror       16.000000
Mystery      35.000000
Romance       8.000000
Sci-Fi       98.333333
Thriller     24.750000
Name: budget_million, dtype: float64

In [100]:
df2.groupby("country").genre.count()

country
Germany           1
India             9
Indonesia         1
South Africa      1
South Korea       2
Spain             2
United Kingdom    4
United States     9
india             1
Name: genre, dtype: int64

In [102]:
df2[["budget_million","imdb_rating"]].mean()

budget_million    38.758621
imdb_rating        7.510345
dtype: float64

In [103]:
df2.groupby("release_year")["imdb_rating"].mean()

release_year
2010         NaN
2016    8.466667
2017    8.150000
2018    7.900000
2019    7.625000
2020    6.712500
2021    7.225000
2022    7.666667
Name: imdb_rating, dtype: float64

In [110]:
# df2.drop()
a = df2[df2["release_year"]==2010]
df2.drop(29)

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False

In [114]:
df2.groupby("category")["imdb_rating"].max().sort_values(ascending=False).head(1)

category
Original    8.8
Name: imdb_rating, dtype: float64

In [115]:
df2.isnull().sum()

show_id             0
title               0
type                0
release_year        0
added_to_netflix    0
country             0
duration            0
genre               0
rating              0
imdb_rating         1
votes               0
language            1
category            0
actors_count        0
budget_million      1
has_won_award       0
dtype: int64

In [117]:
df2["imdb_rating"]=df2["imdb_rating"].fillna(df2["imdb_rating"].mean())

In [118]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.700000,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.200000,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.800000,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.700000,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.600000,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.000000,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.800000,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.600000,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.200000,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.700000,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.500000,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.600000,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.000000,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.500000,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.400000,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.600000,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.100000,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.500000,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.100000,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.100000,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.300000,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.900000,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.600000,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.400000,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.800000,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.200000,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.700000,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.000000,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.200000,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,7.510345,50000,English,Licensed,8,20.0,False

In [119]:
df2["imdb_rating"].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: imdb_rating, dtype: bool

In [120]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   show_id           30 non-null     object
 1   title             30 non-null     object
 2   type              30 non-null     object
 3   release_year      30 non-null     int64
 4   added_to_netflix  30 non-null     object
 5   country           30 non-null     object
 6   duration          30 non-null     object
 7   genre             30 non-null     object
 8   rating            30 non-null     object
 9   imdb_rating       30 non-null     float64
 10  votes             30 non-null     int64
 11  language          29 non-null     object
 12  category          30 non-null     object
 13  actors_count      30 non-null     int64
 14  budget_million    29 non-null     float64
 15  has_won_award     30 non-null     object
dtypes: float64(2), int64(3), object(11)
memory usage: 3.9+ KB

In [123]:
df2["language"] = df2["language"].fillna("Unknown")

In [124]:
df2

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.700000,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.200000,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.800000,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.700000,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.600000,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.000000,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.800000,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.600000,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.200000,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.700000,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.500000,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.600000,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.000000,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.500000,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.400000,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.600000,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.100000,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.500000,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.100000,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.100000,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.300000,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.900000,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.600000,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.400000,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.800000,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.200000,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.700000,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.000000,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.200000,28000,Unknown,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,7.510345,50000,English,Licensed,8,20.0,False

In [125]:
df2.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [126]:
df2.drop_duplicates()

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.700000,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.200000,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.800000,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.700000,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.600000,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.000000,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.800000,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.600000,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.200000,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.700000,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.500000,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.600000,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.000000,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.500000,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.400000,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.600000,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.100000,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.500000,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.100000,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.100000,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.300000,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.900000,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.600000,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.400000,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.800000,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,Tv-28,8.200000,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.700000,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,12-05-2006,United States,,Drama,TV-14,7.000000,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,india,2 Seasons,Drama,TV-MA,7.200000,28000,Unknown,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,7.510345,50000,English,Licensed,8,20.0,False

In [127]:
df2.shape

(30, 16)