In [1]:
import pandas as pd

In [32]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\netflex1.csv")

In [3]:
df.head()

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True

In [4]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [5]:
df = pd.read_csv("matches.csv")

In [6]:
df.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [7]:
df.tail()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [8]:
df.sample()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
234,235,2011,Chennai,2011-04-08,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,bat,normal,0,Chennai Super Kings,2,0,S Anirudha,"MA Chidambaram Stadium, Chepauk",BR Doctrove,PR Reiffel,NaN

In [9]:
df.index

RangeIndex(start=0, stop=636, step=1)

In [10]:
df.sort_values("city")

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
460,461,2014,Abu Dhabi,2014-04-18,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,4,AM Rahane,Sheikh Zayed Stadium,BF Bowden,RK Illingworth,NaN
471,472,2014,Abu Dhabi,2014-04-26,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kings XI Punjab,23,0,Sandeep Sharma,Sheikh Zayed Stadium,HDPK Dharmasena,RK Illingworth,NaN
470,471,2014,Abu Dhabi,2014-04-26,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,6,PV Tambe,Sheikh Zayed Stadium,HDPK Dharmasena,C Shamshuddin,NaN
464,465,2014,Abu Dhabi,2014-04-21,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,normal,0,Chennai Super Kings,93,0,SK Raina,Sheikh Zayed Stadium,RK Illingworth,C Shamshuddin,NaN
459,460,2014,Abu Dhabi,2014-04-18,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Sheikh Zayed Stadium,RK Illingworth,C Shamshuddin,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,467,2014,NaN,2014-04-23,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,normal,0,Chennai Super Kings,7,0,RA Jadeja,Dubai International Cricket Stadium,HDPK Dharmasena,RK Illingworth,NaN
468,469,2014,NaN,2014-04-25,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,4,0,AJ Finch,Dubai International Cricket Stadium,M Erasmus,S Ravi,NaN
469,470,2014,NaN,2014-04-25,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Chennai Super Kings,0,7,MM Sharma,Dubai International Cricket Stadium,BF Bowden,M Erasmus,NaN
474,475,2014,NaN,2014-04-28,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,5,Sandeep Sharma,Dubai International Cricket Stadium,BF Bowden,S Ravi,NaN
476,477,2014,NaN,2014-04-30,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Sunrisers Hyderabad,15,0,B Kumar,Dubai International Cricket Stadium,HDPK Dharmasena,M Erasmus,NaN

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.drop_duplicates()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [14]:
df.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              1
umpire2              1
umpire3            636
dtype: int64

In [16]:
df.drop(columns=["umpire3","umpire1"])

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire2
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",NJ Llong
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,S Ravi
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,CK Nandan
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,C Shamshuddin
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,BNJ Oxenford
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,HDPK Dharmasena
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,C Shamshuddin
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,CK Nandan
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,BNJ Oxenford

In [17]:
df.shape

(636, 18)

In [18]:
df.dropna()

Empty DataFrame
Columns: [id, season, city, date, team1, team2, toss_winner, toss_decision, result, dl_applied, winner, win_by_runs, win_by_wickets, player_of_match, venue, umpire1, umpire2, umpire3]
Index: []

In [19]:
df.shape

(636, 18)

In [20]:
df.shape

(636, 18)

In [21]:
df.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              1
umpire2              1
umpire3            636
dtype: int64

In [28]:
df["city"]=df["city"].dropna(inplace=True)

In [31]:


df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,None,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,None,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,None,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,None,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,None,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,None,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,None,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,None,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,None,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,None,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [33]:
df = pd.read_csv("tested.csv")

In [34]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [39]:
df.drop(columns="Cabin",inplace=True)

In [36]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [40]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [41]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64

In [44]:
df.dropna(inplace=True)

In [45]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [47]:
df.duplicated().sum()

np.int64(0)

In [48]:
df1 = pd.read_csv(r"C:\Users\Admin\Downloads\netflex1.csv")

In [49]:
df1.tail()

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate
27,s28,Null Movie,Movie,2020,NaN,United States,,Drama,TV-14,7.0,30000,English,Original,8,NaN,False
28,s29,Unknown Show,TV Show,2019,2019-08-11,NaN,2 Seasons,Drama,TV-MA,7.2,28000,NaN,Original,7,14.0,False
29,s30,Old Classic,Movie,2010,2020-01-01,United States,145 min,Drama,PG-13,NaN,50000,English,Licensed,8,20.0,False

In [50]:
df1.sample()

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False

In [52]:
df1.dropna().sum()

show_id             s1s2s3s4s5s6s7s8s9s10s11s12s13s14s15s16s17s18s...
title               Stranger ThingsMoney HeistThe IrishmanExtracti...
type                TV ShowTV ShowMovieMovieTV ShowMovieTV ShowMov...
release_year                                                    54517
added_to_netflix    2016-07-152017-05-022019-11-272020-04-242018-0...
country             United StatesSpainUnited StatesUnited StatesIn...
duration            3 Seasons5 Seasons209 min117 min2 Seasons173 m...
genre               Sci-FiThrillerCrimeActionCrimeDramaSci-FiHorro...
rating              TV-14TV-MARRTV-MATV-MATV-MATV-MATV-14TV-MATV-M...
imdb_rating                                                     203.6
votes                                                         6267000
language            EnglishSpanishEnglishEnglishHindiHindiGermanEn...
category            OriginalOriginalLicensedOriginalOriginalLicens...
actors_count                                                      266
budget_million                                                 1090.0
has_won_award       TrueTrueTrueFalseTrueFalseTrueFalseFalseFalseT...
dtype: object

In [53]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
413    False
414    False
415    False
416    False
417    False
Length: 417, dtype: bool

In [54]:
df1.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [56]:
df1["added_to_netflix"] = pd.to_datetime(df1["added_to_netflix"])

In [57]:
df1["added_to_netflix"].dtype

dtype('<M8[ns]')

In [61]:
df1["added_to_netflix"].dropna(inplace=True)

In [67]:
df1

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,s1,Stranger Things,TV Show,2016,2016-07-15,United States,3 Seasons,Sci-Fi,TV-14,8.7,650000,English,Original,14,50.0,True
1,s2,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True
2,s3,The Irishman,Movie,2019,2019-11-27,United States,209 min,Crime,R,7.8,320000,English,Licensed,20,159.0,True
3,s4,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False
4,s5,Sacred Games,TV Show,2018,2018-07-06,India,2 Seasons,Crime,TV-MA,8.6,190000,Hindi,Original,11,30.0,True
5,s6,Kabir Singh,Movie,2019,2020-01-05,India,173 min,Drama,TV-MA,7.0,92000,Hindi,Licensed,7,15.0,False
6,s7,Dark,TV Show,2017,2017-12-01,Germany,3 Seasons,Sci-Fi,TV-MA,8.8,410000,German,Original,10,45.0,True
7,s8,Bird Box,Movie,2018,2018-12-21,United States,124 min,Horror,TV-MA,6.6,280000,English,Original,9,20.0,False
8,s9,Darlings,Movie,2022,2022-08-05,India,133 min,Drama,TV-14,7.2,45000,Hindi,Original,6,12.0,False
9,s10,Guilty,Movie,2020,2020-03-06,India,119 min,Drama,TV-MA,5.7,38000,Hindi,Licensed,5,9.0,False
10,s11,Delhi Crime,TV Show,2019,2019-03-22,India,2 Seasons,Drama,TV-MA,8.5,87000,Hindi,Original,8,10.0,True
11,s12,The Crown,TV Show,2016,2016-11-04,United Kingdom,4 Seasons,Drama,TV-14,8.6,185000,English,Original,15,65.0,True
12,s13,Enola Holmes,Movie,2020,2020-09-23,United Kingdom,123 min,Mystery,PG-13,7.0,140000,English,Original,8,35.0,False
13,s14,Mirzapur,TV Show,2018,2018-11-16,India,2 Seasons,Action,TV-MA,8.5,95000,Hindi,Original,7,22.0,True
14,s15,Tenet,Movie,2020,2021-05-09,United Kingdom,150 min,Sci-Fi,PG-13,7.4,510000,English,Licensed,15,200.0,True
15,s16,Ludo,Movie,2020,2020-11-12,India,150 min,Drama,TV-MA,7.6,43000,Hindi,Original,7,18.0,False
16,s17,Squid Game,TV Show,2021,2021-09-17,South Korea,1 Season,Thriller,TV-MA,8.1,480000,Korean,Original,12,21.0,True
17,s18,All of Us Are Dead,TV Show,2022,2022-01-28,South Korea,1 Season,Horror,TV-MA,7.5,120000,Korean,Original,9,12.0,False
18,s19,The White Tiger,Movie,2021,2021-01-22,India,125 min,Drama,R,7.1,60000,Hindi,Original,6,20.0,False
19,s20,Lucifer,TV Show,2016,2016-06-25,United States,6 Seasons,Crime,TV-14,8.1,410000,English,Licensed,15,55.0,True
20,s21,Wednesday,TV Show,2022,2022-11-23,United States,1 Season,Comedy,TV-14,8.3,370000,English,Original,10,40.0,True
21,s22,Haseen Dillruba,Movie,2021,2021-07-02,India,135 min,Thriller,TV-MA,6.9,54000,Hindi,Original,6,8.0,False
22,s23,Jungle Beat,Movie,2020,2020-10-10,South Africa,89 min,Animation,PG,5.6,15000,English,Licensed,5,6.0,False
23,s24,Darkest Hour,Movie,2017,2018-05-22,United Kingdom,125 min,Drama,PG-13,7.4,125000,English,Licensed,11,30.0,True
24,s25,Layla Majnun,Movie,2021,2021-02-11,Indonesia,119 min,Romance,PG,6.8,28000,Indonesian,Original,6,8.0,False
25,s26,Money Heist,TV Show,2017,2017-05-02,Spain,5 Seasons,Thriller,TV-MA,8.2,550000,Spanish,Original,12,35.0,True # duplicate
26,s27,Extraction,Movie,2020,2020-04-24,United States,117 min,Action,R,6.7,210000,English,Original,10,65.0,False # duplicate

In [65]:
df1.dropna(inplace=True)

In [71]:
df1["added_to_netflix"].dt.day

0     15
1      2
2     27
3     24
4      6
5      5
6      1
7     21
8      5
9      6
10    22
11     4
12    23
13    16
14     9
15    12
16    17
17    28
18    22
19    25
20    23
21     2
22    10
23    22
24    11
25     2
26    24
Name: added_to_netflix, dtype: int32

In [72]:
df1.isnull().sum()

show_id             0
title               0
type                0
release_year        0
added_to_netflix    0
country             0
duration            0
genre               0
rating              0
imdb_rating         0
votes               0
language            0
category            0
actors_count        0
budget_million      0
has_won_award       0
dtype: int64

In [73]:
df1.isna()

,show_id,title,type,release_year,added_to_netflix,country,duration,genre,rating,imdb_rating,votes,language,category,actors_count,budget_million,has_won_award
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [75]:
df1 = pd.read_csv(r"C:\Users\Admin\Downloads\students_scores.csv")

In [76]:
df1

       Name      Sub  Marks Rank
0     Alice     Math   85.0    A
1       Bob  Science   90.0    A
2   Charlie     Math   78.0    B
3     David  English   88.0    A
4       Eve  Science    NaN    A
5     Frank  English   75.0    B
6     Grace     Math   60.0    C
7    Hannah  Science   89.0    A
8       Ivy  English   95.0  NaN
9      Jack     Math   55.0    C
10  Charlie     Math   78.0    B
11    David  English   88.0    A

In [77]:
df1.isna()

     Name    Sub  Marks   Rank
0   False  False  False  False
1   False  False  False  False
2   False  False  False  False
3   False  False  False  False
4   False  False   True  False
5   False  False  False  False
6   False  False  False  False
7   False  False  False  False
8   False  False  False   True
9   False  False  False  False
10  False  False  False  False
11  False  False  False  False

In [78]:
df1.isna().sum()

Name     0
Sub      0
Marks    1
Rank     1
dtype: int64

In [79]:
df1.isnull()

     Name    Sub  Marks   Rank
0   False  False  False  False
1   False  False  False  False
2   False  False  False  False
3   False  False  False  False
4   False  False   True  False
5   False  False  False  False
6   False  False  False  False
7   False  False  False  False
8   False  False  False   True
9   False  False  False  False
10  False  False  False  False
11  False  False  False  False

In [80]:
df1.isnull().sum()

Name     0
Sub      0
Marks    1
Rank     1
dtype: int64

In [82]:
df1["Marks"] = df1["Marks"].fillna(df1["Marks"].mean())

In [83]:
df1

       Name      Sub      Marks Rank
0     Alice     Math  85.000000    A
1       Bob  Science  90.000000    A
2   Charlie     Math  78.000000    B
3     David  English  88.000000    A
4       Eve  Science  80.090909    A
5     Frank  English  75.000000    B
6     Grace     Math  60.000000    C
7    Hannah  Science  89.000000    A
8       Ivy  English  95.000000  NaN
9      Jack     Math  55.000000    C
10  Charlie     Math  78.000000    B
11    David  English  88.000000    A

In [85]:
a = df1["Rank"].mode()

In [86]:
a

0    A
Name: Rank, dtype: object

In [89]:
df1["Rank"] = df1["Rank"].fillna(a.loc[0])

In [90]:
df1

       Name      Sub      Marks Rank
0     Alice     Math  85.000000    A
1       Bob  Science  90.000000    A
2   Charlie     Math  78.000000    B
3     David  English  88.000000    A
4       Eve  Science  80.090909    A
5     Frank  English  75.000000    B
6     Grace     Math  60.000000    C
7    Hannah  Science  89.000000    A
8       Ivy  English  95.000000    A
9      Jack     Math  55.000000    C
10  Charlie     Math  78.000000    B
11    David  English  88.000000    A

In [93]:
df1.groupby("Sub").agg(marks_mean =("Marks","mean"),
                       marks_median = ("Marks","median"),
                       name_count = ("Name","count"))

         marks_mean  marks_median  name_count
Sub
English   86.500000          88.0           4
Math      71.200000          78.0           5
Science   86.363636          89.0           3

In [94]:
df1.dropna(inplace=True)

In [96]:
df1.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [101]:
df1.drop_duplicates(inplace=True)

In [102]:
df1

      Name      Sub      Marks Rank
0    Alice     Math  85.000000    A
1      Bob  Science  90.000000    A
2  Charlie     Math  78.000000    B
3    David  English  88.000000    A
4      Eve  Science  80.090909    A
5    Frank  English  75.000000    B
6    Grace     Math  60.000000    C
7   Hannah  Science  89.000000    A
8      Ivy  English  95.000000    A
9     Jack     Math  55.000000    C

In [114]:
df1["Marks"]=df1["Marks"].astype("int")

In [115]:
df1["Marks"].dtype

dtype('int64')

In [119]:
df1.select_dtypes("int")

   Marks
0     85
1     90
2     78
3     88
4     80
5     75
6     60
7     89
8     95
9     55

In [122]:
df1.groupby("Rank")["Name"].count()

Rank
A    6
B    2
C    2
Name: Name, dtype: int64

In [123]:
df1.Marks

0    85
1    90
2    78
3    88
4    80
5    75
6    60
7    89
8    95
9    55
Name: Marks, dtype: int64

In [125]:
df1.sort_values("Name")

      Name      Sub  Marks Rank
0    Alice     Math     85    A
1      Bob  Science     90    A
2  Charlie     Math     78    B
3    David  English     88    A
4      Eve  Science     80    A
5    Frank  English     75    B
6    Grace     Math     60    C
7   Hannah  Science     89    A
8      Ivy  English     95    A
9     Jack     Math     55    C

In [127]:
df1.sort_index()

      Name      Sub  Marks Rank
0    Alice     Math     85    A
1      Bob  Science     90    A
2  Charlie     Math     78    B
3    David  English     88    A
4      Eve  Science     80    A
5    Frank  English     75    B
6    Grace     Math     60    C
7   Hannah  Science     89    A
8      Ivy  English     95    A
9     Jack     Math     55    C

In [128]:
df1["Marks"].mean()

np.float64(79.5)

In [133]:
df1["Feedback"]=""
df1["Feedback"] = df1.loc[(df1["Marks"]>80) & (df1["Rank"]=="A"),"Feedback"]="Good"

In [135]:
df1.drop(columns="feedback")

      Name      Sub  Marks Rank Feedback
0    Alice     Math     85    A     Good
1      Bob  Science     90    A     Good
2  Charlie     Math     78    B     Good
3    David  English     88    A     Good
4      Eve  Science     80    A     Good
5    Frank  English     75    B     Good
6    Grace     Math     60    C     Good
7   Hannah  Science     89    A     Good
8      Ivy  English     95    A     Good
9     Jack     Math     55    C     Good

In [137]:
df1.drop(columns="Feedback",inplace=True)

In [139]:
df1.dropna()

     Name      Sub  Marks Rank feedback
0   Alice     Math     85    A     Good
1     Bob  Science     90    A     Good
3   David  English     88    A     Good
7  Hannah  Science     89    A     Good
8     Ivy  English     95    A     Good

In [142]:
df1["feedback"]=df1.loc[(df1["Marks"]>=65) & (df1["Marks"]<=80),"feedback"]="Good2"

In [143]:
df1

      Name      Sub  Marks Rank feedback
0    Alice     Math     85    A    Good2
1      Bob  Science     90    A    Good2
2  Charlie     Math     78    B    Good2
3    David  English     88    A    Good2
4      Eve  Science     80    A    Good2
5    Frank  English     75    B    Good2
6    Grace     Math     60    C    Good2
7   Hannah  Science     89    A    Good2
8      Ivy  English     95    A    Good2
9     Jack     Math     55    C    Good2

In [146]:
df1.drop(columns="feedback",inplace=True)

In [148]:
df1["feedback"] = ""

In [150]:
df1.loc[(df1["Marks"]>=80) & (df1["Rank"]=="A"),"feedback"]="Very Good"

In [152]:
df1.isnull()

    Name    Sub  Marks   Rank  feedback
0  False  False  False  False     False
1  False  False  False  False     False
2  False  False  False  False     False
3  False  False  False  False     False
4  False  False  False  False     False
5  False  False  False  False     False
6  False  False  False  False     False
7  False  False  False  False     False
8  False  False  False  False     False
9  False  False  False  False     False

In [153]:
df1["feedback"].empty

False

In [155]:
df1.loc[(df1["Marks"]>65) & (df1["Marks"]<80),"feedback"]="Good"

In [157]:
df1.loc[df1["Marks"]<65,"feedback"]="Not Good"

In [159]:
df1["feedback"].value_counts()

feedback
Very Good    6
Good         2
Not Good     2
Name: count, dtype: int64

In [163]:
import pandas as pd
df = pd.read_csv("tested.csv")

In [4]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

In [5]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [6]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
413,False,False,False,False,False,True,False,False,False,False,True,False
414,False,False,False,False,False,False,False,False,False,False,False,False
415,False,False,False,False,False,False,False,False,False,False,True,False
416,False,False,False,False,False,True,False,False,False,False,True,False
417,False,False,False,False,False,True,False,False,False,False,True,False

In [164]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [7]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [8]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.sample(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
187,1079,0,3,"Davies, Mr. Joseph",male,17.00000,2,0,A/4 48873,8.0500,NaN,S
31,923,0,2,"Jefferys, Mr. Clifford Thomas",male,24.00000,2,0,C.A. 31029,31.5000,NaN,S
86,978,1,3,"Barry, Miss. Julia",female,27.00000,0,0,330844,7.8792,NaN,Q
235,1127,0,3,"Vendel, Mr. Olof Edvin",male,20.00000,0,0,350416,7.8542,NaN,S
219,1111,0,3,"Thomson, Mr. Alexander Morrison",male,30.27259,0,0,32302,8.0500,NaN,S
289,1181,0,3,"Ford, Mr. Arthur",male,30.27259,0,0,A/5 1478,8.0500,NaN,S
157,1049,1,3,"Lundin, Miss. Olga Elida",female,23.00000,0,0,347469,7.8542,NaN,S
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.00000,0,0,347086,7.7750,NaN,S
52,944,1,2,"Hocking, Miss. Ellen Nellie""""",female,20.00000,2,1,29105,23.0000,NaN,S
76,968,0,3,"Miles, Mr. Frank",male,30.27259,0,0,359306,8.0500,NaN,S
353,1245,0,2,"Herman, Mr. Samuel",male,49.00000,1,2,220845,65.0000,NaN,S
340,1232,0,2,"Fillbrook, Mr. Joseph Charles",male,18.00000,0,0,C.A. 15185,10.5000,NaN,S
156,1048,1,1,"Bird, Miss. Ellen",female,29.00000,0,0,PC 17483,221.7792,C97,S
204,1096,0,2,"Andrew, Mr. Frank Thomas",male,25.00000,0,0,C.A. 34050,10.5000,NaN,S
272,1164,1,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",female,26.00000,1,0,13508,136.7792,C89,C

In [11]:
df.shape

(418, 12)

In [12]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [14]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,12.634534,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,23.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,30.272590,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,35.750000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [15]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [16]:
df.isnull().count()

PassengerId    418
Survived       418
Pclass         418
Name           418
Sex            418
Age            418
SibSp          418
Parch          418
Ticket         418
Fare           418
Cabin          418
Embarked       418
dtype: int64

In [17]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [184]:
df["PassengerId"].unique()

array([ 892,  893,  894,  895,  896,  897,  898,  899,  900,  901,  902,
        903,  904,  905,  906,  907,  908,  909,  910,  911,  912,  913,
        914,  915,  916,  917,  918,  919,  920,  921,  922,  923,  924,
        925,  926,  927,  928,  929,  930,  931,  932,  933,  934,  935,
        936,  937,  938,  939,  940,  941,  942,  943,  944,  945,  946,
        947,  948,  949,  950,  951,  952,  953,  954,  955,  956,  957,
        958,  959,  960,  961,  962,  963,  964,  965,  966,  967,  968,
        969,  970,  971,  972,  973,  974,  975,  976,  977,  978,  979,
        980,  981,  982,  983,  984,  985,  986,  987,  988,  989,  990,
        991,  992,  993,  994,  995,  996,  997,  998,  999, 1000, 1001,
       1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012,
       1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023,
       1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034,
       1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045,
       1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056,
       1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067,
       1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078,
       1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089,
       1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100,
       1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111,
       1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122,
       1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133,
       1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144,
       1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155,
       1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166,
       1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177,
       1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188,
       1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199,
       1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210,
       1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221,
       1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232,
       1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243,
       1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254,
       1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265,
       1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276,
       1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287,
       1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298,
       1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309])

In [185]:
df["Pclass"].value_counts()

Pclass
3    218
1    107
2     93
Name: count, dtype: int64

In [189]:
df["Sex"].unique().size

2

In [190]:
df["PassengerId"].unique().size

418

In [18]:
df[["Name","Age","Fare"]]

                                             Name       Age      Fare
0                                Kelly, Mr. James  34.50000    7.8292
1                Wilkes, Mrs. James (Ellen Needs)  47.00000    7.0000
2                       Myles, Mr. Thomas Francis  62.00000    9.6875
3                                Wirz, Mr. Albert  27.00000    8.6625
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.00000   12.2875
..                                            ...       ...       ...
413                            Spector, Mr. Woolf  30.27259    8.0500
414                  Oliva y Ocana, Dona. Fermina  39.00000  108.9000
415                  Saether, Mr. Simon Sivertsen  38.50000    7.2500
416                           Ware, Mr. Frederick  30.27259    8.0500
417                      Peter, Master. Michael J  30.27259   22.3583

[418 rows x 3 columns]

In [193]:
df[df["Age"]>30].shape

(218, 12)

In [195]:
df[df["Fare"]<20].shape

(237, 12)

In [19]:
df.shape

(418, 12)

In [20]:
df[(df["Sex"]=="female") & (df["Pclass"]==1)].shape

(50, 12)

In [21]:
df[(df["Age"]>20) & (df["Age"]<=40)].shape

(272, 12)

In [22]:
df[df["Fare"]>100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
53,945,1,1,"Fortune, Miss. Ethel Flora",female,28.0,3,2,19950,263.0000,C23 C25 C27,S
59,951,1,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C
64,956,0,1,"Ryerson, Master. John Borie",male,13.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
69,961,1,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.0,1,4,19950,263.0000,C23 C25 C27,S
74,966,1,1,"Geiger, Miss. Amalie",female,35.0,0,0,113503,211.5000,C130,C
75,967,0,1,"Keeping, Mr. Edwin",male,32.5,0,0,113503,211.5000,C132,C
81,973,0,1,"Straus, Mr. Isidor",male,67.0,1,0,PC 17483,221.7792,C55 C57,S
114,1006,1,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.0,1,0,PC 17483,221.7792,C55 C57,S
141,1033,1,1,"Daniels, Miss. Sarah",female,33.0,0,0,113781,151.5500,NaN,S
142,1034,0,1,"Ryerson, Mr. Arthur Larned",male,61.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
156,1048,1,1,"Bird, Miss. Ellen",female,29.0,0,0,PC 17483,221.7792,C97,S
184,1076,1,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",female,27.0,1,1,PC 17558,247.5208,B58 B60,C
196,1088,0,1,"Spedden, Master. Robert Douglas",male,6.0,0,2,16966,134.5000,E34,C
202,1094,0,1,"Astor, Col. John Jacob",male,47.0,1,0,PC 17757,227.5250,C62 C64,C
217,1109,0,1,"Wick, Mr. George Dennick",male,57.0,1,1,36928,164.8667,NaN,S
218,1110,1,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.0,1,1,113503,211.5000,C80,C
239,1131,1,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",female,48.0,1,0,PC 17761,106.4250,C86,C
242,1134,0,1,"Spedden, Mr. Frederic Oakley",male,45.0,1,1,16966,134.5000,E34,C
252,1144,0,1,"Clark, Mr. Walter Miller",male,27.0,1,0,13508,136.7792,C89,C
272,1164,1,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",female,26.0,1,0,13508,136.7792,C89,C
306,1198,0,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S
314,1206,1,1,"White, Mrs. John Stuart (Ella Holmes)",female,55.0,0,0,PC 17760,135.6333,C32,C
316,1208,0,1,"Spencer, Mr. William Augustus",male,57.0,1,0,PC 17569,146.5208,B78,C
324,1216,1,1,"Kreuchen, Miss. Emilie",female,39.0,0,0,24160,211.3375,NaN,S
343,1235,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C
371,1263,1,1,"Wilson, Miss. Helen Alice",female,31.0,0,0,16966,134.5000,E39 E41,C
375,1267,1,1,"Bowen, Miss. Grace Scott",female,45.0,0,0,PC 17608,262.3750,NaN,C
400,1292,1,1,"Bonnell, Miss. Caroline",female,30.0,0,0,36928,164.8667,C7,S
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [23]:
df[df["Embarked"]=="S"].shape

(270, 12)

In [24]:
df[(df["Pclass"]==1) | (df["Pclass"]==2)].shape

(200, 12)

In [25]:
df[(df["Sex"]=="male")&(df["Fare"]>50)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
20,912,0,1,"Rothschild, Mr. Martin",male,55.00000,1,0,PC 17603,59.4000,NaN,C
23,915,0,1,"Williams, Mr. Richard Norris II",male,21.00000,0,1,PC 17597,61.3792,NaN,C
34,926,0,1,"Mock, Mr. Philipp Edmund",male,30.00000,1,0,13236,57.7500,C78,C
39,931,0,3,"Hee, Mr. Ling",male,30.27259,0,0,1601,56.4958,NaN,S
50,942,0,1,"Smith, Mr. Lucien Philip",male,24.00000,1,0,13695,60.0000,C31,S
64,956,0,1,"Ryerson, Master. John Borie",male,13.00000,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
75,967,0,1,"Keeping, Mr. Edwin",male,32.50000,0,0,113503,211.5000,C132,C
81,973,0,1,"Straus, Mr. Isidor",male,67.00000,1,0,PC 17483,221.7792,C55 C57,S
118,1010,0,1,"Beattie, Mr. Thomson",male,36.00000,0,0,13050,75.2417,C6,C
142,1034,0,1,"Ryerson, Mr. Arthur Larned",male,61.00000,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
146,1038,0,1,"Hilliard, Mr. Herbert Henry",male,30.27259,0,0,17463,51.8625,E46,S
166,1058,0,1,"Brandeis, Mr. Emil",male,48.00000,0,0,PC 17591,50.4958,B10,C
177,1069,0,1,"Stengel, Mr. Charles Emil Henry",male,54.00000,1,0,11778,55.4417,C116,C
181,1073,0,1,"Compton, Mr. Alexander Taylor Jr",male,37.00000,1,1,PC 17756,83.1583,E52,C
196,1088,0,1,"Spedden, Master. Robert Douglas",male,6.00000,0,2,16966,134.5000,E34,C
202,1094,0,1,"Astor, Col. John Jacob",male,47.00000,1,0,PC 17757,227.5250,C62 C64,C
212,1104,0,2,"Deacon, Mr. Percy William",male,17.00000,0,0,S.O.C. 14879,73.5000,NaN,S
217,1109,0,1,"Wick, Mr. George Dennick",male,57.00000,1,1,36928,164.8667,NaN,S
230,1122,0,2,"Sweet, Mr. George Frederick",male,14.00000,0,0,220845,65.0000,NaN,S
234,1126,0,1,"Cumings, Mr. John Bradley",male,39.00000,1,0,PC 17599,71.2833,C85,C
236,1128,0,1,"Warren, Mr. Frank Manley",male,64.00000,1,0,110813,75.2500,D37,C
242,1134,0,1,"Spedden, Mr. Frederic Oakley",male,45.00000,1,1,16966,134.5000,E34,C
245,1137,0,1,"Kenyon, Mr. Frederick R",male,41.00000,1,0,17464,51.8625,D21,S
252,1144,0,1,"Clark, Mr. Walter Miller",male,27.00000,1,0,13508,136.7792,C89,C
270,1162,0,1,"McCaffry, Mr. Thomas Francis",male,46.00000,0,0,13050,75.2417,C6,C
287,1179,0,1,"Snyder, Mr. John Pillsbury",male,24.00000,1,0,21228,82.2667,B45,S
293,1185,0,1,"Dodge, Dr. Washington",male,53.00000,1,1,33638,81.8583,A34,S
306,1198,0,1,"Allison, Mr. Hudson Joshua Creighton",male,30.00000,1,2,113781,151.5500,C22 C26,S
308,1200,0,1,"Hays, Mr. Charles Melville",male,55.00000,1,1,12749,93.5000,B69,S
316,1208,0,1,"Spencer, Mr. William Augustus",male,57.00000,1,0,PC 17569,146.5208,B78,C
327,1219,0,1,"Rosenshine, Mr. George (Mr George Thorne"")""",male,46.00000,0,0,PC 17585,79.2000,NaN,C
342,1234,0,3,"Sage, Mr. John George",male,30.27259,1,9,CA. 2343,69.5500,NaN,S
352,1244,0,2,"Dibden, Mr. William",male,18.00000,0,0,S.O.C. 14879,73.5000,NaN,S
353,1245,0,2,"Herman, Mr. Samuel",male,49.00000,1,2,220845,65.0000,NaN,S
360,1252,0,3,"Sage, Master. William Henry",male,14.50000,8,2,CA. 2343,69.5500,NaN,S
390,1282,0,1,"Payne, Mr. Vivian Ponsonby",male,23.00000,0,0,12749,93.5000,B24,S
407,1299,0,1,"Widener, Mr. George Dunton",male,50.00000,1,1,113503,211.5000,C80,C

In [26]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [27]:
df[df["Cabin"].isnull()].value_counts()

Series([], Name: count, dtype: int64)

In [28]:
df[(df["SibSp"]==0)&(df["Parch"]==0)].shape

(253, 12)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [216]:
df["Survived"].value_counts()

Survived
0    266
1    152
Name: count, dtype: int64

In [32]:
df.groupby("Pclass").agg(survied_p = ("Survived","value_counts"),
                         survied_p1 = ("SibSp","value_counts")).head(4)

          survied_p  survied_p1
Pclass
1      0       57.0          61
       1       50.0          42
2      0       63.0          62
       1       30.0          27

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [34]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [35]:
df.drop(columns="Cabin")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,C

In [37]:
df[(df["SibSp"]>=1) | (df["Parch"]>=1)].shape

(165, 12)

In [44]:
df.sort_values("Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
354,1246,1,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.5750,NaN,S
201,1093,0,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S
281,1173,0,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
307,1199,0,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S
250,1142,1,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
305,1197,1,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.00,1,1,112901,26.5500,B26,S
236,1128,0,1,"Warren, Mr. Frank Manley",male,64.00,1,0,110813,75.2500,D37,C
179,1071,1,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.00,0,2,PC 17756,83.1583,E45,C
81,973,0,1,"Straus, Mr. Isidor",male,67.00,1,0,PC 17483,221.7792,C55 C57,S
96,988,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.00,1,0,19877,78.8500,C46,S

In [45]:
df.set_index("Age")

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Age,,,,,,,,,,,
34.50000,892,0,3,"Kelly, Mr. James",male,0,0,330911,7.8292,NaN,Q
47.00000,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,1,0,363272,7.0000,NaN,S
62.00000,894,0,2,"Myles, Mr. Thomas Francis",male,0,0,240276,9.6875,NaN,Q
27.00000,895,0,3,"Wirz, Mr. Albert",male,0,0,315154,8.6625,NaN,S
22.00000,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
30.27259,1305,0,3,"Spector, Mr. Woolf",male,0,0,A.5. 3236,8.0500,NaN,S
39.00000,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,0,0,PC 17758,108.9000,C105,C
38.50000,1307,0,3,"Saether, Mr. Simon Sivertsen",male,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
30.27259,1308,0,3,"Ware, Mr. Frederick",male,0,0,359309,8.0500,NaN,S
30.27259,1309,0,3,"Peter, Master. Michael J",male,1,1,2668,22.3583,NaN,C

In [46]:
df["Age"] = df["Age"].astype("int")

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    int64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(1), int64(6), object(5)
memory usage: 39.3+ KB

In [53]:
df.groupby("Name")["Fare"].max().head(10).sort_values(ascending=False)

Name
Allison, Mr. Hudson Joshua Creighton         151.5500
Andersen, Mr. Albert Karvin                   22.5250
Abbott, Master. Eugene Joseph                 20.2500
Aldworth, Mr. Charles Augustus                13.0000
Aks, Master. Philip Frank                      9.3500
Abrahamsson, Mr. Abraham August Johannes       7.9250
Andersson, Miss. Ida Augusta Margareta         7.7750
Abelseth, Miss. Karen Marie                    7.6500
Abelseth, Mr. Olaus Jorgensen                  7.6500
Abrahim, Mrs. Joseph (Sophie Halaut Easu)      7.2292
Name: Fare, dtype: float64

In [54]:
df.sort_values("Fare")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
372,1264,0,1,"Ismay, Mr. Joseph Bruce",male,49,0,0,112058,0.0000,B52 B54 B56,S
266,1158,0,1,"Chisholm, Mr. Roderick Robert Crispin",male,30,0,0,112051,0.0000,NaN,S
21,913,0,3,"Olsen, Master. Artur Karl",male,9,0,1,C 17368,3.1708,NaN,S
133,1025,0,3,"Thomas, Mr. Charles P",male,30,1,0,2621,6.4375,NaN,C
116,1008,0,3,"Thomas, Mr. John",male,30,0,0,2681,6.4375,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
375,1267,1,1,"Bowen, Miss. Grace Scott",female,45,0,0,PC 17608,262.3750,NaN,C
53,945,1,1,"Fortune, Miss. Ethel Flora",female,28,3,2,19950,263.0000,C23 C25 C27,S
69,961,1,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60,1,4,19950,263.0000,C23 C25 C27,S
343,1235,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58,0,1,PC 17755,512.3292,B51 B53 B55,C
152,1044,0,3,"Storey, Mr. Thomas",male,60,0,0,3701,NaN,NaN,S

In [65]:

df["Age"] = df["Age"].fillna(df["Age"].mean())
# df[df["Age"]<0]
df.sort_values("Age").head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
354,1246,1,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.5750,NaN,S
201,1093,0,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S
281,1173,0,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
307,1199,0,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S
250,1142,1,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,NaN,S
263,1155,1,3,"Klasen, Miss. Gertrud Emilia",female,1.00,1,1,350405,12.1833,NaN,S
117,1009,1,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.7000,G6,S
296,1188,1,2,"Laroche, Miss. Louise",female,1.00,1,2,SC/Paris 2123,41.5792,NaN,C
89,981,0,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,NaN,S
284,1176,1,3,"Rosblom, Miss. Salli Helena",female,2.00,1,1,370129,20.2125,NaN,S

In [66]:
df.sort_values("Age").tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
142,1034,0,1,"Ryerson, Mr. Arthur Larned",male,61.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
193,1085,0,2,"Lingane, Mr. John",male,61.0,0,0,235509,12.3500,NaN,Q
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
13,905,0,2,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S
114,1006,1,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.0,1,0,PC 17483,221.7792,C55 C57,S
305,1197,1,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.0,1,1,112901,26.5500,B26,S
236,1128,0,1,"Warren, Mr. Frank Manley",male,64.0,1,0,110813,75.2500,D37,C
179,1071,1,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.0,0,2,PC 17756,83.1583,E45,C
81,973,0,1,"Straus, Mr. Isidor",male,67.0,1,0,PC 17483,221.7792,C55 C57,S
96,988,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S

In [67]:
df["Age"].max()

np.float64(76.0)

In [74]:
df[df["Pclass"]==1].sort_values("Fare",ascending=False).head(3).shape

(3, 12)

In [71]:
df[(df["Sex"]=="female") & (df["Age"]>=25) & (df["Fare"]>=50)].shape

(36, 12)

In [75]:
df[(df["Fare"]>=10) & (df["Fare"]<=80) & (df["Embarked"]=="S")].shape

(158, 12)

In [78]:
df[df["Name"].str.contains("Mr./",False)]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [79]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [80]:
df_clean = df

In [81]:
df_clean

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [83]:
df_clean.duplicated().sum()

np.int64(0)

In [84]:
df.drop_duplicates()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [85]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [86]:
df["Age"]

0      34.50000
1      47.00000
2      62.00000
3      27.00000
4      22.00000
         ...
413    30.27259
414    39.00000
415    38.50000
416    30.27259
417    30.27259
Name: Age, Length: 418, dtype: float64

In [87]:
df["Cabin"] = df["Cabin"].fillna("Unknown")

In [88]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,Unknown,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,Unknown,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,Unknown,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,Unknown,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,Unknown,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,Unknown,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,Unknown,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,Unknown,C

In [89]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Cabin          0
Embarked       0
dtype: int64

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        418 non-null    object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [96]:
 df["Fare"].astype("float")

0        7.8292
1        7.0000
2        9.6875
3        8.6625
4       12.2875
         ...
413      8.0500
414    108.9000
415      7.2500
416      8.0500
417     22.3583
Name: Fare, Length: 418, dtype: float64

In [97]:
df["Fare"].dtype

dtype('float64')

In [98]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,12.634534,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,23.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,30.272590,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,35.750000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [106]:
Q1 = 23.00
Q2 = 35.75

IQR = Q2 - Q1
print(IQR)
lower = Q1-1.5*(IQR)
higher = Q2+1.5*(IQR)
print(higher)
df[(df["Age"]<lower) | (df["Age"]>higher)]

12.75
54.875

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00,0,0,240276,9.6875,Unknown,Q
13,905,0,2,"Howard, Mr. Benjamin",male,63.00,1,0,24065,26.0000,Unknown,S
20,912,0,1,"Rothschild, Mr. Martin",male,55.00,1,0,PC 17603,59.4000,Unknown,C
48,940,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.00,0,0,11813,76.2917,D15,C
69,961,1,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.00,1,4,19950,263.0000,C23 C25 C27,S
77,969,1,1,"Cornell, Mrs. Robert Clifford (Malvina Helen L...",female,55.00,2,0,11770,25.7000,C101,S
81,973,0,1,"Straus, Mr. Isidor",male,67.00,1,0,PC 17483,221.7792,C55 C57,S
89,981,0,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,Unknown,S
96,988,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.00,1,0,19877,78.8500,C46,S
114,1006,1,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.00,1,0,PC 17483,221.7792,C55 C57,S
117,1009,1,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.7000,G6,S
142,1034,0,1,"Ryerson, Mr. Arthur Larned",male,61.00,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
152,1044,0,3,"Storey, Mr. Thomas",male,60.50,0,0,3701,NaN,Unknown,S
179,1071,1,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.00,0,2,PC 17756,83.1583,E45,C
193,1085,0,2,"Lingane, Mr. John",male,61.00,0,0,235509,12.3500,Unknown,Q
201,1093,0,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,Unknown,S
213,1105,1,2,"Howard, Mrs. Benjamin (Ellen Truelove Arman)",female,60.00,1,0,24065,26.0000,Unknown,S
217,1109,0,1,"Wick, Mr. George Dennick",male,57.00,1,1,36928,164.8667,Unknown,S
236,1128,0,1,"Warren, Mr. Frank Manley",male,64.00,1,0,110813,75.2500,D37,C
240,1132,1,1,"Lindstrom, Mrs. Carl Johan (Sigrid Posse)",female,55.00,0,0,112377,27.7208,Unknown,C
250,1142,1,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,Unknown,S
263,1155,1,3,"Klasen, Miss. Gertrud Emilia",female,1.00,1,1,350405,12.1833,Unknown,S
281,1173,0,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.7750,Unknown,S
284,1176,1,3,"Rosblom, Miss. Salli Helena",female,2.00,1,1,370129,20.2125,Unknown,S
296,1188,1,2,"Laroche, Miss. Louise",female,1.00,1,2,SC/Paris 2123,41.5792,Unknown,C
305,1197,1,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.00,1,1,112901,26.5500,B26,S
307,1199,0,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,Unknown,S
308,1200,0,1,"Hays, Mr. Charles Melville",male,55.00,1,1,12749,93.5000,B69,S
314,1206,1,1,"White, Mrs. John Stuart (Ella Holmes)",female,55.00,0,0,PC 17760,135.6333,C32,C
316,1208,0,1,"Spencer, Mr. William Augustus",male,57.00,1,0,PC 17569,146.5208,B78,C
343,1235,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.00,0,1,PC 17755,512.3292,B51 B53 B55,C
354,1246,1,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.5750,Unknown,S
356,1248,1,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.00,2,0,11769,51.4792,C101,S
378,1270,0,1,"Hipkins, Mr. William Edward",male,55.00,0,0,680,50.0000,C39,S
387,1279,0,2,"Ashby, Mr. John",male,57.00,0,0,244346,13.0000,Unknown,S
409,1301,1,3,"Peacock, Miss. Treasteall",female,3.00,1,1,SOTON/O.Q. 3101315,13.7750,Unknown,S

In [107]:
df[df["Age"]<0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [116]:
Q1 = 7.89
Q3 = 31.50

IQR = Q3-Q1

lower = Q1-1.5*(IQR)
higher = Q3+1.5*(IQR)

a = df[(df["Fare"]<lower) | (df["Fare"]>higher)]

In [118]:
Fare_Dataframe = pd.DataFrame(a)

In [119]:
Fare_Dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.00000,1,0,21228,82.2667,B45,S
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.00000,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
48,940,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.00000,0,0,11813,76.2917,D15,C
53,945,1,1,"Fortune, Miss. Ethel Flora",female,28.00000,3,2,19950,263.0000,C23 C25 C27,S
59,951,1,1,"Chaudanson, Miss. Victorine",female,36.00000,0,0,PC 17608,262.3750,B61,C
64,956,0,1,"Ryerson, Master. John Borie",male,13.00000,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
69,961,1,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.00000,1,4,19950,263.0000,C23 C25 C27,S
74,966,1,1,"Geiger, Miss. Amalie",female,35.00000,0,0,113503,211.5000,C130,C
75,967,0,1,"Keeping, Mr. Edwin",male,32.50000,0,0,113503,211.5000,C132,C
81,973,0,1,"Straus, Mr. Isidor",male,67.00000,1,0,PC 17483,221.7792,C55 C57,S
96,988,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.00000,1,0,19877,78.8500,C46,S
114,1006,1,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.00000,1,0,PC 17483,221.7792,C55 C57,S
118,1010,0,1,"Beattie, Mr. Thomson",male,36.00000,0,0,13050,75.2417,C6,C
141,1033,1,1,"Daniels, Miss. Sarah",female,33.00000,0,0,113781,151.5500,Unknown,S
142,1034,0,1,"Ryerson, Mr. Arthur Larned",male,61.00000,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
150,1042,1,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23.00000,0,1,11767,83.1583,C54,C
156,1048,1,1,"Bird, Miss. Ellen",female,29.00000,0,0,PC 17483,221.7792,C97,S
179,1071,1,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.00000,0,2,PC 17756,83.1583,E45,C
181,1073,0,1,"Compton, Mr. Alexander Taylor Jr",male,37.00000,1,1,PC 17756,83.1583,E52,C
184,1076,1,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",female,27.00000,1,1,PC 17558,247.5208,B58 B60,C
188,1080,1,3,"Sage, Miss. Ada",female,30.27259,8,2,CA. 2343,69.5500,Unknown,S
196,1088,0,1,"Spedden, Master. Robert Douglas",male,6.00000,0,2,16966,134.5000,E34,C
202,1094,0,1,"Astor, Col. John Jacob",male,47.00000,1,0,PC 17757,227.5250,C62 C64,C
212,1104,0,2,"Deacon, Mr. Percy William",male,17.00000,0,0,S.O.C. 14879,73.5000,Unknown,S
217,1109,0,1,"Wick, Mr. George Dennick",male,57.00000,1,1,36928,164.8667,Unknown,S
218,1110,1,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.00000,1,1,113503,211.5000,C80,C
234,1126,0,1,"Cumings, Mr. John Bradley",male,39.00000,1,0,PC 17599,71.2833,C85,C
236,1128,0,1,"Warren, Mr. Frank Manley",male,64.00000,1,0,110813,75.2500,D37,C
239,1131,1,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",female,48.00000,1,0,PC 17761,106.4250,C86,C
242,1134,0,1,"Spedden, Mr. Frederic Oakley",male,45.00000,1,1,16966,134.5000,E34,C
252,1144,0,1,"Clark, Mr. Walter Miller",male,27.00000,1,0,13508,136.7792,C89,C
270,1162,0,1,"McCaffry, Mr. Thomas Francis",male,46.00000,0,0,13050,75.2417,C6,C
272,1164,1,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",female,26.00000,1,0,13508,136.7792,C89,C
287,1179,0,1,"Snyder, Mr. John Pillsbury",male,24.00000,1,0,21228,82.2667,B45,S
293,1185,0,1,"Dodge, Dr. Washington",male,53.00000,1,1,33638,81.8583,A34,S
306,1198,0,1,"Allison, Mr. Hudson Joshua Creighton",male,30.00000,1,2,113781,151.5500,C22 C26,S
308,1200,0,1,"Hays, Mr. Charles Melville",male,55.00000,1,1,12749,93.5000,B69,S
314,1206,1,1,"White, Mrs. John Stuart (Ella Holmes)",female,55.00000,0,0,PC 17760,135.6333,C32,C
316,1208,0,1,"Spencer, Mr. William Augustus",male,57.00000,1,0,PC 17569,146.5208,B78,C
324,1216,1,1,"Kreuchen, Miss. Emilie",female,39.00000,0,0,24160,211.3375,Unknown,S
327,1219,0,1,"Rosenshine, Mr. George (Mr George Thorne"")""",male,46.00000,0,0,PC 17585,79.2000,Unknown,C
342,1234,0,3,"Sage, Mr. John George",male,30.27259,1,9,CA. 2343,69.5500,Unknown,S
343,1235,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.00000,0,1,PC 17755,512.3292,B51 B53 B55,C
352,1244,0,2,"Dibden, Mr. William",male,18.00000,0,0,S.O.C. 14879,73.5000,Unknown,S
360,1252,0,3,"Sage, Master. William Henry",male,14.50000,8,2,CA. 2343,69.5500,Unknown,S
365,1257,1,3,"Sage, Mrs. John (Annie Bullen)",female,30.27259,1,9,CA. 2343,69.5500,Unknown,S
371,1263,1,1,"Wilson, Miss. Helen Alice",female,31.00000,0,0,16966,134.5000,E39 E41,C
374,1266,1,1,"Dodge, Mrs. Washington (Ruth Vidaver)",female,54.00000,1,1,33638,81.8583,A34,S
375,1267,1,1,"Bowen, Miss. Grace Scott",female,45.00000,0,0,PC 17608,262.3750,Unknown,C
390,1282,0,1,"Payne, Mr. Vivian Ponsonby",male,23.00000,0,0,12749,93.5000,B24,S
397,1289,1,1,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",female,48.00000,1,1,13567,79.2000,B41,C
400,1292,1,1,"Bonnell, Miss. Caroline",female,30.00000,0,0,36928,164.8667,C7,S
407,1299,0,1,"Widener, Mr. George Dunton",male,50.00000,1,1,113503,211.5000,C80,C
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.00000,1,0,19928,90.0000,C78,Q
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C

In [121]:
df.to_csv("titanic_cleaned.csv",index=False)

In [124]:
df.groupby("Pclass")["Name"].count()

Pclass
1    107
2     93
3    218
Name: Name, dtype: int64

In [125]:
df.groupby("Sex").Age.mean()

Sex
female    30.272400
male      30.272699
Name: Age, dtype: float64

In [126]:
df.groupby("Pclass").Fare.mean()

Pclass
1    94.280297
2    22.202104
3    12.459678
Name: Fare, dtype: float64

In [129]:
df.groupby("Pclass").agg(count_age = ("Age","mean")
                                ,count_age_max=("Age","max"),
                                count_age_min = ("Age","min")
                                ,counts_ages = ("Age","count"))

        count_age  count_age_max  count_age_min  counts_ages
Pclass
1       40.022928           76.0           6.00          107
2       28.857881           63.0           0.92           93
3       26.090397           60.5           0.17          218

In [146]:
# df.groupby(["Pclass","Sex"])["Fare"].aggregate("mean")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,Unknown,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,Unknown,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,Unknown,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,Unknown,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,Unknown,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,Unknown,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,Unknown,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,Unknown,C

In [133]:
df.groupby(["Sex","Embarked"]).Name.count()

Sex     Embarked
female  C            40
        Q            24
        S            88
male    C            62
        Q            22
        S           182
Name: Name, dtype: int64

In [134]:
df.groupby("Sex").Fare.max()

Sex
female    512.3292
male      262.3750
Name: Fare, dtype: float64

In [135]:
df.groupby("Pclass").Fare.sum()

Pclass
1    10087.9918
2     2064.7957
3     2703.7501
Name: Fare, dtype: float64

In [138]:
df.groupby("Embarked").Name.count()

Embarked
C    102
Q     46
S    270
Name: Name, dtype: int64

In [139]:
df["Embarked"].value_counts()

Embarked
S    270
C    102
Q     46
Name: count, dtype: int64

In [140]:
df.groupby(["Sex","Embarked"]).Age.mean()

Sex     Embarked
female  C           35.545444
        Q           28.448795
        S           28.372908
male    C           32.776355
        Q           31.307777
        S           29.294686
Name: Age, dtype: float64

In [142]:
df.groupby("Pclass").agg(Fare_min = ("Fare","min"),
                         Fare_max = ("Fare","max"),
                         Fare_mean = ("Fare","mean"),
                         Fare_median = ("Fare","median"),
                         Fare_count = ("Fare","count"))

        Fare_min  Fare_max  Fare_mean  Fare_median  Fare_count
Pclass
1         0.0000  512.3292  94.280297      60.0000         107
2         9.6875   73.5000  22.202104      15.7500          93
3         3.1708   69.5500  12.459678       7.8958         217

In [147]:

df.groupby("Pclass").agg(sibsp1 = ("SibSp","mean"),
                         parch1 = ("Parch","mean"))

          sibsp1    parch1
Pclass
1       0.476636  0.383178
2       0.376344  0.344086
3       0.463303  0.417431

In [148]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Unknown,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,Unknown,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Unknown,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,Unknown,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,Unknown,S

In [152]:
df.groupby("Pclass").Fare.max().sort_values(ascending=False).head(1)

Pclass
1    512.3292
Name: Fare, dtype: float64

In [156]:
df["Embarked"].value_counts().head(1)

Embarked
S    270
Name: count, dtype: int64

In [162]:
df.groupby("Pclass").agg(passenger_count = ("Name","count"),
                         passenger_age_mean = ("Age","mean"),
                         passenger_fare_mean = ("Fare","mean"))

TypeError: agg function failed [how->mean,dtype->object]

In [158]:
df["Familysize"] = df["SibSp"]+df["Parch"]+1

In [159]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Familysize
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,Unknown,Q,1
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,Unknown,S,2
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,Unknown,Q,1
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,Unknown,S,1
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,Unknown,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,Unknown,S,1
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C,1
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,Unknown,S,1
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,Unknown,S,1
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,Unknown,C,3

In [161]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Familysize
0,892,0,3,"Kelly, Mr. James",male,,0,0,330911,7.8292,Unknown,Q,1
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,,1,0,363272,7.0000,Unknown,S,2
2,894,0,2,"Myles, Mr. Thomas Francis",male,,0,0,240276,9.6875,Unknown,Q,1
3,895,0,3,"Wirz, Mr. Albert",male,,0,0,315154,8.6625,Unknown,S,1
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,,1,1,3101298,12.2875,Unknown,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,,0,0,A.5. 3236,8.0500,Unknown,S,1
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,,0,0,PC 17758,108.9000,C105,C,1
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,,0,0,SOTON/O.Q. 3101262,7.2500,Unknown,S,1
416,1308,0,3,"Ware, Mr. Frederick",male,,0,0,359309,8.0500,Unknown,S,1
417,1309,0,3,"Peter, Master. Michael J",male,,1,1,2668,22.3583,Unknown,C,3

In [164]:
df_clean

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Familysize
0,892,0,3,"Kelly, Mr. James",male,,0,0,330911,7.8292,Unknown,Q,1
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,,1,0,363272,7.0000,Unknown,S,2
2,894,0,2,"Myles, Mr. Thomas Francis",male,,0,0,240276,9.6875,Unknown,Q,1
3,895,0,3,"Wirz, Mr. Albert",male,,0,0,315154,8.6625,Unknown,S,1
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,,1,1,3101298,12.2875,Unknown,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,,0,0,A.5. 3236,8.0500,Unknown,S,1
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,,0,0,PC 17758,108.9000,C105,C,1
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,,0,0,SOTON/O.Q. 3101262,7.2500,Unknown,S,1
416,1308,0,3,"Ware, Mr. Frederick",male,,0,0,359309,8.0500,Unknown,S,1
417,1309,0,3,"Peter, Master. Michael J",male,,1,1,2668,22.3583,Unknown,C,3

In [168]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [169]:
df["Age"]=df["Age"].fillna(df["Age"].median())

In [170]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,NaN,C

In [176]:
df_clean.drop(columns="Pclass")

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Familysize
0,892,0,"Kelly, Mr. James",male,,0,0,330911,7.8292,Unknown,Q,1
1,893,1,"Wilkes, Mrs. James (Ellen Needs)",female,,1,0,363272,7.0000,Unknown,S,2
2,894,0,"Myles, Mr. Thomas Francis",male,,0,0,240276,9.6875,Unknown,Q,1
3,895,0,"Wirz, Mr. Albert",male,,0,0,315154,8.6625,Unknown,S,1
4,896,1,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,,1,1,3101298,12.2875,Unknown,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,"Spector, Mr. Woolf",male,,0,0,A.5. 3236,8.0500,Unknown,S,1
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,,0,0,PC 17758,108.9000,C105,C,1
415,1307,0,"Saether, Mr. Simon Sivertsen",male,,0,0,SOTON/O.Q. 3101262,7.2500,Unknown,S,1
416,1308,0,"Ware, Mr. Frederick",male,,0,0,359309,8.0500,Unknown,S,1
417,1309,0,"Peter, Master. Michael J",male,,1,1,2668,22.3583,Unknown,C,3

In [177]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,NaN,C

In [215]:
df["Agegroup"] = ""


df["Agegroup"]=df.loc[df["Age"]<=18,"Agegroup"]="Child"

In [216]:
df.loc[df["Age"]>18,"Agegroup"]="Adult"

In [217]:
df[df["Age"]<=18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Agegroup
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.00,0,0,7538,9.2250,NaN,S,Child
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00,0,0,2657,7.2292,NaN,C,Child
21,913,0,3,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.1708,NaN,S,Child
55,947,0,3,"Rice, Master. Albert",male,10.00,4,1,382652,29.1250,NaN,Q,Child
60,952,0,3,"Dika, Mr. Mirko",male,17.00,0,0,349232,7.8958,NaN,S,Child
62,954,0,3,"Bjorklund, Mr. Ernst Herbert",male,18.00,0,0,347090,7.7500,NaN,S,Child
64,956,0,1,"Ryerson, Master. John Borie",male,13.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,Child
66,958,1,3,"Burns, Miss. Mary Delia",female,18.00,0,0,330963,7.8792,NaN,Q,Child
80,972,0,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.2458,NaN,C,Child
87,979,1,3,"Badman, Miss. Emily Louisa",female,18.00,0,0,A/4 31416,8.0500,NaN,S,Child
89,981,0,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,NaN,S,Child
104,996,1,3,"Thomas, Mrs. Alexander (Thamine Thelma"")""",female,16.00,1,1,2625,8.5167,NaN,C,Child
115,1007,0,3,"Chronopoulos, Mr. Demetrios",male,18.00,1,0,2680,14.4542,NaN,C,Child
117,1009,1,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.7000,G6,S,Child
120,1012,1,2,"Watt, Miss. Bertha J",female,12.00,0,0,C.A. 33595,15.7500,NaN,S,Child
125,1017,1,3,"Cribb, Miss. Laura Alice",female,17.00,0,1,371362,16.1000,NaN,S,Child
140,1032,1,3,"Goodwin, Miss. Jessie Allis",female,10.00,5,2,CA 2144,46.9000,NaN,S,Child
154,1046,0,3,"Asplund, Master. Filip Oscar",male,13.00,4,2,347077,31.3875,NaN,S,Child
161,1053,0,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.2458,NaN,C,Child
167,1059,0,3,"Ford, Mr. Edward Watson",male,18.00,2,2,W./C. 6608,34.3750,NaN,S,Child
175,1067,1,2,"Brown, Miss. Edith Eileen",female,15.00,0,2,29750,39.0000,NaN,S,Child
182,1074,1,1,"Marvin, Mrs. Daniel Warner (Mary Graham Carmic...",female,18.00,1,0,113773,53.1000,D30,S,Child
187,1079,0,3,"Davies, Mr. Joseph",male,17.00,2,0,A/4 48873,8.0500,NaN,S,Child
192,1084,0,3,"van Billiard, Master. Walter John",male,11.50,1,1,A/5. 851,14.5000,NaN,S,Child
194,1086,0,2,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.5000,NaN,S,Child
196,1088,0,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.5000,E34,C,Child
197,1089,1,3,"Nilsson, Miss. Berta Olivia",female,18.00,0,0,347066,7.7750,NaN,S,Child
201,1093,0,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S,Child
203,1095,1,2,"Quick, Miss. Winifred Vera",female,8.00,1,1,26360,26.0000,NaN,S,Child
212,1104,0,2,"Deacon, Mr. Percy William",male,17.00,0,0,S.O.C. 14879,73.5000,NaN,S,Child
230,1122,0,2,"Sweet, Mr. George Frederick",male,14.00,0,0,220845,65.0000,NaN,S,Child
238,1130,1,2,"Hiltunen, Miss. Marta",female,18.00,1,1,250650,13.0000,NaN,S,Child
250,1142,1,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,NaN,S,Child
263,1155,1,3,"Klasen, Miss. Gertrud Emilia",female,1.00,1,1,350405,12.1833,NaN,S,Child
269,1161,0,3,"Pokrnic, Mr. Mate",male,17.00,0,0,315095,8.6625,NaN,S,Child
281,1173,0,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,Child
283,1175,1,3,"Touma, Miss. Maria Youssef",female,9.00,1,1,2650,15.2458,NaN,C,Child
284,1176,1,3,"Rosblom, Miss. Salli Helena",female,2.00,1,1,370129,20.2125,NaN,S,Child
296,1188,1,2,"Laroche, Miss. Louise",female,1.00,1,2,SC/Paris 2123,41.5792,NaN,C,Child
307,1199,0,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S,Child
310,1202,0,3,"Cacic, Mr. Jego Grga",male,18.00,0,0,315091,8.6625,NaN,S,Child
315,1207,1,3,"Hagardon, Miss. Kate",female,17.00,0,0,AQ/3. 30631,7.7333,NaN,Q,Child
326,1218,1,2,"Becker, Miss. Ruth Elizabeth",female,12.00,2,1,230136,39.0000,F4,S,Child
340,1232,0,2,"Fillbrook, Mr. Joseph Charles",male,18.00,0,0,C.A. 15185,10.5000,NaN,S,Child
345,1237,1,3,"Abelseth, Miss. Karen Marie",female,16.00,0,0,348125,7.6500,NaN,S,Child
352,1244,0,2,"Dibden, Mr. William",male,18.00,0,0,S.O.C. 14879,73.5000,NaN,S,Child
354,1246,1,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.5750,NaN,S,Child
360,1252,0,3,"Sage, Master. William Henry",male,14.50,8,2,CA. 2343,69.5500,NaN,S,Child
379,1271,0,3,"Asplund, Master. Carl Edgar",male,5.00,4,2,347077,31.3875,NaN,S,Child
389,1281,0,3,"Palsson, Master. Paul Folke",male,6.00,3,1,349909,21.0750,NaN,S,Child
392,1284,0,3,"Abbott, Master. Eugene Joseph",male,13.00,0,2,C.A. 2673,20.2500,NaN,S,Child
395,1287,1,1,"Smith, Mrs. Lucien Philip (Mary Eloise Hughes)",female,18.00,1,0,13695,60.0000,C31,S,Child
403,1295,0,1,"Carrau, Mr. Jose Pedro",male,17.00,0,0,113059,47.1000,NaN,S,Child
409,1301,1,3,"Peacock, Miss. Treasteall",female,3.00,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,Child

In [218]:
df["Agegroup"].value_counts()

Agegroup
Adult    364
Child     54
Name: count, dtype: int64

In [219]:
df["FamilySize"] = df["SibSp"]+df["Parch"]+1

In [220]:
df["FarePerPerson"] = df["Fare"]/df["FamilySize"]

In [223]:
df["FarePerPerson"].isnull().count()

np.int64(418)

In [224]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Agegroup,FamilySize,FarePerPerson
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Adult,1,7.829200
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Adult,2,3.500000
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Adult,1,9.687500
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Adult,1,8.662500
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Adult,3,4.095833

In [225]:
df["IsFemale"] = 0

In [227]:
df.loc[df["Sex"]=="female","IsFemale"]=1

In [229]:
df["IsFemale"].value_counts()

IsFemale
0    266
1    152
Name: count, dtype: int64

In [231]:
df["Sex"] = df["Sex"].map({
    "male":1,
    "female":0})

In [232]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Agegroup,FamilySize,FarePerPerson,IsFemale
0,892,0,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,NaN,Q,Adult,1,7.829200,0
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,NaN,S,Adult,2,3.500000,1
2,894,0,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,NaN,Q,Adult,1,9.687500,0
3,895,0,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,NaN,S,Adult,1,8.662500,0
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,NaN,S,Adult,3,4.095833,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",1,27.0,0,0,A.5. 3236,8.0500,NaN,S,Adult,1,8.050000,0
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",0,39.0,0,0,PC 17758,108.9000,C105,C,Adult,1,108.900000,1
415,1307,0,3,"Saether, Mr. Simon Sivertsen",1,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,Adult,1,7.250000,0
416,1308,0,3,"Ware, Mr. Frederick",1,27.0,0,0,359309,8.0500,NaN,S,Adult,1,8.050000,0
417,1309,0,3,"Peter, Master. Michael J",1,27.0,1,1,2668,22.3583,NaN,C,Adult,3,7.452767,0

In [235]:
df["Age"] = df["Age"].astype("float")

In [236]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PassengerId    418 non-null    int64
 1   Survived       418 non-null    int64
 2   Pclass         418 non-null    int64
 3   Name           418 non-null    object
 4   Sex            418 non-null    int64
 5   Age            418 non-null    float64
 6   SibSp          418 non-null    int64
 7   Parch          418 non-null    int64
 8   Ticket         418 non-null    object
 9   Fare           417 non-null    float64
 10  Cabin          91 non-null     object
 11  Embarked       418 non-null    object
 12  Agegroup       418 non-null    object
 13  FamilySize     418 non-null    int64
 14  FarePerPerson  417 non-null    float64
 15  IsFemale       418 non-null    int64
dtypes: float64(3), int64(8), object(5)
memory usage: 52.4+ KB