In [1]:
import pandas as pd

In [2]:

name = ["abc","def","ghi","jkl","mno","pqr","stu","vwx","xyz","qqq","abc"]
students_data = {
                    "rn":[1,2,3,4,5,6,7,8,9,10,1],
                    "name":["abc","def","ghi","jkl","mno","pqr","stu","vwx","xyz","qqq","abc"],
                    "marks":[10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0,10.0],
                    "addr":["pune","karvenagar","akurdi","pimpri","baner","bavdhan","kothrud","nagar","ravet","mumbai","pune"],
                    "attd":[True,False,True,False,True,False,True,False,True,False,False]
                }

df=pd.DataFrame(students_data,index=name)

In [3]:
df

     rn name  marks        addr   attd
abc   1  abc   10.0        pune   True
def   2  def   20.0  karvenagar  False
ghi   3  ghi   30.0      akurdi   True
jkl   4  jkl   40.0      pimpri  False
mno   5  mno   50.0       baner   True
pqr   6  pqr   60.0     bavdhan  False
stu   7  stu   70.0     kothrud   True
vwx   8  vwx   80.0       nagar  False
xyz   9  xyz   90.0       ravet   True
qqq  10  qqq  100.0      mumbai  False
abc   1  abc   10.0        pune  False

In [4]:
df.loc["mno","rn":"marks":1]

rn          5
name      mno
marks    50.0
Name: mno, dtype: object

In [6]:
df[df["marks"]<20]

     rn name  marks  addr   attd
abc   1  abc   10.0  pune   True
abc   1  abc   10.0  pune  False

In [9]:
df[(df["marks"]<30) & (df["addr"]=="pune")]

     rn name  marks  addr   attd
abc   1  abc   10.0  pune   True
abc   1  abc   10.0  pune  False

In [10]:
df[(df["rn"]>4) & (df["attd"]==False)]

     rn name  marks     addr   attd
pqr   6  pqr   60.0  bavdhan  False
vwx   8  vwx   80.0    nagar  False
qqq  10  qqq  100.0   mumbai  False

In [13]:
res = df[(df["marks"]>30) & (df["attd"]!=True)]
res["name"].count()

np.int64(4)

In [14]:
df.loc[df["rn"]==5,"name"]="roshan"

In [15]:
df

     rn    name  marks        addr   attd
abc   1     abc   10.0        pune   True
def   2     def   20.0  karvenagar  False
ghi   3     ghi   30.0      akurdi   True
jkl   4     jkl   40.0      pimpri  False
mno   5  roshan   50.0       baner   True
pqr   6     pqr   60.0     bavdhan  False
stu   7     stu   70.0     kothrud   True
vwx   8     vwx   80.0       nagar  False
xyz   9     xyz   90.0       ravet   True
qqq  10     qqq  100.0      mumbai  False
abc   1     abc   10.0        pune  False

In [17]:
df.loc[((df["rn"]==1) & (df["attd"]==True)), "name"]="tushar"

In [18]:
df

     rn    name  marks        addr   attd
abc   1  tushar   10.0        pune   True
def   2     def   20.0  karvenagar  False
ghi   3     ghi   30.0      akurdi   True
jkl   4     jkl   40.0      pimpri  False
mno   5  roshan   50.0       baner   True
pqr   6     pqr   60.0     bavdhan  False
stu   7     stu   70.0     kothrud   True
vwx   8     vwx   80.0       nagar  False
xyz   9     xyz   90.0       ravet   True
qqq  10     qqq  100.0      mumbai  False
abc   1     abc   10.0        pune  False

In [24]:
df.loc[((df["attd"]==True) & (df["rn"]==1)),"name":"addr":1]

       name  marks  addr
abc  tushar   10.0  pune

In [29]:
df.loc[((df["marks"]>10) & (df["attd"]==False)),"marks"]+=5

In [30]:
df

     rn    name  marks        addr   attd
abc   1  tushar   10.0        pune   True
def   2     def   25.0  karvenagar  False
ghi   3     ghi   30.0      akurdi   True
jkl   4     jkl   45.0      pimpri  False
mno   5  roshan   50.0       baner   True
pqr   6     pqr   65.0     bavdhan  False
stu   7     stu   70.0     kothrud   True
vwx   8     vwx   85.0       nagar  False
xyz   9     xyz   90.0       ravet   True
qqq  10     qqq  105.0      mumbai  False
abc   1     abc   10.0        pune  False

In [31]:
df["marks"].sum()

np.float64(585.0)

In [32]:
df["marks"].mean()

np.float64(53.18181818181818)

In [33]:
df.marks.sum()

np.float64(585.0)

In [34]:
df.marks.mean()

np.float64(53.18181818181818)

In [35]:
df.marks.min()

np.float64(10.0)

In [36]:
df["marks"].unique()

array([ 10.,  25.,  30.,  45.,  50.,  65.,  70.,  85.,  90., 105.])

In [38]:
df["marks"].agg({"sum","max"})

max    105.0
sum    585.0
Name: marks, dtype: float64

In [39]:
df["marks"].aggregate("sum")

np.float64(585.0)

In [40]:
df["marks"].aggregate({"sum","mean","min"})

sum     585.000000
mean     53.181818
min      10.000000
Name: marks, dtype: float64

In [41]:
["abc","def","ghi","jkl","mno","pqr","stu","vwx","xyz","qqq","abc"],

(['abc',
  'def',
  'ghi',
  'jkl',
  'mno',
  'pqr',
  'stu',
  'vwx',
  'xyz',
  'qqq',
  'abc'],)

In [187]:
product_data = {
    "product_id": list(range(101, 126)),
    "product_name": [
        "Laptop", "Mouse", "Keyboard", "Monitor", "Printer",
        "Headphones", "Webcam", "Speaker", "Tablet", "Smartphone",
        "Charger", "USB Cable", "Power Bank", "Smartwatch", "Router",
        "SSD", "Hard Disk", "RAM", "Graphics Card", "Microphone",
        "Projector", "Scanner", "Pendrive", "Laptop Stand", "Cooling Pad"
    ],
    "category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Accessories",
        "Electronics", "Electronics", "Accessories", "Accessories",
        "Accessories", "Electronics", "Networking", "Storage",
        "Storage", "Components", "Components", "Accessories",
        "Electronics", "Electronics", "Storage", "Accessories",
        "Accessories"
    ],
    "price": [
        55000, 500, 1200, 12000, 8500,
        1800, 2500, 3200, 22000, 45000,
        800, 250, 1500, 6500, 2800,
        4500, 3200, 2400, 35000, 2100,
        28000, 6500, 600, 1800, 2200
    ],
    "quantity": [
        10, 50, 30, 12, 8,
        25, 15, 20, 7, 14,
        40, 100, 18, 16, 22,
        20, 15, 25, 5, 12,
        4, 6, 60, 18, 10
    ],
    "rating": [
        4.5, 4.2, 4.4, 4.6, 3.9,
        4.3, 4.1, 4.0, 4.7, 4.8,
        4.2, 3.8, 4.4, 4.5, 4.1,
        4.6, 4.0, 4.3, 4.7, 4.2,
        4.5, 3.9, 4.1, 4.4, 4.0
    ],
    "in_stock": [
        True, True, True, True, False,
        True, True, False, True, True,
        True, True, True, True, False,
        True, True, True, False, True,
        False, True, True, True, False
    ],
    "city": [
        "Pune", "Mumbai", "Pune", "Delhi", "Mumbai",
        "Pune", "Delhi", "Pune", "Mumbai", "Pune",
        "Delhi", "Pune", "Mumbai", "Delhi", "Pune",
        "Mumbai", "Pune", "Delhi", "Mumbai", "Pune",
        "Delhi", "Mumbai", "Pune", "Delhi", "Mumbai"
    ]
}
df = pd.DataFrame(product_data)

In [44]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [45]:
df.head()

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai

In [46]:
df.tail(7)

,product_id,product_name,category,price,quantity,rating,in_stock,city
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [47]:
df.shape

(25, 8)

In [48]:
df.columns

Index(['product_id', 'product_name', 'category', 'price', 'quantity', 'rating',
       'in_stock', 'city'],
      dtype='object')

In [49]:
df.describe()

       product_id         price    quantity     rating
count   25.000000     25.000000   25.000000  25.000000
mean   113.000000   9994.000000   22.480000   4.288000
std      7.359801  15038.923942   21.142611   0.280357
min    101.000000    250.000000    4.000000   3.800000
25%    107.000000   1800.000000   10.000000   4.100000
50%    113.000000   2800.000000   16.000000   4.300000
75%    119.000000   8500.000000   25.000000   4.500000
max    125.000000  55000.000000  100.000000   4.800000

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    25 non-null     int64
 1   product_name  25 non-null     object
 2   category      25 non-null     object
 3   price         25 non-null     int64
 4   quantity      25 non-null     int64
 5   rating        25 non-null     float64
 6   in_stock      25 non-null     bool
 7   city          25 non-null     object
dtypes: bool(1), float64(1), int64(3), object(3)
memory usage: 1.5+ KB

In [51]:
df.describe()

       product_id         price    quantity     rating
count   25.000000     25.000000   25.000000  25.000000
mean   113.000000   9994.000000   22.480000   4.288000
std      7.359801  15038.923942   21.142611   0.280357
min    101.000000    250.000000    4.000000   3.800000
25%    107.000000   1800.000000   10.000000   4.100000
50%    113.000000   2800.000000   16.000000   4.300000
75%    119.000000   8500.000000   25.000000   4.500000
max    125.000000  55000.000000  100.000000   4.800000

In [52]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [53]:
df.product_name.dtype

dtype('O')

In [54]:
df.size

200

In [55]:
df["product_name"].count()

np.int64(25)

In [56]:
df["product_name"]

0            Laptop
1             Mouse
2          Keyboard
3           Monitor
4           Printer
5        Headphones
6            Webcam
7           Speaker
8            Tablet
9        Smartphone
10          Charger
11        USB Cable
12       Power Bank
13       Smartwatch
14           Router
15              SSD
16        Hard Disk
17              RAM
18    Graphics Card
19       Microphone
20        Projector
21          Scanner
22         Pendrive
23     Laptop Stand
24      Cooling Pad
Name: product_name, dtype: object

In [58]:
df[["product_name","price","quantity"]].head()

  product_name  price  quantity
0       Laptop  55000        10
1        Mouse    500        50
2     Keyboard   1200        30
3      Monitor  12000        12
4      Printer   8500         8

In [60]:
df.iloc[0:1:1]

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune

In [63]:
df.iloc[0:5:1]

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai

In [68]:
df.iloc[2:9:3]

,product_id,product_name,category,price,quantity,rating,in_stock,city
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai

In [70]:
df.iloc[3:9:1]

,product_id,product_name,category,price,quantity,rating,in_stock,city
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai

In [72]:
df.loc[5,"product_name":"price":2]

product_name    Headphones
price                 1800
Name: 5, dtype: object

In [73]:
df[["product_name","price"]].iloc[4:5:1]

  product_name  price
4      Printer   8500

In [74]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [76]:
df.iloc[0:11:1,0:4:1]

    product_id product_name     category  price
0          101       Laptop  Electronics  55000
1          102        Mouse  Accessories    500
2          103     Keyboard  Accessories   1200
3          104      Monitor  Electronics  12000
4          105      Printer  Electronics   8500
5          106   Headphones  Accessories   1800
6          107       Webcam  Accessories   2500
7          108      Speaker  Accessories   3200
8          109       Tablet  Electronics  22000
9          110   Smartphone  Electronics  45000
10         111      Charger  Accessories    800

In [77]:
df.loc[10]

product_id              111
product_name        Charger
category        Accessories
price                   800
quantity                 40
rating                  4.2
in_stock               True
city                  Delhi
Name: 10, dtype: object

In [78]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [79]:
df.size

200

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    25 non-null     int64
 1   product_name  25 non-null     object
 2   category      25 non-null     object
 3   price         25 non-null     int64
 4   quantity      25 non-null     int64
 5   rating        25 non-null     float64
 6   in_stock      25 non-null     bool
 7   city          25 non-null     object
dtypes: bool(1), float64(1), int64(3), object(3)
memory usage: 1.5+ KB

In [81]:
df.describe()

       product_id         price    quantity     rating
count   25.000000     25.000000   25.000000  25.000000
mean   113.000000   9994.000000   22.480000   4.288000
std      7.359801  15038.923942   21.142611   0.280357
min    101.000000    250.000000    4.000000   3.800000
25%    107.000000   1800.000000   10.000000   4.100000
50%    113.000000   2800.000000   16.000000   4.300000
75%    119.000000   8500.000000   25.000000   4.500000
max    125.000000  55000.000000  100.000000   4.800000

In [82]:
df["price"].mean()

np.float64(9994.0)

In [83]:
df.price.sum()

np.int64(249850)

In [84]:
df.loc[5:12:1]

,product_id,product_name,category,price,quantity,rating,in_stock,city
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai

In [85]:
df.loc[2:8:1,"product_name":"rating":4]

  product_name  rating
2     Keyboard     4.4
3      Monitor     4.6
4      Printer     3.9
5   Headphones     4.3
6       Webcam     4.1
7      Speaker     4.0
8       Tablet     4.7

In [87]:
df.loc[15,"price"]

np.int64(4500)

In [88]:
df[df["price"]>5000]

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai

In [89]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [96]:
df[df["price"]<2000].shape

(8, 8)

In [97]:
df[df["rating"]>=4.5]

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
20,121,Projector,Electronics,28000,4,4.5,False,Delhi

In [98]:
df[df["quantity"]>=20]

,product_id,product_name,category,price,quantity,rating,in_stock,city
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
17,118,RAM,Components,2400,25,4.3,True,Delhi
22,123,Pendrive,Storage,600,60,4.1,True,Pune

In [103]:
a = df.iloc[2:3:1]
b = df.iloc[5:6:1]
c = df.iloc[10:11:1]

In [104]:
pd.concat((a,b,c))

,product_id,product_name,category,price,quantity,rating,in_stock,city
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi

In [105]:
df[df["in_stock"]==True]

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi

In [109]:
df[df["in_stock"]==False].count().head(1)

product_id    6
dtype: int64

In [115]:
df[["product_name","price"]].sort_values("price",ascending=False).tail(1)

   product_name  price
11    USB Cable    250

In [116]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [120]:
df[df["category"]=="Electronics"].head()

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune

In [122]:
df[df["city"]=="Pune"]

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
14,115,Router,Networking,2800,22,4.1,False,Pune
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
22,123,Pendrive,Storage,600,60,4.1,True,Pune

In [124]:
df[df["category"]!="Accessories"].shape

(14, 8)

In [125]:
df[df["price"]==2500]

,product_id,product_name,category,price,quantity,rating,in_stock,city
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi

In [131]:
df[(df["price"]<2000) & (df["category"]=="Electornic")]

Empty DataFrame
Columns: [product_id, product_name, category, price, quantity, rating, in_stock, city]
Index: []

In [132]:
df[(df["price"]>5000) & (df["in_stock"]==True)]

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai

In [133]:
df[(df["rating"]>4.0) & (df["quantity"]>15)]

,product_id,product_name,category,price,quantity,rating,in_stock,city
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
17,118,RAM,Components,2400,25,4.3,True,Delhi
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi

In [134]:
df[(df["city"]=="Pune") | (df["city"]=="Mumbai")]

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [135]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [137]:
df[(df["price"]>1000) & (df["price"]<5000)]

,product_id,product_name,category,price,quantity,rating,in_stock,city
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [139]:
df[(df["category"]=="Storage")| (df["category"]=="Components")]

,product_id,product_name,category,price,quantity,rating,in_stock,city
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune

In [141]:
df[(df["city"]=="Delhi") & (df["rating"]<20)].count().head(1)

product_id    7
dtype: int64

In [143]:
df[(df["in_stock"]==True) & (df["rating"]>4.2) & (df["price"]>10000)]

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune

In [146]:
df[(df["city"]!="Mumbai") & (df["price"]>3000)].shape

(7, 8)

In [147]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,55000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [153]:
df.loc[df["product_name"]=="Laptop","price"]=58000

In [154]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,58000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [158]:
df.loc[df["product_name"]=="Mouse","quantity"]=75

In [159]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,58000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,75,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [160]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,58000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,75,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [161]:
df.head()

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,58000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,75,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai

In [162]:
df.tail()

,product_id,product_name,category,price,quantity,rating,in_stock,city
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [163]:
df.shape

(25, 8)

In [167]:
df.loc[df["product_name"]=="Printer","city"]="Pune"

In [168]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,58000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,75,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Pune
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [170]:
df.loc[df["product_name"]=="Smartphone","rating"]=4.9

In [171]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,58000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,75,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Pune
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,False,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.9,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [174]:
df.loc[df["product_name"]=="Speaker","in_stock"]=True

In [175]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,58000,10,4.5,True,Pune
1,102,Mouse,Accessories,500,75,4.2,True,Mumbai
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi
4,105,Printer,Electronics,8500,8,3.9,False,Pune
5,106,Headphones,Accessories,1800,25,4.3,True,Pune
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi
7,108,Speaker,Accessories,3200,20,4.0,True,Pune
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,45000,14,4.9,True,Pune
10,111,Charger,Accessories,800,40,4.2,True,Delhi
11,112,USB Cable,Accessories,250,100,3.8,True,Pune
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi
14,115,Router,Networking,2800,22,4.1,False,Pune
15,116,SSD,Storage,4500,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune
17,118,RAM,Components,2400,25,4.3,True,Delhi
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai
19,120,Microphone,Accessories,2100,12,4.2,True,Pune
20,121,Projector,Electronics,28000,4,4.5,False,Delhi
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai
22,123,Pendrive,Storage,600,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai

In [183]:
# df[df["price"],"price"]=a
df["price"]=df["price"]+(df["price"]*10/100)

In [184]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city
0,101,Laptop,Electronics,0.0,10,4.5,True,Pune
1,102,Mouse,Accessories,0.0,75,4.2,True,Mumbai
2,103,Keyboard,Accessories,0.0,30,4.4,True,Pune
3,104,Monitor,Electronics,0.0,12,4.6,True,Delhi
4,105,Printer,Electronics,0.0,8,3.9,False,Pune
5,106,Headphones,Accessories,0.0,25,4.3,True,Pune
6,107,Webcam,Accessories,0.0,15,4.1,True,Delhi
7,108,Speaker,Accessories,0.0,20,4.0,True,Pune
8,109,Tablet,Electronics,0.0,7,4.7,True,Mumbai
9,110,Smartphone,Electronics,0.0,14,4.9,True,Pune
10,111,Charger,Accessories,0.0,40,4.2,True,Delhi
11,112,USB Cable,Accessories,0.0,100,3.8,True,Pune
12,113,Power Bank,Accessories,0.0,18,4.4,True,Mumbai
13,114,Smartwatch,Electronics,0.0,16,4.5,True,Delhi
14,115,Router,Networking,0.0,22,4.1,False,Pune
15,116,SSD,Storage,0.0,20,4.6,True,Mumbai
16,117,Hard Disk,Storage,0.0,15,4.0,True,Pune
17,118,RAM,Components,0.0,25,4.3,True,Delhi
18,119,Graphics Card,Components,0.0,5,4.7,False,Mumbai
19,120,Microphone,Accessories,0.0,12,4.2,True,Pune
20,121,Projector,Electronics,0.0,4,4.5,False,Delhi
21,122,Scanner,Electronics,0.0,6,3.9,True,Mumbai
22,123,Pendrive,Storage,0.0,60,4.1,True,Pune
23,124,Laptop Stand,Accessories,0.0,18,4.4,True,Delhi
24,125,Cooling Pad,Accessories,0.0,10,4.0,False,Mumbai

In [188]:
df["Total_value"]=df["price"]*df["quantity"]

In [189]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city,Total_value
0,101,Laptop,Electronics,55000,10,4.5,True,Pune,550000
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai,25000
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune,36000
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi,144000
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai,68000
5,106,Headphones,Accessories,1800,25,4.3,True,Pune,45000
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi,37500
7,108,Speaker,Accessories,3200,20,4.0,False,Pune,64000
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai,154000
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune,630000
10,111,Charger,Accessories,800,40,4.2,True,Delhi,32000
11,112,USB Cable,Accessories,250,100,3.8,True,Pune,25000
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai,27000
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi,104000
14,115,Router,Networking,2800,22,4.1,False,Pune,61600
15,116,SSD,Storage,4500,20,4.6,True,Mumbai,90000
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune,48000
17,118,RAM,Components,2400,25,4.3,True,Delhi,60000
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai,175000
19,120,Microphone,Accessories,2100,12,4.2,True,Pune,25200
20,121,Projector,Electronics,28000,4,4.5,False,Delhi,112000
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai,39000
22,123,Pendrive,Storage,600,60,4.1,True,Pune,36000
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi,32400
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai,22000

In [190]:
df.head()

,product_id,product_name,category,price,quantity,rating,in_stock,city,Total_value
0,101,Laptop,Electronics,55000,10,4.5,True,Pune,550000
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai,25000
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune,36000
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi,144000
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai,68000

In [193]:
df["Discount_price"]=(df["price"]-(df["price"]*15/100))

In [192]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city,Total_value,Discount_price
0,101,Laptop,Electronics,55000,10,4.5,True,Pune,550000,49500.0
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai,25000,450.0
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune,36000,1080.0
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi,144000,10800.0
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai,68000,7650.0
5,106,Headphones,Accessories,1800,25,4.3,True,Pune,45000,1620.0
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi,37500,2250.0
7,108,Speaker,Accessories,3200,20,4.0,False,Pune,64000,2880.0
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai,154000,19800.0
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune,630000,40500.0
10,111,Charger,Accessories,800,40,4.2,True,Delhi,32000,720.0
11,112,USB Cable,Accessories,250,100,3.8,True,Pune,25000,225.0
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai,27000,1350.0
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi,104000,5850.0
14,115,Router,Networking,2800,22,4.1,False,Pune,61600,2520.0
15,116,SSD,Storage,4500,20,4.6,True,Mumbai,90000,4050.0
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune,48000,2880.0
17,118,RAM,Components,2400,25,4.3,True,Delhi,60000,2160.0
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai,175000,31500.0
19,120,Microphone,Accessories,2100,12,4.2,True,Pune,25200,1890.0
20,121,Projector,Electronics,28000,4,4.5,False,Delhi,112000,25200.0
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai,39000,5850.0
22,123,Pendrive,Storage,600,60,4.1,True,Pune,36000,540.0
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi,32400,1620.0
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai,22000,1980.0

In [200]:
df["stock_status"]=""

In [204]:
# for i in df["stock_status"]:
#     if df[df["in_stock"]==True]:
#         df["stock_status"]="Available"

In [205]:
df.rename(columns={"city":"place"})

,product_id,product_name,category,price,quantity,rating,in_stock,place,Total_value,Discount_price,stock_status
0,101,Laptop,Electronics,55000,10,4.5,True,Pune,550000,46750.0,
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai,25000,425.0,
2,103,Keyboard,Accessories,1200,30,4.4,True,Pune,36000,1020.0,
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi,144000,10200.0,
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai,68000,7225.0,
5,106,Headphones,Accessories,1800,25,4.3,True,Pune,45000,1530.0,
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi,37500,2125.0,
7,108,Speaker,Accessories,3200,20,4.0,False,Pune,64000,2720.0,
8,109,Tablet,Electronics,22000,7,4.7,True,Mumbai,154000,18700.0,
9,110,Smartphone,Electronics,45000,14,4.8,True,Pune,630000,38250.0,
10,111,Charger,Accessories,800,40,4.2,True,Delhi,32000,680.0,
11,112,USB Cable,Accessories,250,100,3.8,True,Pune,25000,212.5,
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai,27000,1275.0,
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi,104000,5525.0,
14,115,Router,Networking,2800,22,4.1,False,Pune,61600,2380.0,
15,116,SSD,Storage,4500,20,4.6,True,Mumbai,90000,3825.0,
16,117,Hard Disk,Storage,3200,15,4.0,True,Pune,48000,2720.0,
17,118,RAM,Components,2400,25,4.3,True,Delhi,60000,2040.0,
18,119,Graphics Card,Components,35000,5,4.7,False,Mumbai,175000,29750.0,
19,120,Microphone,Accessories,2100,12,4.2,True,Pune,25200,1785.0,
20,121,Projector,Electronics,28000,4,4.5,False,Delhi,112000,23800.0,
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai,39000,5525.0,
22,123,Pendrive,Storage,600,60,4.1,True,Pune,36000,510.0,
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi,32400,1530.0,
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai,22000,1870.0,

In [211]:
df.loc[(df["price"]>20000) | (df["city"]=="Pune"),"rating"]=5.00

In [212]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city,Total_value,Discount_price,stock_status
0,101,Laptop,Electronics,55000,5,5.0,True,Pune,550000,46750.0,
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai,25000,425.0,
2,103,Keyboard,Accessories,1200,30,5.0,True,Pune,36000,1020.0,
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi,144000,10200.0,
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai,68000,7225.0,
5,106,Headphones,Accessories,1800,25,5.0,True,Pune,45000,1530.0,
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi,37500,2125.0,
7,108,Speaker,Accessories,3200,20,5.0,False,Pune,64000,2720.0,
8,109,Tablet,Electronics,22000,7,5.0,True,Mumbai,154000,18700.0,
9,110,Smartphone,Electronics,45000,5,5.0,True,Pune,630000,38250.0,
10,111,Charger,Accessories,800,40,4.2,True,Delhi,32000,680.0,
11,112,USB Cable,Accessories,250,100,5.0,True,Pune,25000,212.5,
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai,27000,1275.0,
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi,104000,5525.0,
14,115,Router,Networking,2800,22,5.0,False,Pune,61600,2380.0,
15,116,SSD,Storage,4500,20,4.6,True,Mumbai,90000,3825.0,
16,117,Hard Disk,Storage,3200,15,5.0,True,Pune,48000,2720.0,
17,118,RAM,Components,2400,25,4.3,True,Delhi,60000,2040.0,
18,119,Graphics Card,Components,35000,5,5.0,False,Mumbai,175000,29750.0,
19,120,Microphone,Accessories,2100,12,5.0,True,Pune,25200,1785.0,
20,121,Projector,Electronics,28000,4,5.0,False,Delhi,112000,23800.0,
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai,39000,5525.0,
22,123,Pendrive,Storage,600,60,5.0,True,Pune,36000,510.0,
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi,32400,1530.0,
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai,22000,1870.0,

In [213]:
df

,product_id,product_name,category,price,quantity,rating,in_stock,city,Total_value,Discount_price,stock_status
0,101,Laptop,Electronics,55000,5,5.0,True,Pune,550000,46750.0,
1,102,Mouse,Accessories,500,50,4.2,True,Mumbai,25000,425.0,
2,103,Keyboard,Accessories,1200,30,5.0,True,Pune,36000,1020.0,
3,104,Monitor,Electronics,12000,12,4.6,True,Delhi,144000,10200.0,
4,105,Printer,Electronics,8500,8,3.9,False,Mumbai,68000,7225.0,
5,106,Headphones,Accessories,1800,25,5.0,True,Pune,45000,1530.0,
6,107,Webcam,Accessories,2500,15,4.1,True,Delhi,37500,2125.0,
7,108,Speaker,Accessories,3200,20,5.0,False,Pune,64000,2720.0,
8,109,Tablet,Electronics,22000,7,5.0,True,Mumbai,154000,18700.0,
9,110,Smartphone,Electronics,45000,5,5.0,True,Pune,630000,38250.0,
10,111,Charger,Accessories,800,40,4.2,True,Delhi,32000,680.0,
11,112,USB Cable,Accessories,250,100,5.0,True,Pune,25000,212.5,
12,113,Power Bank,Accessories,1500,18,4.4,True,Mumbai,27000,1275.0,
13,114,Smartwatch,Electronics,6500,16,4.5,True,Delhi,104000,5525.0,
14,115,Router,Networking,2800,22,5.0,False,Pune,61600,2380.0,
15,116,SSD,Storage,4500,20,4.6,True,Mumbai,90000,3825.0,
16,117,Hard Disk,Storage,3200,15,5.0,True,Pune,48000,2720.0,
17,118,RAM,Components,2400,25,4.3,True,Delhi,60000,2040.0,
18,119,Graphics Card,Components,35000,5,5.0,False,Mumbai,175000,29750.0,
19,120,Microphone,Accessories,2100,12,5.0,True,Pune,25200,1785.0,
20,121,Projector,Electronics,28000,4,5.0,False,Delhi,112000,23800.0,
21,122,Scanner,Electronics,6500,6,3.9,True,Mumbai,39000,5525.0,
22,123,Pendrive,Storage,600,60,5.0,True,Pune,36000,510.0,
23,124,Laptop Stand,Accessories,1800,18,4.4,True,Delhi,32400,1530.0,
24,125,Cooling Pad,Accessories,2200,10,4.0,False,Mumbai,22000,1870.0,