In [4]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [5]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\advertising_sales.csv")

In [6]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [7]:
x = df[["TV","Radio","Newspaper"]]
y = df["Sales"]

In [8]:
model = LinearRegression()

In [9]:
model.fit(x,y)

LinearRegression()

In [18]:
result = model.predict([[180.8,10.8,58.4]])

print("the sales is a",round(result[0],2))

the sales is a 17.72

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [19]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [21]:
data = {
    "Study_Hours": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    "Attendance": [60, 65, 70, 72, 75, 78, 80, 85, 88, 90, 92, 95],
    "Previous_Score": [50, 55, 60, 62, 65, 68, 70, 75, 78, 82, 85, 90],
    "Final_Score": [55, 60, 65, 68, 72, 75, 80, 85, 88, 92, 95, 98]
}

df = pd.DataFrame(data)

In [22]:
df.head()

   Study_Hours  Attendance  Previous_Score  Final_Score
0            2          60              50           55
1            3          65              55           60
2            4          70              60           65
3            5          72              62           68
4            6          75              65           72

In [24]:
x = df[["Study_Hours","Attendance","Previous_Score"]]
y = df["Final_Score"]

In [25]:
model = LinearRegression()

In [26]:
model.fit(x,y)

LinearRegression()

In [27]:
result = model.predict([[8,85,75]])

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [28]:
result

array([81.80855708])

In [29]:
df

    Study_Hours  Attendance  Previous_Score  Final_Score
0             2          60              50           55
1             3          65              55           60
2             4          70              60           65
3             5          72              62           68
4             6          75              65           72
5             7          78              68           75
6             8          80              70           80
7             9          85              75           85
8            10          88              78           88
9            11          90              82           92
10           12          92              85           95
11           13          95              90           98

In [31]:
study_h = int(input("enter the a study_hours"))
att = int(input("Enter your attendance:-"))
pre_S = int(input("Enter your Previous score"))

result = model.predict([[study_h,att,pre_S]])
result

enter the a study_hours 14
Enter your attendance:- 96
Enter your Previous score 90

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([101.62551845])

In [34]:
data = {
    "Area_sqft": [800, 1000, 1200, 1500, 1800, 2000, 2200, 2500, 2700, 3000, 3200, 3500],
    "Bedrooms": [2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6],
    "House_Age": [20, 18, 15, 12, 10, 8, 7, 5, 4, 3, 2, 1],
    "Distance_km": [15, 14, 12, 10, 9, 8, 7, 6, 5, 4, 3, 2],
    "Price_Lakh": [30, 35, 45, 60, 75, 85, 95, 120, 135, 160, 180, 210]
}
df = pd.DataFrame(data)

In [35]:
df.head()

   Area_sqft  Bedrooms  House_Age  Distance_km  Price_Lakh
0        800         2         20           15          30
1       1000         2         18           14          35
2       1200         3         15           12          45
3       1500         3         12           10          60
4       1800         3         10            9          75

In [37]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [38]:
df.head()

   Area_sqft  Bedrooms  House_Age  Distance_km  Price_Lakh
0        800         2         20           15          30
1       1000         2         18           14          35
2       1200         3         15           12          45
3       1500         3         12           10          60
4       1800         3         10            9          75

In [40]:
x = df[["Area_sqft","Bedrooms","House_Age","Distance_km"]]
y = df["Price_Lakh"]

In [41]:
model = LinearRegression()

In [42]:
model.fit(x,y)

LinearRegression()

In [57]:
result = model.predict([[1500,3,25,10]])
result

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([196.2236204])

In [51]:
df

    Area_sqft  Bedrooms  House_Age  Distance_km  Price_Lakh
0         800         2         20           15          30
1        1000         2         18           14          35
2        1200         3         15           12          45
3        1500         3         12           10          60
4        1800         3         10            9          75
5        2000         4          8            8          85
6        2200         4          7            7          95
7        2500         4          5            6         120
8        2700         5          4            5         135
9        3000         5          3            4         160
10       3200         5          2            3         180
11       3500         6          1            2         210

In [48]:
df

    Area_sqft  Bedrooms  House_Age  Distance_km  Price_Lakh
0         800         2         20           15          30
1        1000         2         18           14          35
2        1200         3         15           12          45
3        1500         3         12           10          60
4        1800         3         10            9          75
5        2000         4          8            8          85
6        2200         4          7            7          95
7        2500         4          5            6         120
8        2700         5          4            5         135
9        3000         5          3            4         160
10       3200         5          2            3         180
11       3500         6          1            2         210

In [58]:
data = {
    "Experience_Years": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "Certifications": [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6],
    "Performance_Rating": [3, 3, 4, 4, 4, 5, 5, 4, 5, 5, 5, 5],
    "Overtime_Hours": [5, 8, 10, 12, 15, 18, 20, 22, 25, 28, 30, 35],
    "Salary_Lakh": [3, 4, 5, 6, 7.5, 9, 11, 13, 15, 18, 20, 23]
}

df = pd.DataFrame(data)

In [59]:
df.head()

,Experience_Years,Certifications,Performance_Rating,Overtime_Hours,Salary_Lakh
0,1,0,3,5,3.0
1,2,1,3,8,4.0
2,3,1,4,10,5.0
3,4,2,4,12,6.0
4,5,2,4,15,7.5

In [61]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [65]:
x = df[["Experience_Years","Certifications","Performance_Rating","Salary_"]]
y = df["Salary_Lakh"]

In [66]:
model = LinearRegression()

In [67]:
model.fit(x,y)

LinearRegression()

In [75]:
result = model.predict([[7.5,4,1,2]])
result

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([-1.86975891])

In [72]:
df

,Experience_Years,Certifications,Performance_Rating,Overtime_Hours,Salary_Lakh
0,1,0,3,5,3.0
1,2,1,3,8,4.0
2,3,1,4,10,5.0
3,4,2,4,12,6.0
4,5,2,4,15,7.5
5,6,3,5,18,9.0
6,7,3,5,20,11.0
7,8,4,4,22,13.0
8,9,4,5,25,15.0
9,10,5,5,28,18.0
10,11,5,5,30,20.0
11,12,6,5,35,23.0

TypeError: can't multiply sequence by non-int of type 'float'

In [77]:

import pandas as pd
import numpy as np

np.random.seed(101)
n = 1000

data = {
    "House_ID": np.arange(1, n + 1).tolist(),

    "Area_sqft": np.random.randint(500, 4001, n).tolist(),

    "Bedrooms": np.random.randint(1, 7, n).tolist(),

    "Bathrooms": np.random.randint(1, 5, n).tolist(),

    "Age_years": np.random.randint(0, 51, n).tolist(),

    "Distance_to_City_km": np.round(
        np.random.uniform(1, 40, n), 1
    ).tolist(),

    "Parking_Spaces": np.random.randint(0, 5, n).tolist(),

    "Floor_Number": np.random.randint(0, 21, n).tolist(),

    "Nearby_Schools": np.random.randint(0, 11, n).tolist(),

    "Crime_Rate": np.round(
        np.random.uniform(1, 10, n), 1
    ).tolist(),

    "Property_Tax": np.random.randint(5000, 50001, n).tolist()
}

# Generate synthetic house prices
noise = np.random.normal(0, 500000, n)

price = (
    800000
    + np.array(data["Area_sqft"]) * 2500
    + np.array(data["Bedrooms"]) * 300000
    + np.array(data["Bathrooms"]) * 200000
    - np.array(data["Age_years"]) * 25000
    - np.array(data["Distance_to_City_km"]) * 20000
    + np.array(data["Parking_Spaces"]) * 150000
    + np.array(data["Floor_Number"]) * 10000
    + np.array(data["Nearby_Schools"]) * 50000
    - np.array(data["Crime_Rate"]) * 40000
    - np.array(data["Property_Tax"]) * 2
    + noise
)

data["Price_INR"] = np.maximum(
    price, 500000
).round(0).astype(int).tolist()

df = pd.DataFrame(data)

print(df.head(10))
print("Dataset shape:", df.shape)
print(df.info())

   House_ID  Area_sqft  Bedrooms  Bathrooms  Age_years  Distance_to_City_km  \
0         1       1363         2          1         50                 32.6
1         2       2047         4          1         14                 20.3
2         3       1861         4          4         21                 18.3
3         4       2099         4          2          8                 32.6
4         5       1099         1          1          2                 18.7
5         6       2545         1          4         39                 28.3
6         7        575         3          4         19                 21.9
7         8       3965         5          1         31                 11.8
8         9       1473         1          2         21                 20.3
9        10       2076         1          4         36                 19.0

   Parking_Spaces  Floor_Number  Nearby_Schools  Crime_Rate  Property_Tax  \
0               0            13               5         4.9         14897
1               2             5               1         3.8         48315
2               3             4               5         6.6         27733
3               1            11               8         7.8         11432
4               2             9              10         8.5         23664
5               2            16              10         1.4         34083
6               0             5               2         7.4         31041
7               0             4               2         1.6         10774
8               0            12               2         1.5         11637
9               3             2               5         7.2         41702

   Price_INR
0    3149117
1    7029165
2    6588531
3    8243562
4    4116641
5    7646726
6    3393739
7   11323609
8    4419896
9    6291531
Dataset shape: (1000, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   House_ID             1000 non-null   int64
 1   Area_sqft            1000 non-null   int64
 2   Bedrooms             1000 non-null   int64
 3   Bathrooms            1000 non-null   int64
 4   Age_years            1000 non-null   int64
 5   Distance_to_City_km  1000 non-null   float64
 6   Parking_Spaces       1000 non-null   int64
 7   Floor_Number         1000 non-null   int64
 8   Nearby_Schools       1000 non-null   int64
 9   Crime_Rate           1000 non-null   float64
 10  Property_Tax         1000 non-null   int64
 11  Price_INR            1000 non-null   int64
dtypes: float64(2), int64(10)
memory usage: 93.9 KB
None

In [78]:
df.head()

,House_ID,Area_sqft,Bedrooms,Bathrooms,Age_years,Distance_to_City_km,Parking_Spaces,Floor_Number,Nearby_Schools,Crime_Rate,Property_Tax,Price_INR
0,1,1363,2,1,50,32.6,0,13,5,4.9,14897,3149117
1,2,2047,4,1,14,20.3,2,5,1,3.8,48315,7029165
2,3,1861,4,4,21,18.3,3,4,5,6.6,27733,6588531
3,4,2099,4,2,8,32.6,1,11,8,7.8,11432,8243562
4,5,1099,1,1,2,18.7,2,9,10,8.5,23664,4116641

In [79]:
df.isnull().sum()

House_ID               0
Area_sqft              0
Bedrooms               0
Bathrooms              0
Age_years              0
Distance_to_City_km    0
Parking_Spaces         0
Floor_Number           0
Nearby_Schools         0
Crime_Rate             0
Property_Tax           0
Price_INR              0
dtype: int64

In [81]:
df.duplicated().sum()

np.int64(0)

In [82]:
df.columns

Index(['House_ID', 'Area_sqft', 'Bedrooms', 'Bathrooms', 'Age_years',
       'Distance_to_City_km', 'Parking_Spaces', 'Floor_Number',
       'Nearby_Schools', 'Crime_Rate', 'Property_Tax', 'Price_INR'],
      dtype='object')

In [84]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [85]:
df

,House_ID,Area_sqft,Bedrooms,Bathrooms,Age_years,Distance_to_City_km,Parking_Spaces,Floor_Number,Nearby_Schools,Crime_Rate,Property_Tax,Price_INR
0,1,1363,2,1,50,32.6,0,13,5,4.9,14897,3149117
1,2,2047,4,1,14,20.3,2,5,1,3.8,48315,7029165
2,3,1861,4,4,21,18.3,3,4,5,6.6,27733,6588531
3,4,2099,4,2,8,32.6,1,11,8,7.8,11432,8243562
4,5,1099,1,1,2,18.7,2,9,10,8.5,23664,4116641
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2475,6,4,34,1.9,0,2,5,2.2,18464,8288056
996,997,3046,4,2,10,30.8,4,17,8,8.7,43898,9973017
997,998,1120,3,1,11,27.0,2,5,0,7.4,12334,3693208
998,999,2105,2,4,0,10.8,4,6,5,4.4,34863,8529851
999,1000,2461,5,4,5,27.5,0,2,4,1.2,24936,8719583

In [117]:
x = df[['Area_sqft', 'Bedrooms', 'Bathrooms']]

In [118]:
y = df["Price_INR"]

In [119]:
model = LinearRegression()

In [120]:
model.fit(x,y)

LinearRegression()

In [121]:
result = model.predict([[2475,6,4]])
result

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([8976641.2873289])

In [122]:
df.loc[995]

House_ID                   996
Area_sqft                 2475
Bedrooms                     6
Bathrooms                    4
Age_years                   34
Distance_to_City_km          1
Parking_Spaces               0
Floor_Number                 2
Nearby_Schools               5
Crime_Rate                   2
Property_Tax             18464
Price_INR              8288056
Name: 995, dtype: int64

In [123]:
df.loc[10000]

KeyError: 10000

In [125]:
# import importent libraries
# then load your data
# then extract you data in dataframe
# then decide the a columns x and y 
# then model extract
# then a predict
# give the output for the model 

# y = m*(x)+c

In [126]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\healthcare_dirty_dataset_5080_rows.csv")

In [127]:
df.head()

,Patient_ID,Name,Age,Gender,City,Department,Diagnosis,Admission_Date,Discharge_Date,Length_of_Stay,Bill_Amount,Insurance_Type,Medication,Readmission_30_Days,Patient_Status,Doctor_ID,Satisfaction_Score,Follow_Up_Required
0,P104269,Kunal Yadav,68.0,Female,Mumbai,Emergency,Diabetes,2024-03-22,2024-03-25,7,20687.41,NaN,Paracetamol,No,Deceased,D121,3.0,Yes
1,P100019,Priya Sharma,2.0,Female,Nashik,Dermatology,Anemia,2023-03-24,2023-03-28,2,4307.58,Corporate,Salbutamol,No,Under Treatment,D163,2.0,Yes
2,P101856,ananya kulkarni,48.0,Male,Nashik,Emergency,Arthritis,2025-08-09,2025-08-18,20,10409.66,Corporate,Salbutamol,No,Under Treatment,D108,1.0,Yes
3,P100275,Amit Pardeshi,1.0,Female,Dhule,Orthopedics,Migraine,2023-11-08,2023-11-23,17,NaN,Private,Paracetamol,Yes,Under Treatment,D115,2.0,Yes
4,P101023,Kavya Kulkarni,23.0,Female,Nashik,Cardiology,Asthma,2023-05-30,2023-06-14,11,18782.02,Corporate,Paracetamol,Yes,Recovered,D151,2.0,No

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5080 entries, 0 to 5079
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient_ID           5080 non-null   object
 1   Name                 4908 non-null   object
 2   Age                  4892 non-null   object
 3   Gender               5005 non-null   object
 4   City                 4886 non-null   object
 5   Department           4955 non-null   object
 6   Diagnosis            4830 non-null   object
 7   Admission_Date       4995 non-null   object
 8   Discharge_Date       4978 non-null   object
 9   Length_of_Stay       5080 non-null   int64
 10  Bill_Amount          4869 non-null   object
 11  Insurance_Type       4901 non-null   object
 12  Medication           4324 non-null   object
 13  Readmission_30_Days  5080 non-null   object
 14  Patient_Status       4977 non-null   object
 15  Doctor_ID            5080 non-null   object
 16  Satisfaction_Score   4770 non-null   object
 17  Follow_Up_Required   5080 non-null   object
dtypes: int64(1), object(17)
memory usage: 714.5+ KB

In [139]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [143]:
df["Age"] = df["Age"].astype("Int64")

In [146]:
df["Age"].isnull().sum()

np.int64(202)

In [148]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [152]:
df["Age"].describe()

count       5080.0
mean     47.227756
std       27.04693
min           -5.0
25%           24.0
50%           47.0
75%           69.0
max          130.0
Name: Age, dtype: Float64

In [160]:
Q1=24.0
Q3=69.0
IQR = Q3-Q1
lower = Q1-1.5*(IQR)
higher = Q3+1.5*(IQR)

higher

136.5

In [158]:
df[(df["Age"]<lower)&(df["Age"]>higher)]

Empty DataFrame
Columns: [Patient_ID, Name, Age, Gender, City, Department, Diagnosis, Admission_Date, Discharge_Date, Length_of_Stay, Bill_Amount, Insurance_Type, Medication, Readmission_30_Days, Patient_Status, Doctor_ID, Satisfaction_Score, Follow_Up_Required]
Index: []

In [161]:
df["Age"]

0       68
1        2
2       48
3        1
4       23
        ..
5075    54
5076    47
5077    26
5078    39
5079    74
Name: Age, Length: 5080, dtype: Int64

In [162]:
df.columns

Index(['Patient_ID', 'Name', 'Age', 'Gender', 'City', 'Department',
       'Diagnosis', 'Admission_Date', 'Discharge_Date', 'Length_of_Stay',
       'Bill_Amount', 'Insurance_Type', 'Medication', 'Readmission_30_Days',
       'Patient_Status', 'Doctor_ID', 'Satisfaction_Score',
       'Follow_Up_Required'],
      dtype='object')

In [165]:
df['Length_of_Stay'].describe()

count    5080.000000
mean       11.027362
std         6.023861
min         1.000000
25%         6.000000
50%        11.000000
75%        16.000000
max        21.000000
Name: Length_of_Stay, dtype: float64

In [166]:
Q1 = 6.00
Q3 = 16.00

IQR1 = Q3-Q1

lower = Q1-1.5*(IQR1)
higher = Q3+1.5*(IQR1)

df[(df['Length_of_Stay']<lower)|(df['Length_of_Stay']>higher)]

Empty DataFrame
Columns: [Patient_ID, Name, Age, Gender, City, Department, Diagnosis, Admission_Date, Discharge_Date, Length_of_Stay, Bill_Amount, Insurance_Type, Medication, Readmission_30_Days, Patient_Status, Doctor_ID, Satisfaction_Score, Follow_Up_Required]
Index: []

In [167]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [201]:
x  = df[["Age"]]
y = df['Bill_Amount']

In [206]:
model = LinearRegression()

In [207]:
model.fit(x,y)

LinearRegression()

In [222]:
result1 = model.predict([[130]])
result1

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([12168.21020806])

In [219]:
df[df['Age']==130]

,Patient_ID,Name,Age,Gender,City,Department,Diagnosis,Admission_Date,Discharge_Date,Length_of_Stay,Bill_Amount,Insurance_Type,Medication,Readmission_30_Days,Patient_Status,Doctor_ID,Satisfaction_Score,Follow_Up_Required
163,P100615,Isha Pawar,130,Male,Kolhapur,Orthopedics,Pneumonia,2023-10-05,2023-10-05,7,13052.340000,Government,Aspirin,Yes,Under Treatment,D150,2.0,No
572,P102300,NaN,130,Male,Navi Mumbai,Neurology,NaN,2026-08-27,2026-09-01,16,10748.780000,Corporate,Insulin,No,Under Treatment,D177,4.0,Yes
859,P102965,Riya Shinde,130,Female,Nashik,General Medicine,Diabetes,2022-09-07,2022-09-09,20,6909.220000,Government,Salbutamol,No,Discharged,D188,1.0,Yes
1063,P100808,NaN,130,Male,Solapur,Pediatrics,Diabetes,2024-03-07,2024-03-17,10,8782.170000,Private,Ibuprofen,No,Discharged,D123,4.0,Yes
1304,P103879,Riya Shinde,130,Male,Pune,Neurology,Migraine,2022-08-05,2022-08-13,21,10747.900000,Self-pay,Paracetamol,Yes,Recovered,D139,3.0,Yes
1961,P103418,tanvi joshi,130,Male,Aurangabad,Dermatology,Heart Disease,2024-09-07,2024-09-08,13,20420.380000,Self-pay,Insulin,No,Recovered,D116,4.0,No
2207,P102927,Ananya Khan,130,Male,Navi Mumbai,Orthopedics,NaN,2022-12-21,2022-12-27,6,12715.178381,Private,NaN,No,Discharged,D181,2.0,No
2824,P101280,Isha Pardeshi,130,Female,Aurangabad,Pediatrics,Arthritis,2025-07-14,2025-07-18,5,6609.590000,Private,NaN,No,Recovered,D191,1.0,Yes
2836,P103879,Riya Shinde,130,Male,Pune,Neurology,Migraine,2022-08-05,2022-08-13,21,10747.900000,Self-pay,Paracetamol,Yes,Recovered,D139,3.0,Yes
4175,P103847,NaN,130,Female,Aurangabad,Cardiology,Migraine,2024-11-03,2024-11-03,1,12715.178381,Government,Paracetamol,Yes,Discharged,D100,5.0,No

df["Bill_Amount"] = pd.to_numeric(df["Bill_Amount"],errors="coerce")

# df["Bill_Amount"].fillna(df["Bill_Amount"].mean())

In [196]:
df["Bill_Amount"] = df["Bill_Amount"].astype("Int64")

TypeError: cannot safely cast non-equivalent object to int64

In [200]:
df["Bill_Amount"] = df["Bill_Amount"].fillna(df["Bill_Amount"].mean())

#######Roshan

######Roshan

###### Roshan

In [221]:
df

,Patient_ID,Name,Age,Gender,City,Department,Diagnosis,Admission_Date,Discharge_Date,Length_of_Stay,Bill_Amount,Insurance_Type,Medication,Readmission_30_Days,Patient_Status,Doctor_ID,Satisfaction_Score,Follow_Up_Required
0,P104269,Kunal Yadav,68,Female,Mumbai,Emergency,Diabetes,2024-03-22,2024-03-25,7,20687.410000,NaN,Paracetamol,No,Deceased,D121,3.0,Yes
1,P100019,Priya Sharma,2,Female,Nashik,Dermatology,Anemia,2023-03-24,2023-03-28,2,4307.580000,Corporate,Salbutamol,No,Under Treatment,D163,2.0,Yes
2,P101856,ananya kulkarni,48,Male,Nashik,Emergency,Arthritis,2025-08-09,2025-08-18,20,10409.660000,Corporate,Salbutamol,No,Under Treatment,D108,1.0,Yes
3,P100275,Amit Pardeshi,1,Female,Dhule,Orthopedics,Migraine,2023-11-08,2023-11-23,17,12715.178381,Private,Paracetamol,Yes,Under Treatment,D115,2.0,Yes
4,P101023,Kavya Kulkarni,23,Female,Nashik,Cardiology,Asthma,2023-05-30,2023-06-14,11,18782.020000,Corporate,Paracetamol,Yes,Recovered,D151,2.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5075,P104298,Rohan Yadav,54,Female,Nagpur,Orthopedics,Diabetes,2025-11-22,2025-12-07,12,3147.750000,NaN,Salbutamol,Yes,Discharged,D108,4.0,No
5076,P104706,Neha Chavan,47,Female,Thane,Oncology,Anemia,2023-06-17,2023-06-29,9,13888.170000,Self-pay,Metformin,No,Recovered,D181,1.0,Yes
5077,P101144,Riya Pardeshi,26,Male,Aurangabad,Cardiology,Migraine,2023-08-03,2023-08-11,12,6202.400000,Government,Metformin,Yes,Recovered,D170,5.0,No
5078,P100048,Kunal Deshmukh,39,Female,Navi Mumbai,Cardiology,Anemia,2022-07-29,2022-08-02,16,7479.370000,Self-pay,NaN,No,Recovered,D135,3.0,Yes
5079,P100772,Amit Patil,74,Male,Dhule,Emergency,Asthma,2024-04-14,2024-04-21,4,9255.970000,Private,NaN,No,Recovered,D123,1.0,No

In [225]:
df["Gender"].value_counts()

Gender
Female        2391
Male          2391
Other          101
  male          62
  female        58
  other          2
Name: count, dtype: int64