In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\healthcare_patient_dirty_practice.csv")

In [3]:
df.head()

,patient_id,age,gender,diagnosis,systolic_bp,diastolic_bp,glucose_mg_dl,bmi,risk_group,treatment_cost_inr,visit_date,city
0,1,45,Female,Hypertension,145.0,92.0,98.0,29.4,High,7800.0,2025-01-05,Pune
1,2,62,Male,Diabetes,160.0,100.0,145.0,31.2,High,12500.0,2025-01-06,Mumbai
2,3,37,Female,Asthma,118.0,76.0,82.0,24.1,Normal,4300.0,2025-01-07,Nashik
3,4,54,Male,Hypertension,150.0,95.0,105.0,28.7,High,9100.0,2025-01-08,Pune
4,5,29,Female,Migraine,112.0,72.0,76.0,22.8,Normal,2500.0,2025-01-09,Nagpur

In [4]:
df.head(10)

,patient_id,age,gender,diagnosis,systolic_bp,diastolic_bp,glucose_mg_dl,bmi,risk_group,treatment_cost_inr,visit_date,city
0,1,45,Female,Hypertension,145.0,92.0,98.0,29.4,High,7800.0,2025-01-05,Pune
1,2,62,Male,Diabetes,160.0,100.0,145.0,31.2,High,12500.0,2025-01-06,Mumbai
2,3,37,Female,Asthma,118.0,76.0,82.0,24.1,Normal,4300.0,2025-01-07,Nashik
3,4,54,Male,Hypertension,150.0,95.0,105.0,28.7,High,9100.0,2025-01-08,Pune
4,5,29,Female,Migraine,112.0,72.0,76.0,22.8,Normal,2500.0,2025-01-09,Nagpur
5,6,68,Male,Diabetes,170.0,105.0,152.0,33.5,High,14800.0,2025-01-10,Mumbai
6,7,41,Female,Asthma,122.0,80.0,88.0,25.3,Normal,5100.0,2025-01-11,Pune
7,8,50,Male,Hypertension,155.0,98.0,110.0,30.1,High,10200.0,2025-01-12,Nashik
8,9,33,Female,Migraine,108.0,70.0,72.0,21.9,Normal,2800.0,2025-01-13,Mumbai
9,10,59,Male,Diabetes,165.0,102.0,148.0,32.4,High,13200.0,2025-01-14,Pune

In [5]:
df1 = pd.read_csv(r"C:\Users\Admin\Downloads\retail_sales_dirty_practice.csv")

In [6]:
df1.head()

,order_id,product,category,unit_price,quantity,city,order_date,sales_channel
0,1,Laptop,Electronics,55000.0,2.0,Pune,2026-01-05,Online
1,2,Phone,Electronics,25000.0,3.0,Mumbai,2026-01-06,Store
2,3,Desk Chair,Furniture,8500.0,1.0,Pune,2026-01-07,Online
3,4,Headphones,Electronics,2200.0,5.0,Nashik,2026-01-08,Online
4,5,Notebook,Stationery,80.0,20.0,Nagpur,2026-01-09,Store

In [11]:
df1["product"].apply(lambda x:x.split()[0])

0         Laptop
1          Phone
2           Desk
3     Headphones
4       Notebook
5        Monitor
6         Office
7            Pen
8         Tablet
9       Backpack
10      Keyboard
11         Mouse
12         Water
13     Bookshelf
14           USB
15       Printer
16          Sofa
17    Calculator
18         Smart
19        Webcam
20        Laptop
21         Phone
22          Desk
23    Headphones
24      Notebook
25       Monitor
26        Office
27           Pen
28        Tablet
29      Backpack
30      Keyboard
31         Mouse
32         Water
33     Bookshelf
34           USB
35       Printer
36          Sofa
37    Calculator
38         Smart
39        Webcam
40        Laptop
41           Air
42        Gaming
43           Pen
44          Desk
45      External
Name: product, dtype: object

In [40]:
df3 = pd.read_csv(r"C:\Users\Admin\Downloads\employee_data_practice_dirty1.csv")

In [13]:
df3.head()

,Unnamed: 0,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years
0,0,1001,Aarav Sharma,24,Male,IT,42000,4.2,Pune,2023-06-12,2.0
1,1,1002,Priya Patil,27,Female,HR,38000,4.5,Mumbai,2021-03-08,5.0
2,2,1003,Rahul Deshmukh,31,Male,Finance,56000,3.8,Pune,2019-11-20,8.0
3,3,1004,Sneha Joshi,23,Female,IT,45000,4.7,Nashik,2024-01-15,1.0
4,4,1005,Vikram More,29,Male,Sales,39000,3.5,Mumbai,2020-07-01,6.0

In [39]:
df3["name"].apply(lambda x:x.split()[0])

0         Aarav
1         Priya
2         Rahul
3         Sneha
4        Vikram
5            Om
6          Isha
7         Kunal
8         Pooja
9         Sahil
10         Riya
11         Yash
12         Neha
13        Rohan
14        Tanvi
15       Nikhil
16        Aditi
17        Kavya
18          Dev
19         Sana
20        Arjun
21       Mitali
22    Siddharth
23         Diya
25        Irfan
26         Ritu
Name: name, dtype: object

In [33]:
df3.isnull().sum()

Unnamed: 0           0
employee_id          0
name                 0
age                  0
gender               0
department           0
salary               0
performance_score    0
location             0
joining_date         0
experience_years     0
dtype: int64

In [38]:
df3.drop(24,inplace=True)

In [43]:
df3.loc[24]

Unnamed: 0                   30
employee_id                1032
name
age                          26
gender                   Female
department                  IT
salary                    47000
performance_score           4.2
location                   Pune
joining_date         2022-05-17
experience_years            4.0
Name: 24, dtype: object

In [54]:
df3.loc[df3["name"]=="         "]

Empty DataFrame
Columns: [Unnamed: 0, employee_id, name, age, gender, department, salary, performance_score, location, joining_date, experience_years]
Index: []

In [52]:
df3["name"]

0       Aarav Sharma
1        Priya Patil
2     Rahul Deshmukh
3        Sneha Joshi
4        Vikram More
5           Om Pawar
6          Isha Shah
7       Kunal Jadhav
8         Pooja Sane
9       Sahil Chavan
10      Riya Bhosale
11       Yash Thakur
12        Neha Pawar
13      Rohan Shinde
14     Tanvi Gokhale
15      Nikhil Patil
16       Aditi Desai
17        Kavya More
18      Dev Kulkarni
19         Sana Khan
20        Arjun Nair
21       Mitali Shah
22    Siddharth Kale
23        Diya Pawar
24
25      Irfan Shaikh
26        Ritu Pawar
Name: name, dtype: object

In [55]:
df3.name

0       Aarav Sharma
1        Priya Patil
2     Rahul Deshmukh
3        Sneha Joshi
4        Vikram More
5           Om Pawar
6          Isha Shah
7       Kunal Jadhav
8         Pooja Sane
9       Sahil Chavan
10      Riya Bhosale
11       Yash Thakur
12        Neha Pawar
13      Rohan Shinde
14     Tanvi Gokhale
15      Nikhil Patil
16       Aditi Desai
17        Kavya More
18      Dev Kulkarni
19         Sana Khan
20        Arjun Nair
21       Mitali Shah
22    Siddharth Kale
23        Diya Pawar
24
25      Irfan Shaikh
26        Ritu Pawar
Name: name, dtype: object

In [56]:
df3.head()

,Unnamed: 0,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years
0,0,1001,Aarav Sharma,24,Male,IT,42000,4.2,Pune,2023-06-12,2.0
1,1,1002,Priya Patil,27,Female,HR,38000,4.5,Mumbai,2021-03-08,5.0
2,2,1003,Rahul Deshmukh,31,Male,Finance,56000,3.8,Pune,2019-11-20,8.0
3,3,1004,Sneha Joshi,23,Female,IT,45000,4.7,Nashik,2024-01-15,1.0
4,4,1005,Vikram More,29,Male,Sales,39000,3.5,Mumbai,2020-07-01,6.0

In [64]:

df3["name"].apply(lambda x:x if len(x)==1 else "false")

0     false
1     false
2     false
3     false
4     false
5     false
6     false
7     false
8     false
9     false
10    false
11    false
12    false
13    false
14    false
15    false
16    false
17    false
18    false
19    false
20    false
21    false
22    false
23    false
24    false
25    false
26    false
Name: name, dtype: object

In [65]:
df3.loc[24]

Unnamed: 0                   30
employee_id                1032
name
age                          26
gender                   Female
department                  IT
salary                    47000
performance_score           4.2
location                   Pune
joining_date         2022-05-17
experience_years            4.0
Name: 24, dtype: object

In [68]:
df3.loc[df3["name"]==df3["name"].empty]

Empty DataFrame
Columns: [Unnamed: 0, employee_id, name, age, gender, department, salary, performance_score, location, joining_date, experience_years]
Index: []

In [70]:
df3["name"]=df3["name"].str.strip()

In [72]:
df3.isnull().sum()

Unnamed: 0           0
employee_id          0
name                 0
age                  0
gender               0
department           0
salary               0
performance_score    0
location             0
joining_date         0
experience_years     0
dtype: int64

In [74]:
df3 = df3.dropna(subset=["name"])

In [75]:
df3

,Unnamed: 0,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years
0,0,1001,Aarav Sharma,24,Male,IT,42000,4.2,Pune,2023-06-12,2.0
1,1,1002,Priya Patil,27,Female,HR,38000,4.5,Mumbai,2021-03-08,5.0
2,2,1003,Rahul Deshmukh,31,Male,Finance,56000,3.8,Pune,2019-11-20,8.0
3,3,1004,Sneha Joshi,23,Female,IT,45000,4.7,Nashik,2024-01-15,1.0
4,4,1005,Vikram More,29,Male,Sales,39000,3.5,Mumbai,2020-07-01,6.0
5,6,1007,Om Pawar,35,Male,Operations,61000,4.1,Nagpur,2017-02-17,11.0
6,7,1008,Isha Shah,32,Female,HR,41000,4.1,Mumbai,2023-08-22,2.0
7,8,1009,Kunal Jadhav,28,Male,Finance,52000,3.9,Pune,2020-12-05,6.0
8,11,1012,Pooja Sane,32,Female,Finance,59000,4.8,Pune,2018-05-19,9.0
9,12,1013,Sahil Chavan,22,Male,Sales,32000,3.2,Nagpur,2024-07-01,1.0
10,13,1014,Riya Bhosale,28,Female,Operations,50000,4.4,Mumbai,2020-02-14,6.0
11,14,1015,Yash Thakur,33,Male,IT,68000,4.1,Pune,2016-10-30,12.0
12,15,1016,Neha Pawar,24,Female,HR,36000,4.0,Nashik,2023-02-02,2.0
13,16,1017,Rohan Shinde,27,Male,Finance,54000,3.7,Nagpur,2021-06-16,5.0
14,17,1018,Tanvi Gokhale,29,Female,Sales,46000,4.6,Pune,2019-09-09,7.0
15,18,1019,Nikhil Patil,26,Male,Operations,48000,3.6,Mumbai,2022-01-24,4.0
16,19,1020,Aditi Desai,31,Female,IT,63000,4.9,Pune,2018-12-12,9.0
17,21,1022,Kavya More,25,Female,Sales,37000,3.8,Nagpur,2022-11-07,3.0
18,22,1023,Dev Kulkarni,28,Male,IT,51000,4.3,Pune,2021-08-18,5.0
19,23,1024,Sana Khan,34,Female,Operations,58000,4.1,Mumbai,2017-04-03,10.0
20,24,1025,Arjun Nair,23,Male,Sales,33000,3.4,Nashik,2024-02-20,1.0
21,25,1026,Mitali Shah,27,Female,Finance,55000,4.5,Pune,2020-06-29,6.0
22,26,1027,Siddharth Kale,30,Male,IT,62000,4.0,Nagpur,2018-07-13,8.0
23,29,1031,Diya Pawar,32,Female,Marketing,43000,4.1,Kolhapur,2023-10-01,3.0
24,30,1032,,26,Female,IT,47000,4.2,Pune,2022-05-17,4.0
25,31,1033,Irfan Shaikh,29,Female,Marketing,49000,3.9,Aurangabad,2021-02-08,5.0
26,32,1034,Ritu Pawar,28,Female,HR,41000,4.1,Mumbai,2023-08-22,2.0

In [79]:
df3["name"] = df3["name"].apply(lambda x:x.upper())

In [80]:
df3["name"]

0       AARAV SHARMA
1        PRIYA PATIL
2     RAHUL DESHMUKH
3        SNEHA JOSHI
4        VIKRAM MORE
5           OM PAWAR
6          ISHA SHAH
7       KUNAL JADHAV
8         POOJA SANE
9       SAHIL CHAVAN
10      RIYA BHOSALE
11       YASH THAKUR
12        NEHA PAWAR
13      ROHAN SHINDE
14     TANVI GOKHALE
15      NIKHIL PATIL
16       ADITI DESAI
17        KAVYA MORE
18      DEV KULKARNI
19         SANA KHAN
20        ARJUN NAIR
21       MITALI SHAH
22    SIDDHARTH KALE
23        DIYA PAWAR
24
25      IRFAN SHAIKH
26        RITU PAWAR
Name: name, dtype: object

In [82]:
import numpy as np

df3["name"] = df3["name"].str.strip().replace("", np.nan)

In [84]:
df3["name"].dropna()

0       AARAV SHARMA
1        PRIYA PATIL
2     RAHUL DESHMUKH
3        SNEHA JOSHI
4        VIKRAM MORE
5           OM PAWAR
6          ISHA SHAH
7       KUNAL JADHAV
8         POOJA SANE
9       SAHIL CHAVAN
10      RIYA BHOSALE
11       YASH THAKUR
12        NEHA PAWAR
13      ROHAN SHINDE
14     TANVI GOKHALE
15      NIKHIL PATIL
16       ADITI DESAI
17        KAVYA MORE
18      DEV KULKARNI
19         SANA KHAN
20        ARJUN NAIR
21       MITALI SHAH
22    SIDDHARTH KALE
23        DIYA PAWAR
25      IRFAN SHAIKH
26        RITU PAWAR
Name: name, dtype: object

In [91]:
df.dropna(inplace = True)

In [89]:
df.shape

(70, 12)

In [92]:
df.shape

(62, 12)

In [93]:
df

,patient_id,age,gender,diagnosis,systolic_bp,diastolic_bp,glucose_mg_dl,bmi,risk_group,treatment_cost_inr,visit_date,city
0,1,45,Female,Hypertension,145.0,92.0,98.0,29.4,High,7800.0,2025-01-05,Pune
1,2,62,Male,Diabetes,160.0,100.0,145.0,31.2,High,12500.0,2025-01-06,Mumbai
2,3,37,Female,Asthma,118.0,76.0,82.0,24.1,Normal,4300.0,2025-01-07,Nashik
3,4,54,Male,Hypertension,150.0,95.0,105.0,28.7,High,9100.0,2025-01-08,Pune
4,5,29,Female,Migraine,112.0,72.0,76.0,22.8,Normal,2500.0,2025-01-09,Nagpur
...,...,...,...,...,...,...,...,...,...,...,...,...
65,66,51,Male,Hypertension,153.0,97.0,109.0,30.0,High,9900.0,2025-03-11,Mumbai
66,67,34,Female,Migraine,107.0,69.0,71.0,21.8,Normal,2600.0,2025-03-12,Nashik
67,68,67,Male,Diabetes,171.0,107.0,156.0,34.5,High,15200.0,2025-03-13,Pune
68,69,44,Female,Asthma,125.0,82.0,91.0,26.1,Normal,5300.0,2025-03-14,Nagpur
69,70,56,Male,Hypertension,158.0,99.0,112.0,30.8,High,10500.0,2025-03-15,Mumbai

In [95]:
df.duplicated().sum()

np.int64(0)

In [96]:
df.drop_duplicates()

,patient_id,age,gender,diagnosis,systolic_bp,diastolic_bp,glucose_mg_dl,bmi,risk_group,treatment_cost_inr,visit_date,city
0,1,45,Female,Hypertension,145.0,92.0,98.0,29.4,High,7800.0,2025-01-05,Pune
1,2,62,Male,Diabetes,160.0,100.0,145.0,31.2,High,12500.0,2025-01-06,Mumbai
2,3,37,Female,Asthma,118.0,76.0,82.0,24.1,Normal,4300.0,2025-01-07,Nashik
3,4,54,Male,Hypertension,150.0,95.0,105.0,28.7,High,9100.0,2025-01-08,Pune
4,5,29,Female,Migraine,112.0,72.0,76.0,22.8,Normal,2500.0,2025-01-09,Nagpur
...,...,...,...,...,...,...,...,...,...,...,...,...
65,66,51,Male,Hypertension,153.0,97.0,109.0,30.0,High,9900.0,2025-03-11,Mumbai
66,67,34,Female,Migraine,107.0,69.0,71.0,21.8,Normal,2600.0,2025-03-12,Nashik
67,68,67,Male,Diabetes,171.0,107.0,156.0,34.5,High,15200.0,2025-03-13,Pune
68,69,44,Female,Asthma,125.0,82.0,91.0,26.1,Normal,5300.0,2025-03-14,Nagpur
69,70,56,Male,Hypertension,158.0,99.0,112.0,30.8,High,10500.0,2025-03-15,Mumbai

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62 entries, 0 to 69
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          62 non-null     int64
 1   age                 62 non-null     int64
 2   gender              62 non-null     object
 3   diagnosis           62 non-null     object
 4   systolic_bp         62 non-null     float64
 5   diastolic_bp        62 non-null     float64
 6   glucose_mg_dl       62 non-null     float64
 7   bmi                 62 non-null     float64
 8   risk_group          62 non-null     object
 9   treatment_cost_inr  62 non-null     float64
 10  visit_date          62 non-null     object
 11  city                62 non-null     object
dtypes: float64(5), int64(2), object(5)
memory usage: 6.3+ KB

In [98]:
df["visit_date"] = pd.to_datetime(df["visit_date"])

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62 entries, 0 to 69
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          62 non-null     int64
 1   age                 62 non-null     int64
 2   gender              62 non-null     object
 3   diagnosis           62 non-null     object
 4   systolic_bp         62 non-null     float64
 5   diastolic_bp        62 non-null     float64
 6   glucose_mg_dl       62 non-null     float64
 7   bmi                 62 non-null     float64
 8   risk_group          62 non-null     object
 9   treatment_cost_inr  62 non-null     float64
 10  visit_date          62 non-null     datetime64[ns]
 11  city                62 non-null     object
dtypes: datetime64[ns](1), float64(5), int64(2), object(4)
memory usage: 6.3+ KB

In [102]:
df["visit_date"].dtypes

dtype('<M8[ns]')

In [103]:
df.dtypes

patient_id                     int64
age                            int64
gender                        object
diagnosis                     object
systolic_bp                  float64
diastolic_bp                 float64
glucose_mg_dl                float64
bmi                          float64
risk_group                    object
treatment_cost_inr           float64
visit_date            datetime64[ns]
city                          object
dtype: object

In [130]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\online_course_sale_dataset.csv")

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       20 non-null     int64
 1   student_name   20 non-null     object
 2   course_name    20 non-null     object
 3   category       20 non-null     object
 4   price          20 non-null     int64
 5   purchase_date  20 non-null     object
 6   rating         20 non-null     int64
 7   country        20 non-null     object
dtypes: int64(3), object(5)
memory usage: 1.4+ KB

In [109]:
df.describe(include="object")

        student_name           course_name     category purchase_date country
count             20                    20           20            20      20
unique            20                    20            6            20       6
top     Anita Sharma  Python for Beginners  Programming    12-06-2021   India
freq               1                     1            5             1      10

In [111]:
df["student_name"].unique().shape

(20,)

In [112]:
df.head()

,order_id,student_name,course_name,category,price,purchase_date,rating,country
0,101,Anita Sharma,Python for Beginners,Programming,1200,12-06-2021,4,India
1,102,Rohan Patil,Data Science Bootcamp,Data Science,3500,22-03-2020,5,India
2,103,Meera Gupta,Digital Marketing 101,Marketing,1500,05-11-2022,3,USA
3,104,John Lewis,Web Development Mastery,Programming,2500,19-01-2023,4,UK
4,105,Aisha Khan,Machine Learning A-Z,Data Science,4000,17-09-2021,5,UAE

In [113]:
df.loc[df["country"]=="India","country"]="INDIA"

In [129]:
df

0    2021-06-12
1    2020-03-22
2    2022-11-05
3    2023-01-19
4    2021-09-17
5    2020-12-28
6    2023-02-11
7    2021-04-14
8    2022-07-25
9    2020-10-09
10   2023-03-02
11   2021-08-01
12   2022-01-15
13   2023-04-18
14   2021-05-20
15   2020-11-11
16   2022-03-03
17   2023-01-05
18   2022-05-09
19   2021-06-03
Name: purchase_date, dtype: datetime64[ns]

In [131]:
df["purchase_date"] = pd.to_datetime(df["purchase_date"],format="%d-%m-%Y")

In [132]:
df.loc[(df["purchase_date"].dt.year==2023) & (df["purchase_date"].dt.month==3)]

,order_id,student_name,course_name,category,price,purchase_date,rating,country
10,111,Nancy Wilson,UI/UX Masterclass,Design,2600,2023-03-02,5,USA

In [133]:
df.describe(include="object")

        student_name           course_name     category country
count             20                    20           20      20
unique            20                    20            6       6
top     Anita Sharma  Python for Beginners  Programming   India
freq               1                     1            5      10

In [135]:
df.describe()

        order_id        price        purchase_date     rating
count   20.00000    20.000000                   20  20.000000
mean   110.50000  2092.500000  2021-12-18 06:00:00   4.200000
min    101.00000   800.000000  2020-03-22 00:00:00   3.000000
25%    105.75000  1275.000000  2021-05-11 00:00:00   4.000000
50%    110.50000  1900.000000  2021-11-16 00:00:00   4.000000
75%    115.25000  2625.000000  2022-11-20 06:00:00   5.000000
max    120.00000  4500.000000  2023-04-18 00:00:00   5.000000
std      5.91608  1052.850142                  NaN   0.767772

In [141]:
c = str(20210511000000)
df.loc[df["purchase_date"]==c]

Empty DataFrame
Columns: [order_id, student_name, course_name, category, price, purchase_date, rating, country]
Index: []

In [180]:
import pandas as pd
import numpy as np

data = {
    "employee_id": [
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        101, 122, 123, 124, 125, 126, 127, 128, 129, 130
    ],

    "name": [
        "Aarav Sharma", "Priya Patil", "Rahul Deshmukh", "",
        "Sneha Joshi", "Vikram More", "Om Pawar", "Isha Shah",
        "Kunal Jadhav", "Pooja Sane", "Sahil Chavan", None,
        "Riya Bhosale", "Yash Thakur", "Neha Pawar", "Rohan Shinde",
        "Tanvi Gokhale", "Nikhil Patil", "Aditi Desai", "Kavya More",
        "Aarav Sharma", "Dev Kulkarni", "Sana Khan", "Arjun Nair",
        "Mitali Shah", "Siddharth Kale", "Diya Pawar", "Irfan Shaikh",
        "Ritu Pawar", "  "
    ],

    "age": [
        25, 28, 32, 26, np.nan, 35, 150, 24, 29, 31,
        27, 33, 26, -5, 30, 28, 24, 36, 27, 29,
        25, 31, np.nan, 34, 28, 26, 23, 32, 29, 200
    ],

    "gender": [
        "Male", "Female", "Male", "Female", "Female", "Male",
        "Male", "Female", "Male", "Female", "Male", "Female",
        "Female", "Male", "Female", "Male", "Female", "Male",
        "Female", "Female", "Male", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female", "Unknown"
    ],

    "department": [
        "IT", "HR", "Finance", "IT", "Marketing", "IT", "HR",
        "Finance", "IT", "Marketing", "HR", "IT", "Finance",
        "IT", "HR", "Marketing", "IT", "Finance", "HR", "IT",
        "IT", "Finance", "HR", "IT", "Marketing", "IT",
        "Finance", "HR", "IT", "Marketing"
    ],

    "salary": [
        45000, 52000, 60000, 47000, np.nan, 75000, 50000,
        48000, 62000, 55000, 51000, 68000, 49000, -1000,
        53000, 72000, 46000, 80000, 54000, 58000,
        45000, 65000, 0, 90000, 56000, np.nan, 48000,
        61000, 52000, 999999
    ],

    "performance_score": [
        4.2, 3.8, 4.5, 3.9, 4.1, np.nan, 3.5, 4.8,
        4.0, 3.7, 4.3, 3.9, 4.6, 2.8, 4.1, 5.5,
        3.6, 4.7, 4.0, np.nan, 4.2, 3.8, 4.4, 4.1,
        3.9, 4.6, 3.7, 4.0, 4.2, 8.5
    ],

    "location": [
        "Pune", "Mumbai", "Nashik", "Pune", "Pune", "Mumbai",
        "Pune", "Nashik", "Mumbai", "Pune", "PUNE", "Mumbai",
        "Nashik", "Pune", "Mumbai", "Nashik", "Pune", "Mumbai",
        "Pune", "Nashik", "Pune", "Mumbai", "Pune", "Nashik",
        "Mumbai", "Pune", "Nashik", "Mumbai", "Pune", None
    ],

    "joining_date": [
        "2022-05-17", "2021-03-10", "2020-11-25", "2023-01-15",
        "2022-08-20", "2021-06-12", "2020-02-30", "2023-04-18",
        "2022-09-05", None, "2021-12-01", "2020-07-14",
        "2023-02-30", "2022-10-10", "not available", "2021-05-22",
        "2023-06-01", "2020-09-15", "2022-01-30", "2021-11-11",
        "2022-05-17", "2023-03-12", "2021-07-19", "2020-12-05",
        "2022-04-25", "2021-08-16", "2023-05-20", "2022-02-14",
        "2020-10-10", "2024-13-40"
    ],

    "experience_years": [
        2, 4, 7, 1, np.nan, 8, 3, 1, 5, 6,
        4, 9, 2, -1, 5, 7, 1, 10, 3, 4,
        2, 6, 3, 8, 4, 5, 1, 7, 3, 50
    ],

    "email": [
        "aarav@example.com", "priya@example.com", "rahul@example.com",
        "sneha.example.com", "sneha@example.com", None,
        "om@example.com", "isha@example.com", "kunal@example.com",
        "pooja@example.com", "sahil@example.com", "riya@example.com",
        "yash@example.com", "neha@example.com", "rohan@example.com",
        "tanvi@example.com", "nikhil@example.com", "aditi@example.com",
        "kavya@example.com", "dev@example.com", "aarav@example.com",
        "dev.k@example.com", "sana@example.com", "arjun@example.com",
        "mitali@example.com", "siddharth@example.com", "diya@example.com",
        "irfan@example.com", "ritu@example.com", ""
    ]
}

df = pd.DataFrame(data)

print(df)
print(df.shape)

    employee_id            name    age   gender department    salary  \
0           101    Aarav Sharma   25.0     Male         IT   45000.0
1           102     Priya Patil   28.0   Female         HR   52000.0
2           103  Rahul Deshmukh   32.0     Male    Finance   60000.0
3           104                   26.0   Female         IT   47000.0
4           105     Sneha Joshi    NaN   Female  Marketing       NaN
5           106     Vikram More   35.0     Male         IT   75000.0
6           107        Om Pawar  150.0     Male         HR   50000.0
7           108       Isha Shah   24.0   Female    Finance   48000.0
8           109    Kunal Jadhav   29.0     Male         IT   62000.0
9           110      Pooja Sane   31.0   Female  Marketing   55000.0
10          111    Sahil Chavan   27.0     Male         HR   51000.0
11          112            None   33.0   Female         IT   68000.0
12          113    Riya Bhosale   26.0   Female    Finance   49000.0
13          114     Yash Thakur   -5.0     Male         IT   -1000.0
14          115      Neha Pawar   30.0   Female         HR   53000.0
15          116    Rohan Shinde   28.0     Male  Marketing   72000.0
16          117   Tanvi Gokhale   24.0   Female         IT   46000.0
17          118    Nikhil Patil   36.0     Male    Finance   80000.0
18          119     Aditi Desai   27.0   Female         HR   54000.0
19          120      Kavya More   29.0   Female         IT   58000.0
20          101    Aarav Sharma   25.0     Male         IT   45000.0
21          122    Dev Kulkarni   31.0     Male    Finance   65000.0
22          123       Sana Khan    NaN   Female         HR       0.0
23          124      Arjun Nair   34.0     Male         IT   90000.0
24          125     Mitali Shah   28.0   Female  Marketing   56000.0
25          126  Siddharth Kale   26.0     Male         IT       NaN
26          127      Diya Pawar   23.0   Female    Finance   48000.0
27          128    Irfan Shaikh   32.0     Male         HR   61000.0
28          129      Ritu Pawar   29.0   Female         IT   52000.0
29          130                  200.0  Unknown  Marketing  999999.0

    performance_score location   joining_date  experience_years  \
0                 4.2     Pune     2022-05-17               2.0
1                 3.8   Mumbai     2021-03-10               4.0
2                 4.5   Nashik     2020-11-25               7.0
3                 3.9     Pune     2023-01-15               1.0
4                 4.1     Pune     2022-08-20               NaN
5                 NaN   Mumbai     2021-06-12               8.0
6                 3.5     Pune     2020-02-30               3.0
7                 4.8   Nashik     2023-04-18               1.0
8                 4.0   Mumbai     2022-09-05               5.0
9                 3.7     Pune           None               6.0
10                4.3     PUNE     2021-12-01               4.0
11                3.9   Mumbai     2020-07-14               9.0
12                4.6   Nashik     2023-02-30               2.0
13                2.8     Pune     2022-10-10              -1.0
14                4.1   Mumbai  not available               5.0
15                5.5   Nashik     2021-05-22               7.0
16                3.6     Pune     2023-06-01               1.0
17                4.7   Mumbai     2020-09-15              10.0
18                4.0     Pune     2022-01-30               3.0
19                NaN   Nashik     2021-11-11               4.0
20                4.2     Pune     2022-05-17               2.0
21                3.8   Mumbai     2023-03-12               6.0
22                4.4     Pune     2021-07-19               3.0
23                4.1   Nashik     2020-12-05               8.0
24                3.9   Mumbai     2022-04-25               4.0
25                4.6     Pune     2021-08-16               5.0
26                3.7   Nashik     2023-05-20               1.0
27                4.0   Mumbai     2022-02-14               7.0
28                4.2     Pune     2020-10-10               3.0
29                8.5     None     2024-13-40              50.0

                    email
0       aarav@example.com
1       priya@example.com
2       rahul@example.com
3       sneha.example.com
4       sneha@example.com
5                    None
6          om@example.com
7        isha@example.com
8       kunal@example.com
9       pooja@example.com
10      sahil@example.com
11       riya@example.com
12       yash@example.com
13       neha@example.com
14      rohan@example.com
15      tanvi@example.com
16     nikhil@example.com
17      aditi@example.com
18      kavya@example.com
19        dev@example.com
20      aarav@example.com
21      dev.k@example.com
22       sana@example.com
23      arjun@example.com
24     mitali@example.com
25  siddharth@example.com
26       diya@example.com
27      irfan@example.com
28       ritu@example.com
29
(30, 11)

In [143]:
df

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
1,102,Priya Patil,28.0,Female,HR,52000.0,3.8,Mumbai,2021-03-10,4.0,priya@example.com
2,103,Rahul Deshmukh,32.0,Male,Finance,60000.0,4.5,Nashik,2020-11-25,7.0,rahul@example.com
3,104,,26.0,Female,IT,47000.0,3.9,Pune,2023-01-15,1.0,sneha.example.com
4,105,Sneha Joshi,NaN,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com
5,106,Vikram More,35.0,Male,IT,75000.0,NaN,Mumbai,2021-06-12,8.0,None
6,107,Om Pawar,150.0,Male,HR,50000.0,3.5,Pune,2020-02-30,3.0,om@example.com
7,108,Isha Shah,24.0,Female,Finance,48000.0,4.8,Nashik,2023-04-18,1.0,isha@example.com
8,109,Kunal Jadhav,29.0,Male,IT,62000.0,4.0,Mumbai,2022-09-05,5.0,kunal@example.com
9,110,Pooja Sane,31.0,Female,Marketing,55000.0,3.7,Pune,None,6.0,pooja@example.com
10,111,Sahil Chavan,27.0,Male,HR,51000.0,4.3,PUNE,2021-12-01,4.0,sahil@example.com
11,112,None,33.0,Female,IT,68000.0,3.9,Mumbai,2020-07-14,9.0,riya@example.com
12,113,Riya Bhosale,26.0,Female,Finance,49000.0,4.6,Nashik,2023-02-30,2.0,yash@example.com
13,114,Yash Thakur,-5.0,Male,IT,-1000.0,2.8,Pune,2022-10-10,-1.0,neha@example.com
14,115,Neha Pawar,30.0,Female,HR,53000.0,4.1,Mumbai,not available,5.0,rohan@example.com
15,116,Rohan Shinde,28.0,Male,Marketing,72000.0,5.5,Nashik,2021-05-22,7.0,tanvi@example.com
16,117,Tanvi Gokhale,24.0,Female,IT,46000.0,3.6,Pune,2023-06-01,1.0,nikhil@example.com
17,118,Nikhil Patil,36.0,Male,Finance,80000.0,4.7,Mumbai,2020-09-15,10.0,aditi@example.com
18,119,Aditi Desai,27.0,Female,HR,54000.0,4.0,Pune,2022-01-30,3.0,kavya@example.com
19,120,Kavya More,29.0,Female,IT,58000.0,NaN,Nashik,2021-11-11,4.0,dev@example.com
20,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
21,122,Dev Kulkarni,31.0,Male,Finance,65000.0,3.8,Mumbai,2023-03-12,6.0,dev.k@example.com
22,123,Sana Khan,NaN,Female,HR,0.0,4.4,Pune,2021-07-19,3.0,sana@example.com
23,124,Arjun Nair,34.0,Male,IT,90000.0,4.1,Nashik,2020-12-05,8.0,arjun@example.com
24,125,Mitali Shah,28.0,Female,Marketing,56000.0,3.9,Mumbai,2022-04-25,4.0,mitali@example.com
25,126,Siddharth Kale,26.0,Male,IT,NaN,4.6,Pune,2021-08-16,5.0,siddharth@example.com
26,127,Diya Pawar,23.0,Female,Finance,48000.0,3.7,Nashik,2023-05-20,1.0,diya@example.com
27,128,Irfan Shaikh,32.0,Male,HR,61000.0,4.0,Mumbai,2022-02-14,7.0,irfan@example.com
28,129,Ritu Pawar,29.0,Female,IT,52000.0,4.2,Pune,2020-10-10,3.0,ritu@example.com
29,130,,200.0,Unknown,Marketing,999999.0,8.5,None,2024-13-40,50.0,

In [144]:
df.shape

(30, 11)

In [145]:
df.head()

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
1,102,Priya Patil,28.0,Female,HR,52000.0,3.8,Mumbai,2021-03-10,4.0,priya@example.com
2,103,Rahul Deshmukh,32.0,Male,Finance,60000.0,4.5,Nashik,2020-11-25,7.0,rahul@example.com
3,104,,26.0,Female,IT,47000.0,3.9,Pune,2023-01-15,1.0,sneha.example.com
4,105,Sneha Joshi,NaN,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        30 non-null     int64
 1   name               29 non-null     object
 2   age                28 non-null     float64
 3   gender             30 non-null     object
 4   department         30 non-null     object
 5   salary             28 non-null     float64
 6   performance_score  28 non-null     float64
 7   location           29 non-null     object
 8   joining_date       29 non-null     object
 9   experience_years   29 non-null     float64
 10  email              29 non-null     object
dtypes: float64(4), int64(1), object(6)
memory usage: 2.7+ KB

In [148]:
df["name"]= df["name"].str.strip().replace("name",np.nan)

In [153]:
a = df[df["name"].isnull()].index

In [155]:
df.drop(a,inplace=True)

In [156]:
df.shape

(29, 11)

In [174]:
df.isnull().sum()

employee_id          0
name                 0
age                  0
gender               0
department           0
salary               2
performance_score    2
location             1
joining_date         1
experience_years     1
email                1
dtype: int64

In [167]:
# df["age"]=df["age"].fillna(df["age"].median())
df[df["salary"].isnull()]

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
4,105,Sneha Joshi,28.0,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com
25,126,Siddharth Kale,26.0,Male,IT,NaN,4.6,Pune,2021-08-16,5.0,siddharth@example.com

In [177]:
df["salary"]=df.loc[df["salary"].isnull(),"salary"].fillna(df["salary"].mean(),inplace=True)

In [179]:
df.isnull()

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,True,False
5,False,False,False,False,False,True,True,False,False,False,True
6,False,False,False,False,False,True,False,False,False,False,False
7,False,False,False,False,False,True,False,False,False,False,False
8,False,False,False,False,False,True,False,False,False,False,False
9,False,False,False,False,False,True,False,False,True,False,False
10,False,False,False,False,False,True,False,False,False,False,False
12,False,False,False,False,False,True,False,False,False,False,False
13,False,False,False,False,False,True,False,False,False,False,False
14,False,False,False,False,False,True,False,False,False,False,False
15,False,False,False,False,False,True,False,False,False,False,False
16,False,False,False,False,False,True,False,False,False,False,False
17,False,False,False,False,False,True,False,False,False,False,False
18,False,False,False,False,False,True,False,False,False,False,False
19,False,False,False,False,False,True,True,False,False,False,False
20,False,False,False,False,False,True,False,False,False,False,False
21,False,False,False,False,False,True,False,False,False,False,False
22,False,False,False,False,False,True,False,False,False,False,False
23,False,False,False,False,False,True,False,False,False,False,False
24,False,False,False,False,False,True,False,False,False,False,False
25,False,False,False,False,False,True,False,False,False,False,False
26,False,False,False,False,False,True,False,False,False,False,False
27,False,False,False,False,False,True,False,False,False,False,False
28,False,False,False,False,False,True,False,False,False,False,False
29,False,False,False,False,False,True,False,True,False,False,False

In [181]:
df[df["salary"]==50000]

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
6,107,Om Pawar,150.0,Male,HR,50000.0,3.5,Pune,2020-02-30,3.0,om@example.com

In [182]:
df.head()

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
1,102,Priya Patil,28.0,Female,HR,52000.0,3.8,Mumbai,2021-03-10,4.0,priya@example.com
2,103,Rahul Deshmukh,32.0,Male,Finance,60000.0,4.5,Nashik,2020-11-25,7.0,rahul@example.com
3,104,,26.0,Female,IT,47000.0,3.9,Pune,2023-01-15,1.0,sneha.example.com
4,105,Sneha Joshi,NaN,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com

In [183]:
df.tail(10)

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
20,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
21,122,Dev Kulkarni,31.0,Male,Finance,65000.0,3.8,Mumbai,2023-03-12,6.0,dev.k@example.com
22,123,Sana Khan,NaN,Female,HR,0.0,4.4,Pune,2021-07-19,3.0,sana@example.com
23,124,Arjun Nair,34.0,Male,IT,90000.0,4.1,Nashik,2020-12-05,8.0,arjun@example.com
24,125,Mitali Shah,28.0,Female,Marketing,56000.0,3.9,Mumbai,2022-04-25,4.0,mitali@example.com
25,126,Siddharth Kale,26.0,Male,IT,NaN,4.6,Pune,2021-08-16,5.0,siddharth@example.com
26,127,Diya Pawar,23.0,Female,Finance,48000.0,3.7,Nashik,2023-05-20,1.0,diya@example.com
27,128,Irfan Shaikh,32.0,Male,HR,61000.0,4.0,Mumbai,2022-02-14,7.0,irfan@example.com
28,129,Ritu Pawar,29.0,Female,IT,52000.0,4.2,Pune,2020-10-10,3.0,ritu@example.com
29,130,,200.0,Unknown,Marketing,999999.0,8.5,None,2024-13-40,50.0,

In [184]:
df.shape

(30, 11)

In [185]:
df.columns

Index(['employee_id', 'name', 'age', 'gender', 'department', 'salary',
       'performance_score', 'location', 'joining_date', 'experience_years',
       'email'],
      dtype='object')

In [186]:
df.dtypes

employee_id            int64
name                  object
age                  float64
gender                object
department            object
salary               float64
performance_score    float64
location              object
joining_date          object
experience_years     float64
email                 object
dtype: object

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        30 non-null     int64
 1   name               29 non-null     object
 2   age                28 non-null     float64
 3   gender             30 non-null     object
 4   department         30 non-null     object
 5   salary             28 non-null     float64
 6   performance_score  28 non-null     float64
 7   location           29 non-null     object
 8   joining_date       29 non-null     object
 9   experience_years   29 non-null     float64
 10  email              29 non-null     object
dtypes: float64(4), int64(1), object(6)
memory usage: 2.7+ KB

In [188]:
df.isnull().sum()

employee_id          0
name                 1
age                  2
gender               0
department           0
salary               2
performance_score    2
location             1
joining_date         1
experience_years     1
email                1
dtype: int64

In [192]:
df.value_counts()

employee_id  name            age     gender  department  salary    performance_score  location  joining_date   experience_years  email
101          Aarav Sharma     25.0   Male    IT           45000.0  4.2                Pune      2022-05-17      2.0              aarav@example.com     2
102          Priya Patil      28.0   Female  HR           52000.0  3.8                Mumbai    2021-03-10      4.0              priya@example.com     1
103          Rahul Deshmukh   32.0   Male    Finance      60000.0  4.5                Nashik    2020-11-25      7.0              rahul@example.com     1
104                           26.0   Female  IT           47000.0  3.9                Pune      2023-01-15      1.0              sneha.example.com     1
107          Om Pawar         150.0  Male    HR           50000.0  3.5                Pune      2020-02-30      3.0              om@example.com        1
108          Isha Shah        24.0   Female  Finance      48000.0  4.8                Nashik    2023-04-18      1.0              isha@example.com      1
109          Kunal Jadhav     29.0   Male    IT           62000.0  4.0                Mumbai    2022-09-05      5.0              kunal@example.com     1
111          Sahil Chavan     27.0   Male    HR           51000.0  4.3                PUNE      2021-12-01      4.0              sahil@example.com     1
113          Riya Bhosale     26.0   Female  Finance      49000.0  4.6                Nashik    2023-02-30      2.0              yash@example.com      1
114          Yash Thakur     -5.0    Male    IT          -1000.0   2.8                Pune      2022-10-10     -1.0              neha@example.com      1
115          Neha Pawar       30.0   Female  HR           53000.0  4.1                Mumbai    not available   5.0              rohan@example.com     1
116          Rohan Shinde     28.0   Male    Marketing    72000.0  5.5                Nashik    2021-05-22      7.0              tanvi@example.com     1
117          Tanvi Gokhale    24.0   Female  IT           46000.0  3.6                Pune      2023-06-01      1.0              nikhil@example.com    1
118          Nikhil Patil     36.0   Male    Finance      80000.0  4.7                Mumbai    2020-09-15      10.0             aditi@example.com     1
119          Aditi Desai      27.0   Female  HR           54000.0  4.0                Pune      2022-01-30      3.0              kavya@example.com     1
122          Dev Kulkarni     31.0   Male    Finance      65000.0  3.8                Mumbai    2023-03-12      6.0              dev.k@example.com     1
124          Arjun Nair       34.0   Male    IT           90000.0  4.1                Nashik    2020-12-05      8.0              arjun@example.com     1
125          Mitali Shah      28.0   Female  Marketing    56000.0  3.9                Mumbai    2022-04-25      4.0              mitali@example.com    1
127          Diya Pawar       23.0   Female  Finance      48000.0  3.7                Nashik    2023-05-20      1.0              diya@example.com      1
128          Irfan Shaikh     32.0   Male    HR           61000.0  4.0                Mumbai    2022-02-14      7.0              irfan@example.com     1
129          Ritu Pawar       29.0   Female  IT           52000.0  4.2                Pune      2020-10-10      3.0              ritu@example.com      1
Name: count, dtype: int64

In [193]:
df.describe()

,employee_id,age,salary,performance_score,experience_years
count,30.000000,28.000000,28.000000,28.000000,29.000000
mean,114.833333,37.964286,87178.535714,4.264286,5.862069
std,9.123986,39.952270,179882.912690,0.965791,8.911165
min,101.000000,-5.000000,-1000.000000,2.800000,-1.000000
25%,107.250000,26.000000,48000.000000,3.875000,2.000000
50%,114.500000,28.500000,53500.000000,4.100000,4.000000
75%,122.750000,32.000000,62750.000000,4.425000,7.000000
max,130.000000,200.000000,999999.000000,8.500000,50.000000

In [195]:
df[df["employee_id"]==101]

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
20,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com

In [196]:
df

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
1,102,Priya Patil,28.0,Female,HR,52000.0,3.8,Mumbai,2021-03-10,4.0,priya@example.com
2,103,Rahul Deshmukh,32.0,Male,Finance,60000.0,4.5,Nashik,2020-11-25,7.0,rahul@example.com
3,104,,26.0,Female,IT,47000.0,3.9,Pune,2023-01-15,1.0,sneha.example.com
4,105,Sneha Joshi,NaN,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com
5,106,Vikram More,35.0,Male,IT,75000.0,NaN,Mumbai,2021-06-12,8.0,None
6,107,Om Pawar,150.0,Male,HR,50000.0,3.5,Pune,2020-02-30,3.0,om@example.com
7,108,Isha Shah,24.0,Female,Finance,48000.0,4.8,Nashik,2023-04-18,1.0,isha@example.com
8,109,Kunal Jadhav,29.0,Male,IT,62000.0,4.0,Mumbai,2022-09-05,5.0,kunal@example.com
9,110,Pooja Sane,31.0,Female,Marketing,55000.0,3.7,Pune,None,6.0,pooja@example.com
10,111,Sahil Chavan,27.0,Male,HR,51000.0,4.3,PUNE,2021-12-01,4.0,sahil@example.com
11,112,None,33.0,Female,IT,68000.0,3.9,Mumbai,2020-07-14,9.0,riya@example.com
12,113,Riya Bhosale,26.0,Female,Finance,49000.0,4.6,Nashik,2023-02-30,2.0,yash@example.com
13,114,Yash Thakur,-5.0,Male,IT,-1000.0,2.8,Pune,2022-10-10,-1.0,neha@example.com
14,115,Neha Pawar,30.0,Female,HR,53000.0,4.1,Mumbai,not available,5.0,rohan@example.com
15,116,Rohan Shinde,28.0,Male,Marketing,72000.0,5.5,Nashik,2021-05-22,7.0,tanvi@example.com
16,117,Tanvi Gokhale,24.0,Female,IT,46000.0,3.6,Pune,2023-06-01,1.0,nikhil@example.com
17,118,Nikhil Patil,36.0,Male,Finance,80000.0,4.7,Mumbai,2020-09-15,10.0,aditi@example.com
18,119,Aditi Desai,27.0,Female,HR,54000.0,4.0,Pune,2022-01-30,3.0,kavya@example.com
19,120,Kavya More,29.0,Female,IT,58000.0,NaN,Nashik,2021-11-11,4.0,dev@example.com
20,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
21,122,Dev Kulkarni,31.0,Male,Finance,65000.0,3.8,Mumbai,2023-03-12,6.0,dev.k@example.com
22,123,Sana Khan,NaN,Female,HR,0.0,4.4,Pune,2021-07-19,3.0,sana@example.com
23,124,Arjun Nair,34.0,Male,IT,90000.0,4.1,Nashik,2020-12-05,8.0,arjun@example.com
24,125,Mitali Shah,28.0,Female,Marketing,56000.0,3.9,Mumbai,2022-04-25,4.0,mitali@example.com
25,126,Siddharth Kale,26.0,Male,IT,NaN,4.6,Pune,2021-08-16,5.0,siddharth@example.com
26,127,Diya Pawar,23.0,Female,Finance,48000.0,3.7,Nashik,2023-05-20,1.0,diya@example.com
27,128,Irfan Shaikh,32.0,Male,HR,61000.0,4.0,Mumbai,2022-02-14,7.0,irfan@example.com
28,129,Ritu Pawar,29.0,Female,IT,52000.0,4.2,Pune,2020-10-10,3.0,ritu@example.com
29,130,,200.0,Unknown,Marketing,999999.0,8.5,None,2024-13-40,50.0,

In [197]:
df.isnull().sum()

employee_id          0
name                 1
age                  2
gender               0
department           0
salary               2
performance_score    2
location             1
joining_date         1
experience_years     1
email                1
dtype: int64

In [198]:
df[df["name"].isnull()]

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
11,112,None,33.0,Female,IT,68000.0,3.9,Mumbai,2020-07-14,9.0,riya@example.com

In [200]:
df['name'] = df["name"].str.strip().replace("name",np.nan)

In [202]:
df

,employee_id,name,age,gender,department,salary,performance_score,location,joining_date,experience_years,email
0,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
1,102,Priya Patil,28.0,Female,HR,52000.0,3.8,Mumbai,2021-03-10,4.0,priya@example.com
2,103,Rahul Deshmukh,32.0,Male,Finance,60000.0,4.5,Nashik,2020-11-25,7.0,rahul@example.com
3,104,,26.0,Female,IT,47000.0,3.9,Pune,2023-01-15,1.0,sneha.example.com
4,105,Sneha Joshi,NaN,Female,Marketing,NaN,4.1,Pune,2022-08-20,NaN,sneha@example.com
5,106,Vikram More,35.0,Male,IT,75000.0,NaN,Mumbai,2021-06-12,8.0,None
6,107,Om Pawar,150.0,Male,HR,50000.0,3.5,Pune,2020-02-30,3.0,om@example.com
7,108,Isha Shah,24.0,Female,Finance,48000.0,4.8,Nashik,2023-04-18,1.0,isha@example.com
8,109,Kunal Jadhav,29.0,Male,IT,62000.0,4.0,Mumbai,2022-09-05,5.0,kunal@example.com
9,110,Pooja Sane,31.0,Female,Marketing,55000.0,3.7,Pune,None,6.0,pooja@example.com
10,111,Sahil Chavan,27.0,Male,HR,51000.0,4.3,PUNE,2021-12-01,4.0,sahil@example.com
11,112,None,33.0,Female,IT,68000.0,3.9,Mumbai,2020-07-14,9.0,riya@example.com
12,113,Riya Bhosale,26.0,Female,Finance,49000.0,4.6,Nashik,2023-02-30,2.0,yash@example.com
13,114,Yash Thakur,-5.0,Male,IT,-1000.0,2.8,Pune,2022-10-10,-1.0,neha@example.com
14,115,Neha Pawar,30.0,Female,HR,53000.0,4.1,Mumbai,not available,5.0,rohan@example.com
15,116,Rohan Shinde,28.0,Male,Marketing,72000.0,5.5,Nashik,2021-05-22,7.0,tanvi@example.com
16,117,Tanvi Gokhale,24.0,Female,IT,46000.0,3.6,Pune,2023-06-01,1.0,nikhil@example.com
17,118,Nikhil Patil,36.0,Male,Finance,80000.0,4.7,Mumbai,2020-09-15,10.0,aditi@example.com
18,119,Aditi Desai,27.0,Female,HR,54000.0,4.0,Pune,2022-01-30,3.0,kavya@example.com
19,120,Kavya More,29.0,Female,IT,58000.0,NaN,Nashik,2021-11-11,4.0,dev@example.com
20,101,Aarav Sharma,25.0,Male,IT,45000.0,4.2,Pune,2022-05-17,2.0,aarav@example.com
21,122,Dev Kulkarni,31.0,Male,Finance,65000.0,3.8,Mumbai,2023-03-12,6.0,dev.k@example.com
22,123,Sana Khan,NaN,Female,HR,0.0,4.4,Pune,2021-07-19,3.0,sana@example.com
23,124,Arjun Nair,34.0,Male,IT,90000.0,4.1,Nashik,2020-12-05,8.0,arjun@example.com
24,125,Mitali Shah,28.0,Female,Marketing,56000.0,3.9,Mumbai,2022-04-25,4.0,mitali@example.com
25,126,Siddharth Kale,26.0,Male,IT,NaN,4.6,Pune,2021-08-16,5.0,siddharth@example.com
26,127,Diya Pawar,23.0,Female,Finance,48000.0,3.7,Nashik,2023-05-20,1.0,diya@example.com
27,128,Irfan Shaikh,32.0,Male,HR,61000.0,4.0,Mumbai,2022-02-14,7.0,irfan@example.com
28,129,Ritu Pawar,29.0,Female,IT,52000.0,4.2,Pune,2020-10-10,3.0,ritu@example.com
29,130,,200.0,Unknown,Marketing,999999.0,8.5,None,2024-13-40,50.0,