In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\student_performance_test.csv")

In [3]:
df.head()

,Student_ID,Name,Department,Gender,Study_Hours_Per_Day,Attendance_Percent,Python_Marks,Statistics_Marks,Database_Marks
0,STU101,Aarav Sharma,Electronics,Male,6,85.0,70,70.0,72
1,STU102,Priya Patil,Information Technology,Female,4,52.0,82,76.0,75
2,STU103,Rohan Verma,Electronics,Male,6,93.0,81,86.0,95
3,STU104,Sneha Kulkarni,Mechanical,Female,5,66.0,78,63.0,69
4,STU105,Aditya Shah,Mechanical,Male,5,70.0,71,59.0,73

In [4]:
df.rename(columns={"Aerage_Marks":"Average_Marks"})

,Student_ID,Name,Department,Gender,Study_Hours_Per_Day,Attendance_Percent,Python_Marks,Statistics_Marks,Database_Marks
0,STU101,Aarav Sharma,Electronics,Male,6,85.0,70,70.0,72
1,STU102,Priya Patil,Information Technology,Female,4,52.0,82,76.0,75
2,STU103,Rohan Verma,Electronics,Male,6,93.0,81,86.0,95
3,STU104,Sneha Kulkarni,Mechanical,Female,5,66.0,78,63.0,69
4,STU105,Aditya Shah,Mechanical,Male,5,70.0,71,59.0,73
5,STU106,Ananya Deshmukh,Information Technology,Female,2,65.0,76,65.0,72
6,STU107,Vivek Joshi,Computer Science,Female,1,90.0,61,64.0,61
7,STU108,Neha Singh,Information Technology,Male,3,NaN,54,49.0,40
8,STU109,Karan Mehta,Mechanical,Female,4,74.0,43,58.0,61
9,STU110,Isha Pawar,Electronics,Female,6,99.0,75,75.0,73
10,STU111,Rahul Gupta,Computer Science,Female,3,100.0,58,62.0,57
11,STU112,Pooja Jadhav,Electronics,Female,1,70.0,53,60.0,48
12,STU113,Siddharth Rao,Computer Science,Male,0,77.0,67,49.0,64
13,STU114,Kavya Nair,Computer Science,Female,6,96.0,72,71.0,77
14,STU115,Omkar More,Electronics,Male,1,85.0,41,48.0,50
15,STU116,Tanvi Shinde,Information Technology,Female,3,63.0,54,59.0,53
16,STU117,Arjun Kapoor,Mechanical,Female,4,75.0,80,67.0,72
17,STU118,Aditi Mishra,Information Technology,Male,2,71.0,60,51.0,48
18,STU119,Sahil Khan,Information Technology,Male,3,100.0,62,83.0,74
19,STU120,Mansi Thakur,Computer Science,Male,1,64.0,44,54.0,57
20,STU121,Yash Chavan,Mechanical,Female,6,73.0,68,76.0,63
21,STU122,Riya Soni,Mechanical,Male,3,74.0,61,NaN,84
22,STU123,Akash Yadav,Electronics,Female,5,80.0,79,81.0,73
23,STU124,Simran Kaur,Electronics,Male,6,73.0,83,88.0,77
24,STU125,Nikhil Bhosale,Mechanical,Male,2,73.0,60,57.0,54
25,STU126,Meera Iyer,Electronics,Male,2,73.0,64,61.0,45
26,STU127,Dev Malhotra,Mechanical,Male,6,73.0,55,48.0,73
27,STU128,Sana Shaikh,Electronics,Female,5,70.0,63,57.0,68
28,STU129,Harsh Vora,Information Technology,Female,1,54.0,42,35.0,36
29,STU130,Diya Kulkarni,Information Technology,Male,2,79.0,53,36.0,68
30,STU131,Manav Jain,Mechanical,Male,5,97.0,71,73.0,85
31,STU132,Ira Desai,Information Technology,Male,1,99.0,58,63.0,61
32,STU133,Atharva Patil,Mechanical,Female,5,69.0,62,76.0,61
33,STU134,Shruti Joshi,NaN,Female,3,83.0,72,75.0,65
34,STU135,Kabir Anand,Information Technology,Female,3,64.0,56,56.0,71
35,STU136,Anushka Roy,Information Technology,Female,2,89.0,48,72.0,49
36,STU137,Pranav Naik,Computer Science,Female,5,82.0,73,93.0,78
37,STU138,Sakshi Pawar,Information Technology,Female,3,76.0,70,68.0,78
38,STU139,Varun Shah,Information Technology,Female,1,78.0,62,46.0,54
39,STU140,Nandini Rao,Mechanical,Male,2,69.0,48,46.0,42
40,STU141,Dhruv Mehta,Mechanical,Female,2,99.0,68,52.0,53
41,STU142,Ayesha Khan,Mechanical,Male,1,100.0,35,33.0,49
42,STU143,Parth Kulkarni,Computer Science,Female,4,87.0,70,62.0,84
43,STU144,Myra Singh,Mechanical,Female,1,98.0,59,43.0,62
44,STU145,Saurabh More,Information Technology,Female,4,82.0,48,82.0,58
45,STU146,Khushi Desai,Information Technology,Male,2,86.0,38,36.0,28
46,STU147,Ritvik Nair,Computer Science,Female,3,74.0,50,55.0,56
47,STU148,Jhanvi Joshi,Electronics,Female,5,67.0,74,70.0,59
48,STU149,Abhishek Jain,Mechanical,Female,3,88.0,59,61.0,58
49,STU150,Palak Sharma,Electronics,Male,1,84.0,46,52.0,76
50,STU105,Aditya Shah,Mechanical,Male,5,70.0,71,59.0,73

In [5]:
df

,Student_ID,Name,Department,Gender,Study_Hours_Per_Day,Attendance_Percent,Python_Marks,Statistics_Marks,Database_Marks
0,STU101,Aarav Sharma,Electronics,Male,6,85.0,70,70.0,72
1,STU102,Priya Patil,Information Technology,Female,4,52.0,82,76.0,75
2,STU103,Rohan Verma,Electronics,Male,6,93.0,81,86.0,95
3,STU104,Sneha Kulkarni,Mechanical,Female,5,66.0,78,63.0,69
4,STU105,Aditya Shah,Mechanical,Male,5,70.0,71,59.0,73
5,STU106,Ananya Deshmukh,Information Technology,Female,2,65.0,76,65.0,72
6,STU107,Vivek Joshi,Computer Science,Female,1,90.0,61,64.0,61
7,STU108,Neha Singh,Information Technology,Male,3,NaN,54,49.0,40
8,STU109,Karan Mehta,Mechanical,Female,4,74.0,43,58.0,61
9,STU110,Isha Pawar,Electronics,Female,6,99.0,75,75.0,73
10,STU111,Rahul Gupta,Computer Science,Female,3,100.0,58,62.0,57
11,STU112,Pooja Jadhav,Electronics,Female,1,70.0,53,60.0,48
12,STU113,Siddharth Rao,Computer Science,Male,0,77.0,67,49.0,64
13,STU114,Kavya Nair,Computer Science,Female,6,96.0,72,71.0,77
14,STU115,Omkar More,Electronics,Male,1,85.0,41,48.0,50
15,STU116,Tanvi Shinde,Information Technology,Female,3,63.0,54,59.0,53
16,STU117,Arjun Kapoor,Mechanical,Female,4,75.0,80,67.0,72
17,STU118,Aditi Mishra,Information Technology,Male,2,71.0,60,51.0,48
18,STU119,Sahil Khan,Information Technology,Male,3,100.0,62,83.0,74
19,STU120,Mansi Thakur,Computer Science,Male,1,64.0,44,54.0,57
20,STU121,Yash Chavan,Mechanical,Female,6,73.0,68,76.0,63
21,STU122,Riya Soni,Mechanical,Male,3,74.0,61,NaN,84
22,STU123,Akash Yadav,Electronics,Female,5,80.0,79,81.0,73
23,STU124,Simran Kaur,Electronics,Male,6,73.0,83,88.0,77
24,STU125,Nikhil Bhosale,Mechanical,Male,2,73.0,60,57.0,54
25,STU126,Meera Iyer,Electronics,Male,2,73.0,64,61.0,45
26,STU127,Dev Malhotra,Mechanical,Male,6,73.0,55,48.0,73
27,STU128,Sana Shaikh,Electronics,Female,5,70.0,63,57.0,68
28,STU129,Harsh Vora,Information Technology,Female,1,54.0,42,35.0,36
29,STU130,Diya Kulkarni,Information Technology,Male,2,79.0,53,36.0,68
30,STU131,Manav Jain,Mechanical,Male,5,97.0,71,73.0,85
31,STU132,Ira Desai,Information Technology,Male,1,99.0,58,63.0,61
32,STU133,Atharva Patil,Mechanical,Female,5,69.0,62,76.0,61
33,STU134,Shruti Joshi,NaN,Female,3,83.0,72,75.0,65
34,STU135,Kabir Anand,Information Technology,Female,3,64.0,56,56.0,71
35,STU136,Anushka Roy,Information Technology,Female,2,89.0,48,72.0,49
36,STU137,Pranav Naik,Computer Science,Female,5,82.0,73,93.0,78
37,STU138,Sakshi Pawar,Information Technology,Female,3,76.0,70,68.0,78
38,STU139,Varun Shah,Information Technology,Female,1,78.0,62,46.0,54
39,STU140,Nandini Rao,Mechanical,Male,2,69.0,48,46.0,42
40,STU141,Dhruv Mehta,Mechanical,Female,2,99.0,68,52.0,53
41,STU142,Ayesha Khan,Mechanical,Male,1,100.0,35,33.0,49
42,STU143,Parth Kulkarni,Computer Science,Female,4,87.0,70,62.0,84
43,STU144,Myra Singh,Mechanical,Female,1,98.0,59,43.0,62
44,STU145,Saurabh More,Information Technology,Female,4,82.0,48,82.0,58
45,STU146,Khushi Desai,Information Technology,Male,2,86.0,38,36.0,28
46,STU147,Ritvik Nair,Computer Science,Female,3,74.0,50,55.0,56
47,STU148,Jhanvi Joshi,Electronics,Female,5,67.0,74,70.0,59
48,STU149,Abhishek Jain,Mechanical,Female,3,88.0,59,61.0,58
49,STU150,Palak Sharma,Electronics,Male,1,84.0,46,52.0,76
50,STU105,Aditya Shah,Mechanical,Male,5,70.0,71,59.0,73

In [6]:
df.drop(columns="Aerage_Marks",inplace=True)

KeyError: "['Aerage_Marks'] not found in axis"

In [ ]:
df

In [ ]:
df.columns

In [ ]:
df["Total_marks"] = df["Total_marks"].fillna(df["Total_marks"].mean())

In [ ]:
df.isnull().sum()

In [ ]:
df["Statistics_Marks"] = df["Statistics_Marks"].fillna(df["Statistics_Marks"].mean())

In [ ]:
df.isnull().sum()

In [ ]:
a = df.groupby("Name")["Total_marks"].mean()

In [ ]:
a.shape

In [ ]:
df.drop(columns="Total_marks",inplace=True)

In [ ]:
df

In [ ]:
a = df.groupby("Name")["Total_marks"].mean()

In [ ]:
a.values

In [ ]:
a.shape

In [ ]:
df["Average_marks1"] = df["Statistics_Marks"] + df["Python_Marks"] + df["Database_Marks"]

In [ ]:
df["Average_marks3"] = df["Average_marks1"]/3

In [ ]:
df["Average_marks3"]

In [ ]:
df.columns

In [ ]:
df.drop(columns="Total_marks",inplace=True)

In [ ]:
df

In [ ]:
df[df["Average_marks"]>75]

In [ ]:
df.shape

In [ ]:
df.drop(columns="Average_marks",inplace=True)

In [ ]:
df

In [ ]:
df[df["Average_marks3"]>75]

In [ ]:
df[(df['Python_Marks']<40) | (df['Statistics_Marks']<40) | (df['Database_Marks']<40)]

In [ ]:
df.groupby("Gender")["Average_marks3"].mean()

In [ ]:
df.columns

In [ ]:
df.sort_values('Attendance_Percent').head(5)

In [ ]:
df[(df["Study_Hours_Per_Day"]>3) & (df["Average_marks3"]>70)]

In [ ]:
a = df["Department"].mode()

In [ ]:
a[0]

In [ ]:
df["Department"] = df["Department"].fillna(a[0])

In [ ]:
df.isnull().sum()

In [ ]:
df["Attendance_Percent"] = df["Attendance_Percent"].fillna(df["Attendance_Percent"].mean())

In [ ]:
df.isnull().sum()

In [ ]:
df.columns

In [ ]:
df.groupby('Department')['Attendance_Percent'].mean()

In [ ]:
df["Result"] = ""

In [ ]:
df.info()

In [ ]:
df.loc[df["Average_marks3"]>=40,"Result"]="Pass"

In [ ]:
df.loc[df["Average_marks3"]<=40,"Result"]="fail"

In [ ]:
# df.drop(columns="Result",inplace=True)

In [ ]:
df

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df.columns

In [ ]:
plt.plot(df["Average_marks3"])

In [ ]:
plt.bar(df['Average_marks3'],df["Department"])

In [ ]:
df.columns

In [ ]:
plt.scatter(df['Study_Hours_Per_Day'],df['Average_marks3'])

In [ ]:
df.columns

In [ ]:
plt.bar(df['Department'],df['Average_marks3'])

In [ ]:
a = df.groupby("Gender")['Average_marks3'].mean()

In [ ]:
plt.bar(a.index,a.values)

In [ ]:
df['Department'].value_counts().plot(kind="pie",autopct=")

In [ ]:
df.info()

In [ ]:
df

In [ ]:
df.columns

In [ ]:
a = df["Python_Marks"]+df['Statistics_Marks']+ df['Database_Marks']

In [ ]:
df["Average_Marks"] =a/3

In [ ]:
df[df["Average_Marks"]>75]

In [ ]:
df[(df["Python_Marks"]<=40) | (df["Statistics_Marks"]<=40)|(df["Database_Marks"]<=40)]

In [ ]:
df.groupby("Gender")["Average_Marks"].mean()

In [ ]:
df.sort_values("Attendance_Percent").head(5)

In [ ]:
df[(df["Study_Hours_Per_Day"]>3) & (df["Average_Marks"]>70)]

In [ ]:
df["Attendance_Percent"]= df["Attendance_Percent"].fillna(df["Attendance_Percent"].mean())

In [ ]:
df["Statistics_Marks"] = df["Statistics_Marks"].fillna(df["Statistics_Marks"].mean())

In [ ]:
a = df["Department"].mode()

In [ ]:
df["Department"] = df["Department"].fillna(df["Department"].fillna(a[0]))

In [ ]:
df.isnull().sum()

In [ ]:
df["Average_Marks"] = df["Average_Marks"].fillna(df["Average_Marks"].mean())

In [ ]:
df.groupby("Department")["Attendance_Percent"].mean()

In [ ]:
df["Result"] = df["Average_Marks"].apply(lambda x:"Pass" if x>=40 else "Fail")

In [ ]:
df

In [ ]:
import matplotlib.pyplot as plt


x = len(df)
width = 0.5

plt.bar(x-width,df["Python_Marks"],width=0.3)
plt.bar(x,df["Statistics_Marks"],width=0.3)
plt.bar(x+width,df["Database_Marks"],width=0.3,color="red",edgecolor="black")
plt.legend(["PYTHON","STACT","DATA"])

In [ ]:
print(len(df))

In [ ]:
x

In [ ]:
plt.bar(df["Department"],df["Average_Marks"])

In [ ]:
plt.scatter(df["Study_Hours_Per_Day"],df["Average_Marks"])

In [ ]:
# plt.boxplot([df[
df.columns

In [ ]:
df[['Python_Marks','Statistics_Marks','Database_Marks']].value_counts().plot(kind="box")

In [ ]:
# plt.bar(df["Department"],df["Average_Marks"])
df

In [ ]:
a = df.groupby("Gender").agg(python_m = ("Python_Marks","mean"),
                         stack_m = ("Statistics_Marks","mean"),
                         data = ("Database_Marks","mean")
                        )

In [ ]:
# plt.bar(a.index,a.values)
a

In [ ]:
a.values

In [ ]:
df["Department"].value_counts().plot(kind="pie",autopct="%.2f%%",explode=[0.4,0,0,0],shadow=True)

In [ ]:
a = df.groupby("Department")["Name"].count()

In [ ]:
df["Department"].value_counts().plot(kind="pie",labeldistance=1.1,radius=2)